### ISSUE TITLE
Using the new oauth from homeassistant

### ISSUE THREAD

**Issue by chronm** [zachowj/node-red-contrib-home-assistant-websocket#1]
I am trying to use the new oauth login scheme from homeassistant with your module, but what am I supposed to enter in the AccessToken-field. Do you have an example for this scenario?
I am starting with a fresh install of homeassistant and nodered with only some hue lights configured in HA

**Comment by zachowj** [comment]
Take a look in the wiki for a small guide on how to generate the access token.

https://github.com/zachowj/node-red-contrib-home-assistant-websocket/wiki

**Comment by chronm** [comment]
Thank you a lot
