### ISSUE TITLE
Plugin does not connect to HA after reboot

### ISSUE THREAD

**Issue by jncanches** [zachowj/node-red-contrib-home-assistant-websocket#10]
**Describe the bug**
On an Hassbian Raspberry Pi 3, Home assistant and Node red configured to launch at startup, just after the raspberry boot, NodeRed can't connect to Home assistant.
Redeploying nodes in NodeRed or restart once Home assistant, solves the issue and NodeRed connects well to Home-Assistant

**Expected behavior**
NodeRed must connect to Home Assistant after a boot without restarting HA or NR.

**Environment (please complete the following information):**
 - Node Red Version: 0.19
 - NR Home Assistant websocket Plugin Version: 0.1.2
 - Is Node Red running in Docker: no

**Other (please complete the following information):**
- Have you searched previous issues for duplicates?: yes
- Did you attempt to reproduce the issue in the dev docker environment, if so what were results (See README.md): no

By the way, very good plugin ! Keep this way !

Thank you

**Comment by Swamp-Ig** [comment]
I also have this issue, running in a docker container on a QNAP NAS FWIW.

**Comment by jncanches** [comment]
Wonderful zachowj.

Does it mean that the next release will try to connect again even after a first refused connection ?

Thank you very much !

**Comment by zachowj** [comment]
#13

**Comment by jncanches** [comment]
Thank you!
Do you plan to make a 0.1.3 release soon ?

**Comment by zachowj** [comment]
it's out
