### ISSUE TITLE
Nothing Auto-populationg from homeassistant 

### ISSUE THREAD

**Issue by jonny190** [zachowj/node-red-contrib-home-assistant-websocket#101]
**Describe the bug**
Ive configured node-red with the plugin but it is not auto populating the Domain, Service, Entity ID or Data fields

I can controll items in homeassistant using the inject node direct to call service 

**To Reproduce**

Add call service node,
Edit node
Start Typing turn_on/off switch/light etc 

**Expected behavior**
Suggest items to click and auto fill

**Screenshots**
![image](https://user-images.githubusercontent.com/8059327/54089245-f18c4780-435e-11e9-9390-addaef8369bc.png)
![image](https://user-images.githubusercontent.com/8059327/54089258-02d55400-435f-11e9-9e5e-fa65d05760bd.png)

**Example Flow**
`[{"id":"ebe10d1f.b3e198","type":"api-call-service","z":"25afdae6.ed0c2e","name":"Toggle Main Light","server":"35ff681e.3325f8","service_domain":"switch","service":"toggle","data":"{\"entity_id\":\"swi\"}","mergecontext":"","output_location":"","output_location_type":"none","x":531,"y":123,"wires":[[]]},{"id":"35ff681e.3325f8","type":"server","z":"","name":"Home Assistant","legacy":false,"hassio":false,"rejectUnauthorizedCerts":true,"ha_boolean":"y|yes|true|on|home|open","connectionDelay":true}]`

**Environment (please complete the following information):**

- Node Red Version: 0.19.6: Maintenance Release
- NR Home Assistant Plugin Version: 0.9.1
- Is Node Red running in Docker: yes

**Other (please complete the following information):**
The host os is Unraid
one docker container for home-assistant
one docker container for Node-Red

- Have you searched previous issues for duplicates?:
yes but they are maked resolved so i cannot commen on them

**Comment by zachowj** [comment]
Can you check your browser debug console after you open up a call-service node and check the status and contents of the two requests that go out? Should be one called entities and services.

**Comment by jonny190** [comment]
thanks for hte quick reply, i've opened this and can see these errors in the console:
`window.controllers/Controllers is deprecated. Do not use it for UA detection. ace.js:1:18479
Node-RED: 0.19.6 red.min.js:16:1725
Projects disabled main.min.js:16:9224
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help http://xhr.spec.whatwg.org/ vendor.js:5:25377
Empty string passed to getElementById().
vendor.js:2:24487
Empty string passed to getElementById().
vendor.js:2:24487
Password fields present on an insecure (http://) page. This is a security risk that allows user login credentials to be stolen.[Learn More] 192.168.4.22:1880
Empty string passed to getElementById().
vendor.js:2:24487
Empty string passed to getElementById().
vendor.js:2:24487
Password fields present on an insecure (http://) page. This is a security risk that allows user login credentials to be stolen.[Learn More] 192.168.4.22:1880`

**Comment by jonny190** [comment]
Empty string passed to getElementById().
vendor.js:2:24487
Empty string passed to getElementById().
vendor.js:2:24487

**Comment by jonny190** [comment]
Internet Explorer seems to have more issues *Rolls Eyes*
`Node-RED: 0.19.6
Projects disabled
[node-red-contrib-home-assistant-websocket/server-events] SyntaxError: Invalid character
[node-red-contrib-home-assistant-websocket/server-state-changed] SyntaxError: Invalid character
[node-red-contrib-home-assistant-websocket/trigger-state] SyntaxError: Invalid character
[node-red-contrib-home-assistant-websocket/poll-state] SyntaxError: Invalid character
[node-red-contrib-home-assistant-websocket/api-call-service] SyntaxError: Invalid character
[node-red-contrib-home-assistant-websocket/ha-fire-event] SyntaxError: Invalid character
[node-red-contrib-home-assistant-websocket/api-current-state] SyntaxError: Invalid character
[node-red-contrib-home-assistant-websocket/ha-get-entities] SyntaxError: Syntax error
[node-red-contrib-home-assistant-websocket/api-get-history] SyntaxError: Invalid character
[node-red-contrib-home-assistant-websocket/api-render-template] SyntaxError: Invalid character
[node-red-contrib-home-assistant-websocket/ha-wait-until] SyntaxError: Invalid character
[node-red-contrib-home-assistant-websocket/ha-api] SyntaxError: Syntax error
SCRIPT5007: Object expected
main.min.js (16,4296)
SCRIPT5007: Object expected
main.min.js (16,4296)
SCRIPT5007: Object expected
main.min.js (16,4296)
`

**Comment by zachowj** [comment]
If I had to guess at this point you're not running the v8 version of node-red image.

**Comment by fwclements** [comment]
I'm actually seeing the same thing with a fresh install.  Access via OSX 10.14, both Safari and Chrome.

```
> node-red-docker@1.0.0 start /usr/src/node-red
> node $NODE_OPTIONS node_modules/node-red/red.js -v $FLOWS "--userDir" "/data"

3 Apr 12:32:25 - [info]

Welcome to Node-RED
===================

3 Apr 12:32:25 - [info] Node-RED version: v0.20.3
3 Apr 12:32:25 - [info] Node.js  version: v8.15.1
3 Apr 12:32:25 - [info] Linux 4.15.0-46-generic x64 LE
3 Apr 12:32:25 - [info] Loading palette nodes
3 Apr 12:32:25 - [warn] rpi-gpio : Raspberry Pi specific node set inactive
3 Apr 12:32:25 - [warn] rpi-gpio : Cannot find Pi RPi.GPIO python library
3 Apr 12:32:25 - [info] Settings file  : /data/settings.js
3 Apr 12:32:25 - [info] Context store  : 'default' [module=memory]
3 Apr 12:32:25 - [info] User directory : /data
3 Apr 12:32:25 - [warn] Projects disabled : editorTheme.projects.enabled=false
3 Apr 12:32:25 - [info] Flows file     : /data/flows.json
3 Apr 12:32:25 - [info] Creating new flow file
```
I get no feedback from the console of Safari but the Chrome browser shows this in the console when I add/click through the 'call service' node:

```
[Violation] Added non-passive event listener to a scroll-blocking <some> event. Consider marking event handler as 'passive' to make the page more responsive. See <URL>
[Violation] Forced reflow while executing JavaScript took 32ms
:1880/#flow/9beb24ef.f68ee:1 [DOM] Input elements should have autocomplete attributes (suggested: "current-password"): (More info: https://goo.gl/9p2vKq) <input type=​"password" style=​"display:​ none;​">​
```
