### ISSUE TITLE
events: all node not showing zwave.scene_activated events

### ISSUE THREAD

**Issue by sea3pea0** [zachowj/node-red-contrib-home-assistant-websocket#102]
**Describe the bug**
Events:All node isn't catching zwave.scene_activated events. I can see these events in the open zwave log but they do not show up with the events:all node.

**To Reproduce**

1. Add events:all node to flow.
2. Connect debug node with complete message object.
3. Add switch to filter out state_changed events
4. Activate zwave scene.
5. Watch debug and open zwave log for event.
6. Scene info shows up in ozw.log
7. Nothing shows up in the debug output for the events all node

**Expected behavior**
When I activate zwave scenes I expect to see them in the debug output from the events:all node.

**Environment (please complete the following information):**

- Node Red Version: 0.19.6
- NR Home Assistant Plugin Version: 0.9.1
- Is Node Red running in Docker: hassio

- Have you searched previous issues for duplicates?: yes

**Comment by zachowj** [comment]
The event:all node is just a firehose of events received from home assistant. There's no filtering done on that node. Can you post your flow?

**Comment by sea3pea0** [comment]
Yes here it is:
`
[{"id":"a165122d.f9cb8","type":"server-events","z":"4a47b7ce.81a9a8","name":"","server":"5e33c60f.a63028","event_type":"","x":200,"y":1260,"wires":[["80424e9d.b1824"]]},{"id":"80424e9d.b1824","type":"switch","z":"4a47b7ce.81a9a8","name":"","property":"payload.event_type","propertyType":"msg","rules":[{"t":"neq","v":"state_changed","vt":"str"}],"checkall":"true","repair":false,"outputs":1,"x":350,"y":1260,"wires":[["124fcdcb.1f1de2"]]},{"id":"124fcdcb.1f1de2","type":"debug","z":"4a47b7ce.81a9a8","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","x":490,"y":1260,"wires":[]},{"id":"5e33c60f.a63028","type":"server","z":"","name":"Home Assistant","legacy":false,"hassio":true,"rejectUnauthorizedCerts":true,"ha_boolean":"y|yes|true|on|home|open"}]
`
I have a few different installations of hassio and I don't see zwave events on any of them in the events: all node. I've read several threads in different places on the web about people using the events: all node with the "zwave.scene_activated" event. For me those events don't make it to the events: all node. 

Could this be a change in home assistant with how zwave events are handled? Here is screenshot of my /dev-event page in HA: 
![/dev-event page](https://i.imgur.com/6VE115V.png)

I don't see anything zwave related there, but like I said I do see the zwave scene info show up in the ozw.log when I activate my zwave scenes

**Comment by marc-gist** [comment]
Can you post some ozw.log lines where you see the scene events?  sometimes you need to modify the xml file to get proper scene support in HA.
I have this working fine in NodeRed and HA.

**Comment by sea3pea0** [comment]
So it turns out that my problem was that I had to re-learn that for changes to be saved to the zwcfg*.xml file, home assistant needs to be stopped. Thanks for your help! After figuring that out everything is working as expected!

**Comment by marc-gist** [comment]
> So it turns out that my problem was that I had to re-learn that for changes to be saved to the zwcfg*.xml file, home assistant needs to be stopped. Thanks for your help! After figuring that out everything is working as expected!

Yes, for those finding this thread.
Modify zwcfg*.xml file **AFTER** you shutdown HomeAssistant (as when HA shuts down, it writes a NEW version of zwcfg_*.xml overwriting any changes you make.
