### ISSUE TITLE
Wrong triger name

### ISSUE THREAD

**Issue by kgiedrius** [zachowj/node-red-contrib-home-assistant-websocket#1032]
### Describe the bug

Wrong naming when switch device have >1  button.

<img width="1334" alt="image" src="https://github.com/zachowj/node-red-contrib-home-assistant-websocket/assets/15670549/12a6743d-5ae1-4c5e-83d9-9ccf4fac9dff">

### To Reproduce

sometimes show different names for triggers, sometimes show all same when device have more than 1 switch. (zigbee switch). Before saving sometimes show correct names, but after saving always wrong. 

### Expected behavior

<img width="547" alt="image" src="https://github.com/zachowj/node-red-contrib-home-assistant-websocket/assets/15670549/c765987b-ec9f-40c7-918f-fcaeda778ee7">

### This package's version (not the Home Assistant add-on version)

all

### Is Node-RED running in Docker?

Home Assistant add-on

### Node-RED version

all

### Node.js version

14.4.2

**Comment by rein222222** [comment]
same problem on node-red-contrib-home-assistant-websocket 0.63.0
Node-Red HA AddOn 17.0.7
