### ISSUE TITLE
nodejs v10 support

### ISSUE THREAD

**Issue by marc-gist** [zachowj/node-red-contrib-home-assistant-websocket#104]
Thanks for a great node module!!!
I noticed that nodejs v8 LTS ends this year December 2019.  Are you working on v10 support?

**Comment by zachowj** [comment]
It should run fine with the latest v10 release.

**Comment by marc-gist** [comment]
Thanks, I'll test out asap. Your readme still says to pull V8 of the docker.

**Comment by zachowj** [comment]
Last I checked I don't think node-red has an official v10 release for docker on the RPi. I could be wrong now, maybe v10 just runs on the pi without a special build.

**Comment by marc-gist** [comment]
on the RPi I believe you are correct.  I'm using a small PC as find it way faster for HA and with MySQL and then room to spare to run things like Node-Red, etc without issue.
I've pulled the latest (which defaults to v8 now, and also trying the nodered/node-red:v10 and so far seems to work.
