### ISSUE TITLE
not a valid value for dictionary value @ data['entity_id']. Got None

### ISSUE THREAD

**Issue by lublak** [zachowj/node-red-contrib-home-assistant-websocket#1045]
### Describe the bug

If I try to trigger a action using the device node I get an error: not a valid value for dictionary value @ data['entity_id']. Got None

### To Reproduce

Create a simple flow:
![IMG_0193](https://github.com/zachowj/node-red-contrib-home-assistant-websocket/assets/44057030/6369f9e0-8d6d-4557-b6a7-8de8e22c7319)
![IMG_0194](https://github.com/zachowj/node-red-contrib-home-assistant-websocket/assets/44057030/e9a8d464-603d-4840-b1f8-1b8d42c92c77)

### Expected behavior

Should not throw an error

### Screenshots

See to reproduce

### Example Flow

```json
[{"id":"63cbdfe69644d91e","type":"ha-device","z":"ea82b441f55b2fcf","name":"","server":"fea6860f.124988","version":0,"debugenabled":false,"exposeToHomeAssistant":false,"haConfig":[{"property":"name","value":""},{"property":"icon","value":""}],"inputs":1,"deviceType":"action","device":"585fc77acabe0678f80d510d3988795d","event":{"device_id":"585fc77acabe0678f80d510d3988795d","domain":"select","entity_id":"0eee6b53b082e932123c2ce96ff75481","type":"select_option","metadata":{"secondary":true}},"capabilities":[{"name":"option","type":"select","value":"On"}],"outputProperties":[],"x":610,"y":620,"wires":[[]]},{"id":"fea6860f.124988","type":"server","name":"Home Assistant","addon":true}]
```

### This package's version (not the Home Assistant add-on version)

2.2.0

### Is Node-RED running in Docker?

Home Assistant add-on

### Node-RED version

14.4.5

### Node.js version

?

**Comment by VIMVa** [comment]
Same here on all previously created and new HA **Device** nodes except if starting with a State Node just before the Device node.

**Comment by Amadudl** [comment]
![image](https://github.com/zachowj/node-red-contrib-home-assistant-websocket/assets/24881416/d4388984-74e9-4de4-9b82-c5e461e58e14)
![image](https://github.com/zachowj/node-red-contrib-home-assistant-websocket/assets/24881416/3edfc3cb-ee36-4bc2-8779-57ea73ac4dc2)
![image](https://github.com/zachowj/node-red-contrib-home-assistant-websocket/assets/24881416/f9b642e5-df3f-4c27-9ff3-3848419875df)

Same problems here. It looks like Node-Red is trying to use the name field for the device ID.

**Comment by AllStarzes** [comment]
Same problemes here. If i update existing nodes, i get the same issue. Is there a solution for this problem or have anyone solved the problem?

Best Regards 
Ben

**Comment by VIMVa** [comment]
I have replaced all 'Device' nodes in my NodeRed flows with 'Call Service' nodes as nothing is moving since the start of this thread. That works for me at least.

**Comment by jonaslewin** [comment]
I have also replaced 'Device' with 'Call Service'. I no longer need
node-red-contrib-home-assistant-websocket. How can I remove it from HA/HACS?

Den fre 6 okt. 2023 kl 11:48 skrev VIMVa ***@***.***>:

**Comment by AllStarzes** [comment]
Yes i saw this workaound but You cant call the Service "armed_home" and "armed_away" on the Homebase von eufy. Only my 3 custom armed, if i call one of them IT works but You dont See IT active in the eufy App as active. I hope u know hat i mean 🤣🤣

**Comment by VIMVa** [comment]
@jonaslewin In HACS, select NodeRed Companion, then 3 dots top-right to see remove. Is it that what you are looking for?

**Comment by mitch569** [comment]
Also having the same issue, rolling back this update for now :)

**Comment by robsch94** [comment]
From looking at the JSON of a flow, the thing, that seems to have changed is the entity_id format in the event under device action. In older flows, that are still working, this entity_id is a human-readable string, in my case for example "light.living_room". In newer flows, this ID is an hex string. I was not able to find out, where this hex ID is coming from so far.
When exporting a flow as JSON, changing the entity_id back to the human-readable string, and re-importing the flow, everything works fine.

**Comment by chrisroxor** [comment]
I'm also getting this issue. Did anyone have success with rolling back? And to which version?

**Comment by gbraux** [comment]
Same issue here ... Can someone have a look ? ;-)

**Comment by AllStarzes** [comment]
> Same issue here ... Can someone have a look ? ;-)

Dont usw the beta nodes.
User the call Service. I replace All my nodes with the call Service und works fine.

https://github.com/zachowj/node-red-contrib-home-assistant-websocket/issues/1045#issuecomment-1750523425

**Comment by gbraux** [comment]
Thx @AllStarzes. Service is definitely working, thx for the tip.
BTW, fun that my old nodes (create somethink like 1y ago) are still working ... The issue is only for newly created nodes ...

**Comment by AllStarzes** [comment]
> Thx @AllStarzes. Service is definitely working, thx for the tip. BTW, fun that my old nodes (create somethink like 1y ago) are still working ... The issue is only for newly created nodes ...

U welcome. Yes this is the know issue, If u create a New node. I would replace All these nodes. I also did that. Regards 👋

**Comment by VIMVa** [comment]
> Thx @AllStarzes. Service is definitely working, thx for the tip. BTW, fun that my old nodes (create somethink like 1y ago) are still working ... The issue is only for newly created nodes ...

[Who's](https://github.com/zachowj/node-red-contrib-home-assistant-websocket/issues/1045#issuecomment-1750307373) tip? 😉

**Comment by VIMVa** [comment]
So sad that since September '23 nothing has changed yet 😭

**Comment by AllStarzes** [comment]
> So sad that since September '23 nothing has changed yet 😭

Hi, Use the call Service. Dont usw the beta (Red) Services. Works fine and u can all replace IT with the normal Call Services

**Comment by VIMVa** [comment]
> > So sad that since September '23 nothing has changed yet 😭
> 
> Hi, Use the call Service. Dont usw the beta (Red) Services. Works fine and u can all replace IT with the normal Call Services

Thanks for repeating my own suggestion of October 6, 2023 above 😊 for a workaround that needs us to review and modify all our flows where we used that nice node.
**With all respect**: believe we do not ask too much for things to work as they are meant to work, especially when we feedback their errors popping up in a new beta release and while numerous NodeRed releases have appeared since then.
