### ISSUE TITLE
Allow for star pattern in "entity id" field

### ISSUE THREAD

**Issue by AnderssonPeter** [zachowj/node-red-contrib-home-assistant-websocket#105]
I'm currently using the call `service node` a lot, and lets say i need to turn off all lights in a room, then i would have to comma separate all `Entity Ids`

**Describe the solution you'd like**
It would be nice if i just could write `light.guest_bedroom_*` and it would figure out what lights that is on its own.

**Describe alternatives you've considered**
If that is not an option, could you make `Entity Id` overridable just like `domain`,  `service` and `data`.

**Comment by zachowj** [comment]
entity_id is actually part of the data field. It's only broken out in the UI to allow for autocomplete. If you pass in `msg.payload.data.entity_id` it will overwrite the config in the node.

Also, I saw the other day that there was a commit to allow targeting of areas in service calls. This might be another option for you if you're using areas already. https://github.com/home-assistant/home-assistant/commit/8213016eaf06035884d76565f62ed5b32298e7a1

You could also just add the entity ids of all of the lights in a given room to a global or flow variable and reference that in the entity id field of the call-service node,  `{{flow.guest_bedroom_lights}}`. Another option to do it dynamically on each call.

![chrome_2019-03-13_15-13-30](https://user-images.githubusercontent.com/37859597/54318222-ca25bc80-45a2-11e9-82da-ff811c46fe0c.png)

```
[{"id":"2324104b.0a845","type":"inject","z":"5eb3594f.d294b8","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":144,"y":816,"wires":[["2a41cfe8.b256a"]]},{"id":"2a41cfe8.b256a","type":"ha-get-entities","z":"5eb3594f.d294b8","server":"ef067c6f.620e6","name":"","rules":[{"property":"entity_id","logic":"is","value":"^light\\.guest_bedroom_","valueType":"re"}],"output_type":"array","output_empty_results":false,"output_location_type":"msg","output_location":"payload","output_results_count":1,"x":294,"y":816,"wires":[["bbadfc75.5207e"]]},{"id":"71bc0337.49140c","type":"join","z":"5eb3594f.d294b8","name":"","mode":"custom","build":"string","property":"payload","propertyType":"msg","key":"topic","joiner":",","joinerType":"str","accumulate":false,"timeout":"","count":"","reduceRight":false,"reduceExp":"","reduceInit":"","reduceInitType":"num","reduceFixup":"","x":594,"y":816,"wires":[["5c7826b7.14cce8"]]},{"id":"bbadfc75.5207e","type":"template","z":"5eb3594f.d294b8","name":"","field":"payload","fieldType":"msg","format":"handlebars","syntax":"mustache","template":"{{payload.entity_id}}","output":"str","x":460,"y":816,"wires":[["71bc0337.49140c"]]},{"id":"5c7826b7.14cce8","type":"api-call-service","z":"5eb3594f.d294b8","name":"","server":"ef067c6f.620e6","service_domain":"homeassistant","service":"turn_off","data":"{\"entity_id\":\"{{payload}}\"}","mergecontext":"","output_location":"payload","output_location_type":"msg","x":792,"y":816,"wires":[[]]}]
```

**Comment by zachowj** [comment]
Upon further consideration, I believe there are adequate ways to accomplish this without adding in a new feature in. Might revisit this in the future.

**Comment by Exit2Studios** [comment]
> entity_id is actually part of the data field. It's only broken out in the UI to allow for autocomplete. If you pass in `msg.payload.data.entity_id` it will overwrite the config in the node.
> 
> Also, I saw the other day that there was a commit to allow targeting of areas in service calls. This might be another option for you if you're using areas already. [home-assistant/home-assistant@8213016](https://github.com/home-assistant/home-assistant/commit/8213016eaf06035884d76565f62ed5b32298e7a1)
> 
> You could also just add the entity ids of all of the lights in a given room to a global or flow variable and reference that in the entity id field of the call-service node, `{{flow.guest_bedroom_lights}}`. Another option to do it dynamically on each call.
> 
> ![chrome_2019-03-13_15-13-30](https://user-images.githubusercontent.com/37859597/54318222-ca25bc80-45a2-11e9-82da-ff811c46fe0c.png)
> 
> ```
> [{"id":"2324104b.0a845","type":"inject","z":"5eb3594f.d294b8","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":144,"y":816,"wires":[["2a41cfe8.b256a"]]},{"id":"2a41cfe8.b256a","type":"ha-get-entities","z":"5eb3594f.d294b8","server":"ef067c6f.620e6","name":"","rules":[{"property":"entity_id","logic":"is","value":"^light\\.guest_bedroom_","valueType":"re"}],"output_type":"array","output_empty_results":false,"output_location_type":"msg","output_location":"payload","output_results_count":1,"x":294,"y":816,"wires":[["bbadfc75.5207e"]]},{"id":"71bc0337.49140c","type":"join","z":"5eb3594f.d294b8","name":"","mode":"custom","build":"string","property":"payload","propertyType":"msg","key":"topic","joiner":",","joinerType":"str","accumulate":false,"timeout":"","count":"","reduceRight":false,"reduceExp":"","reduceInit":"","reduceInitType":"num","reduceFixup":"","x":594,"y":816,"wires":[["5c7826b7.14cce8"]]},{"id":"bbadfc75.5207e","type":"template","z":"5eb3594f.d294b8","name":"","field":"payload","fieldType":"msg","format":"handlebars","syntax":"mustache","template":"{{payload.entity_id}}","output":"str","x":460,"y":816,"wires":[["71bc0337.49140c"]]},{"id":"5c7826b7.14cce8","type":"api-call-service","z":"5eb3594f.d294b8","name":"","server":"ef067c6f.620e6","service_domain":"homeassistant","service":"turn_off","data":"{\"entity_id\":\"{{payload}}\"}","mergecontext":"","output_location":"payload","output_location_type":"msg","x":792,"y":816,"wires":[[]]}]
> ```
> 
> edit:
> Yes, this is something I could add in the future.

@zachowj, I was playing with the flow you attached and I can get the entities to be identified, but the service call doesn't happen.  Any ideas what I'm doing wrong?  I copy and pasted and only changed the get-entities property to fit my lights.
