### ISSUE TITLE
Call service: input_select.select_option not working

### ISSUE THREAD

**Issue by glassbase** [zachowj/node-red-contrib-home-assistant-websocket#106]
**Describe the bug**
Trying to use input_select.select_option and getting API error. Works fine in dev tools - services. Copy and pasting from it from there into NR.

**To Reproduce**
1. Create input_select in HA
2. Try and use call service: input_select.select_option in NR
3. Receive API error in NR and errors in HA log
4. See errors below

NR error:
"Call-service API error. Error Message: extra keys not allowed @ data['option']"

HA logs error:
Traceback (most recent call last):
  File "/usr/src/app/homeassistant/components/websocket_api/commands.py", line 148, in handle_call_service
    connection.context(msg))
  File "/usr/src/app/homeassistant/core.py", line 1113, in async_call
    processed_data = handler.schema(service_data)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 267, in __call__
    return self._compiled([], data)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 589, in validate_dict
    return base_validate(path, iteritems(data), out)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 427, in validate_mapping
    raise er.MultipleInvalid(errors)
voluptuous.error.MultipleInvalid: extra keys not allowed @ data['option']

**Expected behavior**
No errors and service runs.

**Screenshots**

**Example Flow**
If applicable, add an example of exported json of a flow exhibiting the issue to aid in reproduction.

**Environment (please complete the following information):**
Docker with HA and NodeRed 
- Node Red Version: 0.20.2
- NR Home Assistant Plugin Version: 0.9.1
- Is Node Red running in Docker: y

**Other (please complete the following information):**

- Have you searched previous issues for duplicates?:
Y

**Additional context**

**Comment by zachowj** [comment]
If you post your flow I can confirm this but I'm assuming you have a node prior to the call-service node that is setting something to `msg.payload.data` and the call-service node is importing that value.

**Comment by glassbase** [comment]
`[{"id":"beff2630.72a538","type":"server-state-changed","z":"34a270ac.a28dc","name":"HT I/S","server":"5357eaea.8ef744","entityidfilter":"input_select.home_theatre_activity","entityidfiltertype":"exact","outputinitially":true,"state_type":"str","haltifstate":"","halt_if_type":"str","halt_if_compare":"is","outputs":1,"output_only_on_state_change":false,"x":110,"y":140,"wires":[["cb47a67a.3ef218"]]},{"id":"cb47a67a.3ef218","type":"switch","z":"34a270ac.a28dc","name":"Off, Bell, PS4, MiBox","property":"payload","propertyType":"msg","rules":[{"t":"eq","v":"Off","vt":"str"},{"t":"eq","v":"BELL","vt":"str"},{"t":"eq","v":"PS4","vt":"str"},{"t":"eq","v":"MIBOX","vt":"str"}],"checkall":"true","repair":false,"outputs":4,"x":380,"y":140,"wires":[["4c59c69f.ebb458"],["c0043cc7.4fe01"],["60811671.64eb48"],["16c1276d.71f9d9"]]},{"id":"4c59c69f.ebb458","type":"api-call-service","z":"34a270ac.a28dc","name":"Off","server":"5357eaea.8ef744","service_domain":"scene","service":"turn_on","data":"{\"entity_id\":\"scene.home_theatre_off\"}","mergecontext":"","output_location":"payload","output_location_type":"msg","x":690,"y":80,"wires":[["9ec3b726.07bbc8"]]},{"id":"c0043cc7.4fe01","type":"api-call-service","z":"34a270ac.a28dc","name":"Bell","server":"5357eaea.8ef744","service_domain":"scene","service":"turn_on","data":"{\"entity_id\":\"scene.home_theatre_bell\"}","mergecontext":"","output_location":"payload","output_location_type":"msg","x":690,"y":140,"wires":[["9ec3b726.07bbc8"]]},{"id":"60811671.64eb48","type":"api-call-service","z":"34a270ac.a28dc","name":"PS4","server":"5357eaea.8ef744","service_domain":"scene","service":"turn_on","data":"{\"entity_id\":\"scene.home_theatre_ps4\"}","mergecontext":"","output_location":"payload","output_location_type":"msg","x":687.7777709960938,"y":188.88888549804688,"wires":[["9ec3b726.07bbc8"]]},{"id":"16c1276d.71f9d9","type":"api-call-service","z":"34a270ac.a28dc","name":"MiBox","server":"5357eaea.8ef744","service_domain":"scene","service":"turn_on","data":"{\"entity_id\":\"scene.home_theatre_mibox\"}","mergecontext":"","output_location":"payload","output_location_type":"msg","x":690,"y":240,"wires":[["9ec3b726.07bbc8"]]},{"id":"9ec3b726.07bbc8","type":"api-call-service","z":"34a270ac.a28dc","name":"Reset I/S","server":"5357eaea.8ef744","service_domain":"input_select","service":"select_option","data":"{\"entity_id\":\"input_select.home_theatre_activity\",\"option\":\"Select...\"}","mergecontext":"","output_location":"payload","output_location_type":"msg","x":920,"y":160,"wires":[[]]},{"id":"5357eaea.8ef744","type":"server","z":"","name":"Home Assistant","legacy":false,"hassio":false,"rejectUnauthorizedCerts":true,"ha_boolean":"y|yes|true|on|home|open"}]`

**Comment by zachowj** [comment]
The call-service nodes before Reset I/S are overriding Reset I/S config via `msg.payload`. On each one set `Output Location` to `None` or something other than `msg.payload`.

**Comment by glassbase** [comment]
That worked. Does not any sense to me because I think of it as run this service, then this service. Why the previous has any effect is what I don't get.

**Comment by zachowj** [comment]
It's basically a node-red paradigm being able to set/overwrite properties of a node via the message object.
