### ISSUE TITLE
State changed event firing twice

### ISSUE THREAD

**Issue by mLupine** [zachowj/node-red-contrib-home-assistant-websocket#107]
**Describe the bug**
I have set up a "trigger: state" node that is supposed to let me know when movement is detected in a room, as well as when there is no more movement. And for the last part, it works fine – I get a single trigger with state: off. However, when movement is detected, I receive two triggers in quick succession – the first one with a duplicated state: off, and basically at the same time, another one with the correct state: on. This also happens when using the "events: state" node.

**Example Flow**

Here's my node code:
`[{"id":"f86b9101.92219","type":"trigger-state","z":"a02b5211.8d441","name":"Bedroom movement","server":"e6f3287a.29a158","entityid":"binary_sensor.motion_sensor_bedroom_1","entityidfiltertype":"exact","debugenabled":false,"constraints":[],"constraintsmustmatch":"all","outputs":2,"customoutputs":[],"outputinitially":false,"state_type":"str","x":140,"y":100,"wires":[["dbfc027d.bc78d"],[]]},{"id":"e6f3287a.29a158","type":"server","z":"","name":"Home Assistant","legacy":true,"hassio":false,"rejectUnauthorizedCerts":true,"ha_boolean":"y|yes|true|on|home|open","connectionDelay":true}]`

**Environment (please complete the following information):**

- Node Red Version: [e.g. 0.19.5] 0.20.0
- NR Home Assistant Plugin Version: [e.g. 0.5.0] 0.9.1
- Is Node Red running in Docker: [e.g. yes/no/hassio] yes

**Other (please complete the following information):**

- Have you searched previous issues for duplicates?: yes

**Additional context**
I have verified that the state is **not** changed to "off" in HA before going to "on". The movement sensor changes it directly from "off" to "on" in one state change.

**Comment by zachowj** [comment]
The trigger-node is firing every time it receives an update from HA. This is just not when the state changes but if any information in the entity changes like 'last_updated` which is probably occurring in your case. This can be solved with using a node-red-node-rbe node or the event-state node has this builtin but you need to make sure the `Output only on state change` is checked.
