### ISSUE TITLE
Entity problem after last update

### ISSUE THREAD

**Issue by djgragra** [zachowj/node-red-contrib-home-assistant-websocket#1078]
### Describe the bug

I I configured a bunch of ZigBee buttons in NodeRed but after the latest update I get the following message.

Attention: This node requires [Node-RED custom integration version 0.5.0+ ](https://github.com/zachowj/hass-node-red) to be installed in Home Assistant for it to function.

How can I solve it?
Thank you

### This package's version (not the Home Assistant add-on version)

-

### Is Node-RED running in Docker?

Home Assistant add-on

### Node-RED version

3.1.0

### Node.js version

-

**Comment by Orhelien** [comment]
Hello, what's your home-assistant version ?

**Comment by djgragra** [comment]
Home Assistant OS 2023.9.3

Graziano Melzi

Please consider the environment before printing this e-mail notice
Il 26 set 2023, 22:41 +0200, Orhelien ***@***.***>, ha scritto:

**Comment by Orhelien** [comment]
Ok same for me, after updating node red palette, with home assistant 2023.7.0
All home assistant node stop responding

**Comment by pdbintheusa** [comment]
I am having the same issue.  I upgraded both home assistant and node red and now the "device trigger" doesn't work.  However, the device in Home Assistant is still seeing the events.

**Comment by zachowj** [comment]
Are you running version 3.0.0 of the companion integration? Do you meet all the requirements? <https://github.com/zachowj/hass-node-red#minimum-requirements>

**Comment by pdbintheusa** [comment]
> Are you running version 3.0.0 of the companion integration? Do you meet all the requirements? https://github.com/zachowj/hass-node-red#minimum-requirements

I am running 3.0.0 of the companion integration. In my case the devices are the Philip's Hue Switches and Tap Dials that I have.  The node "Events All" with the filter "hue_event" does still work for catching the home assistant events of these devices, but the "device trigger" node doesn't ever catch and send the event.  As in, there is no "debug" message shown (including when the debug is set to "complete msg").  It broke when I updated Node Red to the most recent update, as well as Home Assistant Core to the most recent update of 2023.9.3

**Comment by zachowj** [comment]
Do you meet all the requirements?

[node-red-contrib-home-assistant-websocket](https://github.com/zachowj/node-red-contrib-home-assistant-websocket) v0.57+
[Home Assistant](https://github.com/home-assistant/core) 2023.7.0+

**Comment by AETGH** [comment]
I have the same problem and when I search in Node Red for home-assistant-websocket I only find version 0.56.1
Everything is up to date, Node Red runs as a HomeAssistant addon

**Comment by zachowj** [comment]
If you're not running [v0.57.0](https://github.com/zachowj/node-red-contrib-home-assistant-websocket/releases/tag/v0.57.0-beta.1) which is in beta release revert the custom component back to version 2.2.0.

**Comment by AETGH** [comment]
many thanks for the quick response :-) !
can I install the beta?
or what do I have to reset to 2.2.0?

**Comment by pdbintheusa** [comment]
> I have the same problem and when I search in Node Red for home-assistant-websocket I only find version 0.56.1 Everything is up to date, Node Red runs as a HomeAssistant addon

I found the solution.  In HomeAssistant go to Settings -> Addons and then click on Node-Red.  If  you go to the Configuration tab, you will find a field named "npm_packages" add this to it "node-red-contrib-home-assistant-websocket@beta" and hit enter to save the entry.

It should look like this.
![image](https://github.com/zachowj/node-red-contrib-home-assistant-websocket/assets/122150377/31ef5c55-7cba-49ce-a2f5-a3984136c206)

Then hit save and restart Node-Ned.  Then open Node-Red and you should have a message to update existing nodes (which it can do automatically) just follow those prompts and it should now all work.

**Comment by AETGH** [comment]
Unfortunately that doesn't work for me, as if he didn't recognize it, I still only find 0.56.1


I get several error:
npm WARN config optional Use `--omit=optional` to exclude optional dependencies, or
npm WARN config `--include=optional` to include them.
npm WARN config 
npm WARN config     Default value does install optional deps unless otherwise omitted.
npm WARN config only Use `--omit=dev` to omit dev dependencies from the install.

**Comment by AETGH** [comment]
I've now managed it, I simply had to upload the tgz manually --> https://registry.npmjs.org/node-red-contrib-home-assistant-websocket/-/node-red-contrib-home-assistant-websocket -0.57.0-beta.1.tgz

**Comment by DjBac** [comment]
> Unfortunately that doesn't work for me, as if he didn't recognize it, I still only find 0.56.1
> 
> I get several error:
> 
> ```
> npm WARN config optional Use `--omit=optional` to exclude optional dependencies, or
> npm WARN config `--include=optional` to include them.
> npm WARN config 
> npm WARN config     Default value does install optional deps unless otherwise omitted.
> npm WARN config only Use `--omit=dev` to omit dev dependencies from the install.
> removed 1 package, changed 5 packages, and audited 693 packages in 6s
> 101 packages are looking for funding
>   run `npm fund` for details
> 13 vulnerabilities (8 moderate, 3 high, 2 critical)
> To address all issues possible (including breaking changes), run:
>   npm audit fix --force
> Some issues need review, and may require choosing
> a different dependency.
> Run `npm audit` for details.
> ```

Same here. I am getting the exact same errors.

**Comment by DjBac** [comment]
> I've now managed it, I simply had to upload the tgz manually --> https://registry.npmjs.org/node-red-contrib-home-assistant-websocket/-/node-red-contrib-home-assistant-websocket -0.57.0-beta.1.tgz

Where did you upload it to?

**Comment by AETGH** [comment]
in node red --> manage palette --> install --> upload tgz

**Comment by djgragra** [comment]
If I go to the link (https://registry.npmjs.org/node-red-contrib-home-assistant-websocket/-/node-red-contrib-home-assistant-websocket -0.57.0-beta.1.tgz ) it gives me an error.
How do I download the tgz file?

Graziano Melzi

Please consider the environment before printing this e-mail notice
Il 27 set 2023, 13:23 +0200, DjBac ***@***.***> ha scritto:

**Comment by djgragra** [comment]
I installed 0.57.0-beta.1.tgz and for a moment everything worked.
In reality the flows are working but if I select the device node I don't see the entities.
Every now and then "running" appears under the nodes and at that point I see the entities.
Yesterday after installing 0.57.0-beta.1.tgz I could see everything but when I closed the browser and reopened it I couldn't see any entities anymore.

![Immagine 2023-09-28 114303](https://github.com/zachowj/node-red-contrib-home-assistant-websocket/assets/65872226/883c907c-e81c-4cc7-9bf7-055b3decdf01)

**Comment by djgragra** [comment]
Just as I was writing the previous message they started working again as per the attached image.
I closed the browser and reopened it and the nodes are no longer "running" so I don't see the entities but the flow works!


![Immagine 2023-09-28 120229](https://github.com/zachowj/node-red-contrib-home-assistant-websocket/assets/65872226/3343b15a-d764-47dc-b96c-e11d957cd11c)
![Immagine 2023-09-28 120415](https://github.com/zachowj/node-red-contrib-home-assistant-websocket/assets/65872226/043951ad-4fb9-4e04-9e69-b9a09b40e11d)
![Immagine 2023-09-28 120714](https://github.com/zachowj/node-red-contrib-home-assistant-websocket/assets/65872226/116c03c1-b310-43fb-ae87-81d9c2400566)

**Comment by Caligo82** [comment]
For me at least the update to the beta websocket didn't fix the problem. Had to completely revert to a backup.
I feel like it was maybe a bit early to release the companion addon as stable with the new output_path and messages while one of its core dependencies is in beta stage at best...

**Comment by jctull** [comment]
> For me at least the update to the beta websocket didn't fix the problem. Had to completely revert to a backup. I feel like it was maybe a bit early to release the companion addon as stable with the new output_path and messages while one of its core dependencies is in beta stage at best...

Agreed, it is a bit confusing to have it show up in HA as an update with a caveat that requires some digging around on GitHub for more information on the solution and potential problems that are still occurring for users. I greatly appreciate the developers and their hard work to make node red and HA integration so great, but would encourage holding off on publishing an update to the companion before the subcomponents are in place to make it work smoothly.

**Comment by Meisteryoda1994** [comment]
I had this same issue before and resolved it by reinstalling a backup. Now, I'm hesitant to update. Has this problem been fixed in the new release?
