### ISSUE TITLE
Attributes in binary_sensor missing [0.57.0 beta 1]

### ISSUE THREAD

**Issue by klatka** [zachowj/node-red-contrib-home-assistant-websocket#1079]
### Describe the bug

I have a binary_sensor defined in Node-RED with some attributes.

After upgrading to beta and updating companion to 3.0.0 the binary sensor shows only the first defined attribute from the list in HA.

### This package's version (not the Home Assistant add-on version)

0.57.0 beta 1

### Is Node-RED running in Docker?

Yes

### Node-RED version

3.1.0

### Node.js version

16+

### Additional context

Home Assistant 2023.9.3
Supervisor 2023.09.2
Operating System 10.5
Frontend 20230911.0 - latest

**Comment by zachowj** [comment]
Attributes are working for me in binary sensors. Can you provide an example flow?
