### ISSUE TITLE
JSON parsing and Mustache templates in service node

### ISSUE THREAD

**Issue by bohtho** [zachowj/node-red-contrib-home-assistant-websocket#108]
When I try a HA service from within HA with a certain JSON object containing a list of one (“systems”: [1]) HA runs it, however when I feed the same JSON as msg.payload.data to the service node in NR I get an error (from the API) saying “missing key in ‘systems’”.

Is the node data field interpreted in a special way? Do I need to escape [ and ]?

<sub>Sent from <a href="https://itunes.apple.com/cn/app/id1314212521">PPHub For GitHub</a></sub>

**Comment by bohtho** [comment]
I would have tried the same mustache template as I use in my template node which outputs to the service node, but the service node refuses to accept moustache tags without quotes around. However when I try to set a static/hard-coded JSON in the data field of the node, yes, it works.

So I guess its the format of the data that is input in msg.payload.data then. Shouldn't it accept a JSON from a Template node which is outputted from there as "Plain text" ?

**Comment by bohtho** [comment]
Actually, it only seems to accept the output of my template node as "Parsed JSON". Which is ok, but I understood the service node info text differently.

**Comment by zachowj** [comment]
I didn't fully understand what your issue was. The data passed to the call-service node must be valid JSON even with the mustache templates. Can you post the JSON object/string?

**Comment by bohtho** [comment]
With mustache template (now handled by separate Template node):
```
{
    "system": 00001,
    "systems": [
        1
    ],
    "id": {{payload.id}},
    "name": "{{payload.value1}}",
    "temperature": {{payload.value2}},
    "target_temperature": {{payload.value3}},
    "valve_position": {{payload.valve}}
}
```
Also tested with hardcoded values. Mustache tags around anything other than strings arent handled in the Service node data field itself so I had to use a separate Template node. Whereas other nodes that accept JSON gladly parse a JSON string, the HA Service node wouldnt, only a preparsed JSON object outoput from the Template node.
