### ISSUE TITLE
Unable to select entity config when configuring input_select

### ISSUE THREAD

**Issue by cdn4lf** [zachowj/node-red-contrib-home-assistant-websocket#1081]
### Describe the bug

Trying to create a new input select in NR.  I've setup the config and can see it as an unused entity config, however when I got to select it, the config is missing from the drop-down

### To Reproduce

1) open blank sensor action
2) Create new entity config with type select
3) Click okay
4) newly created entity config is missing

### Expected behavior

Newly created type select entity config should appear in the drop-down list

### Screenshots

![Screenshot 2023-09-27 191511](https://github.com/zachowj/node-red-contrib-home-assistant-websocket/assets/49874417/7f5f6b87-ab03-4d83-b442-da4813feeddc)
![Screenshot 2023-09-27 191706](https://github.com/zachowj/node-red-contrib-home-assistant-websocket/assets/49874417/09172091-747a-4c20-a405-b7930f9bc76b)

### This package's version (not the Home Assistant add-on version)

0.57

### Is Node-RED running in Docker?

Yes

### Node-RED version

3.1

### Node.js version

unknown

**Comment by zachowj** [comment]
The screenshot of the select missing from the dropdown is of the sensor node, not the select node.

**Comment by cdn4lf** [comment]
So maybe I'm confused.  How do I create a new select entity inline with an
existing flow?

**Comment by zachowj** [comment]
What are you trying to do? Have you looked at the examples?

https://zachowj.github.io/node-red-contrib-home-assistant-websocket/node/select.html#examples

**Comment by cdn4lf** [comment]
I'm trying to avoid making a text array if I can help it, but I don't think I have a choice.

I have a flow that's pulling Spotify playlist names and setting them as individual sensors.  I was hoping to simply program the 6 options as 6 default fields.

![image](https://github.com/zachowj/node-red-contrib-home-assistant-websocket/assets/49874417/d3cd6a4e-7458-4928-ada8-6018a266be36)

Based on the docs, my only real option is to do it separate from initializing the input_select

**Comment by zachowj** [comment]
I don't fully understand what you're going for. But if you're trying to dynamically set the options of the select you can do it using the update config node. There's an example of that.

**Comment by cdn4lf** [comment]
I saw that, was simply hoping to avoid that approach.

I'll close up the issue as everything is working and it was clearly user error.  Thank you for maintaining this, it's awesome.
