### ISSUE TITLE
Ikea Double switch stopped working after latest update

### ISSUE THREAD

**Issue by cmd85** [zachowj/node-red-contrib-home-assistant-websocket#1088]
### Describe the bug

My IKEA doubleswitcher which is used to toggle on/off a powersocket stopped sending in NodeRed after latest update.
The device itself is working fine and sends its signals in HA normal flow.

![nodered](https://github.com/zachowj/node-red-contrib-home-assistant-websocket/assets/50905040/67146522-5dfd-4d68-9b2f-d65f53a10705)

### Expected behavior

Button sends signals in node red

### Screenshots

![nodered](https://github.com/zachowj/node-red-contrib-home-assistant-websocket/assets/50905040/1cd73def-74a1-46b6-a03b-61628c557307)

### This package's version (not the Home Assistant add-on version)

0.33.1

### Is Node-RED running in Docker?

Home Assistant add-on

### Node-RED version

1.3.5

### Node.js version

13.17.1

**Comment by cmd85** [comment]
I noticed it works now by getting the entities state instead, is that new expected setup ? 
![noderedstate](https://github.com/zachowj/node-red-contrib-home-assistant-websocket/assets/50905040/ef2461d4-de2e-419b-8cea-7e26bc28b351)

**Comment by zachowj** [comment]
You probably upgraded the companion integration and didn't meet the minimum requirements.

**Comment by cmd85** [comment]
Ok, how would I go about fixing that issue , any good links for upgrading it correctly?

**Comment by zachowj** [comment]
> Only use this version if you're running 0.57+, currently in beta, of the Home Assistant nodes.

https://github.com/zachowj/hass-node-red/releases

Revert back to v2.2.0

**Comment by cmd85** [comment]
Ah ok, Thx.
I just pressed update via HACS as usual :)
