### ISSUE TITLE
halt if state is

### ISSUE THREAD

**Issue by jarzebskim** [zachowj/node-red-contrib-home-assistant-websocket#109]
I want to have some kind of service switch in my heating system. This swich should disable any forced settings of my thermostates.

I can do a swich in HA, check its state and set variable in the flow. Is it possible to use it in "pool state node" in “halt if state is” filed? How can I do that?

I tired:

is flow.nameofvariable
is flow.nameofvariable=True
is flow.nameofvariable==True

I can do this check in the next step but this can be more elegant way. Is it possible?

How to use flow. and global. in this node?

**Comment by zachowj** [comment]
Answered on your forum post:
https://community.home-assistant.io/t/halt-if-state-is-how-to-use-with-flow-variable/106271/4?u=kermit
