### ISSUE TITLE
Nodes relying on events are not sending any message

### ISSUE THREAD

**Issue by RomRider** [zachowj/node-red-contrib-home-assistant-websocket#110]
**Describe the bug**
Any node that relies on events is not working at all (nothing on the output) even though every other node which doesn't rely on events are working as expected.

**To Reproduce**
![image](https://user-images.githubusercontent.com/21064206/55682457-e9123700-5933-11e9-91d4-0727a3944523.png)

**Expected behavior**
When there is a state change for my entity, it should be displayed on the debug panel with this flow. I don't see anything.

**Screenshots**
See above.

**Example Flow**
N/A

**Environment (please complete the following information):**

- Node Red Version: 0.20.3
- NR Home Assistant Plugin Version: 0.10.2 (never worked before either)
- Is Node Red running in Docker: yes
- Hass: 0.90.2 (not using hass.io)

**Other (please complete the following information):**
Using SSL, tokens, and a reverse proxy in front of Home Assistant.
On the web interface, I receive all the events through the websocket (checked in chrome debug panel) and it's working as expected. On the events panel I can also receive all the events.

![image](https://user-images.githubusercontent.com/21064206/55682512-0267b300-5935-11e9-879d-7024888510b8.png)

- Have you searched previous issues for duplicates?: yes

**Additional context**
N/A

**Comment by RomRider** [comment]
Looks like my token was bugged... I changed it and now it works... Really strange as every other node not relying on events was working with the previous token.

**Comment by zachowj** [comment]
Check to see if you have two different configuration nodes

**Comment by RomRider** [comment]
No I have only one config node
