### ISSUE TITLE
Cannot search for entity in list. Cannot add events:state node for specific entity due to this

### ISSUE THREAD

**Issue by slbailey** [zachowj/node-red-contrib-home-assistant-websocket#1103]
### Describe the bug

I am no longer able to add events:state node for specific entities.  The list no longer filters based on what I type and I'm unable to type in the full entity name and have it appear in the list.

### To Reproduce

1. Add Event:State Node
2. In the entity field, select an entity (try to pick one not displayed in the drop down).
3. The list doesn't filter or move to the typed in entry and you are unable to enter the value manually as the list will select some arbitrary value.

### Expected behavior

I expect the entity list to filter down to the entities that match what I've typed in the field or, at the very least, I should be able to type in the full entity name and have it work.

### Screenshots

![image](https://github.com/zachowj/node-red-contrib-home-assistant-websocket/assets/141894/f6f8aca6-fcc3-4845-8c0e-0458bcd5a669)

### This package's version (not the Home Assistant add-on version)

0.57.2

### Is Node-RED running in Docker?

Home Assistant add-on

### Node-RED version

14.6.1

### Node.js version

unknown

**Comment by zachowj** [comment]
What browser?
Do you have any errors in the browser?

**Comment by slbailey** [comment]
No error in the browser.  As an update, I did some more research and when I typed in "binary_sensor.steve_in_bed" I got the results I shared above.  However, after scrolling all the way to the bottom of the drop down selection, I did see this entry and was able to saw it.

So I would say "it works" but the expected behavior is incorrect.  I would expect the drop down list to filter itself down as I type to only entries that match the string I'm typing in.  Typing in binary_sensor, for example, should ONLY list entries in the drop down that contain "binary_sensor" ... This list should also be sorted alphabetically and continue reducing in size as I type.  "binary_sensor.s" should only show binary sensors that start with the letter "s" -- this is not happening.

**Comment by marc-gist** [comment]
I started to see this as well. Even though you enter the exact ID, it is at the bottom of the list, when it should be the only item in the list as its a perfect and only match (well, I guess its possible to have others that match the first part, like 1, 2, 3 or something like that).

**Comment by ljmerza** [comment]
its a hit or miss for me whether the correct entity will pop up in the list. either way a ton of entites that dont even match what im searching for show up. its gotten worse lately

**Comment by ofirsnb** [comment]
Same issue here,   happened months ago (sorry,  can't pin the version of when it first started),  but same got worse lately.

More info if it helps:
I'm using the HA's NR addon,   first install about 3 years ago,   currently updated to the latest version.
Tested on both Chrome+Firefox - same result and no console errors.
Tried disabling/enabling "Cache autocomplete results" - no change.
Tried changing the "entity selector" from "friendly name" to "id" - same result on both.
There is no "pattern" I could find of which the other results are shown - looks like every day or two another list of entities are being shown atop of the searched entity.    Yet,  these "random" entities remain the same for about one day or two as said.
I have ~1800 active entities (+ ~300 disabled ones).

Most important,  as this issue says,   it happens **only** on `events:state` node,  on other nodes (like `current state` etc) it works perfectly fine.

Would be super helpful if this can be fixed.

Lemme know if other info is needed.
Thank you!

**Comment by ljmerza** [comment]
Still an issue

**Comment by bednim** [comment]
still an issue:
![image](https://github.com/zachowj/node-red-contrib-home-assistant-websocket/assets/43878548/e43e491d-086d-4610-ac8d-da90486479ba)


this happens for a long time - around few months but decided to look up this issue recently.

**Comment by ofirsnb** [comment]
Still an issue on latest version

**Comment by ofirsnb** [comment]
Still an issue on latest version

**Comment by tpjanssen** [comment]
I'm experiencing the same issue. A very annoying one.....

**Comment by zachowj** [comment]
fixed 57a8ab7845fb28d0ff082ebf67818130551ea27a
