### ISSUE TITLE
Not all Service Domains showing in service-node

### ISSUE THREAD

**Issue by niklasfink** [zachowj/node-red-contrib-home-assistant-websocket#111]
**Describe the bug**
When using the service-node, there are domains missing in the selection dropdown. I'm specifically looking for the "yeelight" domain to do a "set_mode".

**To Reproduce**

0. In HomeAssistant, check your available services and see that you have the "yeelight" service-domain available.
1. Create service-node in node-red.
2. Have a proper HomeAssistant system linked to your node-red.
3. Go to the "domain" field and try to select "yeelight" domain.

**Expected behavior**
I expect the "yeelight" domain to be available so that I can use that service domain and call methods like "set_mode" on it. However, this domain is not showing up as only the default domains like "light", "switch", ... are showing.

**Environment (please complete the following information):**

- Node Red Version: 0.20.3
- NR Home Assistant Plugin Version: 0.10.2 (most recent)
- Is Node Red running in Docker: hassio

**Comment by zachowj** [comment]
That is just autocomplete not showing it you can manually type it in and it will work fine.

Try running this flow and see if Home Assistant is passing yeelight along when `get_services` is called. If it doesn't show in the debug window Home Assistant isn't passing it along and there's really nothing that can be done on this end. If it does show then it could be a different issue.

```
[{"id":"3e6cdd5d.a9f382","type":"ha-api","z":"5eb3594f.d294b8","name":"","server":"ef067c6f.620e6","protocol":"websocket","method":"get","path":"","data":"{\"type\":\"get_services\"}","location":"payload","locationType":"msg","responseType":"json","x":226,"y":544,"wires":[["3d2221b4.3cbbbe"]]},{"id":"c93b91ba.e697f","type":"inject","z":"5eb3594f.d294b8","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":96,"y":544,"wires":[["3e6cdd5d.a9f382"]]},{"id":"3d2221b4.3cbbbe","type":"debug","z":"5eb3594f.d294b8","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":374,"y":544,"wires":[]}]
```

**Comment by niklasfink** [comment]
Strange, after a restart of hassio, all services are now showing up in the service-node (and are received via your supplied flow). Thanks!
