### ISSUE TITLE
Events: all node does not support variables in event data field

### ISSUE THREAD

**Issue by stevegroom** [zachowj/node-red-contrib-home-assistant-websocket#1120]
### Describe the bug

If set the Event Data field to {"device_ieee": "00:17:88:01:0b:59:ef:1a" } , it successfully matches when a button is pressed. 

Trying to make the flows more portable, I want to replace the id with an environment variable. 

https://nodered.org/docs/user-guide/environment-variables describes how env variables can be substituted in different ways, but it does not seem to work for the events: all Event Data field.

These did not work for ID = "00:17:88:01:0b:59:ef:1a"
{"device_ieee": "${ID}" }
{"device_ieee": "$env('ID')" }
{"device_ieee": "{{env.ID}}" }

### To Reproduce

1. Create flow environment variable called ID 
2. add events: all node
3. set Event Data to {"device_ieee": "{{env.ID}}" }
4. button press does not trigger the node

### Expected behavior

Node should trigger if matching with env variables

### Screenshots

Works with a static string: 
<img width="505" alt="image" src="https://github.com/zachowj/node-red-contrib-home-assistant-websocket/assets/2097486/a2b8ddc9-1516-4e66-9c13-0a18f6e21d32">

Does not work with a variable string:
<img width="497" alt="image" src="https://github.com/zachowj/node-red-contrib-home-assistant-websocket/assets/2097486/0121fe2b-55b4-4124-a976-b3e51f21b71f">

### This package's version (not the Home Assistant add-on version)

14.6.2

### Is Node-RED running in Docker?

Home Assistant add-on

### Node-RED version

3.1.0

### Node.js version

no idea

**Comment by zachowj** [comment]
https://nodered.org/docs/user-guide/environment-variables

> This only works if it replaces the entire property - it cannot be used to substitute just part of the value. For example, it is not possible to use CLIENT-${HOST}.

**Comment by stevegroom** [comment]
Ah! 
env : remote1_id = {"device_ieee": "00:17:88:01:0b:59:ef:1a" }

then
Event Data = ${remote2_id}
