### ISSUE TITLE
Auto complete no cache issues selecting new ids

### ISSUE THREAD

**Issue by marc-gist** [zachowj/node-red-contrib-home-assistant-websocket#1128]
### Describe the bug

When I try to select by ID, auto complete isn't always accurate, therefore, I can not select the correct entity.
I have auto complete cache off. Doesn't always help.

I should be able to manually ad an ID, without auto complete!

### To Reproduce

1. create new entity id
2. goto node red try to select via state change from auto complete.
3. if not in list, try to leave the id in the field. 
4. it will select the first one for the auto complete list rather than your manual id typed in.

### Expected behavior

allow me to enter my entity_id manually!

### Environment Information

Version: 

Home Assistant version: utd
Companion version: utd

Node-RED version: utd
Docker: yes
Add-on: no

Node.js version: docker image
OS: docker img

**Comment by zachowj** [comment]
> Custom ids can be inserted into the list by adding a # at the end of the id

https://zachowj.github.io/node-red-contrib-home-assistant-websocket/node/events-state.html#entity-id

**Comment by marc-gist** [comment]
> > Custom ids can be inserted into the list by adding a # at the end of the id
> 
> https://zachowj.github.io/node-red-contrib-home-assistant-websocket/node/events-state.html#entity-id

bah, sorry, guess I didn't read the first part of the documents for that section :( thank you!
