### ISSUE TITLE
Number Node (beta) - unit of measurement does not appear to be correctly reflected

### ISSUE THREAD

**Issue by illuzn** [zachowj/node-red-contrib-home-assistant-websocket#1138]
### Describe the bug

In the Number Node (beta), setting the unit of measurement correctly applies within Node-RED however the  details are not reflected in the entity attributes in Home Assistant.

### To Reproduce

1. Import the following number node:
````json
[{"id":"11a6c81c23f185ba","type":"ha-number","z":"0696dd904aa6c7de","name":"test","version":1,"debugenabled":false,"inputs":0,"outputs":1,"entityConfig":"a733dab73ae8e41f","mode":"listen","value":"payload","valueType":"msg","outputProperties":[{"property":"payload","propertyType":"msg","value":"","valueType":"value"},{"property":"previousValue","propertyType":"msg","value":"","valueType":"previousValue"}],"x":1270,"y":700,"wires":[[]]},{"id":"a733dab73ae8e41f","type":"ha-entity-config","server":"f1028730287dd073","deviceConfig":"","name":"test","version":"6","entityType":"number","haConfig":[{"property":"name","value":"test"},{"property":"icon","value":""},{"property":"entity_category","value":""},{"property":"entity_picture","value":""},{"property":"device_class","value":""},{"property":"unit_of_measurement","value":"m"},{"property":"min_value","value":""},{"property":"max_value","value":""},{"property":"step_value","value":""},{"property":"mode","value":"auto"}],"resend":false,"debugEnabled":false}]
````
2. Deploy
3. Using Home Assistant developer tools the `unit_of_measurement` attribute is not set.

### Expected behavior

The `unit_of_measurement` attribute should be set as appropriate.

### Environment Information

Version: 

Home Assistant version: 2023.11.0
Companion version: 3.0.1

Node-RED version: 15.0.0
Docker: no
Add-on: yes

Node.js version:
OS: HA OS 11.1

**Comment by zachowj** [comment]
Fixed https://github.com/zachowj/hass-node-red/commit/4847f98cc728536372279ad503c27a3c519d6bd4
