### ISSUE TITLE
Entity search always returns unavailable entities regardless of the search

### ISSUE THREAD

**Issue by hagak** [zachowj/node-red-contrib-home-assistant-websocket#1149]
### Describe the bug

If you type in the entity field for the events: state node (probably others as well).  It will always return any "unavailable entities" even if what is typed does not match any part.  example I could type "ASDFASKJASFDGD" which I have no entities that match this but ALL of the unavail entites are listed.    I have a few devices that are seasonal and notice that when they are online they do not show in the list.

### To Reproduce

1. Have entities defined in HA that are unavailable, good test is a seasonal item that is offline most of the year
2. In the events:state node type gibberish into the Entity field (that does not match any entity in your system)
3. Note all unavailable entities are in the list.

### Expected behavior

Only entities that match the search criteria should be shown.

### Environment Information

Version: 

Home Assistant version:
Companion version: 3.1.1

Node-RED version: 0.59
Docker: yes
Add-on: no

Node.js version:
OS:

**Comment by Raspatat** [comment]
I have the same experience. As a workaround I use a substring with the full entity name, the issue does not occur then.

**Environment Information**
Version:

Home Assistant version:
Core 2023.12.0

Node-RED version: 3.1.1
node-red-contrib-home-assistant-websocket: 0.59.0
Docker: yes
Add-on: no

**Comment by hagak** [comment]
This is still a bug, adding activity to prevent auto-closure.

**Comment by hagak** [comment]
Still a bug

**Comment by hagak** [comment]
This is still a bug

**Comment by zachowj** [comment]
should be fixed 57a8ab7845fb28d0ff082ebf67818130551ea27a
