### ISSUE TITLE
current state node stops flow if entity doesn't exist

### ISSUE THREAD

**Issue by heikomat** [zachowj/node-red-contrib-home-assistant-websocket#115]
**Describe the bug**
[logAndContinueEmpty](https://github.com/zachowj/node-red-contrib-home-assistant-websocket/blob/29d7330b08a04b34e30b8f78b6f3f71ad10bdcff/nodes/current-state/current-state.js#L44) does not actually continue anymore.

i'm trying to check the existence of an entity using the `current state` node, by checking if `msg.data.state` is `null` or `'unavailable'`. This was working in the past, but is not working now, because the flow isn't continued (as in: the next node isn't executed)

**To Reproduce**

1. add a simple "current state" node for an entity that doesn't exist
2. put a debug node behind the current state node, and make it log the whole msg object
3. open the debug message panel
4. trigger the flow
5. see how the error message ""entity could not be found in cache for entity_id: YOUR_ENTITY_ID, sending empty payload" is logged
6. see how nothing from the debug node is logged, because it stops executing after the current state node

**Expected behavior**
The warning says "sending empty payload". i would therefore expect the execution of the flow to continue with an empty payload

**Screenshots**
<img width="946" alt="Screenshot 2019-04-24 at 22 57 03" src="https://user-images.githubusercontent.com/20770029/56693266-50760800-66e4-11e9-99da-f401f8fc418d.png">

**Example Flow**
<details>
<summary>click to open</summary>

```JSON
[
    {
        "id": "85192604.ea2b88",
        "type": "tab",
        "label": "Flow 1",
        "disabled": false,
        "info": ""
    },
    {
        "id": "de847ed2.eedc9",
        "type": "api-current-state",
        "z": "85192604.ea2b88",
        "name": "",
        "server": "8c8a6e3b.c09a4",
        "outputs": 1,
        "halt_if": "",
        "halt_if_type": "str",
        "halt_if_compare": "is",
        "override_topic": false,
        "entity_id": "some_entity",
        "state_type": "str",
        "state_location": "payload",
        "override_payload": "msg",
        "entity_location": "data",
        "override_data": "msg",
        "x": 860,
        "y": 120,
        "wires": [
            [
                "bec9e3ca.ea63e"
            ]
        ]
    },
    {
        "id": "bec9e3ca.ea63e",
        "type": "debug",
        "z": "85192604.ea2b88",
        "name": "",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "true",
        "targetType": "full",
        "x": 1070,
        "y": 120,
        "wires": []
    },
    {
        "id": "d5a2b0fc.3e9c7",
        "type": "inject",
        "z": "85192604.ea2b88",
        "name": "",
        "topic": "",
        "payload": "",
        "payloadType": "date",
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "x": 640,
        "y": 120,
        "wires": [
            [
                "de847ed2.eedc9"
            ]
        ]
    },
    {
        "id": "8c8a6e3b.c09a4",
        "type": "server",
        "z": "",
        "name": "home.heikomat.com",
        "legacy": false,
        "hassio": true,
        "rejectUnauthorizedCerts": true,
        "ha_boolean": "y|yes|true|on|home|open",
        "connectionDelay": true
    }
]
```

</details>

**Environment (please complete the following information):**

- Node Red Version: 0.20.5
- NR Home Assistant Plugin Version: 0.10.2 (node-red-contrib-home-assistant-websocket) / 3.0.2 (node red hassio addon)
- Is Node Red running in Docker: yes (i'm using the dockerized hassio instance, which spawns a docker container for every hassio addon)

**Other (please complete the following information):**

- Have you searched previous issues for duplicates?: yes

**Additional context**
i'm trying to check if plex is playing something on my main computer. the media player entity for that plex instance is unavailable however, if plex isn't currently running on that computer. 
Therefore i'd like to handle "media player entity doesn't exist" and "plex is available, but not currently playing" the same.
This has been working before, but the flow execution now stops, when the entity is unavailable, resulting in my flow no longer working.

**Comment by zachowj** [comment]
I actually noticed this the other day when I was refactoring the current-state node. This has never actually worked as it is stated "sending empty payload" in the websocket version. It is actually a pretty simple fix but at this point, I am more worried about consequences to existing flows if I fix this. It might be more useful to just reword the error and leave it stopping the flow.

One possible solution for you currently is to use a function node

```javascript
const states = global.get('homeassistant').homeAssistant.states;
const plex = states['media_player.plex'];

if (plex && plex.state === "playing") {
    return null;
}
  
return msg;
```

**Comment by zachowj** [comment]
Another possible solution would be to use a get-entities node and check if the count equal to zero.

```
[{"id":"62640ba9.94e404","type":"ha-get-entities","z":"ffbd7f06.4a014","server":"2dad33ee.42bf5c","name":"","rules":[{"property":"entity_id","logic":"is","value":"media_player.plex","valueType":"str"},{"property":"state","logic":"is","value":"playing","valueType":"str"}],"output_type":"count","output_empty_results":false,"output_location_type":"msg","output_location":"payload","output_results_count":1,"x":358,"y":720,"wires":[["9152428d.7c548"]]}]
```

**Comment by heikomat** [comment]
Both of these solutions sound reasonable, thank you :)

But rewording the warnings in this file would definitely be a good idea, so that it tells the user that the flow was stopped there
