### ISSUE TITLE
Templating cannot return integer?

### ISSUE THREAD

**Issue by ciB89** [zachowj/node-red-contrib-home-assistant-websocket#117]
**Describe the bug**
When using the service call node, it says in the description that we can use templates, e.g. for accessing states. I was trying to implement a dimmer for my lights based on their current brightness settings, but unfortunately adding templates to the data field does not work. Either the JSON is incorrect (if I leave out the '"') or it does not resolve the template correctly. 

> "Call-service API error. Error Message: expected int for dictionary value @ data['brightness']"

**To Reproduce**

Service call node with light.turn_on and in the data field add:

`{"brightness": {{states.light.unterschraenke.attributes.brightness + 64}}}`
or
`{"brightness": "{{states.light.unterschraenke.attributes.brightness + 64}"}}`

**Expected behavior**
Calling the service with (example)
`{"brightness": 190}` or
`{"brightness": "190"}`
**Screenshots**

**Example Flow**

**Environment (please complete the following information):**
 - NR Home Assistant Plugin Version: 3.0.3 hassio

**Other (please complete the following information):**
- Have you searched previous issues for duplicates?: Yes
- Did you attempt to reproduce the issue in the dev docker environment, if so what were results (See README.md): No

**Additional context**

**Comment by zachowj** [comment]
You are unable to do arithmetic inside a mustache template.
