### ISSUE TITLE
HASS Post gets connection error 401 (not authorized)

### ISSUE THREAD

**Issue by Haacker** [zachowj/node-red-contrib-home-assistant-websocket#118]
**Describe the bug**
I have the home assistant web sockets node in my Node-Red pallet. I have it configured to use a long lived access token in HASS and I am trying to use the HASS POST node to send some data to HASS. When the flow runs, I get a 401 error in the debug for the flow.

**To Reproduce**

**Expected behavior**
I expected the msg.payload JSON to be sent to HASS to update the state on an entity there.

**Screenshots**
![image](https://user-images.githubusercontent.com/2917971/57717889-2a3fea00-764a-11e9-90e1-527fd0013838.png)

![image](https://user-images.githubusercontent.com/2917971/57717943-417ed780-764a-11e9-901c-4316c8169597.png)

**Example Flow**
[{"id":"c21a43b4.023cc","type":"tab","label":"Flow 1","disabled":false,"info":""},{"id":"d881ca12.b980b8","type":"inject","z":"c21a43b4.023cc","name":"","topic":"","payload":"{\"state\":\"new_state\"}","payloadType":"json","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":150,"y":180,"wires":[["e2f821f0.e4523","a182ef38.54b0b"]]},{"id":"e2f821f0.e4523","type":"hass-post","z":"c21a43b4.023cc","endpoint":"3cad400b.7c656","entityid":"sump_pump.lastrantime","name":"Post to HASSiIO","x":420,"y":180,"wires":[]},{"id":"a182ef38.54b0b","type":"debug","z":"c21a43b4.023cc","name":"","active":true,"tosidebar":true,"console":false,"tostatus":true,"complete":"payload","targetType":"msg","x":410,"y":80,"wires":[]},{"id":"3cad400b.7c656","type":"hass-config","z":"","host":"http://localhost","port":"8123"}]

**Comment by zachowj** [comment]
The node you are referencing is not part of this package.
