### ISSUE TITLE
Call Service node requires putting a value in Data field

### ISSUE THREAD

**Issue by mrreview** [zachowj/node-red-contrib-home-assistant-websocket#1183]
### Describe the bug

If Data field is left empty then it complains about invalid value

### To Reproduce

Use a Call Service node and leave Data field blank.

### Expected behavior

It should be optional and don't complain

### Screenshots

![image](https://github.com/zachowj/node-red-contrib-home-assistant-websocket/assets/5017072/cff27881-e1d5-4e7b-9b3c-5e170b10bd92)
![image](https://github.com/zachowj/node-red-contrib-home-assistant-websocket/assets/5017072/ceb30b1a-04bc-4104-96c4-834bff786456)

### Example Flow

```json
[
    {
        "id": "6dc50e1f59a8cdeb",
        "type": "api-call-service",
        "z": "c876c6844a9471d4",
        "name": "test toggle light",
        "server": "22accfe0.1a85a",
        "version": 5,
        "debugenabled": false,
        "domain": "light",
        "service": "toggle",
        "areaId": [],
        "deviceId": [],
        "entityId": [
            "light.shelly_2_5_llum_despatx_rebedor_relay_0"
        ],
        "data": "",
        "dataType": "jsonata",
        "mergeContext": "",
        "mustacheAltTags": false,
        "outputProperties": [],
        "queue": "none",
        "x": 1080,
        "y": 140,
        "wires": [
            []
        ]
    },
    {
        "id": "22accfe0.1a85a",
        "type": "server",
        "name": "Home Assistant",
        "version": 5,
        "addon": false,
        "rejectUnauthorizedCerts": true,
        "ha_boolean": "y|yes|true|on|home|open",
        "connectionDelay": true,
        "cacheJson": true,
        "heartbeat": false,
        "heartbeatInterval": "30",
        "areaSelector": "friendlyName",
        "deviceSelector": "friendlyName",
        "entitySelector": "friendlyName",
        "statusSeparator": "at: ",
        "statusYear": "hidden",
        "statusMonth": "short",
        "statusDay": "numeric",
        "statusHourCycle": "h23",
        "statusTimeFormat": "h:m",
        "enableGlobalContextStore": true
    }
]
```

### Environment Information

Version: 0.59.0

Home Assistant version: 2023.11.3
Companion version:

Node-RED version: 3.1.1
Docker: no
Add-on: no

Node.js version: 20.10.0
OS: Ubuntu 22.04.3 LTS

**Comment by obbers** [comment]
I'm also seeing this in the Node-RED docker version.

**Comment by Balooforever** [comment]
Same problem, +1

**Comment by aeleus** [comment]
I'm seeing the same problem. Previously configured nodes are fine, but new nodes with empty data fields indicate a problem as shown above.

Happened while running version 0.56.1 and also after upgrading to 0.59.0.

**Comment by eamonnsullivan** [comment]
I noticed this only happening in the last couple of days. I'm using version 0.59.0 with Home Assistant (container) 2023.12.1 and Node Red (docker) 3.1.3. The workaround is just to put '{}' in data.

**Comment by Caros2017** [comment]
Same issue here in the newest docker. Started at `0.56.1`. At this version I also got API errors after opening an entity. So I just updated to `0.59.0`. Issue exists, but have to use the same workaround as above. I also putted `{}` in data.
