### ISSUE TITLE
v0.60.1 - Syntax error, unrecognized expression

### ISSUE THREAD

**Issue by DanijelVOCKIC** [zachowj/node-red-contrib-home-assistant-websocket#1187]
### Describe the bug

Hi, 

after the update to v0.60.1 all my call-service note got the same error "Syntax error, unrecognized expression"

<img width="495" alt="Bildschirmfoto 2023-12-10 um 09 53 17" src="https://github.com/zachowj/node-red-contrib-home-assistant-websocket/assets/61582369/80e03ba0-9f59-4ef1-a023-30920b6ba52c">
<img width="669" alt="Bildschirmfoto 2023-12-10 um 09 54 20" src="https://github.com/zachowj/node-red-contrib-home-assistant-websocket/assets/61582369/60ddd87d-d9bc-4ee4-8200-48dafde19109">

### Environment Information

Version: 

Home Assistant version: 2023.12
Companion version:

Node-RED version: 3.1.0
Docker: no
Add-on: no

Node.js version:
OS:

**Comment by zachowj** [comment]
What version of Node-RED is the add-on running in the version?

**Comment by zachowj** [comment]
Version 60.1+ is going to require Node-RED 3.1.1+

**Comment by mortenmoulder** [comment]
I experience the same issue. Also Data being required/red colored for all call service nodes

**Comment by DanijelVOCKIC** [comment]
now nothing works anymore

<img width="1220" alt="Bildschirmfoto 2023-12-10 um 11 03 17" src="https://github.com/zachowj/node-red-contrib-home-assistant-websocket/assets/61582369/54d54cd8-b112-4c03-b48c-2e6fbde0929c">
<img width="1011" alt="Bildschirmfoto 2023-12-10 um 11 03 53" src="https://github.com/zachowj/node-red-contrib-home-assistant-websocket/assets/61582369/6d71e7ac-2257-4393-b209-10f50535dd1a">
