### ISSUE TITLE
trying to "catch" errors

### ISSUE THREAD

**Issue by rbflurry** [zachowj/node-red-contrib-home-assistant-websocket#119]
**Describe the bug**
This may not be related or it might be something I am doing wrong or nodered is doing wrong.

I have a flow to watch recorder to make sure it is still working. It fires every minute and checks for historical events for a certain device. It then generates a notification if there is no history. This is done using the get history node. This all works fine.

However if recorder fails to load on bootup the get history node now fails with the following message.

```
5/21/2019, 8:18:49 AMnode: f77c4142.82f1e
msg : string[44]
"Error get-history, home assistant api error."
```

I tried using a catch node to collect this message and trigger a new alert but the catch does not seem to capture the error and trigger the flow.

**To Reproduce**
1. Use a time trigger to fire a get history node when recorder is disabled.
2. use a catch node to catch the errors and trigger a new flow.

**Expected behavior**
Catch node will trigger second flow to alert on API error.

**Screenshots**

**Example Flow**
If applicable, add an example of exported json of a flow exhibiting the issue to aid in reproduction.

**Environment (please complete the following information):**

- Node Red Version: [e.g. 0.19.5]
0.19.5
- NR Home Assistant Plugin Version: [e.g. 0.5.0]
0.11.0
- Is Node Red running in Docker: [e.g. yes/no/hassio]
yes
**Other (please complete the following information):**

- Have you searched previous issues for duplicates?:
yes
**Additional context**

**Comment by zachowj** [comment]
The get-history is not reporting the error correctly so you'll be unable to use the catch node. I'll get a fix out for it.

**Comment by zachowj** [comment]
Here's a possible workaround until I get the fix in. Makes an API call on connecting to check the config if the recorder component is loaded.

```
[{"id":"f01a1cb.d14c2e","type":"server-events","z":"5eb3594f.d294b8","name":"","event_type":"home_assistant_client","x":152,"y":1424,"wires":[["4e7684ca.c8abfc"]]},{"id":"29575c5c.48e354","type":"ha-api","z":"5eb3594f.d294b8","name":"","protocol":"websocket","method":"get","path":"","data":"{\"type\": \"get_config\"}","location":"payload","locationType":"msg","responseType":"json","x":610,"y":1424,"wires":[["14404559.255e2b"]]},{"id":"14404559.255e2b","type":"function","z":"5eb3594f.d294b8","name":"","func":"const loaded = msg.payload.components.find(ele => ele === \"recorder\");\n\nif(loaded === \"recorder\") return;\n\nreturn msg;","outputs":1,"noerr":0,"x":738,"y":1424,"wires":[["4d05ef9d.65179"]]},{"id":"4d05ef9d.65179","type":"debug","z":"5eb3594f.d294b8","name":"Do something because recorder didn't load","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":996,"y":1424,"wires":[]},{"id":"4e7684ca.c8abfc","type":"switch","z":"5eb3594f.d294b8","name":"","property":"payload","propertyType":"msg","rules":[{"t":"eq","v":"connected","vt":"str"}],"checkall":"true","repair":false,"outputs":1,"x":338,"y":1424,"wires":[["e02ce0a5.69f85"]]},{"id":"e02ce0a5.69f85","type":"delay","z":"5eb3594f.d294b8","name":"","pauseType":"delay","timeout":"5","timeoutUnits":"seconds","rate":"1","nbRateUnits":"1","rateUnits":"second","randomFirst":"1","randomLast":"5","randomUnits":"seconds","drop":false,"x":476,"y":1424,"wires":[["29575c5c.48e354"]]}]
```
