### ISSUE TITLE
6.1.1 will not stay installed after NR restart

### ISSUE THREAD

**Issue by derekakessler** [zachowj/node-red-contrib-home-assistant-websocket#1199]
### Describe the bug

After updating to version 6.1.1 of these nodes they will not stay installed when Node-Red is restarted. When NR starts, all HA nodes show as "unknown", all associated flows are stopped, and no HA nodes are available in the palette.

node-red-contrib-home-assistant-websocket no longer shows as installed in the palette manager, but is available under the install tab. When installed, the nodes properly reassert themselves but as version 0.59.0.

The next time NR is restarted, all HA nodes revert to "unknown".

### To Reproduce

1. Update or install 6.1.1 nodes
3. Restart Node-Red
4. Open NR, see HA nodes all marked as "unknown" and HA nodes missing from the palette.
5. Return to step 1.

### Expected behavior

1. Update or install 6.1.1 nodes
2. Restart Node-Red
3. Open NR and see HA nodes present and functioning

### Screenshots

Missing nodes after 6.1.1 update and restart:
![screenshot 2023-12-11 at 16 09 03](https://github.com/zachowj/node-red-contrib-home-assistant-websocket/assets/1646121/ce64a50e-e10a-489c-a096-6ce2ec255902)

Restored nodes after reinstallation of 6.1.1:
![screenshot 2023-12-11 at 16 11 13](https://github.com/zachowj/node-red-contrib-home-assistant-websocket/assets/1646121/b62d44d6-cd0c-4222-82f2-7f3d6bca73d5)

### Environment Information

Version: 6.1.1

Home Assistant version: 2023.12.1
Companion version: 3.1.1

Node-RED version: 16.0.2
Docker: no
Add-on: no

Node.js version:
OS:

**Comment by zachowj** [comment]
Node-RED 3.1.1 is required

**Comment by raphaelsavina** [comment]
Ah!! indeed. I actually got v3.1.3 now and it is all back to normal.
Raphaël
