### ISSUE TITLE
Allow/offer ability to pass error message on node failure.

### ISSUE THREAD

**Issue by ghvader** [zachowj/node-red-contrib-home-assistant-websocket#120]
**Is your feature request related to a problem? Please describe.**
using the call service node, specifically calling the hangouts.send_message service, sometimes the service becomes disconnected. Manually issuing a reconnect fixes the issue.
I would like to automate this, however when it fails, the call service node doesn't pass any messages that i can use, it logs an error, but nothing is output to the next node if it fails, so I have nothing that i can look for to automate a reconnect.

**Describe the solution you'd like**
Allow a error message of some sort if the call service node fails
that way i can look for "Error" or whatever text comes out, i can then automate a fix at present it simply stops at the call service node and goes no further.

**Describe alternatives you've considered**
none see possible if the output of a failed service call does not exist.

**Additional context**
n/a

**Comment by zachowj** [comment]
This is what the catch and status nodes are for. On the dev branch or in the next release you'll be able to use the catch node. Currently, you can make it work with a status node.

**Comment by ghvader** [comment]
@zachowj Thanks for the reply. I had tried the status node, but it only shows "undefined" in the current release. which is too generic form me to do anything with, hence the request.
I will see what the next release brings, perhaps it will work better for me. thanks!

**Comment by zachowj** [comment]
The status node doesn't output a payload so `msg.payload` would be undefined but `msg.status` should contain information about what the status of the node was change to.

**Comment by ghvader** [comment]
@zachowj well that worked :)
thanks for the tip. i will close this request as that will get me where i need to be.
