### ISSUE TITLE
v0.62.1 Failed to upgrade, failed to install

### ISSUE THREAD

**Issue by SergioRius** [zachowj/node-red-contrib-home-assistant-websocket#1206]
### Describe the bug

After upgrading the node, asked to reboot the node-red instance, then a message saying that the flows are stopped due to missing nodes (ALL HA NODES) is shown.
Going to the palette reveals that the package is not installed.
Installation fails with the following log:

```
-----------------------------------------------------------
2023-12-14T17:37:13.543Z Install : node-red-contrib-home-assistant-websocket 0.62.1

2023-12-14T17:37:13.929Z npm install --no-audit --no-update-notifier --no-fund --save --save-prefix=~ --production --engine-strict node-red-contrib-home-assistant-websocket@0.62.1
2023-12-14T17:37:14.306Z [err] npm
2023-12-14T17:37:14.306Z [err]  
2023-12-14T17:37:14.306Z [err] WARN
2023-12-14T17:37:14.306Z [err]  
2023-12-14T17:37:14.306Z [err] config
2023-12-14T17:37:14.306Z [err]  production Use `--omit=dev` instead.
2023-12-14T17:37:17.164Z [out] 
2023-12-14T17:37:17.164Z [out] up to date in 3s
2023-12-14T17:37:17.183Z rc=0
```

### Environment Information

Version: 

Home Assistant version:
Companion version:

Node-RED version:
Docker: no
Add-on: no

Node.js version:
OS:

**Comment by osulivanDE** [comment]
Same Problem for me. I can reinstall "node-red-contrib-home-assistant-websocket" and my nodes work as long as i do not restart Node-Red

**Comment by osulivanDE** [comment]
Workaround for me was this post to manually upload the file: https://github.com/hassio-addons/addon-node-red/issues/1774#issuecomment-1854478442

**Comment by SergioRius** [comment]
> You need to restore a a backup. Please refer to this post:
> 
> [#1198 (comment)](https://github.com/zachowj/node-red-contrib-home-assistant-websocket/issues/1198#issuecomment-1853220172)

I don't have node-red installed as an Addon.

**Comment by SergioRius** [comment]
So I downgraded the node to version 0.60.1 and that seems to install completely.
I forgot to mention that I'm on HA version 2023.12.2, so I guess it shouldn't be any problem at all.

But with this node version, I think a new field "Data" has been added to the `api-call-service` and `server-events`nodes that break my flows. I can't see any documentation on it and I don't know what must be informed. I don't know why shows as a required field, when the summary on the palette doesn't indicate as required.

I need help on this.

**Comment by SergioRius** [comment]
> > But something should be done with those last "unstable" versions released. Or at least any explanation in how the upgrades should be done from here for not to lose our installations.
> 
> Meet the requirements of the package and it will run fine. In your case, update Node-RED to 3.1.1+.

I was so focused on HA that I forgot node-red version.
