### ISSUE TITLE
wait until

### ISSUE THREAD

**Issue by rbflurry** [zachowj/node-red-contrib-home-assistant-websocket#121]
**Is your feature request related to a problem? Please describe.**

Can the wait until node take the entity_id from an incoming message?
**Describe the solution you'd like**
the wait until node uses the entity_id from the incoming message such as msg.topic
Just like the current_state node does
![image](https://user-images.githubusercontent.com/22154114/58349441-553bf200-7e31-11e9-80f2-fe7bc283cbde.png)

**Describe alternatives you've considered**

Currently I use a delay and current state loop.

**Additional context**

![image](https://user-images.githubusercontent.com/22154114/58349102-67696080-7e30-11e9-947d-b8d8500293a3.png)

**Comment by JCrankWV** [comment]
I would also like to see this feature.

Thanks for the Great work

**Comment by zachowj** [comment]
https://github.com/zachowj/node-red-contrib-home-assistant-websocket/commit/c4d308196f4f34d369b451b376a507b30508cc75

**Comment by JCrankWV** [comment]
thank you
