### ISSUE TITLE
After attempting to update from 0.59.0 to 0.62.2, Node no longer works - Nach versuchtem Update von 0.59.0 auf 0.62.2 funktioniert Node nicht mehr

### ISSUE THREAD

**Issue by zumheulen** [zachowj/node-red-contrib-home-assistant-websocket#1214]
### Describe the bug

I wanted to update the node under Palette from 0.59.0 to 0.62.2 while it was running (Nodered under Homeassistant). But since then the flows have no longer been executed because the node crashes. It then has to be reinstalled, but appears again under version 0.59.0 with an update function to 0.62.2.
If you do this, the node will crash again.
I even completely reinstalled Nodered and deleted the old folder beforehand, always the same problem.

Auf Deutsch:
Ich hatte im laufenden Betrieb (Nodered unter Homeassistant) die Node unter Palette von 0.59.0 auf 0.62.2 updaten wollen. Doch seither werden die Flows nicht mehr ausgeführt da die Node abstürzt. Sie muss dann neu installiert werden, erscheint aber wieder unter Version 0.59.0 mit Updatefunktion auf 0.62.2.
Führt man dies aus, stürzt die Node wieder ab.
Hatte sogar Nodered komplett neu installiert und vorher alten Ordner gelöscht, immer das selbe Problem.

### Screenshots

![HA_websocket Update](https://github.com/zachowj/node-red-contrib-home-assistant-websocket/assets/81460155/f7bb47c9-ab0c-484c-aa8e-eddf7a1ca89c)

### Environment Information

Version: 16.0.2

Home Assistant version: OS 11.2  (amd64 / generic-x86-64)
 Home Assistant Core: 2023.12.3
 Home Assistant Supervisor: 2023.12.0

Node-RED version:
Docker: no
Add-on: no

Node.js version: 0.59.0 to 0.62.2
OS:

**Comment by emimor123** [comment]
Same to me, when I update to 0.62.2 from 0.59.0 and restart node-red all nodes in node-red-contrib-home-assistant-websocket dissappear. I have to install again. But when node-red is restarted, nodes dissappear again.
Are there any way to downgrade to 0.59.0 or install 0.59.0?

**Comment by zolakt** [comment]
I have the same issue. It keep deleting itself after upgrade.
When I manually install it again, it installs the 0.59.0 version.

**Comment by zachowj** [comment]
> 20 Dec 19:51:42 - [warn] [node-red-contrib-home-assistant-websocket] Node module cannot be loaded on this version. Requires: >=3.1.1

**Comment by emimor123** [comment]
There are not Hass-os 3.1.1 Node-Red version available. I try to restore node-red from previous backup, but do not resolve problem. Websocket nodes disappear in each restart. 

Please how can I to go back websocket's nodes to 0.59.0 version?

**Comment by mP765** [comment]
> Please how can I to go back websocket's nodes to 0.59.0 version?

This worked for me: https://forums.opto22.com/t/install-older-version-specific-version-of-a-node-red-node/3796/4.
You can choose any version from here: https://www.npmjs.com/package/node-red-contrib-home-assistant-websocket?activeTab=versions.

I used 0.60.1 (download: https://registry.npmjs.org/node-red-contrib-home-assistant-websocket/-/node-red-contrib-home-assistant-websocket-0.60.1.tgz) since it is the last version requiring only Node-RED v3.0.0+, and it works just fine even after restarting Node-Red in Home Assistant several times.

**Comment by alexruffell** [comment]
> There are not Hass-os 3.1.1 Node-Red version available. I try to restore node-red from previous backup, but do not resolve problem. Websocket nodes disappear in each restart.
> 
> Please how can I to go back websocket's nodes to 0.59.0 version?

https://community.home-assistant.io/t/warning-do-not-update-websocket-to-0-61-1-with-add-on-version-16-0-2/653887/5?u=aruffell

```
FYI, for those having issues, here;s what I did to revert back (Home-Assistant supervised):
1- stop Node-red addon
2- on your home-assistant OS:
cd /usr/share/hassio/addon_configs/a0d7b954_nodered
sudo vi package.json
3- in the package.json file, locate the node-red-contrib-home-assistant-websocket
4- change the version to “~0.59.0”
5- save and exit
6- start Node-red addon.
```

I did the above but simply opening the json file in Notepad++ from the shared node red config folder. Once the file was edited and I rebooted, the websocket was still installed and working.

**Comment by emimor123** [comment]
Ok, perfect, Thank you very much. This trick works for me. 
Now I can wait patiently to node-red 3.1.1 update. 
Thanks again.

**Comment by townsmcp** [comment]
Same just happened to me - NR completely blew up after installing the updated pallete.
To get round it, I did a partial restore from last nights HA backup - restored just NR and its back on the older version and working fine
