### ISSUE TITLE
Nodes uninstalled after restart

### ISSUE THREAD

**Issue by giorgiomanieri** [zachowj/node-red-contrib-home-assistant-websocket#1217]
### Describe the bug

In Home Assistant when I update node-red-contrib-home-assistant-websocket from Manage Palette from 0.59.0 to 0.62.2, after restarting Node-Red, the nodes are uninstalled. I have to reinstall again the nodes to have flows working properly but if I restart the system or Node-red, I lose again the nodes. When I reinstall node-red-contrib-home-assistant-websocket, the version is 0.59.0 (not the newest 0.62.2)

Same issue on 2 different HA servers.

### To Reproduce

1. Go to Manage Palette to update node-red-contrib-home-assistant-websocket to v0.62.2
2. Restart Node-red to apply the update
3. Nodes have been uninstalled

### Screenshots

![image](https://github.com/zachowj/node-red-contrib-home-assistant-websocket/assets/54476289/c4abae2e-3977-4084-8cb7-fd984eb7fdc4)
![image](https://github.com/zachowj/node-red-contrib-home-assistant-websocket/assets/54476289/29f2533a-1791-4cd3-a5d5-b3bafdea2b1e)
![image](https://github.com/zachowj/node-red-contrib-home-assistant-websocket/assets/54476289/20a8c74d-3704-4736-9df6-03e4339e54ae)
![image](https://github.com/zachowj/node-red-contrib-home-assistant-websocket/assets/54476289/b48eabf2-6b75-4b0a-8c26-5aab64140062)

### Environment Information

Version: 

Home Assistant version: 2023.12.3

Node-RED version: 3.1.0
Docker: no
Add-on: yes

Node.js version:
OS:

**Comment by zachowj** [comment]
0.62.2 required Node-RED 3.1.1+
