### ISSUE TITLE
Update errors node-red-contrib-home-assistant-websocket when??

### ISSUE THREAD

**Issue by aavosnl** [zachowj/node-red-contrib-home-assistant-websocket#1218]
### Describe the bug

When there is an update for the problems with node-red-contrib-home-assistant-websocket and home assisstant?  

### Environment Information

Version: 

Home Assistant version:
Companion version:

Node-RED version:
Docker: no
Add-on: no

Node.js version:
OS:

**Comment by zachowj** [comment]
No idea about your issue.

**Comment by aavosnl** [comment]
The issue is that the node-red-contrib-home-assistant-websocket is not longer working ok under node-red in home asssistant. 

[https://community.home-assistant.io/t/warning-do-not-update-websocket-to-0-61-1-with-add-on-version-16-0-2/653887](url)

**Comment by zachowj** [comment]
You have to wait until the hass add-on gets updated. It doesn't have anything to do with this package.
