### ISSUE TITLE
Invalid format of Base URL: undefined

### ISSUE THREAD

**Issue by DominikPalo** [zachowj/node-red-contrib-home-assistant-websocket#122]
**Describe the bug**
I'm trying to setup connection to my Home Assistant server, but every time I click the "Update" button, the error "Invalid format of Base URL: undefined" pop-ups.
 
**To Reproduce**

1. Go to the 'events: all' entity configuration
2. Click on the pencil button (to edit the Home Assistant server settings)
3. Enter the required properties (including the Base URL and the API Pass)
4. Click the "Update" button
4. See the error

**Expected behavior**
Settings are stored and connection to the HA server is made

**Screenshots**
https://gyazo.com/0930d985bb14941b93e4518b5c718424

**Environment (please complete the following information):**

- Node Red Version: 0.20.5
- Is Node Red running in Docker: no (hassbian)

**Other (please complete the following information):**

- Have you searched previous issues for duplicates?: yes

**Additional context**
I'm using Home Assistant on the same Raspberry Pi for months without problems

**Comment by zachowj** [comment]
That screenshot is either from a really old version of this package or from one of the other two. What version are you using?

**Comment by zachowj** [comment]
Actually, that's not from this package now that I think about it. I am guessing you're running either 

https://github.com/AYapejian/node-red-contrib-home-assistant
https://github.com/Spartan-II-117/node-red-contrib-home-assistant-llat

**Comment by DominikPalo** [comment]
Oh, thank you and sorry - it seems that I forget to refresh the Node-RED webpage after replacing the `node-red-contrib-home-assistant`(that I installed by accident) with `node-red-contrib-home-assistant-websocket` 🤦‍♂️But it's really strange that I was able to add that UI card and open the settings although the old module `node-red-contrib-home-assistant` was uninstalled before. My fault

**Comment by zachowj** [comment]
I can explain why it happened but only if you really want to know.
