### ISSUE TITLE
Problem updating to 0.11.0 (several changes?)

### ISSUE THREAD

**Issue by rapejim** [zachowj/node-red-contrib-home-assistant-websocket#123]
**Describe the bug**
I have working the node-red-contrib-home-assistant-websocket (v0.10.1) plugin perfect on my NodeRED but, when I update it to v0.11.0 the NodeRED show me errors loading NR Home Assistant Plugin. If I downgrade it to v0.10.1 again it loads & works good.

**To Reproduce**
Only update NR Home Assistant Plugin configurated and working from older version to v0.11.0

**Expected behavior**
Continue working after update.

**Screenshots**
![image](https://user-images.githubusercontent.com/7972545/58618441-f0feaf80-82c2-11e9-9015-24d60e3fafde.png)

**Example Flow**
-

**Environment:**

- Node Red Version: v0.20.5
- NR Home Assistant Plugin Version: 0.11.0
- Is Node Red running in Docker: yes

**Other (please complete the following information):**

- Have you searched previous issues for duplicates?: Yes, I saw all issues (since v0.11.0 release date, 23 days ago) opened and closed issues.

**Additional context**
-

**Comment by zachowj** [comment]
Are you running a version of node.js <  v8.12+ ?

**Comment by rapejim** [comment]
No, I am using a NodeRED image of docker for Raspberry Pi with Node.JS v8:

nodered/node-red-docker:rpi-v8

**Comment by zachowj** [comment]
rpi-v8 docker container using node.js 8.1.0 and this package needs at least 8.12. You need to upgrade node.js within the container.

**Comment by rapejim** [comment]
> rpi-v8 docker container using node.js 8.1.0 and this package needs at least 8.12. You need to upgrade node.js within the container.

I updated nodejs to v8.16.0 and now its working again.

THANKS!!!
