### ISSUE TITLE
Current State passing original message

### ISSUE THREAD

**Issue by DKCryptoKing** [zachowj/node-red-contrib-home-assistant-websocket#124]
**Describe the bug**
After updating to version 0.11.0, all my current flows that are using the "Current State" node aren't working anymore. Apparently this node no longer pass the message from the current state entity, but is instead passing the original message.

**To Reproduce**
Example:

![Skærmbillede 2019-05-31 kl  09 21 04](https://user-images.githubusercontent.com/39259151/58688713-8febe000-8385-11e9-9ea1-12fb888f9080.png)

**Expected behavior**
In the example above, I would have expected the current state node to pass the state for my SONOS entity, so that I can use the switch node to redirect the flow based on the value on my Sonos payer. Instead, what happens is, that the payload of my Xiaomi Push Button is passed through.

![Skærmbillede 2019-05-31 kl  09 26 37](https://user-images.githubusercontent.com/39259151/58689068-5bc4ef00-8386-11e9-9011-2738c3bf5ce7.png)

**Environment (please complete the following information):**

- Node Red Version: 3.1.1
- Node.js Version: unkown
- NR Home Assistant Plugin Version: 0.11.0
- Is Node Red running in Docker: yes 

**Other (please complete the following information):**

- Have you searched previous issues for duplicates?:

Yes, I have tried my best.

- Comments:

Thank you very much in advance for looking into this. I see in the release notes that a significant enhancement was introduced to this node, which might very well be the reason behind my issues.

**Comment by zachowj** [comment]
You are correct in that the changes to the current-state node is the reason behind your issue. The events: all node payload contains `entity_id` which will override the current-state node's config. It not that the current-state is sending on the original message but it is getting the current state of the entity id passed in by the events all node and passing that new data along.

Currently the solution is to delete `msg.payload.entity_id` before the current-state node. A different solution may appear in the next release.
