### ISSUE TITLE
Merge context error

### ISSUE THREAD

**Issue by ikorpershoek** [zachowj/node-red-contrib-home-assistant-websocket#1249]
### Describe the bug

After update to 16.0.2 all flows using Global Variable in Merge Context in "call service" stopped working. Resulting in a failure message:
'msg : error
"InputError: Invalid merge context: keuken-eten"

The Global variable 'keuken-eten' is set to {"brightness_pct":75,"kelvin":2800}

Node red log message
undefined undefined
8 Jan 08:20:41 - [error] [api-call-service:keuken aan] InputError: Invalid merge context: keuken_eten

It has been working before 16.0.2 perfectly

### Expected behavior

After update to 16.0.2 all flows using Global Variable in Merge Context in "call service" stopped working. Resulting in a failure message:
'msg : error
"InputError: Invalid merge context: keuken-eten"

The Global variable 'keuken-eten' is set to {"brightness_pct":75,"kelvin":2800}

Node red log message
undefined undefined
8 Jan 08:20:41 - [error] [api-call-service:keuken aan] InputError: Invalid merge context: keuken_eten

It has been working before 16.0.2 perfectly

### Environment Information

Version: 

Home Assistant version:
Companion version:

Node-RED version:
Docker: no
Add-on: no

Node.js version:
OS:

**Comment by zachowj** [comment]
Was fixed here 7388c45f8698fda1fb65fd96363076d5352ec751
