### ISSUE TITLE
authentication error after upgrading to v0.12.0

### ISSUE THREAD

**Issue by marc-gist** [zachowj/node-red-contrib-home-assistant-websocket#125]
**Describe the bug**
Upgraded to v0.12.0 via pallet on node-red docker 0.20.5

GUI now doesn't load after login window (remains blank), error in console read

`https://server:1880/homeassistant/static/common.js net::ERR_ABORTED 401 (Unauthorized)`

[edit] to be clear; the above error message is in the browser debug console.

**To Reproduce**

Update module to v0.12.0 with authentication for node-red installed.

**Expected behavior**
Login to node-red after restart and get GUI back.

**Environment (please complete the following information):**

- Node Red Version: 0.20.5
- Node.js Version: ? node-red docker latest
- NR Home Assistant Plugin Version: 0.11.0 to 0.12.0
- Is Node Red running in Docker: yes

**Comment by Cjdavidson** [comment]
Same problem same environment.
But did not get a error message.
