### ISSUE TITLE
Call Service: Light Turn-On - Entity Option Is Removed

### ISSUE THREAD

**Issue by teek541** [zachowj/node-red-contrib-home-assistant-websocket#1256]
### Describe the bug

When you edit a call service node, you select light for the domain, and when you select anything for the service, the area, device, and entity fields are removed.

### To Reproduce

-Add a Call Service node.
-Select "Light" for the domain
-Select any service

### Expected behavior

The area, device and entity fields remain for you to select anything in those fields.

### Screenshots

![image](https://github.com/zachowj/node-red-contrib-home-assistant-websocket/assets/45326308/becd783e-d62b-4586-9f5a-91b3bd5f9113)

![image](https://github.com/zachowj/node-red-contrib-home-assistant-websocket/assets/45326308/0ccc9324-6c8b-4ef9-852e-dc1e45774ebd)

### Environment Information

Version: 0.62.3

Home Assistant version: 2024.1.2
Companion version: N/A

Node-RED version: 3.1.3
Docker: no
Add-on: no

Node.js version:
OS:

**Comment by zachowj** [comment]
I am guessing the services didn't load correctly. If you restart NR does it display the correct fields?

**Comment by teek541** [comment]
You win sir.  Never seen this before and I didn't implement the old Microsoft fix (reboot)... thanks for the easy fix!

**Comment by koosc** [comment]
I also see this issue and restarting it doesn't fix it.
