### ISSUE TITLE
Climate Set_temperature "call service"

### ISSUE THREAD

**Issue by driagi** [zachowj/node-red-contrib-home-assistant-websocket#1258]
### Describe the bug

In call service, set_temperature, hvac_mode does not work. In the examples, it seems possible to use it.

### Screenshots

![Cattura](https://github.com/zachowj/node-red-contrib-home-assistant-websocket/assets/74871092/c5cfa4e3-e4a5-4aa9-b97a-ef7bd1d83b37)

### Environment Information

Version: 0.62.3

Home Assistant version: 2024.1.3
Companion version:

Node-RED version: 3.1.3
Docker: no
Add-on: no

Node.js version:
OS: Home Assistant OS 11.3

**Comment by zachowj** [comment]
The example details are pulled directly from Home Assistant 

<https://github.com/home-assistant/core/blob/00165fef5bc8d34a90e1882d88131d64c1321ea2/homeassistant/components/climate/services.yaml#L35-L79>

Does it work if you use the developer tools in Home Assistant?

**Comment by driagi** [comment]
I tried, it doesn't work even calling the service from HA. The bug therefore belongs to Home assistant. Thank you very much for your commitment.

**Comment by driagi** [comment]
The problem is in the Home Assistant Core !!
