### ISSUE TITLE
Current State Node State Location: None

### ISSUE THREAD

**Issue by bjohnson8949** [zachowj/node-red-contrib-home-assistant-websocket#126]
Description:
My payload is being over ridden when state is set to null. I use this to test if condition can allow code to keep running. 

1. Add Timestamp
2. Connect to Current State Node
3. Connect Debug node
4. Set Current State Node - State Location = None.
5. Set Entity ID
6. When you look at debug payload will be the value of the entity_id not timestamp

Expected behavior:
I would expect the timestamp to pass though as msg.payload

Screenshots:
![image](https://user-images.githubusercontent.com/43796978/58909437-1f282900-86e1-11e9-8c1f-12e0f9eb0f17.png)

Example Flow:
[{"id":"22534d37.e27002","type":"tab","label":"Test","disabled":false,"info":""},{"id":"6b98b319.5bc7ac","type":"inject","z":"22534d37.e27002","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":500,"y":400,"wires":[["2a156b24.b17f94"]]},{"id":"2a156b24.b17f94","type":"api-current-state","z":"22534d37.e27002","name":"Motion Enabled?","server":"ff720e01.f70b9","version":1,"outputs":2,"halt_if":"on","halt_if_type":"str","halt_if_compare":"is","override_topic":false,"entity_id":"input_boolean.motion","state_type":"str","state_location":"","override_payload":"none","entity_location":"","override_data":"none","blockInputOverrides":false,"x":670,"y":400,"wires":[["3eb712ff.371cfe"],[]]},{"id":"3eb712ff.371cfe","type":"debug","z":"22534d37.e27002","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","x":850,"y":400,"wires":[]},{"id":"ff720e01.f70b9","type":"server","z":"","name":"Home Assistant","legacy":false,"hassio":false,"rejectUnauthorizedCerts":true,"ha_boolean":"y|yes|true|on|home|open"}]

Environment:

- Node Red Version: [e.g. 0.19.4]
- Node.js Version: [e.g. 10.16.0]
- Is Node Red running in Docker: [no]

**Comment by chimpy** [comment]
Thank you both for the quick reporting and the quick fix. I was wondering why my flows were breaking.

**Comment by bjohnson8949** [comment]
Thanks! I tested this morning and things are working :)
