### ISSUE TITLE
Write File Node not writing to file

### ISSUE THREAD

**Issue by Mossi777** [zachowj/node-red-contrib-home-assistant-websocket#1268]
### Describe the bug

The following flow does not write to the file.

![image](https://github.com/zachowj/node-red-contrib-home-assistant-websocket/assets/3333564/0fc4c45c-8801-4e26-82ec-850a2803ebc5)

### To Reproduce

Press the inject node button

### Expected behavior

Text should appear in file.

### Screenshots

![image](https://github.com/zachowj/node-red-contrib-home-assistant-websocket/assets/3333564/37485a0b-64b5-452d-8e97-d241b359b492)

![image](https://github.com/zachowj/node-red-contrib-home-assistant-websocket/assets/3333564/854da002-c42f-43a2-a2eb-957c16e2c0d4)

### Example Flow

```json
[{"id":"2facc55530c3e83c","type":"tab","label":"Flow 1","disabled":false,"info":"","env":[]},{"id":"4a4248afaa72f378","type":"debug","z":"2facc55530c3e83c","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":690,"y":80,"wires":[]},{"id":"e36b8a69acd63cdb","type":"file","z":"2facc55530c3e83c","name":"","filename":"/config/logs/hot_water_control_log.txt","filenameType":"str","appendNewline":true,"createDir":true,"overwriteFile":"false","encoding":"none","x":470,"y":80,"wires":[["4a4248afaa72f378"]]},{"id":"c0f3d9819c260637","type":"inject","z":"2facc55530c3e83c","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"This is a test message","payloadType":"str","x":200,"y":80,"wires":[["e36b8a69acd63cdb"]]}]
```

### Environment Information

Version: 3.1.3

Home Assistant version: 2024.1.3
Companion version:

Node-RED version: 17.0.3
Docker: no
Add-on: no

Node.js version:
OS:

### Additional context

Node-Red add on restarted, Home Assistant rebooted.  The issue is still apparent.

**Comment by zachowj** [comment]
You should read up on the changes to the directory structure that is exposed to the add-on. I don't run add-on and it doesn't have anything to do with this repo.

https://github.com/hassio-addons/addon-node-red
