### ISSUE TITLE
Flows stopped due to missing node types (all HA ones..)

### ISSUE THREAD

**Issue by timdonovanuk** [zachowj/node-red-contrib-home-assistant-websocket#128]
Just updated my node-red-contrib-home-assistant-websocket to the latest using the pallet update. That worked fine in NR 19.5. Then did an update to the latest NR docker image (20.5) and now every single HA related node is missing. It's totally hosed my NR/HA install!

**Comment by timdonovanuk** [comment]
Looks like its broken with the latest nodered/node-red-docker:rpi-v8 docker image. The only version of node-red-contrib-home-assistant-websocket that works is 0.10.2 or lower.

**Comment by timdonovanuk** [comment]
I see now (https://github.com/zachowj/node-red-contrib-home-assistant-websocket/issues/123) I need to update Node in the NodeRed container, but this isn't ideal...most people will just use the offical NR docker container, and there is no node v10 version :( Updating in the container will just get it trashed on next update...

**Comment by zachowj** [comment]
This is why I recommend using a different container here https://github.com/zachowj/node-red-contrib-home-assistant-websocket/issues/127#issuecomment-500345381 and [here](https://community.home-assistant.io/t/docker-on-rpi-and-can-t-get-node-red-to-show-up-on-web-anymore/119934/10?u=kermit) until node-red releases either an updated v8 version or a v10 for the pi.
