### ISSUE TITLE
wait until (ha-wait-until) always timing out

### ISSUE THREAD

**Issue by viotemp1** [zachowj/node-red-contrib-home-assistant-websocket#129]
Hello,
I tried to use wait until to detect when a switch is on for too long. 
For me it looks like is not reading the state or something like this (even that initially it says connected) - al the time is going to second output even if the conditions are met before timeout.
![Screenshot 2019-06-22 at 11 06 16](https://user-images.githubusercontent.com/34300519/59961242-dd1f2580-94dd-11e9-91bc-8fd68e6e4fbf.png)
![Screenshot 2019-06-22 at 11 05 45](https://user-images.githubusercontent.com/34300519/59961243-ddb7bc00-94dd-11e9-8477-a6db15731d6a.png)

**Comment by zachowj** [comment]
Can you provide an export of the flow?

**Comment by viotemp1** [comment]
[{"id":"4f552e66.26127","type":"ha-wait-until","z":"271ece24.da86c2","name":"Wait to stop x minutes","server":"1c18de7e.2ed152","outputs":2,"entityId":"switch.fibaro_system_fgwpe_f_water_plant_wall_plug_gen5_switch","property":"state","comparator":"is","value":"off","valueType":"str","timeout":"15","timeoutUnits":"seconds","entityLocation":"","entityLocationType":"none","checkCurrentState":true,"x":620,"y":200,"wires":[["fabff11.102de1"],["c8f17e67.3c9f7"]]},{"id":"c8f17e67.3c9f7","type":"debug","z":"271ece24.da86c2","name":"off timeout","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":910,"y":240,"wires":[]},{"id":"fabff11.102de1","type":"debug","z":"271ece24.da86c2","name":"off now","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":900,"y":120,"wires":[]},{"id":"2c0f4fd7.7f4ac","type":"trigger-state","z":"271ece24.da86c2","name":"Water Plant Living","server":"1cf11846.481798","entityid":"switch.fibaro_system_fgwpe_f_water_plant_wall_plug_gen5_switch","entityidfiltertype":"exact","debugenabled":false,"constraints":[],"constraintsmustmatch":"all","outputs":2,"customoutputs":[],"outputinitially":true,"state_type":"str","x":350,"y":200,"wires":[["4f552e66.26127"],[]]},{"id":"1c18de7e.2ed152","type":"server","z":"","name":"Home Assistant","legacy":false,"hassio":true,"rejectUnauthorizedCerts":true,"ha_boolean":"y|yes|true|on|home|open","connectionDelay":true},{"id":"1cf11846.481798","type":"server","z":"","name":"Home Assistant - no delay","legacy":false,"hassio":true,"rejectUnauthorizedCerts":true,"ha_boolean":"y|yes|true|on|home|open","connectionDelay":false}]

**Comment by viotemp1** [comment]
I did o restart of hassio and NR and everything is working fine now. Very strange...
Sorry for the inconvenience. If the issue will reappear, I will raise again the issue.
Thanks,
