### ISSUE TITLE
Error installing node-red-contrib-home-assistant-websocket v0.12.3 in node red palette.

### ISSUE THREAD

**Issue by oscargali** [zachowj/node-red-contrib-home-assistant-websocket#130]
**Describe the bug**
I am using node-red on docker running on a raspberry pi 3 b+.
I am using the latest official docker image available for node-red (nodered/node-red-docker:rpi-v8) and when I install the node-red-contrib-home-assistant-websocket v0.12.3 (latest available) I get the following error for each of the nodes:

> **ReferenceError: Can't find variable: nodeVersion**

As a result the nodes are not showing up in the palette and if you consult installed nodes they show as :

<img width="704" alt="image" src="https://user-images.githubusercontent.com/13383403/59976097-2b0c5a00-95c0-11e9-8e34-e6b5ff179507.png">

**To Reproduce**

1. Go to menu > manage palette
2. Click on install
3. Look for node-red-contrib-home-assistant-websocket
4. Click install

**Expected behavior**
Installation without error and nodes showing up in the palette.

**Screenshots**

Errors right after installation

<img width="704" alt="image" src="https://user-images.githubusercontent.com/13383403/59976147-b7b71800-95c0-11e9-89c0-75ea8b707c61.png">

Installation log

<img width="939" alt="image" src="https://user-images.githubusercontent.com/13383403/59976294-88090f80-95c2-11e9-8571-b9156bffa3a5.png">

**Environment (please complete the following information):**

- Node Red Version: v.0.20.5 (the one that comes with nodered/node-red-docker:rpi-v8)

- Node.js Version: 8.1.3 (the one that comes with nodered/node-red-docker:rpi-v8)

- NR Home Assistant Plugin Version: v.0.12.3

- Is Node Red running in Docker: yes, docker running on raspbian in a raspberry pi 3 b+ 
 the image is the lates official available in docker hub: nodered/node-red-docker:rpi-v8
**Other (please complete the following information):**

- Have you searched previous issues for duplicates?:
Yes with no success.

**Additional context**

**Comment by zachowj** [comment]
https://github.com/zachowj/node-red-contrib-home-assistant-websocket/issues/127#issuecomment-500345381

**Comment by ndrwstn** [comment]
I'm unable to fix this problem using #127; I've even tried the recommended raymondmm/node-red container with the same issue. The npm install -g n command fails due to permissions issues. I could probably get it to work with root, but that seems to be inadvised. Suggestions?

**Comment by zachowj** [comment]
It definitely works with raymondmm/node-red container I just did a fresh install. You don't have to refresh the page after adding this package.

https://github.com/zachowj/node-red-contrib-home-assistant-websocket/issues/127#issuecomment-500345381 for that to work you need to install it as root.

**Comment by ndrwstn** [comment]
@zachowj a clean install of raymondmm/node-red still gives me a nodeVersion not defined error when I install this package from the palette, and only events state, poll state and current state show up, though they all show up as enabled but without the blue dot filled (under the installed tab). I can then disable all and enable all and all the nodes appear and appear normally.

I add an events-all to a flow, add my server normally, and when I update get a "cannot GET' error something home assistant, which I can't copy fast enough. The settings are saved, but the node shows disconnected after deploy. a Debug node doesn't give any real information, nor do the Node-RED logs via the docker logs command.

Running: Ubuntu 18.04, Docker 18.06.1-ce (e68fc7a).

**Comment by zachowj** [comment]
@ndrwstn try version 0.13.1 with raymondmm/node-red

**Comment by ndrwstn** [comment]
@zachowj Success. Thank you.
