### ISSUE TITLE
'Select' home assistant entity has unexpected behaviour

### ISSUE THREAD

**Issue by AussieMakerGeek** [zachowj/node-red-contrib-home-assistant-websocket#1313]
### Describe the bug

When creating a select box and configuring it with 'Listen for changes', there is no incoming connection.  However, with 'Get Value' and 'Set Value', there is. I would only expect only 'Set' to not have an input.

Unexpected behavior - 'Listen for changes' seems to work like 'Set'.

### To Reproduce

Create a new 'Select' node
Set it to 'Listen for changes'
No input connection is available

When creating events by changing the value in HA, it will fire off a payload immediately, acting like 'Set'
When in Get or Set mode, it only fires a payload when the input is triggered, not when changed in HA, but will be the value you set, ignoring the incoming payload.msg

### Expected behavior

I could be missing something here but I would have thought to 'listen' it would need an input connection.

Desired operation:
List box initiates a msg.payload when changed directly (Via HA)
List box updates to msg.payload when it receives an update (and does not pass on the payload, or have that option)

### Environment Information

Version: 

Home Assistant version: 2024.2.
Companion version: 3.1.3

Node-RED version: 17.0.7
Docker: no
Add-on: no

Node.js version:
OS: HAOS

**Comment by psy0rz** [comment]
I also was wondering this, some other widget types do have an input by default, but not select.
