### ISSUE TITLE
Timeout on call http://172.30.32.1:8123/api/core/state and WebSocket API error

### ISSUE THREAD

**Issue by Salsalove** [zachowj/node-red-contrib-home-assistant-websocket#1328]
### Describe the bug

Despite the latest updates, node-red is causing serious instability issues.
Sometimes it won't start, causing reebots...or, if it's working, it causes websocket api errors, timeout on call errors with system freeze 3-4 times in an hour or reebots.
I'm frustraited, and I don't understand why this still happens after 2 months and various updates and why nobody can give an explanation or a solution.

Can someone investigate? Node-red is unusable with this node.

### Example Flow

```json
24-03-16 09:36:54 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API error: Cannot proxy websocket message of unsupported type: 257
24-03-16 09:36:54 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API for a0d7b954_nodered closed
24-03-16 09:36:55 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API error: Cannot proxy websocket message of unsupported type: 257
24-03-16 09:36:56 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API for a0d7b954_nodered closed
24-03-16 09:37:08 ERROR (MainThread) [supervisor.homeassistant.api] Timeout on call http://172.30.32.1:8123/api/core/state.
24-03-16 09:37:57 ERROR (MainThread) [supervisor.homeassistant.api] Timeout on call http://172.30.32.1:8123/api/core/state.
24-03-16 09:38:06 ERROR (MainThread) [supervisor.homeassistant.api] Timeout on call http://172.30.32.1:8123/api/core/state.
```

### Environment Information

Version: 

Home Assistant version:
Companion version:

Node-RED version: 
Docker: no
Add-on: no

Node.js version:
OS:

**Comment by Salsalove** [comment]
@zachowj

**Comment by zachowj** [comment]
Try connecting directly to Home Assistant and not using the proxy.

<https://zachowj.github.io/node-red-contrib-home-assistant-websocket/guide/#configuration>
