### ISSUE TITLE
Accept boolean inputs to call_service nodes

### ISSUE THREAD

**Issue by deece** [zachowj/node-red-contrib-home-assistant-websocket#134]
I would like to turn a device on/off based on the state of a boolean.

I am currently using a function node with the following code to do this:

if (msg.bool) {
    msg.payload = {service: "turn_on"}
} else {
    msg.payload = {service: "turn_off"}
}
return msg;

The flow would be less cluttered if the call_service node could interpret booleans as calls to turn_on/turn_off.

**Comment by zachowj** [comment]
You can use mustache templates within the service field. You can either pass in the state of the input_boolean or access it directly from the call-service node.

`turn_{{payload}}`

`turn_{{entity.input_boolean.test}}`

**Comment by deece** [comment]
Hmm, from the previous boolean node (an and-gate from node-red-contrib-bool-gate) I have:
```
{ topic: null, payload: true, bool: false, _msgid: "58754fb7.809e4" }
```
(note that these nodes pass payload in from the triggering input, so it is bogus, the output is 'bool'. This is possibly a poor mechanism, I believe it should output on 'payload'.)

call_service doesn't have turn_true or turn_false, so I can't use the first example `turn_{{bool}}`, giving the following error (which could be improved to show the failing service): ```
"Call-service API error. Error Message: Service not found."
```

Likewise, the second example also fails with the same error.

**Comment by zachowj** [comment]
I misread your original post and thought you were referencing an input_boolean where the state would have been `on` and `off`.

I don't think making this work for one output of a single node is really valid. The output of `msg.bool` is probably pretty unique and to make this more universal the bool would need to be transformed into `msg.payload.service` like you're already doing and at that point, you might as well make it either `on` or `off`.

So at this point, I think there are already tools in place to make this relatively easy to accomplish.
