### ISSUE TITLE
Home Assistant Connection Issue in Docker

### ISSUE THREAD

**Issue by ReArmedHalo** [zachowj/node-red-contrib-home-assistant-websocket#135]
**Describe the bug**
Pallete doesn't appear to properly connect to HA when running in docker without Node-RED also having networking mode set to HOST.

**To Reproduce**
Running Home Assistant and Node-RED in docker on the same host (testing in a VM as I currently use HASSIO on a Pi3). HA is running in host networking mode and Node-RED is not. After getting a token and trying to setup a node (let's say get state but it really doesn't matter) and deploying, NR will alternate between connecting and disconnected, never goes green and shows the state. I see the following in my docker console logs repeatedly:

(10.0.10.28 being my VMs LAN IP address)

```
13 Jul 00:10:33 - [debug] [server:Home Assistant] WebSocket Connecting http://10.0.10.28:8123
13 Jul 00:10:33 - [debug] [server:Home Assistant] config server event listener connecting
13 Jul 00:10:33 - [debug] [server:Home Assistant] config server event listener closed
```

**Expected behavior**
NR will show the current state

**Example Flow**
```json
[
    {
        "id": "c941380a.4958d8",
        "type": "tab",
        "label": "Flow 1",
        "disabled": false,
        "info": ""
    },
    {
        "id": "8716b963.ee4d18",
        "type": "poll-state",
        "z": "c941380a.4958d8",
        "name": "",
        "server": "5835eabe.efccf4",
        "version": 1,
        "updateinterval": "60",
        "updateIntervalUnits": "seconds",
        "outputinitially": true,
        "outputonchanged": true,
        "entity_id": "person.dustin",
        "state_type": "str",
        "halt_if": "home",
        "halt_if_type": "str",
        "halt_if_compare": "is",
        "outputs": 2,
        "x": 120,
        "y": 140,
        "wires": [
            [],
            []
        ]
    },
    {
        "id": "96a4871d.cf9fe8",
        "type": "server-state-changed",
        "z": "c941380a.4958d8",
        "name": "Dustin's Home state changed",
        "server": "5835eabe.efccf4",
        "version": 1,
        "entityidfilter": "person.dustin",
        "entityidfiltertype": "exact",
        "outputinitially": true,
        "state_type": "str",
        "haltifstate": "",
        "halt_if_type": "str",
        "halt_if_compare": "is",
        "outputs": 1,
        "output_only_on_state_change": true,
        "x": 140,
        "y": 240,
        "wires": [
            [
                "8295453b.b51f18",
                "cdbaa010.fc2a2"
            ]
        ]
    },
    {
        "id": "8295453b.b51f18",
        "type": "debug",
        "z": "c941380a.4958d8",
        "name": "",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "false",
        "x": 410,
        "y": 240,
        "wires": []
    },
    {
        "id": "cdbaa010.fc2a2",
        "type": "api-call-service",
        "z": "c941380a.4958d8",
        "name": "Hello, World!",
        "server": "5835eabe.efccf4",
        "service_domain": "tts",
        "service": "google_translate_say",
        "data": "{\"entity_id\":\"media_player.bedroom_google_home\",\"message\":\"Hello, World!\"}",
        "mergecontext": "",
        "output_location": "payload",
        "output_location_type": "msg",
        "mustacheAltTags": false,
        "x": 410,
        "y": 300,
        "wires": [
            [
                "8295453b.b51f18"
            ]
        ]
    },
    {
        "id": "5835eabe.efccf4",
        "type": "server",
        "z": "",
        "name": "Home Assistant",
        "legacy": false,
        "hassio": false,
        "rejectUnauthorizedCerts": true,
        "ha_boolean": "y|yes|true|on|home|open",
        "connectionDelay": true
    }
]
```

**Environment (please complete the following information):**

- Node Red Version: 0.20.7
- Node.js Version: 8.16.0
- NR Home Assistant Plugin Version: 0.13.1
- Is Node Red running in Docker: Yes

**Other (please complete the following information):**

- Have you searched previous issues for duplicates?: Yes

**Additional context**
I configured the HA server base URL as "http://10.0.10.28:8123" in NR. The VMs firewall is set to trusted network zone. Running CentOS 7 and latest docker + docker-compose version as of yesterday.

I think this may be more a docker issue but I know I can ping the host from the NR container and just wanted to see if perhaps it was something with pallete. I'm a n00b with NR so sorry if I didn't grab all the right information or used the proper terms. Not really sure how to get any  more detailed output as to what is going on. At one point I was able to see in my Chrome DevTools a connection to the NR endpoint `http://ha:1880/homeassistant/5835eabe.efccf4/entities` (HA is a mapped DNS record in my homelab AD DNS server so that resolves just fine) and was seeing a 304 response with an empty array response ("[]" shown as response body)  I know that NR can work as I was able to connect to my VMs HA instance when I set it also to HOST networking mode as well as I was able to connect to an off-host Hassio instance without issue (even without host networking)

Compose file:
```yaml
version: '3'

services:
  homeassistant:
    image: homeassistant/home-assistant
    container_name: home-assistant
    depends_on:
      - rtspcaster
    network_mode: host
    restart: unless-stopped
    volumes:
      - /docker/homeassistant-config:/config
      - /etc/localtime:/etc/localtime:ro

  nodered:
    image: nodered/node-red-docker
    container_name: nodered
    depends_on:
      - homeassistant
    ports:
      - 1880:1880
    restart: unless-stopped
    user: 1000:1000
    volumes:
      - /docker/nodered:/data
```

**Comment by zachowj** [comment]
Give this flow a try and see if it connects. You should get a response in the debug window similar to `{"type": "auth_required", "ha_version": "0.94.4"}`. If doesn't connect you're having a general connection issue between docker containers.

![image](https://user-images.githubusercontent.com/37859597/61336747-611bb300-a7e7-11e9-9372-9445840e008d.png)

```
[{"id":"fd5756d0.5510a8","type":"websocket in","z":"fac037bf.a42d78","name":"","server":"","client":"93894937.60b228","x":400,"y":656,"wires":[["fe83fbb9.4cd5d8"]]},{"id":"fe83fbb9.4cd5d8","type":"debug","z":"fac037bf.a42d78","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":662,"y":656,"wires":[]},{"id":"93894937.60b228","type":"websocket-client","z":"","path":"ws://10.0.10.28:8123/api/websocket","tls":"","wholemsg":"false"}]
```

**Comment by ReArmedHalo** [comment]
Sorry for not replying sooner, missed the notification email.

Anyways, it still didn't work, shows disconnected. I still think the issue is entirely on Docker still so I'll investigate further there. In the meantime, my WAN and VLAN firewall rules are pretty locked down so I'll just run NodeRed with `network_mode: host` for now.

Thank you for your assistance!

Just to add to the weirdness that is Docker Networking, ran from within the NodeRed container:
```bash
node@bf684b8d4a3c:/usr/src/node-red$ curl -i -N -H "Connection: Upgrade" -H "Upgrade: websocket" -H "Host: 10.0.10.28:8123" -H "Origin: http://localhost" http://10.0.10.28:8123/api/websocket
curl: (7) Failed to connect to 10.0.10.28 port 8123: No route to host

node@bf684b8d4a3c:/usr/src/node-red$ ping 10.0.10.28
PING 10.0.10.28 (10.0.10.28) 56(84) bytes of data.
64 bytes from 10.0.10.28: icmp_seq=1 ttl=64 time=0.091 ms
64 bytes from 10.0.10.28: icmp_seq=2 ttl=64 time=0.072 ms
^C
--- 10.0.10.28 ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1000ms

node@bf684b8d4a3c:/usr/src/node-red$ ip route list
default via 172.23.0.1 dev eth0
172.23.0.0/16 dev eth0 proto kernel scope link src 172.23.0.4
```
