### ISSUE TITLE
Breaking change on call service node

### ISSUE THREAD

**Issue by manonstreet** [zachowj/node-red-contrib-home-assistant-websocket#136]
**Describe the bug**
Multiple comma delimited entity_ids provided in the Entity_Id field to the call service node works as expected in the prior version and as per the inline help.  After upgrading the call service node, the call succeeds however no action is taken.

**To Reproduce**
While in Node Red:

1) If there is an existing un-upgraded node with multiple comma delimited entity_ids, test and verify that it works as expected.
2) Make a copy of the node, and edit it.  Without making any changes, click Done to upgrade the node to version 1.  Test again and observe that the call service succeeds however no action was taken. 

**Expected behavior**
The call service should be called for each entity_id provided

**Environment (please complete the following information):**

- Node Red Version: v0.20.7
- Node.js Version: ?
- NR Home Assistant Plugin Version: 4.0.5
- Is Node Red running in Docker: hassio

- Have you searched previous issues for duplicates?:
Yes.  This is related to Feature #12 however that feature now seems broken.

**Comment by zachowj** [comment]
What domain are you using are you? I just tried to replicate this with input_booleans and it's working as intended.

```
[{"id":"b2de48d0.3ee368","type":"api-call-service","z":"fac037bf.a42d78","name":"test22","version":0,"service_domain":"input_boolean","service":"toggle","data":"{\"entity_id\": \"input_boolean.test, input_boolean.test2\"}","dataType":"jsonata","mergecontext":"","output_location":"payload","output_location_type":"msg","mustacheAltTags":false,"x":274,"y":400,"wires":[["bc0d1c2d.789b4"]]},{"id":"184955a0.1168aa","type":"inject","z":"fac037bf.a42d78","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":124,"y":400,"wires":[["b2de48d0.3ee368"]]},{"id":"bc0d1c2d.789b4","type":"debug","z":"fac037bf.a42d78","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"payload","targetType":"msg","x":552,"y":400,"wires":[]},{"id":"871df3bc.b101c","type":"api-call-service","z":"fac037bf.a42d78","name":"test22","version":1,"service_domain":"input_boolean","service":"toggle","entityId":"input_boolean.test, input_boolean.test2","data":"","dataType":"jsonata","mergecontext":"","output_location":"payload","output_location_type":"msg","mustacheAltTags":false,"x":274,"y":448,"wires":[["22f2090e.c5c396"]]},{"id":"231bf26e.011ffe","type":"inject","z":"fac037bf.a42d78","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":124,"y":448,"wires":[["871df3bc.b101c"]]},{"id":"22f2090e.c5c396","type":"debug","z":"fac037bf.a42d78","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"payload","targetType":"msg","x":552,"y":448,"wires":[]}]
```

**Comment by manonstreet** [comment]
After further testing, it appears to perhaps only impact the home assistant domain.
