### ISSUE TITLE
"Error: Invalid server config"

### ISSUE THREAD

**Issue by joelegg** [zachowj/node-red-contrib-home-assistant-websocket#1364]
### Describe the bug

I'm encountering an issue with my HA configuration in Node-RED. Previously, everything was working smoothly, but now it's reporting that it can't locate it. I'm running Home Assistant Operating System (HAOS) on an Intel NUC, version 2024.4.4, with Node-RED 17.0.12.

I've tried removing and re-adding the configuration using the Home Assistant Add-On, but it hasn't resolved the issue. Additionally, I've reset HA multiple times and updated palettes. I've also ensured that the websocket is updated to the latest version.

Could this be a bug unique to my setup? I'm leaning towards that conclusion, but I'm unable to resolve it on my own. Any assistance would be greatly appreciated.

### To Reproduce

Running Home Assistant Operating System (HAOS) on an Intel NUC.
Installed Node-RED version 17.0.12.
Previously had a working HA configuration in Node-RED.
Encountered an issue where Node-RED reported it couldn't locate the HA configuration.
Attempted to resolve the issue by removing and re-adding the configuration using the Home Assistant Add-On.
Tried resetting HA multiple times.
Updated Node-RED palettes.
Ensured that the websocket was updated to the latest version.
Despite these efforts, the issue persists, leading to the suspicion of a unique bug in the setup.

### Expected behavior

Node red should not error and accept the HA server config 

### Screenshots

![image](https://github.com/zachowj/node-red-contrib-home-assistant-websocket/assets/4109858/abc4288a-71db-4155-a26e-5345930f9086)
![image](https://github.com/zachowj/node-red-contrib-home-assistant-websocket/assets/4109858/92f4b299-4998-4b45-b1c7-ea7b6097d5c5)

### Environment Information

Version: 0.64.0

Home Assistant version: 2024.4.4
Companion version: 0.0.0

Node-RED version: 3.1.9
Docker: yes
Add-on: no

Node.js version: v18.20.2 x64 linux
OS: Linux 6.6.25-haos x64

**Comment by zachowj** [comment]
If you deleted and recreated your server config. Every HA node lost its server config.

The easiest option would to be find the node id of the new server config. Then stop NR edit flows.json file and search and replace the old node id with the new one.

The second option would be to open each HA node in NR and then deploy.

**Comment by joelegg** [comment]
thank you,. so the server config only appears once? but it copied over to all nodes?

**Comment by zachowj** [comment]
Yes, they reference in their config under `server`.

**Comment by joelegg** [comment]
i found it thank you!
