### ISSUE TITLE
Allow using Env Variables on events:state node

### ISSUE THREAD

**Issue by carlos-sarmiento** [zachowj/node-red-contrib-home-assistant-websocket#137]
**Is your feature request related to a problem? Please describe.**
I want to create a subflow for behavior like Halt if 'EntityId' is equal to 'X' in which both EntityId and X are passed to the subflow as Environment Variables

**Describe the solution you'd like**
Allow the node to pull the entityId from Environment Variables

**Describe alternatives you've considered**
I'm currently using a state:node that outputs all my state changes and use a function node to filter all topics but the one I'm interested in ($ENTITY_ID).

**Additional context**
None right now.

**Comment by zachowj** [comment]
I would have to test if this is possible within the events: state node. Not sure exactly when the constructor gets called for subflow nodes.

Another possible solution would be to use events: all node with the filter to state_changed then you can check the entity_id against the environment variable in the following switch node.

**Comment by carlos-sarmiento** [comment]
So, did a bit of further research and discovered that this is already possible according to https://nodered.org/docs/user-guide/environment-variables.

Tested it on my Node-Red instance and it works beautifully. It even works for Regex and Substrings.

Although it is not a feature from this project, I think it would be pretty useful to include it in the documentation

**Comment by zachowj** [comment]
nice find.
