### ISSUE TITLE
Call service - selecting domain & service hide area, device & entity field

### ISSUE THREAD

**Issue by dudu7731** [zachowj/node-red-contrib-home-assistant-websocket#1372]
### Describe the bug

Hello

When i try to create a call service for a switch, le fields  area, device & entity are hidden, so i can't declare on witch entity I want to call this service

### To Reproduce

1. grab a call service node
2. open it 
3. this windows appears :
![image](https://github.com/zachowj/node-red-contrib-home-assistant-websocket/assets/117290248/e7214c77-ca14-49c0-ac1b-850a2d2bcaf1)
4. select domain and service end the fields are hidden :
![image](https://github.com/zachowj/node-red-contrib-home-assistant-websocket/assets/117290248/c2043049-2360-4e93-8ccf-22d66e2c246e)
 

### Expected behavior

explain me how to do now please, i have a few nodes who work because i declared them a few month ago (when those fields weren't hidden) or fix this bug :)

### Environment Information

Version: 0.64.0

Home Assistant version: 2024.5.0
Companion version: 3.1.5

Node-RED version: 3.1.9
Docker: yes
Add-on: no

Node.js version: v18.20.2 arm64 linux
OS: Linux 6.6.25-haos arm64

**Comment by zachowj** [comment]
Try restarting Node-RED. It looks like the service data didn't load properly.

**Comment by dudu7731** [comment]
already tried, thanks you

**Comment by dudu7731** [comment]
i had to reboot my entire system, it's ok now
