### ISSUE TITLE
Templates in call service node not rendering for Entity Id field

### ISSUE THREAD

**Issue by manonstreet** [zachowj/node-red-contrib-home-assistant-websocket#138]
**Describe the bug**
The Entity Id field in the call service node does not appear to be rendering templates

**To Reproduce**

1. Connect an inject node to a change node
2. Configure the change node to set any property (ie payload) to a string value of a valid entity_id
3. Connect the change node to a call service node and reference the property in the Entity Id field (ie {{payload}}
4. See error in NodeRED debug console and more tellingly in the Home Assistant error log:
Entity ID {{payload}} is an invalid entity id for dictionary value @ data['entity_id']

Home Assistant does not appear to be receiving the rendered template, rather the raw template string.

**Expected behavior**
The template should be rendered

**Screenshots**
None.  See steps above.

**Example Flow**
None.  See steps above.

**Environment (please complete the following information):**

Node Red Version: v0.20.7
Node.js Version: ?
NR Home Assistant Plugin Version: 4.0.6
Is Node Red running in Docker: hassio

**Other (please complete the following information):**

- Have you searched previous issues for duplicates?: Yes

**Additional context**

**Comment by zachowj** [comment]
Already fixed here https://github.com/zachowj/node-red-contrib-home-assistant-websocket/commit/888935512ac7f9bf56c8f6611c28b90cb282b2ca

**Comment by zachowj** [comment]
The fix was released in version [0.14.2](https://github.com/zachowj/node-red-contrib-home-assistant-websocket/releases/tag/v0.14.2) but it doesn't look like the hass.io addon has been updated yet.

**Comment by manonstreet** [comment]
Add-on has been updated. Working as expected.
