### ISSUE TITLE
No search results for service, entity etc.

### ISSUE THREAD

**Issue by IanAber** [zachowj/node-red-contrib-home-assistant-websocket#140]
**Describe the bug**
When selecting a node eg. Call Service, there is no list content for the Domain, Service or Entity. Entering the full information results in a working flow but there is no pick list so it is difficult to know what to insert.
**To Reproduce**
Create a new flow.
Add an injection node
Add a 'call service' node and configure the server
Click in the Domain box - No drop down shown
Type Light pausing between each character - still no drop down.
Enter Service as turn_on
Enter entity by copying from the Home Assistant screen since no entities are listed.
Deploy and run the flow and it turns on the light.

**Expected behavior**
When clicking into the Service box I expected there to be a drop list of available service displayed for me to pick from. I expected this list to filter based on what I was typing into the box.

**Screenshots**
The cursor is in the Domain box and the L character has just been typed on the keyboard at this point.

![image](https://user-images.githubusercontent.com/4250012/62649774-70dc7200-b923-11e9-8d76-6536356efa9a.png)

**Example Flow**

**Environment (please complete the following information):**

- Node Red Version: 0.20.7
- Node.js Version: 10.16.2
- NR Home Assistant Plugin Version: 0.14.2
- Is Node Red running in Docker: No. Node Red is installed in Hassbian (Raspberry Pi)

**Other (please complete the following information):**

- Have you searched previous issues for duplicates?:
Yes

**Additional context**
NodeRed and Home Assistant are running on the same machine named Home.Local with NO SSL on the standard ports, 1880 and 8123 respectively. The client is a Mac running Mohave 10.14.6 with Safari 12.1.2.

Server is a Raspberry Pi 3B+ connected via built in WiFi and renamed to Home but otherwise a completely fresh install of Hassbian.

**Comment by tomjonkman** [comment]
I got the same issue. What node-red image are you using?

**Comment by IanAber** [comment]
I downloaded and ran the Node Red installation according to the latest WEB site instructions (Aug-6th-2019) on the nodered.org WEB site using the bash script provided.

**Comment by IanAber** [comment]
I just re-ran the install script and this time everything seems to work correctly, at least as far as the drop lists is concerned.

After running the script I had to manually restart the service 'sudo systemctl start nodered' but then my original flow came up and I was able to get the drop lists in both Firefox and Safari.

**Comment by tomjonkman** [comment]
Same for me!

**Comment by IanAber** [comment]
I reinstalled everything using Docker. It has not been the easy route that was promised and the last piece caught me out again with no drop downs listed. In docker, if you have Node Red and Home Assistant in independant containers with their networks set to 'bridge' then each one is given an IP address. It is this address, as listed for the Home Assistant container that you need to give Node Red to connect to the Home Assistant API.

I recommend using the Docker approach but use Portainer to manage it. Install Docker and then install Portainer. 

docker run -d -p 8000:8000 -p 9000:9000 -v /var/run/docker.sock:/var/run/docker.sock -v portainer_data:/data portainer/portainer

Next install Home Assistant using the docker image.

docker run --init -d --name="home-assistant" -v /home/pi/docker/homeassistant:/config -v /etc/localtime:/etc/localtime:ro --net=host homeassistant/raspberrypi3-homeassistant

Now install Node Red. Don't use the Node Red official site as this won't work properly with the Home Assistant plugin. Use Portainer to go an get the image from raymondmm/node-red

You can now set everything up correctly. Check the container information in Portainer for the Home Assistant IP address and feed that to the service when setting up the connection from NodeRed. DO NOT use the Raspberry Pi host IP address or LocalHost.
