### ISSUE TITLE
Events: State node automatically exposed

### ISSUE THREAD

**Issue by meks007** [zachowj/node-red-contrib-home-assistant-websocket#1423]
### Describe the bug

There appears to be a bug in Node-RED 4.0.0 and HA nodes 0.65.0 where when 
(1) an events state node is inserted, the node is automatically exposed using the alphabetically first config node.
(2) an events state node that was not exposed previously is edited, is automitcally exposed using the same logic as (1)

Settings "Exposed as" to None does work after it's deployed but as soon as the node is edited the first config node is selected in the Exposed As dropdown

As a workaround I've created a "switch a_none" config that gets automatically selected for a new node to prevent triggering the new node by a previously created exposed switch.

### To Reproduce

Create at least one exposed events state node
Insert another events state node
Observer that the 2nd node is using the expose config from the first node.

### Expected behavior

New nodes are supposed to not be exposed

### Screenshots

![image](https://github.com/zachowj/node-red-contrib-home-assistant-websocket/assets/23148641/8e326d37-ce58-4677-8e76-46d6aa81684f)

### Environment Information

Node-RED 4.0.0
Nodes 0.65.0

**Comment by gmcui** [comment]
I can confirm the same issue.  Also when this happens, my **events:state** will show a "DISABLED" status line underneath that won't clear even after restart.  The only working fix seems to be to set the **Expose as** to none and immediately deploy.

**Comment by gmcui** [comment]
I am seeing the same issue.  In addition, it seems to cause my **events:state** node to show a "DISABLED" status line.  Changing **Exposed as** to none and immediate deploy seems to be the only fix AFAIK.

![Node-RED_–_Home_Assistant-3](https://github.com/zachowj/node-red-contrib-home-assistant-websocket/assets/1258503/4e499377-d1f4-4578-9439-f95fbf49937c)

**Comment by i7zTr0n** [comment]
Thanks Guys, you saved my day, been searching the internet all day, because of the DISABLED thing.
At least there's a workaround for now.
So yes, same thing here. Not only with the event:state nodes, but with the trigger:state nodes, as well.

**Comment by zachowj** [comment]
It's an issue in Node-RED 4.0 that is being fixed.

<https://github.com/node-red/node-red/pull/4800>

**Comment by meks007** [comment]
Thanks for linking the PR. I'll close this issue then.
