### ISSUE TITLE
Changes Value dropdown by itself when opening card (properties)

### ISSUE THREAD

**Issue by StaffordBully** [zachowj/node-red-contrib-home-assistant-websocket#1433]
### Describe the bug

I have added a call service card for my fibaro walli switch.
When i add a scene as Trigger i need to select a Value in the dropdown list.
if i select a value and click Done, its correct. But when i  double click the card to open it the dropdown value changes to the first value of the dropdown list, so the i selected is not selected anymore.

I loses the selected and saved value

![image](https://github.com/zachowj/node-red-contrib-home-assistant-websocket/assets/144690805/c3570c30-b8de-4bee-9db1-ffdbc5627b18)

### Environment Information

Version: 0.65.1

Home Assistant version: 2024.7.0
Companion version: 4.0.0

Node-RED version: 4.0.2
Docker: yes
Add-on: no

Node.js version: v18.20.3 arm64 linux
OS: Linux 6.6.31-haos-raspi arm64

**Comment by zachowj** [comment]
should be fixed with 48cfa545ca34e1d6afe9c21992f2c8fab76b1eb7
