### ISSUE TITLE
Call Service Node broken

### ISSUE THREAD

**Issue by LooneyN** [zachowj/node-red-contrib-home-assistant-websocket#1434]
### Describe the bug

I'm having the exact same problem like [this issue](https://github.com/zachowj/node-red-contrib-home-assistant-websocket/issues/1372#issue-2277090797). When I try to create a call service and choose a service, I can't declare an entity, and only the "Data" field is left. I already restarted the addon, Home Assistant, and even the NUC itself. I also downgraded the websocket node to 0.65.0 and 0.64.0. Nothing fixes the issue (running 0.65.1 again).

Edit: I even restored a pretty old (3 months) NodeRed Backup. Didn't fix the issue

### To Reproduce

1. Pick Call Service Node
2. Choose Domain 
![553](https://github.com/zachowj/node-red-contrib-home-assistant-websocket/assets/30878831/4c83fa48-3e59-48a5-b4fb-276ce24b4ab4)
4. Choose Servce and poof. Everything is gone 
![554](https://github.com/zachowj/node-red-contrib-home-assistant-websocket/assets/30878831/3b6399fa-dc95-4181-8e1a-bb77344efd28)

### Environment Information

Version: 0.65.1

Home Assistant version: 2024.7.1
Companion version: 4.0.0

Node-RED version: 4.0.2
Docker: yes
Add-on: no

Node.js version: v18.20.3 x64 linux
OS: Linux 6.6.33-haos x64

**Comment by memphisdj** [comment]
I am having the exact same issue, but only the switch domain is affected in my case.

**Comment by memphisdj** [comment]
Funny enough, if i select the switch service in homeassistant the fields are not populated either:
![image](https://github.com/user-attachments/assets/ead0badd-91da-4bb1-a1d8-19a221adde56)

I guess those are not related, but i cannot create an automation to call the service there either.

**Comment by memphisdj** [comment]
More on this, restarting home-assistant in safe mode fixed the bug in the UI and also fixes the issue in node red. After restarting back out of safe mode, the issue got resolved in both places.

**Comment by zachowj** [comment]
Should be fixed with 20e08aba4fd34ff58f7d75feb9df241ac8a6cccf
