### ISSUE TITLE
how to get trigger:attr?

### ISSUE THREAD

**Issue by stkang** [zachowj/node-red-contrib-home-assistant-websocket#144]
**Is your feature request related to a problem? Please describe.**

how to get trigger:attr?

**Comment by ericvitale** [comment]
Can you be more specific? You want to get a specified attribute of the device that triggered? Or you want the state?

**Comment by stkang** [comment]
@ericvitale 

I don't know if it's already supported because here is no wiki.
I want to trigger on an attribute.

Alternatively, i can create an attribute sensor from ha to a template and trigger it.

Can you develop it? Is it already developed?

**Comment by stkang** [comment]
trigger:state -> add Constraints -> property  right?

**Comment by zachowj** [comment]
> trigger:state -> add Constraints -> property right?

yes
