### ISSUE TITLE
Create a "Check States" nodes that works almost like "trigger: state" but doesn't trigger on an event.

### ISSUE THREAD

**Issue by ericvitale** [zachowj/node-red-contrib-home-assistant-websocket#145]
**Is your feature request related to a problem? Please describe.**
I'm looking for an easy way to check the state of multiple entities. 

**Describe the solution you'd like**
Your "trigger: state" node does this already, but in order for it to fire you need a trigger to fire off for that node. I'm suggesting you create another node type, call it "check states" or something like that and works exactly like "trigger: state" except it doesn't trigger, it acts a msg is received.

**Describe alternatives you've considered**
I've written my own "function" that does this, but a configuration based node would be better and would be more flexible to all scenarios.

**Additional context**

**Comment by zachowj** [comment]
Would this be any different than chaining several current-state nodes together?

**Comment by ericvitale** [comment]
It wouldn't be, except it would make a flow look a lot cleaner. I have a lot of devices and automations. I also check several conditions before doing automations. For example, before turning the master bedroom lights on when motion is detected I make sure that the following switches are set:

All Automations = on
Second Floor Automations = on
Master Bedroom Automations = on
Lighting Automations = on
In Bed = off

I'm just looking to clean up my flows.
