### ISSUE TITLE
GetEntities node not working as expected with timeSinceChangedMs

### ISSUE THREAD

**Issue by gcorgnet** [zachowj/node-red-contrib-home-assistant-websocket#147]
**Describe the bug**
I am trying to get an array of entities whose state hasn't been updated in say 1h (ie timeSinceChangedMs > 3600000).
It seems like no entities are being returned

**To Reproduce**
See sample flow

**Expected behavior**
Returns an array containing entities whose id starts with "sensor.room" which haven't been updated in the last 1h

**Screenshots**
![image](https://user-images.githubusercontent.com/4731735/63053187-4ac35d00-bf35-11e9-866c-3ca12539e112.png)

**Example Flow**
```
[{"id":"438cbf26.4f616","type":"ha-get-entities","z":"e18a73d1.8886e","server":"3aa20170.8cf73e","name":"","rules":[{"property":"entity_id","logic":"starts_with","value":"sensor.room","valueType":"str"},{"property":"timeSinceChangedMs","logic":"gt","value":"3600000","valueType":"num"}],"output_type":"array","output_empty_results":false,"output_location_type":"msg","output_location":"payload","output_results_count":1,"x":250,"y":340,"wires":[["7f6c972b.ab8468"]]},{"id":"3aa20170.8cf73e","type":"server","z":"","name":"Home Assistant"}]
```

**Comment by zachowj** [comment]
https://community.home-assistant.io/t/examples-for-using-the-new-get-entities-node/85777/40?u=kermit
