### ISSUE TITLE
Update to 0.66.0 breaks get_entities node

### ISSUE THREAD

**Issue by klatka** [zachowj/node-red-contrib-home-assistant-websocket#1478]
### Describe the bug

After updating to 0.66.0 my existing get_entitites nodes breaks. I am running now 0.67.0 but it is still the same behavior.
I have to open the editor for each node and save it without making changes to force an update to its config.

Here is an example:

```
751 | 751 | "rules": [
752 | 752 | {
  | 753 | +        "condition": "state_object",
753 | 754 | "property": "entity_id",
754 | 755 | "logic": "starts_with",
755 | 756 | "value": "media_player.wallpanel_",
```

As you can see line 753:  "condition": "state_object" was added after closing the editor.
With this updated config the node works again.

I love the new features in this release! 👍🏻 

### Environment Information

Version: 0.67.0

Home Assistant version: 2024.8.2
Companion version: 4.0.2

Node-RED version: 4.0.2
Docker: yes
Add-on: no (yes but I am using my own credentials)

Node.js version: v18.20.3 x64 linux
OS: Linux 6.6.44-haos x64

**Comment by zachowj** [comment]
Did it throw an error or not return the expected results?

**Comment by klatka** [comment]
> Did it throw an error or not return the expected results?

No errors were thrown, but either no results were returned. Thanks for fixing this!
