### ISSUE TITLE
Attribute of other entity undefined in trigger

### ISSUE THREAD

**Issue by TimSoethout** [zachowj/node-red-contrib-home-assistant-websocket#148]
**Describe the bug**
When using the trigger, it seems that the attributes of other entities are not loaded. When enabling debug mode, it seems that `attributes.source` is undefined, while a query to the entity shows it being set.

**To Reproduce**

1. Create trigger on some entity.
2. Add constract on other entity's property
3. Enable debug in trigger
4. Run and trigger state change in original trigger entity.

**Expected behavior**
The trigger should have a value for the other entity's property and do the conditional check on this.

**Screenshots**
![image](https://user-images.githubusercontent.com/593132/63188609-1b5e3e80-c062-11e9-847b-0e5d074e6f8e.png)

**Environment (please complete the following information):**

- Node Red Version: 0.19.5
- Node.js Version: v8.10.0
- NR Home Assistant Plugin Version: 0.14.2
- Is Node Red running in Docker: no

**Other (please complete the following information):**

- Have you searched previous issues for duplicates?: yes

**Comment by zachowj** [comment]
The current workaround for this is to reference `new_state.attibutes.source`

**Comment by TimSoethout** [comment]
Cool. Thanks for the quick response and the fix.
