### ISSUE TITLE
After upgrading to 0.67.1 debug nodes / inject are greyed out, HA nodes shows no status

### ISSUE THREAD

**Issue by cpuks** [zachowj/node-red-contrib-home-assistant-websocket#1480]
### The problem

# Problem/Motivation

Running latest version of NR within HA as and add-on I decided to upgrade node-red-websocket to latest which is 0.67.1 and after that I've been prompted to upgrade HA nodes and I did but realized that all of my debug nodes and inject nodes are grayed out, nothing displays inside debug window nor any HA node shows connection status. Nodes work as intended, but there's no feedback is provided by Node-Red.
I've enabled heartbeat - set 60 sec and for over 10 min I had no connection drop.

I don't have anything fancy installed and didn't change anything except nr-websocket upgrade - double checked that.

## Expected behavior

Proper feedback from NR<->HA connection, debug nodes / inject nodes work as intended, providing data.

## Actual behavior

No feedback from NR - debug/inject and no connection status on any of HA nodes.

## Steps to reproduce

Latest HA NR addon 18.0.5 - go to palette and upgrade node-red-ha-websocket to 0.67.1, then restart NR.

## Proposed changes

Unknown

**Comment by zachowj** [comment]
Are you using the NR UI through the iframe in Home Assistant? If so, try connecting directly to NR. Check your browser console for errors.

This package doesn't modify anything related to the inject/debug nodes.

**Comment by jjvelar** [comment]
> Are you using the NR UI through the iframe in Home Assistant? If so, try connecting directly to NR. Check your browser console for errors.
> 
> This package doesn't modify anything related to the inject/debug nodes.

I am experiencing the same issue but can confirm that connecting directly to Node-RED makes the nodes non-grayed again.
I am afraid I don't know how to check browser console for errors.

**Comment by sanderlv** [comment]
> Are you using the NR UI through the iframe in Home Assistant? If so, try connecting directly to NR. Check your browser console for errors.
> 
> This package doesn't modify anything related to the inject/debug nodes.

I think I hacve this eaxact same issue... When using NR addon and nodered via HA I get not status... When I go to IP:1880 all is fine... I started after I updated to node-red-contrib-home-assistant-websocket 0.67.2 (from the latest in the addon).

**Comment by cpuks** [comment]
> I had the same issue after upgrading from 0.65 to 0.68. I downgraded to 0.67.2 and the inject nodes started working again as they should.
> 
> However...there is no auto complete now within the nodes for action, entity, device id, area, floor, or label. it will give me a list of entities...but only about 10 or so. Nothing at all is listed under action, even if I put in a light for the entity. I have to type in the entire light.office_lamp and light.turn_on. Even typing them out fully doesn't bring up any match.
> 
> Disabled autocaching in server config node...restarted nodered...no change...re-enabled it...restarted...no change.
> 
> But when I connect to IP:1880 autocomplete works fine. Any thoughts? Not unusable...but a pain.
> 
> **Update**...was able to fix the issue by deleting all the browser data...then disabled caching of autocomplete...restarted node red...renabled caching...restarted nodered (entities worked after this but only entities)...restarted node red again...then everything else started working.

So debug and inject nodes are all working fine after you deleted browser data and played with caching?

**Comment by zachowj** [comment]
@HaraldGithub Are you accessing the Node-RED UI through an iframe, such as within Home Assistant, or directly? If it's through an iframe, have you tried accessing it directly to see if the issue persists? If it works directly, the problem may not be with this package but with the add-on.

**Comment by HaraldGithub** [comment]
The problem persists if i connect by iframe, directly over HA sidebar.
If i connect to NR by HA-IP:1880 closes within 10 seconds, so I couldn't adjust the above mentioned work around.
On weekend I'll try once more, maybe than it works.

**Comment by dannycohn** [comment]
Still seeing this in 0.72.0.  Using IP:port works, but seemingly intermittently, or only after waiting a while after a restart?  Haven't nailed down a pattern yet.

**Comment by tomadan1968** [comment]
Same problem for me....

**Comment by sanderlv** [comment]
I know this is an HA problem... still hoping for the next add=on update to resolve this. In the meantime, does anyone know where to mention this to get some help to resolve this from HA side?

**Comment by nappyjim** [comment]
I had this same issue when accessing NR through HA.  I then went to homeassistant.local:1880,  entered in my HA user credentials when prompted and then NR loaded and everything is working again.

**Comment by sanderlv** [comment]
I know, but that's a workaround and not a solution.

**Comment by zachowj** [comment]
@sanderlv you could try the node-red add-on repo. There's already several issues posted about it there.

https://github.com/hassio-addons/addon-node-red

**Comment by Markus730** [comment]
I Have the same Problem:
In the Web Interface the Status of the Nodes after 45 Minutes.
And high 40% Nodred Cpu usage
Starting with this Versions:
HA: 2024.8
Node red 18.0.5
Node-RED Companion Integration v4.02
node-red-contrib-home-assistant-websocket 0.67.2

**Comment by twister36** [comment]
I resolved this by going to node-red directly through the 1800 port (http://node-red-ip:1800). Once into node-red, in the upper right corner, node-red showed a yellow warning sign with X number of issues. Clicking this shows you all nodes with errors or references to Home Assistant entities that are missing/wrong. 

I went through all these issue and resolved them. When I got the the last one and hit 'deploy', node-red automatically restarted the node-red service. When it came back up, I check Node-red through HA and everything is working again!

**Comment by sanderlv** [comment]
I have no issues and problem persistent.

**Comment by zachowj** [comment]
Is everyone accessing the Home Assistant UI through a domain or an IP address? If you're using a domain, try accessing the UI via the IP address—does that resolve the issue with Node-RED?

**Comment by blaxxor** [comment]
I'm using HA with IP-adress and I had the same problem when using the embedded link within HA.
If i connected directly to Node-Red then it works fine.

I restored a snapshot so I'm at an old version that works for the moment.

**Comment by cpuks** [comment]
> Is everyone accessing the Home Assistant UI through a domain or an IP address? If you're using a domain, try accessing the UI via the IP address—does that resolve the issue with Node-RED?

In my case IP address is same so doesn't work correctly. Tried on Edge and Chrome, cleared cache, tried Windows/Android/iOS.

**Comment by zachowj** [comment]
The inject node, debug window, and other similar features all rely on WebSocket communication between the frontend and backend. You'll likely see WebSocket connection errors if you check your browser's developer tools under the Network tab.

Can someone share the specific errors that are happening?

**Comment by cpuks** [comment]
> The inject node, debug window, and other similar features all rely on WebSocket communication between the frontend and backend. You'll likely see WebSocket connection errors if you check your browser's developer tools under the Network tab.
> 
> Can someone share the specific errors that are happening?

Ok so you want me to dump those errors:
![{B91248AE-791A-4BB0-8912-C5B9BE2ABDEA}](https://github.com/user-attachments/assets/6135afdd-ef7d-4893-9cb3-cdc5ab98beb9)

**Comment by KevinHurts** [comment]
I also have the issue when connecting directly via ip

**Comment by bkr1969** [comment]
I can access via :1880 at home, but how do I do that remotely via NabuCasa?  I would like to be able to use NR away from home.

**Comment by cpuks** [comment]
Try inst

> I can access via :1880 at home, but how do I do that remotely via NabuCasa? I would like to be able to use NR away from home.

Easies way is to setup zerotier or tailscale or some kind of VPN to get inside home network while away - OpenVPN, Wireguard etc. Zerotier / Tailscale / Wireguard are available in addon store.
Why do you need access to such things as NR while away ?

**Comment by HaraldGithub** [comment]
@cpuks 

Sorry for my comment, but I would appreciate if the developer team will fix this issue instead of discussing VPN-access to my home-assistant-instance. ;-)

**Comment by cpuks** [comment]
Well HA is free and open source - anyone can help no one can expect miracles to be honest....

**Comment by bkr1969** [comment]
> Try inst
> 
> > I can access via :1880 at home, but how do I do that remotely via NabuCasa? I would like to be able to use NR away from home.
> 
> Easiest way is to setup zerotier or tailscale or some kind of VPN to get inside home network while away - OpenVPN, Wireguard etc. Zerotier / Tailscale / Wireguard are available in addon store. Why do you need access to such things as NR while away ?

I access NR from work sometimes when schedule is slow/thigs in automations break.  Not going to do VPN, just wondered if Nabu had the ability to connect to a specific port.

**Comment by sanderlv** [comment]
This is not a chatbox. Got to a forum then. This is about an issue, please provide info about the issue only.

**Comment by zachowj** [comment]
@cpuks That's the console output, but what I need is from the Network tab. Depending on your browser, it will look like the image below. Open the browser's developer tools before loading the Node-RED page, then switch to the Network tab. You can filter by type and look for "WS" (WebSocket). I'm specifically looking for the file /comms.

![image](https://github.com/user-attachments/assets/1415612b-dfd7-4233-be3a-1471cd658d1a)

**Comment by cpuks** [comment]
Ok, but how to provide you that results to be useful?
![{FB384240-85C6-41F8-884D-2E5AE9D0CF48}](https://github.com/user-attachments/assets/bc661a30-0f26-4de5-901c-451e851c0519)
![{8EACDC4B-EEDB-450F-8D8F-ACB486A8A3F1}](https://github.com/user-attachments/assets/6ec4c891-fb04-47f4-90e1-c0775fe788c1)

**Comment by zachowj** [comment]
When you connect directly to the Node-RED UI via port 1880, do you only see a single connection attempt to the `/comms` endpoint?

**Comment by Jens-Wymeersch** [comment]
With me, the port 1880 works perfectly, but the iframe does not. There is nothing to see in the logs.
Node-RED version: v4.0.3
Node.js  version: v18.20.4

**Comment by Markus730** [comment]
I have several Errors in the Console. And the Node Red Flows are very slow and get stuck. If the Browser is open.
Node Red Core Usage from 10%to 40%
HA: 2024.9
Node red 18.1.1
Node-RED Companion Integration v4.1.1
node-red-contrib-home-assistant-websocket 0.73.0

![Bildschirmfoto 2024-10-06 um 14 53 42](https://github.com/user-attachments/assets/c9557fe2-d3af-4fa4-91d0-8de16c2f9bb4)
![Bildschirmfoto 2024-10-06 um 14 53 13](https://github.com/user-attachments/assets/f52e89a7-7bd2-4481-a060-6402c4e87294)
![Bildschirmfoto 2024-10-06 um 14 47 02](https://github.com/user-attachments/assets/5d0d9d27-7a55-4e65-ae66-fa068d0b4557)
![Bildschirmfoto 2024-10-06 um 14 40 21](https://github.com/user-attachments/assets/e75f22c7-6c36-4139-b277-7068d58142db)

**Comment by S-E-B-123** [comment]
First of all, I would like to say that I am not directly affected by the problem. However, if I set up another HA server in one of my HA nodes as a test with exactly the same settings as in my original HA server configuration node, I can observe the described effect with the inject nodes after restarting the NR add-on.
The Inject nodes can then no longer be triggered.  If I remove the duplicate HA-server entry again in the corresponding node and restart the NR add-on, all was fine without any problem.
So the problem could possibly be due to duplicate HA server entries that were created by importing external flows.
In the case of the error, I could see also a lot of comms lines in the browser developer tools under Network -> Websocks. If everything is fine, there is only one comms line.

Maybe this information is helpful for someon.

**Comment by jonrupell** [comment]
Seems like all the forums discussing this have MANY people with this problem. Ones monitored by node red claim it is an HA problem and the ones affiliated with the HA teams say it is a node red problem. Truthfully, who's problem it is doesn't matter too much if both your pools of users are effected. Can the Node Red team and the HA team please tag up and try to solve this soon! As someone who relies on node red with their home of 500 HA connected smart devices, I would greatly appreciate it!

**Comment by zachowj** [comment]
The latest release, v0.74.2, should resolve this issue for most users, but it’s more of a temporary fix. The underlying problem is that both the Supervisor ingress proxy and the Home Assistant ingress proxy have their `websocket max_msg_size` set to a default of 4MB. For users with a large number of entities, devices, floors, areas, or Home Assistant issues, when the Node-RED backend sends this data during connection startup, the large payload causes the websocket to loop between connecting and disconnecting.

This issue specifically affects users who access the Node-RED UI via the Home Assistant UI using the ingress address (through the iframe). It doesn’t impact users accessing Node-RED directly on port 1880, as the Node.js default max message size is 100MB, which can handle larger message payloads without connection issues.

Node-RED relies heavily on the websocket connection for status updates, inject nodes, the Home Assistant issue tracker, and more. When the websocket connection fails to remain stable, all these features break, which is why users are encountering various issues—all stemming from the same root cause of the websocket connection repeatedly disconnecting.

**Comment by bkr1969** [comment]
Thank you so much for that detailed explanation. Sometimes just knowing that “the people responsible for” things are aware of an issue is reassuring. Your explanation makes total sense and even if it’s only a temporary fix, maybe it will eventually lead to something more permanent. 

Will this update show up in HA? Or asked another way, what’s the quickest way to update this for those of us using HA?

Thanks again!

**Comment by HaraldGithub** [comment]
> 
> Will this update show up in HA? Or asked another way, what’s the quickest way to update this for those of us using HA?
> 

No, it will shown in Node-Red it selves, where you can see all node-updates.

**Comment by zachowj** [comment]
@bkr1969 You can update in a few ways. One is through the [palette manager](https://nodered.org/docs/user-guide/editor/palette/manager). Alternatively, you can go to the GitHub release page and download the `node-red-contrib-home-assistant-websocket-*.tgz` file from the assets section. Then, in Node-RED, go to the palette manager under the "Install" tab and click on "Upload module tgz file" button.


![image](https://github.com/user-attachments/assets/7f1b7390-af31-4c26-8adb-bd6f40802e06)

**Comment by KevinHurts** [comment]
I'm hoping that the update fixes the issue but I'm also having the problem if I connect to node red directly via port 1880

**Comment by cpuks** [comment]
Happy to report that 0.74.2 fixed issues I had - thanks for work, and it was worth waiting, I know there are some edge cases and problems might persist, but I can close that bug now.

**Comment by sanderlv** [comment]
YES! It works again :-) THANK YOU!

**Comment by blaxxor** [comment]
Confirmed working here as well. Well done fixing this issue.

**Comment by MarkoBolt** [comment]
> The latest release, v0.74.2, should resolve this issue for most users, but it’s more of a temporary fix. The underlying problem is that both the Supervisor ingress proxy and the Home Assistant ingress proxy have their `websocket max_msg_size` set to a default of 4MB. For users with a large number of entities, devices, floors, areas, or Home Assistant issues, when the Node-RED backend sends this data during connection startup, the large payload causes the websocket to loop between connecting and disconnecting.
> 
> This issue specifically affects users who access the Node-RED UI via the Home Assistant UI using the ingress address (through the iframe). It doesn’t impact users accessing Node-RED directly on port 1880, as the Node.js default max message size is 100MB, which can handle larger message payloads without connection issues.
> 
> Node-RED relies heavily on the websocket connection for status updates, inject nodes, the Home Assistant issue tracker, and more. When the websocket connection fails to remain stable, all these features break, which is why users are encountering various issues—all stemming from the same root cause of the websocket connection repeatedly disconnecting.

Many thanks. This fix has been created! The efforts are greatly appreciated! 🥇

**Comment by lucode** [comment]
Well, I still have the same problems after updating the palette. It seems even more worth, because some of the entities I have created via the Node-Red companion are occasionally unavailable.

I should eventually try to run Node Red on a separate VM? But I'm not sure if this would help as it will probably the same memory for the websocket communication.  And I'm wondering why so many people suddenly had such problems since summer.
 
I guess it has something to do with the change in the HA websocket as this change happened around the same time:
**hass.http.register_static_path which is deprecated**

The question is that eventually other integrations are not yet or not correctly updated to the new `hass.http.async_register_static_paths` method.

https://github.com/jeroenterheerdt/HAsmartirrigation/issues/429
