### ISSUE TITLE
extra entities shown in entity autocomplete results

### ISSUE THREAD

**Issue by poldim** [zachowj/node-red-contrib-home-assistant-websocket#1492]
### Describe the bug

- When searching for entity names, these 5 entities persistently come up as results no matter the search query
- It appears to happen in `events: state node` and `trigger: state node` but not in `current state node`

### To Reproduce

1. Place a new or modify an existing `events: state node`
2. Click on entity field and type any search query to narrow the results

### Expected behavior

Only results would be shown that match the wildcard of the typed text.  

### Screenshots

<img width="505" alt="image" src="https://github.com/zachowj/node-red-contrib-home-assistant-websocket/assets/16869713/3d841c63-8e03-45bd-9971-083bed9145b1">

<img width="502" alt="image" src="https://github.com/user-attachments/assets/640bfff6-15ef-4802-88a8-50fd5b48bb5f">

![image](https://github.com/zachowj/node-red-contrib-home-assistant-websocket/assets/16869713/b8a8017f-5215-4357-b23d-38963de1b74c)  

![image](https://github.com/zachowj/node-red-contrib-home-assistant-websocket/assets/16869713/e89363e1-49d2-48a9-94c5-33006a251721)

But these individual entities arent in my node red flows as they're not found in search:
<img width="527" alt="image" src="https://github.com/user-attachments/assets/2e37d76a-f974-44ef-b049-ebd71200a687">

<img width="527" alt="image" src="https://github.com/user-attachments/assets/e3c2bba0-ef84-497b-9650-0a404b467571">

### Environment Information

Home Assistant version: 2024.7.4

Node-RED version: v4.0.2
Docker: `nodered/node-red:latest`
Add-on: no

node-red-contrib-home-assistant-websocket 0.68.0

Item | version
-- | --
NODE_RED_VERSION | v4.0.2
NODE_VERSION | 20.15.1
YARN_VERSION | 1.22.22

<br class="Apple-interchange-newline">

### Additional context

Config for the first input boolean is very basic:
```yaml
input_boolean:
  today_is_holiday:
    initial: off
```

**Comment by zachowj** [comment]
Could you double-check the version of the node-red-contrib-home-assistant-websocket you have installed? The screenshots are not from v0.68.0

**Comment by poldim** [comment]
> Could you double-check the version of the node-red-contrib-home-assistant-websocket you have installed? The screenshots are not from v0.68.0

Good catch!  I had taken the screenshots last week but didnt get to writing out the issue until today after the update.

Checking again, it looks like it's no longer an issue:
<img width="498" alt="image" src="https://github.com/user-attachments/assets/4f4a72f2-7b00-4c29-b41e-df6f5de8ce0c">


<img width="497" alt="image" src="https://github.com/user-attachments/assets/e37342df-1cda-4ef9-ac03-4cf798b4aac9">
