### ISSUE TITLE
Getting - Alert:This node will be updated to version 1 from 0 (changes)

### ISSUE THREAD

**Issue by michaelblight** [zachowj/node-red-contrib-home-assistant-websocket#150]
I have version 0.14.2 of this running as part of the Node Red add-on for Hass.io. I upgraded HA to 0.97.2 and the Node Red add-on to 4.0.7 and restarted Home Assistant. Node.js is on version 10.16.0.

Somewhere along the way, all of the websocket nodes started displaying text in yellow italics with "Alert:This node will be updated to version 1 from 0 (changes)". I Googled it to death, but couldn't find any reference to this alert, other than in the source code. Some of the other nodes in the NR palette have an "Update to xxx" button, but not this one. Consequently I can't figure out what I need to do to cause the update to happen.

I'm running in Docker (since it's hass.io) under a VirtualBox Ubuntu VM on a Windows machine.

**Comment by zachowj** [comment]
[v0.12.0](https://github.com/zachowj/node-red-contrib-home-assistant-websocket/releases/tag/v0.12.0) (top)

[v0.14.0](https://github.com/zachowj/node-red-contrib-home-assistant-websocket/releases/tag/v0.14.0) (bottom)

and clicking on the changes link in the alert will show you the changes for that version.

**Comment by michaelblight** [comment]
Ah thanks. I had clicked on the link, but it takes you to the link below, which didn't seem to make sense.

https://github.com/zachowj/node-red-contrib-home-assistant-websocket/wiki/current-state#version

**Comment by timdonovanuk** [comment]
So do all these nodes need to be manually replaced with new ones? 

Sorry this thread isn't very insightful or clear as to how to resolve this.

**Comment by Banthaf0dder** [comment]
I'd like to know the same thing. What do I need to do to actually update the node to version 1?

**Comment by michaelblight** [comment]
I found that if you go in to each node you can just save the node and the message goes away. I didn’t find an easier way to do it.
