### ISSUE TITLE
Stopping NodeRed from loading at all

### ISSUE THREAD

**Issue by Jleagle** [zachowj/node-red-contrib-home-assistant-websocket#1504]
### Describe the bug

As the UI loads, i gets stuck at `Loading Nodes 39/59`

The console shows it trying to load some assets:
```
GET https://nodered.xx.com/resources/node-red-contrib-home-assistant-websocket/select2.full.min.js?v=4.1.0-rc.0 net::ERR_ABORTED 404 (Not Found)
GET https://nodered.xx.com/resources/node-red-contrib-home-assistant-websocket/maximize-select2-height.min.js?v=1.0.4 net::ERR_ABORTED 404 (Not Found)
```

Thanks!!

### To Reproduce

I just load up the UI in chrome

### Expected behavior

For things to load as normal 😢 

### Screenshots

<img width="1303" alt="Screenshot 2024-08-27 at 08 55 30" src="https://github.com/user-attachments/assets/8a3a0019-b421-4c3c-9b8a-f91f7b6c1ff2">

### Environment Information

I cant click the button as its in the UI but i have everything updated to the latest stable as of the last week or so.

**Comment by zachowj** [comment]
Try doing a hard refresh on the page. Those are old files that have been removed.

**Comment by Jleagle** [comment]
> Try doing a hard refresh on the page. Those are old files that have been removed.

Doesn't seem to fix it.

**Comment by zachowj** [comment]
If you're using the latest version of this package, a caching issue is likely causing the problem, as those files are no longer present in the code.

**Comment by Jleagle** [comment]
I tried to use the cli to disable the plugin and realised its not quite the latest version.. Is there a way i can update it or disable it? When i try to disable via the cli i just get told the types are in use..

```
nodered:/usr/src/node-red# node-red-admin info node-red-contrib-home-assistant-websocket/all
Name:      node-red-contrib-home-assistant-websocket/all
Module:    node-red-contrib-home-assistant-websocket
Version:   0.65.1
Types:     ha_entity_filter, ha_sidebar, ha_sidebar_toolbar, x-tmpl-handlebars, x-tmpl-handlebars, ha-api, ha-binary-sensor, ha-button, api-call-service, server, api-current-state, ha-device, ha-device-config, ha-entity, ha-entity-config, server-events, ha-events-calendar, server-state-changed, ha-fire-event, ha-get-entities, api-get-history, ha-number, poll-state, api-render-template, ha-select, ha-sensor, ha-sentence, ha-switch, ha-tag, ha-text, ha-time, ha-time-entity, trigger-state, ha-update-config, ha-wait-until, ha-webhook, ha-zone
State:     enabled
```
```
nodered:/usr/src/node-red# node-red-admin disable node-red-contrib-home-assistant-websocket
400: Type in use: ha-binary-sensor, ha-button, api-call-service, server, api-current-state, ha-device-config, ha-entity-config, server-events, server-state-changed, ha-switch
```

**Comment by zachowj** [comment]
From within the `config` directory you should be able to run `npm install node-red-contrib-home-assistant-websocket`

**Comment by Jleagle** [comment]
Thanks! For some reason npm only managed to update it to ^0.66.1 but that was enough to get the UI working where it let me update to 0.68.1

**Comment by a011528** [comment]
This is now solved. Essentially after the update in Nodered, i needed to start nodered, it would not reboot (even though it looked like it was) though the terminal to reboot.
