### ISSUE TITLE
API node http 403

### ISSUE THREAD

**Issue by john-arvid** [zachowj/node-red-contrib-home-assistant-websocket#151]
**Describe the bug**
Not sure if it is a bug or if I am doing it wrong. (Maybe the json data is wrong, but then it shouldn't give a 403)
But I am trying to POST a REST API message with the API node, but there is nowere to add authentication.

**To Reproduce**

1. Add the API node
2. Choose HTTP as protocol and POST as method
3. Add path and data and trigger the node
4. See error in the debug log "Error Message: Request failed with status code 403"

**Expected behavior**
A posibility to add authentication.

**Example Flow**
```
[
    {
        "id": "c5d30dcd.8f1ad",
        "type": "ha-api",
        "z": "26e3101e.d5bb6",
        "name": "JAKB Home",
        "server": "d30490a3.29bd",
        "protocol": "http",
        "method": "post",
        "path": "http://192.168.1.20:8123/api/states/light.white_led",
        "data": "{\"state\":\"on\"}",
        "dataType": "json",
        "location": "payload",
        "locationType": "msg",
        "responseType": "json",
        "x": 570,
        "y": 440,
        "wires": [
            []
        ]
    },
    {
        "id": "b3b1faf2.fc43f8",
        "type": "inject",
        "z": "26e3101e.d5bb6",
        "name": "",
        "topic": "",
        "payload": "",
        "payloadType": "date",
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "x": 240,
        "y": 400,
        "wires": [
            [
                "c5d30dcd.8f1ad"
            ]
        ]
    },
    {
        "id": "d30490a3.29bd",
        "type": "server",
        "z": "",
        "name": "Home Assistant"
    }
]
```

**Environment (please complete the following information):**

- Node Red Version: v0.20.7
- Node.js Version: v10.16.0
- NR Home Assistant Plugin Version: 4.1.0
- Is Node Red running in Docker: hassio

**Other (please complete the following information):**

- Have you searched previous issues for duplicates?:
Yes

**Comment by zachowj** [comment]
The API node already knows the authentication from the server you have selected in the node. The `path` should be `/api/states/light.white_led`

**Comment by john-arvid** [comment]
Ok, now I get a 401. 
But home assistant is still giving me this message: "Login attempt or request with invalid authentication"

**Comment by john-arvid** [comment]
Yes, I have several other flows that is connecting to Home Assistant.
The reason is just to simplify troubleshooting. My end result is to call a set state.

**Comment by zachowj** [comment]
Are you sure you have the correct server selected under the API node?

**Comment by john-arvid** [comment]
Yes, I only have one server.

I tested again now after a Home Asssitant update, and now it is working.
I updated from 0.97.1 to 0.98.1, not sure if that was the fix, but the same code is now working.
