### ISSUE TITLE
Client exceeded max pending messages [2]: 512

### ISSUE THREAD

**Issue by nirkons** [zachowj/node-red-contrib-home-assistant-websocket#153]
**Describe the bug**
Node Red randomly throws "API Error" on any Hass websocket nodes.

I think it may be related to this:
Client exceeded max pending messages [2]: 512
9:14 AM components/websocket_api/http.py (ERROR) - message first occurred at September 1, 2019, 8:09 PM and shows up 11504 times

I am trying to pinpoint the origin of this error, because the only thing i can do to fix it is to completely reinstall HASS.

**To Reproduce**
Please see my comment here:
https://github.com/home-assistant/home-assistant/issues/23938#issuecomment-527038901

**Expected behavior**

**Environment (please complete the following information):**

- Node Red Version: latest on Hass.IO
- Node.js Version: latest one that comes with hass node red
- NR Home Assistant Plugin Version: [e.g. 0.5.0]: latest
- Is Node Red running in Docker: [e.g. yes/no/hassio]: hassio

**Other (please complete the following information):**

- Have you searched previous issues for duplicates?:

**Additional context**

**Comment by Pirol62** [comment]
I do not think, that node red is the key.
I have exactly this error but no node red activated and never before.

**Comment by zachowj** [comment]
@nirkons Are you getting any errors in the node-red logs about disconnects or anything? They only thing I can think of is that you might be spamming an output node, call-servce, fire-event, or api node, which is overloading home assistant.

**Comment by nirkons** [comment]
> @nirkons Are you getting any errors in the node-red logs about disconnects or anything? They only thing I can think of is that you might be spamming an output node, call-servce, fire-event, or api node, which is overloading home assistant.

Define spamming, what is considered too much? more than 512 requests at once? I don't think I am getting there.

I do have about 30 ESP32 devices each with 17 sensors and 8 switches (I use node red to call those switches for all 30 devices at once every couple of minutes, so that makes 240 requests at once).
however, this worked fine for weeks until the error first appeared, if I reinstall HASS completely and import the flows, the error will not show up for weeks again

**Comment by zachowj** [comment]
Really don't have any more ideas for you. This package uses the same one as the web UI of HA uses so not really sure what might be causing your issues. Nothing in the communication layers has changed in over 60+ days so if this is something new it might not even be an issue with this package.

**Comment by WoLpH** [comment]
I can confirm it's definitely an issue with this package. Since enabling this package in Node-RED I'm getting the exact same issues. The reason that you cannot reproduce it is most likely related to the amount of devices you have. 

Using the following command I get 497 different devices:
```
cat .storage/core.entity_registry | jq '.data.entities | length'
```

(tiny portion of the log, the actual one is nearly 100 times larger)
```
2019-09-14 22:23:32 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.34930339120] Client exceeded max pending messages [2]: 512
2019-09-14 22:23:32 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.34930339120] Client exceeded max pending messages [2]: 512
2019-09-14 22:23:32 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.34930339120] Client exceeded max pending messages [2]: 512
2019-09-14 22:23:32 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.34930339120] Client exceeded max pending messages [2]: 512
2019-09-14 22:23:32 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.34930339120] Client exceeded max pending messages [2]: 512
2019-09-14 22:23:32 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.34930339120] Client exceeded max pending messages [2]: 512
2019-09-14 22:23:32 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.34930339120] Client exceeded max pending messages [2]: 512
2019-09-14 22:23:32 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.34930339120] Client exceeded max pending messages [2]: 512
2019-09-14 22:23:32 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.34930339120] Client exceeded max pending messages [2]: 512
2019-09-14 22:23:32 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.34930339120] Client exceeded max pending messages [2]: 512
2019-09-14 22:23:32 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.34930339120] Client exceeded max pending messages [2]: 512
2019-09-14 22:23:32 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.34930339120] Client exceeded max pending messages [2]: 512
2019-09-14 22:23:32 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.34930339120] Client exceeded max pending messages [2]: 512
```

**Comment by WoLpH** [comment]
To work around the issue (by disabling this package) you can use the following steps:

1. Go to Node-RED
2. Click down pointing button at the top right
![image](https://user-images.githubusercontent.com/270571/64913957-f553b900-d749-11e9-8e98-dcb9a8c14e8f.png)

3. Click on "Configuration nodes" in the menu dropdown
4. Doubleclick on the Home Assistant server
5. Press the "Delete" button on that node :)

**Comment by nirkons** [comment]
> To work around the issue (by disabling this package) you can use the following steps:
> 
> 1. Go to Node-RED
> 2. Click down pointing button at the top right
>    ![image](https://user-images.githubusercontent.com/270571/64913957-f553b900-d749-11e9-8e98-dcb9a8c14e8f.png)
> 3. Click on "Configuration nodes" in the menu dropdown
> 4. Doubleclick on the Home Assistant server
> 5. Press the "Delete" button on that node :)

That's not really a solution... thats like saying "just uninstall HASS and the error will go away"
I am using the package heavily, deleting that node will basically stop all my flows from working

**Comment by WoLpH** [comment]
That's why I call it a workaround and not a solution ;)

I personally have no idea if the issue is new or old. I was planning to enable Node-RED and ran into this issue so I'll wait a bit for the time being.

**Comment by zachowj** [comment]
I attempted to reproduce this based on the assumption that the number of entities was causing the issue.

I set up two different VMs, with specs close to a raspberry pi 3, running HA, Node-RED, and MQTT. Created 400 and 800 devices on each instance that would get random updates every 10 to 30 seconds.

Both those setups have been running around a week without issue.

**Comment by Pirol62** [comment]
My guess is, thy t it has something to do with mobile apps like wallpaper. Sometimes, the error doesn't appear one day and then suddenly I have it 20 times. As I wrote, I haven't installed note red. But I have several mobile devices with wallpaper or webgui running sometimes via duckdns and sometimes NABU Casa

**Comment by nirkons** [comment]
> I attempted to reproduce this based on the assumption that the number of entities was causing the issue.
> 
> I set up two different VMs, with specs close to a raspberry pi 3, running HA, Node-RED, and MQTT. Created 400 and 800 devices on each instance that would get random updates every 10 to 30 seconds.
> 
> Both those setups have been running around a week without issue.

thanks for trying to replicate, I think system specs even are not relevant as I am running it on a dedicated quad core, 32GB, raid-0 server.

1. Another direction that might be related is putting many of these entities on the UI itself, so the UI also received updates when the switch/sensor changes.

2. additional errors that happen in conjunction with this API one, but may be unrelated
```
2019-09-23 18:18:53 WARNING (MainThread) [homeassistant.components.mqtt] Can't decode payload b'\xc0\x0024.' on pod7/sensor/pod_7_liquid_volume/state with encoding utf-8
2019-09-24 03:50:16 WARNING (MainThread) [homeassistant.components.mqtt] Can't decode payload b'\xc0\x0025.' on pod14/sensor/pod_14_liquid_volume/state with encoding utf-8
2019-09-24 06:47:08 WARNING (MainThread) [homeassistant.components.mqtt] Can't decode payload b'\xc0\x0064.' on pod9/sensor/pod_9_lux/state with encoding utf-8
2019-09-24 08:31:16 WARNING (MainThread) [homeassistant.components.mqtt] Can't decode payload b'\xc0\x0014.' on pod15/sensor/pod_15_uva/state with encoding utf-8
2019-09-24 10:13:16 WARNING (MainThread) [homeassistant.components.mqtt] Can't decode payload b'\xc0\x0025.' on pod14/sensor/pod_14_liquid_volume/state with encoding utf-8
2019-09-24 14:09:01 WARNING (MainThread) [homeassistant.components.mqtt] Can't decode payload b'\xc0\x000.' on pod28/sensor/pod_28_uvi/state with encoding utf-8
2019-09-24 17:48:38 WARNING (MainThread) [homeassistant.components.mqtt] Can't decode payload b'\xc0\x001.' on pod2/sensor/pod_2_board_power_consumption/state with encoding utf-8
2019-09-24 17:58:04 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (MySQLdb._exceptions.OperationalError) (1206, 'The total number of locks exceeds the lock table size')

and

2019-09-24 20:14:48 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 275, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp\_http_parser.pyx", line 523, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: invalid HTTP method
2019-09-24 20:14:50 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 275, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp\_http_parser.pyx", line 523, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: invalid HTTP method
2019-09-24 20:15:07 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 275, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp\_http_parser.pyx", line 523, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: invalid HTTP method
2019-09-24 20:15:10 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 275, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp\_http_parser.pyx", line 523, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: invalid HTTP method
2019-09-24 20:15:11 ERROR (MainThread) [aiohttp.server] Error handling request

and

2019-09-25 13:29:58 WARNING (MainThread) [asyncio] socket.send() raised exception.
2019-09-25 13:29:58 WARNING (MainThread) [asyncio] socket.send() raised exception.
2019-09-25 13:29:58 WARNING (MainThread) [asyncio] socket.send() raised exception.
2019-09-25 13:29:58 WARNING (MainThread) [asyncio] socket.send() raised exception.
2019-09-25 13:29:58 WARNING (MainThread) [asyncio] socket.send() raised exception.
2019-09-25 13:29:58 WARNING (MainThread) [asyncio] socket.send() raised exception.
2019-09-25 13:29:58 WARNING (MainThread) [asyncio] socket.send() raised exception.
2019-09-25 13:29:58 WARNING (MainThread) [asyncio] socket.send() raised exception.
2019-09-25 13:29:58 WARNING (MainThread) [asyncio] socket.send() raised exception.

```

in addition, it seems my error has alternating numbers
```
2019-09-22 14:24:27 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.**139734682041680**] Client exceeded max pending messages [2]: 512
2019-09-22 14:24:27 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.**139734688729360**] Client exceeded max pending messages [2]: 512
```

any idea what is the meaning of these numbers?

**Comment by nirkons** [comment]
> My guess is, that it has something to do with mobile apps like wallpaper. Sometimes, the error doesn't appear one day and then suddenly I have it 20 times. As I wrote, I haven't installed note red. But I have several mobile devices with wallpaper or webgui running sometimes via duckdns and sometimes NABU Casa

what is wallpaper in this regard? I dont think I have such a thing (i do run duckdns though)

maybe its also related to the UI or to the node-red-dashboard which I actually am running.

**Comment by Pirol62** [comment]
Wallpaper is an android app for hassio

**Comment by WoLpH** [comment]
Thanks for trying to replicate.

I personally doubt it's related to the system specs too. I'm running an i7 with 32 GB of ram with a 3 disk raidz and a dedicated cache. Not the fastest machine but no slouch either, especially when comparing to a Pi. 

As for apps, I don't run wallpaper but I do have Ariela on my phone. I don't expect them to be the culprits though, but I'll have to do more research to find what's causing this.

My node red install is completely fresh as I'm not using it yet so that's probably no factor either.
I'm running a plain node red install from the freebsd ports with home assistant from the dev branch.

Hard to pinpoint but I'll add a bunch of logging to see what's causing this

**Comment by zachowj** [comment]
@nirkons 
> in addition, it seems my error has alternating numbers
> 
> ```
> 2019-09-22 14:24:27 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.**139734682041680**] Client exceeded max pending messages [2]: 512
> 2019-09-22 14:24:27 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.**139734688729360**] Client exceeded max pending messages [2]: 512
> ```
> 
> any idea what is the meaning of these numbers?

In my quick research, it's the internal id given to the websockethandler class. So you actually have two different connections reporting the error at the same time. Node-RED should only be using one connection unless you have more than one server config setup. 

https://github.com/home-assistant/home-assistant/blob/b1118cb8ffa4c21a955ae569697a3f81eae94e8a/homeassistant/components/websocket_api/http.py#L51

**Comment by WoLpH** [comment]
After adding a bunch of logging to hass I can confirm it's definitely related to the amount of devices and values.

The way this library subscribes to the events results in a torrent of messages being sent to the websocket. During normal processing this is probably not an issue but during startup there is some resource starvation causing this to overflow the queue when running a large hass instance.

For what it's worth, changing the limit from `512` to `1024` seems to solve the issue for me. I'm not sure if that's the right solution, another might be to add a startup delay to this library or something.

**Comment by nirkons** [comment]
How is it possible to change the limit?

**Comment by WoLpH** [comment]
I simply changed: https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/components/websocket_api/const.py#L10

With a bit of work you could probably monkeypatch it from a custom module or something, but I'm running from source anyway so it's easy enough to change.

**Comment by nirkons** [comment]
I'm running HASS.io so not so easy for me... Maybe we can try to merge it
into master?

**Comment by WoLpH** [comment]
I've already raised the question in the Home Assistant Discord whether the right solution is to raise the limit. If noone has any objections I'll create a pull request

**Comment by balloob** [comment]
The problem is that the messages are not read fast enough by the client. 512 messages is a lot. 

Does the Node Red HA integration wait for anything to execute before reading the next message?

**Comment by Pirol62** [comment]
Hi, by the way: this problem is not only related to node red. I have these issues daily without having node red installed

**Comment by WoLpH** [comment]
@balloob I honestly don't think the integration is to blame here, here's a log of how many messages are queued and sent in my instance:

| Time     | Queued | Sent |
|----------|--------|------|
| 19:49:40 | 1      | 0    |
| 19:49:42 | 0      | 1    |
| 19:49:44 | 1      | 0    |
| 19:49:46 | 0      | 1    |
| 19:49:49 | 1      | 0    |
| 19:50:35 | 4      | 0    |
| 19:50:36 | 142    | 5    |
| 19:50:37 | 73     | 0    |
| 19:50:38 | 40     | 0    |
| 19:50:51 | 0      | 8    |
| 19:50:54 | 421    | 247  |
| 19:50:55 | 572    | 579  |
| 19:50:56 | 712    | 837  |
| 19:50:57 | 943    | 520  |
| 19:50:58 | 347    | 1059 |
| 19:50:59 | 13     | 12   |
| 19:51:00 | 13     | 14   |
| 19:51:01 | 5      | 4    |
| 19:51:05 | 0      | 1    |
| 19:51:08 | 24     | 24   |
| 19:51:09 | 7      | 7    |
| 19:51:10 | 8      | 8    |
| 19:51:29 | 28     | 28   |
| 19:51:31 | 5      | 5    |
| 19:51:42 | 8      | 8    |
| 19:51:44 | 41     | 41   |

**Comment by balloob** [comment]
Are all messages queued up state changes ?

**Comment by WoLpH** [comment]
@balloob they're the result of the debug log line in `http.py` for sent: https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/components/websocket_api/http.py#L64

And a log line I added here for queued: https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/components/websocket_api/http.py#L89

**Comment by balloob** [comment]
This is our code to send messages:
https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/components/websocket_api/http.py#L56

Based on the implementation of `send_json`, we could simplify it, which should save us 1 await. https://github.com/aio-libs/aiohttp/blob/c09c538e036619ae549280fb9051fd6084e8252c/aiohttp/client_ws.py#L165-L168

I'll put that in a PR and see if that helps emptying the queue faster.

**Comment by WoLpH** [comment]
@balloob wouldn't increasing the limit to perhaps 2048 be a good idea in any case? With close to a thousand messages being queued within a second even a tiny hiccup will fill up a queue of 512 items.

**Comment by nirkons** [comment]
I also second if possible to increase the limit as well or better yet, have an option to configure it via yaml or UI, although I'm not sure what is the best approach to make HASS scalable.

**Comment by balloob** [comment]
We're not going to add config option for this. Config options are a maintenance death sentence.

We can't just randomly go around increasing limits until we figure out what is causing the issue. First test to see if the current fix is helping to resolve it. 

It's not normal to have 500 messages queued up . Please enable logging for the websocket to see what is queued up.

```
logger:
  default: info
  logs:
    homeassistant.components.websocket_api: debug
```

**Comment by WoLpH** [comment]
I've sent a log to you @balloob through discord :)

I'm not sure if there really is an issue but it's simply a lot of data. But I'm not sure how the usage of the feature was intended, should it aggregate?

From what I can gather, I have 3227 different "topics" in a few minutes of logs. And the most prominent one is sent 15 times but most of them only once.

**Comment by balloob** [comment]
After diagnosing with @WoLpH, we found a combination of factors at play.

One part was that he was using MQTT statestream which publishes a lot to MQTT. Each state attribute is a service call. So 1 state change becomes 10 publishes. This on its own is not a problem for Home Assistant, but it is a problem in combination with this lib.

This lib is subscribing to **all** events [here](https://github.com/zachowj/node-red-contrib-home-assistant-websocket/blob/89978d628f2a7deaed69349a8ee2a47ef3fceb46/lib/ha-websocket.js#L67). Since each MQTT publish is a service call, each of those events is sent to Node Red where it will most likely be discarded.

I think that to solve this bug, this lib should only subscribe to events that Nodes are subscribing to.

**Comment by WoLpH** [comment]
With regards to not subscribing to all events, specific subscriptions are possible with the library (although it still subscribes to all events internally right now), but for debugging purposes I imagine it could still be convenient to (temporarily) subscribe to all events.

A list of the available nodes right now:
![image](https://user-images.githubusercontent.com/270571/66398360-eb864400-e9dd-11e9-834b-d2089b1f56eb.png)

The first one is mostly for debug purposes of course but it's quite convenient :)

**Comment by balloob** [comment]
@zachowj I don't know how Node Red works, but would it be possible to only subscribe to events if a node is connected to it?

**Comment by zachowj** [comment]
Three of the four event nodes only use only the state_changed event. The remaining node is sort of a firehose node for all events received from HA which allows users to filter out non-standard events such as zwave or deconz and perform actions based on those events.

The nodes work on an event bus so currently, the backend doesn't know which events are being listened for that's why the backend subscribes to all events from HA. This could be changed to require the events: all nodes to register which event(s) it needs and only subscribe to those events. As the current way doesn't seem maintainable for large amounts of events.

This definitely can be changed to only subscribed to needed events. I need to attempt to find a way where this won't be a huge breaking change to everyone who is currently using the firehose method.

@balloob If I understand the problem correctly, are we still going to have an issue when a user has an extremely high number of state_changed events fired in quick succession?

**Comment by balloob** [comment]
Theoretically, yes. In practice you won't reach that limit. This means that there would need to be 512 state changes in the same event loop cycle. That is very unlikely.

**Comment by nirkons** [comment]
> Theoretically, yes. In practice you won't reach that limit. This means that there would need to be 512 state changes in the same event loop cycle. That is very unlikely.

How long is an event loop cycle?

The question is, is the current implementation scale-able? this is the only issue I've run into so far with HomeAssistant in regards to scaling :)

I am running ~50 ESP32 devices, each with ~15 sensors which update every 10 seconds and about 10 switches, 4 of them are being turned on/off every 5 minutes.
If everything is synced (which could happen), that's (750+200) 950 state changes simultaneously.

But this is only my use case, what about if someone were to run hundreds of such devices?
if you look at the big picture, 50 devices isn't really a lot.

Anyhow, thanks for your help!

**Comment by balloob** [comment]
Event loop cycles are as short as possible. Depending on the amount of work but something like 10ms ? The odds that 50 devices hit the same cycle are like 0.000001%. 

If you want to see how fast Home Assistant handles state change events, run the benchmark.

```
hass --script benchmark async_million_state_changed_helper
```

My system handles a million state change events in 2.9s. You'll be fine.

**Comment by zachowj** [comment]
@nirkons If you wanted to try this out before it gets updated in the hass.io addon you can add this to your config:

```
"npm_packages": [
  "git+https://github.com/zachowj/node-red-contrib-home-assistant-websocket#dev"
],
```

**Comment by nirkons** [comment]
> @nirkons If you wanted to try this out before it gets updated in the hass.io addon you can add this to your config:
> 
> ```
> "npm_packages": [
>   "git+https://github.com/zachowj/node-red-contrib-home-assistant-websocket#dev"
> ],
> ```

still getting the error btw even after latest PR

**Comment by zachowj** [comment]
Are you still running any events: all nodes without the Event Type defined? The solution I implemented still allows you to listen for all events from HA if is not defined.

If that's not the case you could try turning on the debug level logging of the websocket_api like stated above, and see if all the events are state_changed events or something else.

**Comment by timdonovanuk** [comment]
Sorry dead thread, but wondering why this node doesn't allow you to filter by entity_id that fired the event? Most other HA nodered nodes include this filter natively. This would completely avoid this issue.
