### ISSUE TITLE
Cant specify Target on Action node with Action: tts.google_translate_say  

### ISSUE THREAD

**Issue by defisit** [zachowj/node-red-contrib-home-assistant-websocket#1534]
### Describe the bug

In an existing Action node (previously the call service node), the target is not visible or can be specified (Eventhough for the existing node the target is still being called somehow) when using Action tts.google_translate_say. With a new Action node, the target is also not selectable when using the Action tts.google_translate_say 

![Schermafbeelding 2024-09-08 113555](https://github.com/user-attachments/assets/5532b2d9-9280-421b-90c2-b5c2f2c00de4)

### To Reproduce

When using a new Action node and selecting Action: tts.google_translate_say the Target selection is not displayed.  

### Expected behavior

That the target (entity_id) is selectable from the Action node. I have checked in Home Assistant using Developer Tools - Action if an entity_id can be selected and thats the case.

![Schermafbeelding 2024-09-08 114130](https://github.com/user-attachments/assets/694441e0-2b4c-4c91-a6c1-559562e27730)

### Example Flow

```json
[
    {
        "id": "3ff12940090dg5e",
        "type": "api-call-service",
        "z": "6bb5b2e7.31e72c",
        "name": "Play message Huiskamer / Waskamer / Chris",
        "server": "3a91fcba.cfd1c4",
        "version": 6,
        "debugenabled": false,
        "action": "tts.google_translate_say",
        "floorId": [],
        "areaId": [],
        "deviceId": [],
        "entityId": [
            "media_player.zolder_speaker",
            "media_player.huiskamer",
            "media_player.waskamer_speaker"
        ],
        "labelId": [],
        "data": "{\"message\":\"Er is aangebeld\",\"language\":\"nl\",\"cache\":\"true\"}",
        "dataType": "json",
        "mergeContext": "",
        "mustacheAltTags": false,
        "outputProperties": [],
        "queue": "none",
        "domain": "tts",
        "service": "google_translate_say",
        "x": 720,
        "y": 410,
        "wires": [
            [
                "9d754a6c0a8f8eb4"
            ]
        ]
    },
    {
        "id": "3a91fcba.cfd1c4",
        "type": "server",
        "name": "Home Assistant",
        "version": 5,
        "addon": false,
        "rejectUnauthorizedCerts": true,
        "ha_boolean": "y|yes|true|on|home|open",
        "connectionDelay": true,
        "cacheJson": true,
        "heartbeat": false,
        "heartbeatInterval": "30",
        "areaSelector": "friendlyName",
        "deviceSelector": "friendlyName",
        "entitySelector": "friendlyName",
        "statusSeparator": "at: ",
        "statusYear": "hidden",
        "statusMonth": "short",
        "statusDay": "numeric",
        "statusHourCycle": "h23",
        "statusTimeFormat": "h:m",
        "enableGlobalContextStore": true
    }
]
```

### Environment Information

node-red-contrib-home-assistant-websocket 0.68.9
node-red 4.02 and running in LXC
Core 2024.9.1 running in VM

**Comment by zachowj** [comment]
If you're using the [legacy](https://www.home-assistant.io/integrations/google_translate/#action-say-legacy) method, the `entity_id` should be placed under the `data` property, not as a target. You can verify this in the Home Assistant developer tools by switching the action from UI mode to YAML mode.

At the moment, the fields within the `data` property must be manually entered, as there is no auto-completion or dedicated UI elements for each field.

**Comment by defisit** [comment]
Understood, thanks!
