### ISSUE TITLE
Passing of true or false via data field to HA is inconsistent?

### ISSUE THREAD

**Issue by Swiftnesses** [zachowj/node-red-contrib-home-assistant-websocket#155]
Passing a boolean to a service via a simple:

Service Node
`{"value":true}`

Shows in HA state with a capital 'T'.

Passing a boolean to a service via:

Function:
`msg.test = true;`

into

Service Node:
`{"value":"{{{ test }}}"}`

Shows in HA status with a lowercase 't' (correct).

Is there a reason for this, I'd expect them both to show in the HA status as 'true' (lowercase)?

**Comment by zachowj** [comment]
If understand you correctly they are both showing correctly.

In the first example, it's passing as boolean and python booleans are Capitalized.

For the second one, you have quotes around the mustache templates so it's passing it to HA as a string which would be the full lowercase word `true`.
