### ISSUE TITLE
Toolbar header showing 1 HA node with issues even after removing said node

### ISSUE THREAD

**Issue by dannycohn** [zachowj/node-red-contrib-home-assistant-websocket#1570]
### Describe the bug

After upgrading to 0.72.0, I noticed the new toolbar header next to the Node Red hamburger menu in the top right corner that highlights HA nodes with issues. I started out with 10.  I worked thru them all. When I disabled the last problematic node, the count did not drop to 0 or disappear.  I tried deleting the node alltogether, but the header still says 1 node with issues. When I click on it, it does not open the sidebar with the list of problematic nodes anymore.

### Screenshots

<img width="352" alt="image" src="https://github.com/user-attachments/assets/593833dc-bf40-4330-b0cd-cb6c67fa28c6">

### Environment Information

Version: 0.72.0

Home Assistant version: 2024.9.1
Companion version: 4.1.0

Node-RED version: 4.0.2
Docker: yes
Add-on: no

Node.js version: v18.20.3 x64 linux
OS: Linux 6.6.46-haos x64

**Comment by zachowj** [comment]
Do you have any errors in the browser console? Does it show any issues under the sidebar tab from Home Assistant?
