### ISSUE TITLE
Time node errors out with incorrect claim.

### ISSUE THREAD

**Issue by nappyjim** [zachowj/node-red-contrib-home-assistant-websocket#1575]
### Describe the bug

I will be attaching video to the bottom.  Below is the steps that are occurring in the video:

1. On first line you will see me simulate a button press which adds 15 seconds to a HomeAssistant datetime helper called test1.

2. On second line, the time node tied to **input_datetime.test1**  is waiting to expire. When it does, it adds 30 seconds to **input_datetime.test2**
 
3. On third line, the time node tide to input_datetime.test2 is waiting to expire, which will happen in 30 seconds.

**So far so good. But then here is where things go bad.**

4. After test2 expires, it adds 30 seconds to the time and tries to set test2 again. That is when you see the error and in the debug log it says "Date in past. Will never be fired". But that is NOT true. You can see the node triggered at 19:26, but on the right side of the screen in the other browser you can see the test2 time node is set for 19:27. Last time I checked, 19:27 is in the future in reference to 19:26.

Everything is updated. I have tried a restart. I have tried deleting everything and restarting from scratch, it doesnt matter.   For purposes of taking video, I reduced the time to seconds, but even when I had it set to days, the issue occured.

### Expected behavior

In step 4 above, I should not have an error as the datetime helper is set to the future, not the past.

### Screenshots

https://www.youtube.com/watch?v=iCnvJFhC1X0

### Example Flow

```json
[{"id":"62f33b91447bf1c4","type":"tab","label":"Flow 1","disabled":false,"info":"","env":[]},{"id":"c8a58b2f06ace016","type":"ha-time","z":"62f33b91447bf1c4","name":"input_datetime.test1","server":"ab3e2c53.e3491","version":3,"exposeAsEntityConfig":"","entityId":"input_datetime.test1","property":"state","offset":"0","offsetType":"num","offsetUnits":"minutes","randomOffset":false,"repeatDaily":false,"outputProperties":[{"property":"payload","propertyType":"msg","value":"","valueType":"date"}],"sunday":true,"monday":true,"tuesday":true,"wednesday":true,"thursday":true,"friday":true,"saturday":true,"x":1335,"y":525,"wires":[["b5e28bb9a324bcd2"]]},{"id":"b5e28bb9a324bcd2","type":"moment","z":"62f33b91447bf1c4","name":"Add 30 seconds","topic":"","input":"payload","inputType":"msg","inTz":"ETC/UTC","adjAmount":"10","adjType":"seconds","adjDir":"add","format":"YYYY-MM-DD HH:mm:ss","locale":"En","output":"payload","outputType":"msg","outTz":"America/Chicago","x":1585,"y":525,"wires":[["7739dfb4c9d275eb"]]},{"id":"7739dfb4c9d275eb","type":"api-call-service","z":"62f33b91447bf1c4","name":"Set test2","server":"ab3e2c53.e3491","version":7,"debugenabled":false,"action":"input_datetime.set_datetime","floorId":[],"areaId":[],"deviceId":[],"entityId":["input_datetime.test2"],"labelId":[],"data":"{\"datetime\": payload }","dataType":"jsonata","mergeContext":"","mustacheAltTags":false,"outputProperties":[],"queue":"none","blockInputOverrides":false,"domain":"input_datetime","service":"set_datetime","x":1770,"y":525,"wires":[[]]},{"id":"26852d81db7cbbdd","type":"ha-time","z":"62f33b91447bf1c4","name":"input_datetime.test2","server":"ab3e2c53.e3491","version":3,"exposeAsEntityConfig":"","entityId":"input_datetime.test2","property":"state","offset":"0","offsetType":"num","offsetUnits":"minutes","randomOffset":false,"repeatDaily":false,"outputProperties":[{"property":"payload","propertyType":"msg","value":"","valueType":"date"},{"property":"data","propertyType":"msg","value":"","valueType":"entity"},{"property":"topic","propertyType":"msg","value":"","valueType":"triggerId"}],"sunday":true,"monday":true,"tuesday":true,"wednesday":true,"thursday":true,"friday":true,"saturday":true,"x":1335,"y":615,"wires":[["b5e28bb9a324bcd2"]]},{"id":"94a1f3a130a6b952","type":"inject","z":"62f33b91447bf1c4","name":"Simulate button press","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"iso","payloadType":"date","x":1355,"y":435,"wires":[["2fb52b2829bb7654"]]},{"id":"2fb52b2829bb7654","type":"moment","z":"62f33b91447bf1c4","name":"add 15 seconds","topic":"","input":"payload","inputType":"msg","inTz":"ETC/UTC","adjAmount":"15","adjType":"seconds","adjDir":"add","format":"YYYY-MM-DD HH:mm:ss","locale":"En","output":"payload","outputType":"msg","outTz":"America/Chicago","x":1580,"y":435,"wires":[["9fc707bb7aa24b3d"]]},{"id":"9fc707bb7aa24b3d","type":"api-call-service","z":"62f33b91447bf1c4","name":"Set test1","server":"ab3e2c53.e3491","version":7,"debugenabled":false,"action":"input_datetime.set_datetime","floorId":[],"areaId":[],"deviceId":[],"entityId":["input_datetime.test1"],"labelId":[],"data":"{\"datetime\": payload }","dataType":"jsonata","mergeContext":"","mustacheAltTags":false,"outputProperties":[],"queue":"none","blockInputOverrides":false,"domain":"input_datetime","service":"set_datetime","x":1765,"y":435,"wires":[[]]},{"id":"ab3e2c53.e3491","type":"server","name":"AvilaSmartHome","version":5,"addon":true,"rejectUnauthorizedCerts":true,"ha_boolean":"y|yes|true|on|home|open","connectionDelay":true,"cacheJson":true,"heartbeat":false,"heartbeatInterval":30,"areaSelector":"friendlyName","deviceSelector":"friendlyName","entitySelector":"friendlyName","statusSeparator":"at: ","statusYear":"hidden","statusMonth":"short","statusDay":"numeric","statusHourCycle":"h23","statusTimeFormat":"h:m","enableGlobalContextStore":true}]
```

### Environment Information

Version: 0.72.2

Home Assistant version: 2024.9.1
Companion version: 4.1.0

Node-RED version: 4.0.2
Docker: yes
Add-on: no

Node.js version: v18.20.3 x64 linux
OS: Linux 6.6.46-haos x64

**Comment by WhiteSockedDancer** [comment]
It seems that i have a similar problem after updating my nodes and HA some days ago..
Everything worked fine until i updated to the newest version.

My time node also claims that a datetime that i set into the future is in the past with the debug Error: "Error: WARNING: Date in past. Will never be fired."
This almost everytime happens. But not 100% always. I didn't get when it happens exactly.. 

Example:
Input Node to set a property of a HA entity with jsonata. For example 20s: $fromMillis($millis() + 20*1000)

I get two different messages from two different time nodes which trigger from different set properties of my entity:
"Date is in the past: 2024-09-17T21:54:34.267Z"
and
"Error: WARNING: Date in past. Will never be fired."

**Comment by zachowj** [comment]
It appears there's an upstream issue with the cron package we're using. I'll need to investigate this further. The issue was originally reported in December 2023.
