### ISSUE TITLE
"TypeError: Cannot read property 'addListener' of undefined"

### ISSUE THREAD

**Issue by thorleifjaocbsen** [zachowj/node-red-contrib-home-assistant-websocket#158]
Getting a bunch of these on my installation:

"TypeError: Cannot read property 'addListener' of undefined"

It says "No connection" not sure what this can be?

[{"id":"da7b55ae.f0d438","type":"api-call-service","z":"7c7b6b11.f709b4","name":"Turn On Hallway Light","server":"a9e29932.d988b8","version":1,"service_domain":"switch","service":"turn_on","entityId":"switch.hallway_light","data":"","dataType":"json","mergecontext":"","output_location":"payload","output_location_type":"msg","mustacheAltTags":false,"x":1980,"y":80,"wires":[[]]},{"id":"a9e29932.d988b8","type":"server","z":"","name":"Home Assistant","legacy":false,"hassio":false,"rejectUnauthorizedCerts":true,"ha_boolean":"y|yes|true|on|home|open","connectionDelay":true}]

**Comment by zachowj** [comment]
When NR tried to set up one of the event nodes there was no connection to HA that caused the error to be thrown. This should be handled better.

**Comment by thorleifjaocbsen** [comment]
Does this have one connection for every node? It seems like they are reaching a limit on my house automation. Not working properly all the time. It worked with the old version (not websocket).

**Comment by zachowj** [comment]
There's only one WebSocket connection to HA no matter how many nodes you have placed on the workspace.
