### ISSUE TITLE
migration issue

### ISSUE THREAD

**Issue by Jmilesy** [zachowj/node-red-contrib-home-assistant-websocket#159]
I have tried the migration from @Ayapejian by removing all flows, removing the old node-red-contrib-home- assistant, then installing node-red-contrib-home-assistant-websocket
 I then get the following in the logs and then node red web page refuses to load, have i messed something up?

`2 Oct 16:16:34 - [info] Node-RED version: v1.0.0

2 Oct 16:16:34 - [info] Node.js  version: v10.16.3

2 Oct 16:16:34 - [info] Linux 4.18.0-25-generic x64 LE

2 Oct 16:16:36 - [info] Loading palette nodes

2 Oct 16:17:42 - [info] Dashboard version 2.15.4 started at /ui

2 Oct 16:17:48 - [warn] ------------------------------------------------------

2 Oct 16:17:48 - [warn] [node-red-contrib-home-assistant-websocket/server] Type already registered

2 Oct 16:17:48 - [warn] [node-red-contrib-home-assistant-websocket/server-events] Type already registered

2 Oct 16:17:48 - [warn] [node-red-contrib-home-assistant-websocket/server-state-changed] Type already registered

2 Oct 16:17:48 - [warn] [node-red-contrib-home-assistant-websocket/trigger-state] Type already registered

2 Oct 16:17:48 - [warn] [node-red-contrib-home-assistant-websocket/poll-state] Type already registered

2 Oct 16:17:48 - [warn] [node-red-contrib-home-assistant-websocket/api-call-service] Type already registered

2 Oct 16:17:48 - [warn] [node-red-contrib-home-assistant-websocket/api-current-state] Type already registered

2 Oct 16:17:48 - [warn] [node-red-contrib-home-assistant-websocket/api-get-history] Type already registered

2 Oct 16:17:48 - [warn] [node-red-contrib-home-assistant-websocket/api-render-template] Type already registered

2 Oct 16:17:48 - [warn] ------------------------------------------------------

2 Oct 16:17:48 - [info] Settings file  : /data/settings.js

2 Oct 16:17:48 - [info] Context store  : 'default' [module=memory]

2 Oct 16:17:48 - [info] User directory : /data

2 Oct 16:17:48 - [warn] Projects disabled : editorTheme.projects.enabled=false

2 Oct 16:17:48 - [info] Flows file     : /data/flows.json
`

**Comment by zachowj** [comment]
Looks like you didn't successfully remove node-red-contrib-home-assistant before adding this package.

Here's a post that explains several options to remove it: https://community.home-assistant.io/t/node-red-contrib-home-assistant-websocket/71032/7?u=kermit

**Comment by Jmilesy** [comment]
thats what i had assumed. 

i had used the "If that’s not an option you could export all the flows that use the Home Assistant nodes save them in a text file so you accidentally don’t lose them. Then delete the flows you exported which should then allow you to uninstall node-red-contrib-home-assistant via the palette and then install node-red-contrib-home-assistant-websocket. After that, you should be able to import the flows that you exported earlier. Using this method you’ll probably have to re-enter your Home Assistant credentials." method, and thats the errors i was receiving, i restarted node red at each step just in case.

I have managed to fix it byt recreating the docker container it was running in after delting the modules manually.

typically though, i cant find one palette!

thanks for getting back to me though.
