### ISSUE TITLE
Node red addon caught in start up loop

### ISSUE THREAD

**Issue by theSC** [zachowj/node-red-contrib-home-assistant-websocket#160]
**Describe the bug**
Addon won't fully start. Get's caught in a loop.  Seems to be this package causing the issues.

**To Reproduce**
This is a 100% new fresh install in ProxMox using HassOS. I just install the addon and try to start it.

**Expected behavior**
Addon starts

**Environment (please complete the following information):**

- Node Red Version: 
- Node.js Version: 
- NR Home Assistant Plugin Version: 4.2.1
- Is Node Red running in Docker: hassio

**Other (please complete the following information):**

- Have you searched previous issues for duplicates?:
Yes
**Additional context**
Here is the section of the log that loops:

[08:47:12] INFO: Starting Node-RED...
> hassio-addon-node-red@ start /opt
> node $NODE_OPTIONS node_modules/node-red/red.js "--settings" "/etc/node-red/config.js"
5 Oct 08:47:32 - [info] 
Welcome to Node-RED
===================
5 Oct 08:47:32 - [info] Node-RED version: v0.20.8
5 Oct 08:47:32 - [info] Node.js  version: v10.16.3
5 Oct 08:47:32 - [info] Linux 4.19.72 x64 LE
5 Oct 08:47:38 - [info] Loading palette nodes
5 Oct 08:47:58 - [warn] rpi-gpio : Raspberry Pi specific node set inactive
5 Oct 08:48:01 - [info] Dashboard version 2.16.3 started at /endpoint/ui
5 Oct 08:48:05 - [info] Settings file  : /etc/node-red/config.js
5 Oct 08:48:05 - [info] Context store  : 'default' [module=memory]
5 Oct 08:48:05 - [info] User directory : /config/node-red/
5 Oct 08:48:05 - [warn] Projects disabled : editorTheme.projects.enabled=false
5 Oct 08:48:05 - [info] Flows file     : /config/node-red/flows.json
5 Oct 08:48:06 - [info] Starting flows
5 Oct 08:48:06 - [info] Started flows
5 Oct 08:48:06 - [info] Server now running at http://127.0.0.1:46836/
5 Oct 08:48:11 - [red] Uncaught Exception:
5 Oct 08:48:11 - TypeError [ERR_INVALID_OPT_VALUE]: The value "4294967295" is invalid for option "family"
    at lookup (dns.js:112:11)
    at net.js:1003:5
    at defaultTriggerAsyncIdScope (internal/async_hooks.js:294:19)
    at lookupAndConnect (net.js:1002:3)
    at Socket.connect (net.js:937:5)
    at Object.connect (net.js:156:17)
    at Object.netConnect [as createConnection] (/opt/node_modules/node-red-contrib-home-assistant-websocket/node_modules/ws/lib/websocket.js:659:14)
    at new ClientRequest (_http_client.js:255:33)
    at request (http.js:42:10)
    at get (http.js:46:13)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! hassio-addon-node-red@ start: `node $NODE_OPTIONS node_modules/node-red/red.js "--settings" "/etc/node-red/config.js"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the hassio-addon-node-red@ start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-10-05T15_48_11_741Z-debug.log
[08:48:12] INFO: Starting Node-RED...

**Comment by theSC** [comment]
Can some one at least try to point me in the right direction? I'm at a loss here

**Comment by zachowj** [comment]
It looks like a DNS issue when it attempts to connect to HA. You're using hass.io so it's attempting to resolve `hassio` as a domain and bailing.

**Comment by theSC** [comment]
Agreed. Not sure what could be actually causing the issue though. Everything else seems to work fine.  For example I can ping out to google.ca ok and Hassio seems to be able to look up weather

**Comment by zachowj** [comment]
I am not a hass.io user but I believe you can log into the node-red container and see it resolve `hassio` as the IP of the HA container.
