### ISSUE TITLE
tts.google_translate_say action missing target options 

### ISSUE THREAD

**Issue by ge33ek** [zachowj/node-red-contrib-home-assistant-websocket#1604]
### Describe the bug

In the most recent update the action (previously call service) no longer has a target option resulting in this node failing.

In previous versions this “call service” action enabled you to specify the target device/entity.

Testing the action via HA developer tools works as intended by specifying a message, a entity and sending the command - but the current action in NR no longer works and appears solely because no target can be specified in the command.

Any ideas if there is a workaround until this is rectified?

### To Reproduce

1) add an action node
2) select the action “tts.google_translate_say”
3) note there is no ability to specify a target 
4) data does let you specify a message as previously 

### Expected behavior

When adding the action node for TTS google translate action having the ability to specify a target as with other action types.

### Environment Information

Version: 0.73.0

Home Assistant version: 2024.9.3
Companion version: 4.1.1

Node-RED version: 4.0.2
Docker: yes
Add-on: 18.0.5

Node.js version: v18.20.3 x64 linux
OS: Linux 6.6.46-haos x64

**Comment by zachowj** [comment]
duplicate #1534
