### ISSUE TITLE
Creating a Comma-Delimited Entity ID List

### ISSUE THREAD

**Issue by mwarchulinski** [zachowj/node-red-contrib-home-assistant-websocket#1606]
### Describe the bug

The page [Creating a Comma-Delimited Entity ID List](https://zachowj.github.io/node-red-contrib-home-assistant-websocket/guide/action.html#creating-a-comma-delimited-entity-id-list) describes how to pass multiple entity ids to a action call but target field is always empty in debug and no action is performed.

### To Reproduce

1. create a payload containing an array of entity_ids
2. create a "Action" node and fill data as described in the page (with $join(payload.entities) )
3. trigger the action

### Expected behavior

Target field should contain the list of entity_id

### Screenshots

![Screenshot From 2024-09-30 17-08-05](https://github.com/user-attachments/assets/07ee03c9-4ec9-4b8d-af06-573a74954826)
![Screenshot From 2024-09-30 17-09-02](https://github.com/user-attachments/assets/b399a51d-47d6-4ee8-b9b2-2001fc04f516)

### Environment Information

Version: 0.73.0

Home Assistant version: 2024.9.3
Companion version: 0.0.0

Node-RED version: 4.0.2
Docker: yes
Add-on: 18.0.5

Node.js version: v18.20.3 arm64 linux
OS: Linux 6.6.31-haos-raspi arm64

**Comment by zachowj** [comment]
I'll look to see if this broke on the Home Assistant side. The example should be updated to clarify that this approach works if you don't want to use an additional node to format the entity IDs. While the current example is fine, a better approach would be to pass the array directly into the action node via `msg.payload.entity_id`, eliminating the need for extra code in the data field, as it will automatically be imported into the config.

**Comment by zachowj** [comment]
In my testing with Home Assistant version 2024.10.0, a comma-delimited list of entity IDs in `data.entity_id` is still successfully performing the action.

**Comment by mwarchulinski** [comment]
Works fine, probably an error somewhere in my flow.

**Comment by mwarchulinski** [comment]
Works fine, probably an error somewhere in my flow.
