### ISSUE TITLE
Call-Service attempted without connection to server

### ISSUE THREAD

**Issue by AK5nowman** [zachowj/node-red-contrib-home-assistant-websocket#161]
**Describe the bug**
Node-Red doesn't appear to even attempt to connect to my home assistant instance.

**Screenshots**
Log output from node-red:
![image](https://user-images.githubusercontent.com/37681141/66438144-516fcd00-e9d8-11e9-8d18-5952133f003f.png)

Server config:
![image](https://user-images.githubusercontent.com/37681141/66438208-83812f00-e9d8-11e9-90c0-510b4fdd2c02.png)

**Example Flow**
I have a simple inject to a call-service node configured to toggle a light

**Environment (please complete the following information):**

- Node Red Version: 0.20.8
- Node.js Version: 8.16.1
- NR Home Assistant Plugin Version: 0.15.0
- Is Node Red running in Docker: yes
- Home Assistant (in docker) 0.97.1

**Other (please complete the following information):**

- Have you searched previous issues for duplicates?:
Yes, though I'm a github novice so might now have done it properly. 
**Additional context**
I've tested the home assistant API with an external REST client to verify that it is operational. There is no indication that node-red is event attempting to reach out to connect to HASS.

**Comment by zachowj** [comment]
Your log shows from 14:17:59 to 14:19:23 it attempting to connect to HA and the connection being closed probably due to incorrect password or token.

You can add `DEBUG=home-assistant*` at the beginning of your startup script or ENV to see more of the authentication process logs.

**Comment by jerobins** [comment]
This [thread](https://www.reddit.com/r/nodered/comments/de2tp7/node_red_problem_i_think/) is also about call-service API flakiness. I've added the DEBUG line so I can get more info.

**Comment by AK5nowman** [comment]
> Your log shows from 14:17:59 to 14:19:23 it attempting to connect to HA and the connection being closed probably due to incorrect password or token.
> 
> You can add `DEBUG=home-assistant*` at the beginning of your startup script or ENV to see more of the authentication process logs.

I tested the access token with a rest api client so I'm confident the token is correct. Looking at home assistant logs I don't see anything about any incoming requests from my node red server, where as I do see logs when I use the REST client w/ and w/o a valid token. (Token copied from node-red)

I don't understand where I would add the DEBUG-home-assistant* line. I assume node-red? Will this provide more logs then having the log level set to trace in the settings.js file?

**Comment by zachowj** [comment]
@AK5nowman Give this a try: https://github.com/zachowj/node-red-contrib-home-assistant-websocket/issues/135#issuecomment-512040976

@jerobins the Reddit post and this issue are completely different problems

**Comment by jerobins** [comment]
Okay, thank you. Will open another ticket.

**Comment by AK5nowman** [comment]
> @AK5nowman Give this a try: [#135 (comment)](https://github.com/zachowj/node-red-contrib-home-assistant-websocket/issues/135#issuecomment-512040976)
> 
> @jerobins the Reddit post and this issue are completely different problems

I appreciate the responsiveness. So, I've deployed the flow and it shows up as disconnected. From reading the other thread it sounds like this is general docker networking troubles, correct? Thank you

**Comment by AK5nowman** [comment]
Thanks for the clues! I originally had home assistants network set to host but for some reason that was causing issues. I've changed it to bridged and assigned an IP and now I'm able to connect with the command you linked, have other issues but I feel like I can pin those down on my own....wish I would have tried a simple ping node a few days ago.

Thanks again!
