### ISSUE TITLE
Call service node failing with "Call-service API error."

### ISSUE THREAD

**Issue by jerobins** [zachowj/node-red-contrib-home-assistant-websocket#162]
**Describe the bug**
Call service node appears to randomly fail. The flow can be tested and works. If the flow is triggered either by a timer or manually after some time quantum of at least 22 mins, it will fail with the error "Call-service API error." I tested it at 15 mins. and it still worked.

Home assistant logs have no information or errors.

**To Reproduce**

1. trigger call service node; with success.
2. wait at least 22 mins.
3. trigger call service node.

**Expected behavior**
Call service node should work consistently.

**Screenshots**
Log:
````
9 Oct 00:48:40 - [info] Starting flows,
2019-10-09T00:48:40.274Z home-assistant Instantiating HomeAssistant,
2019-10-09T00:48:40.275Z home-assistant:ws [Auth Phase] Initializing ws://192.168.1.168:8123/api/websocket,
9 Oct 00:48:40 - [info] Started flows,
2019-10-09T00:48:40.279Z home-assistant:ws [Auth Phase] New connection ws://192.168.1.168:8123/api/websocket,
2019-10-09T00:48:40.286Z home-assistant:ws [Auth Phase] Received { type: 'auth_required', ha_version: '0.99.3' },
2019-10-09T00:48:40.287Z home-assistant:ws [Auth Phase] Received { type: 'auth_ok', ha_version: '0.99.3' },
9 Oct 00:48:40 - [info] [server:Home Assistant] WebSocket Connected to http://192.168.1.168:8123,
2019-10-09T01:12:28.671Z home-assistant:ws events connection closed, cleaning up connection,
9 Oct 01:12:28 - [info] [server:Home Assistant] WebSocket Closed http://192.168.1.168:8123,
9 Oct 01:12:28 - [error] [api-call-service:Send Tstamp] Call-service API error.,
9 Oct 01:12:28 - [error] [api-call-service:Send Tstamp] Call-service API error.,
2019-10-09T01:12:28.676Z home-assistant:ws [Auth Phase] Initializing ws://192.168.1.168:8123/api/websocket,
2019-10-09T01:12:28.677Z home-assistant:ws [Auth Phase] New connection ws://192.168.1.168:8123/api/websocket,
2019-10-09T01:12:28.686Z home-assistant:ws [Auth Phase] Received { type: 'auth_required', ha_version: '0.99.3' },
2019-10-09T01:12:28.687Z home-assistant:ws [Auth Phase] Received { type: 'auth_ok', ha_version: '0.99.3' },
9 Oct 01:12:28 - [info] [server:Home Assistant] WebSocket Connected to http://192.168.1.168:8123,
````

After it reconnected at 00:48, I triggered a call-service. That worked.
At 00:59, I triggered a call-service. That worked.
At 01:10, I triggered a call-service, which was successful, but still showed "Sending" on the node status.
At 01:12, I triggered a call-service which resulted in the closed connection and the error messages.

**Example Flow**

````
[{"id":"9d24240f.95db2","type":"tab","label":"Test Bed","disabled":false,"info":""},{"id":"337b4e93.0b4b1a","type":"api-call-service","z":"9d24240f.95db2","name":"Send Tstamp","server":"dd51b125.ad54a","version":1,"service_domain":"notify","service":"telegram_jerobins","entityId":"","data":"{\"title\":\"Title\",\"message\":\"{{payload}}\"}","dataType":"json","mergecontext":"","output_location":"","output_location_type":"none","mustacheAltTags":false,"x":520,"y":90,"wires":[[]]},{"id":"d6b7b108.9959","type":"inject","z":"9d24240f.95db2","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":255,"y":90,"wires":[["337b4e93.0b4b1a"]]},{"id":"dd51b125.ad54a","type":"server","z":"","name":"Home Assistant","legacy":false,"hassio":false,"rejectUnauthorizedCerts":false,"ha_boolean":"y|yes|true|on|home|open","connectionDelay":false}]
````

**Environment (please complete the following information):**

- Node Red Version: 1.0.1
- Node.js Version: 10.16.3
- NR Home Assistant Plugin Version: 0.15.0
- Is Node Red running in Docker: yes

**Other (please complete the following information):**

- Have you searched previous issues for duplicates?: Yes

**Additional context**
- Hass.io: 0.99.3

Reddit [thread](https://www.reddit.com/r/nodered/comments/de2tp7/node_red_problem_i_think/).
I also had this problem with Node-RED 0.20 and went to 1.0 in hopes of resolving it.

**Comment by zachowj** [comment]
From what you have described and what I can gather from the logs, it looks like the WebSocket connection is timing out but NR is realizing this until the call-service node it triggered then it realizes it doesn't have a connection anymore and then reconnects.

After 22 mins are you still receiving events from HA or do they just die off? I am not the biggest docker user, could docker be closing the connection because of inactivity?

What do the logs in HA show for the websocket_api? Is it losing connection after 22 mins before you trigger the call-service node?

**Comment by Jmilesy** [comment]
for me, it doesnt even last 22 minutes:  

```
9 Oct 08:22:15 - [info] [server:Home Assistant] WebSocket Connected to http://192.168.1.109:8123
9 Oct 08:24:35 - [info] [server:Home Assistant] WebSocket Closed http://192.168.1.109:8123
9 Oct 08:24:35 - [error] [api-call-service:new boys bedtime off] Call-service API error
```

**Comment by jerobins** [comment]
@zachowj Is the same websocket connection used by get entities? That works all day long, without fail.

**Comment by jerobins** [comment]
Moved docker container from bridged to host and that appears to have resolved the connectivity issue; just so weird that it only affected some connection types and not others.

**Comment by Nobeernogman** [comment]
> Moved docker container from bridged to host and that appears to have resolved the connectivity issue; just so weird that it only affected some connection types and not others.

Moved from bridged to host? I dont understand this line. 
Since i updated my nodered docker container i have sometimes also the API error..
[https://i.imgur.com/HPo2lXH.png](url)

I just updated my nodered to 1.0.2, and i'm updating my docker home assistant right now.

**Comment by jerobins** [comment]
Docker containers, by default, are set-up with their own IP and communicate through a networking bridge that the docker controller sets up. You can change that to host networking; where the container shares the same IP as the host and uses the host networking stack for communication.

I found that the bridged mode was causing websocket disconnects.

**Comment by Nobeernogman** [comment]
Jerobins, still nt having new problems? I have, my docker instalation shares the same ip as my host raspberry pi, that cannot be the problem I think?

**Comment by jerobins** [comment]
No, no problems since moving from bridged to host mode. Using the same IP is fine; they communicate over different ports on the same host.

**Comment by Nobeernogman** [comment]
> ent ports on th

Can you tell me how to do this? This is my line, portmap 1820 is for the Join addon.

docker run -it --user="1000:1000" -p 1880:1880 -p 1820:1820 -v /home/pi/docker/nodered/data:/data --name mynodered -e TZ=Europe/Amsterdam --user=root nodered/node-red
