### ISSUE TITLE
Light sensor state is wrong if flow starts with Button action

### ISSUE THREAD

**Issue by zvirja** [zachowj/node-red-contrib-home-assistant-websocket#1624]
### Describe the bug

I experience a very weird bug. I have a flow when I push a button and examine light state. It always return me that light is ON if flow is triggered by me pushing a button. But if I use `inject` - everything is fine. The flow is trivial, but the issue is quite stable. I tried changing the trigger to different buttons and lights to different bulbs - it still happens.

### To Reproduce

You will not be able to reproduce it. But on my end I just press the button and examine Debug output. It's ON if I push the button and it's `OFF` if I start by inject.

### Expected behavior

It should return the real state

### Screenshots

![image](https://github.com/user-attachments/assets/2ecf7080-fdc5-4e21-b458-a5da3c7eecc5)

### Example Flow

```json
[
    {
        "id": "7d5a4fb9f0859c47",
        "type": "tab",
        "label": "Flow 1",
        "disabled": false,
        "info": "",
        "env": []
    },
    {
        "id": "63a7d7090e42b418",
        "type": "ha-device",
        "z": "7d5a4fb9f0859c47",
        "name": "",
        "server": "b09c67db78d4f4b1",
        "version": 1,
        "exposeAsEntityConfig": "",
        "inputs": 0,
        "deviceType": "trigger",
        "device": "85524690a56e4b2aa33eafc9f165fc27",
        "event": {
            "type": "turned_on",
            "platform": "device",
            "device_id": "85524690a56e4b2aa33eafc9f165fc27",
            "entity_id": "d642179ba347000a7e63d5b2f6e40bbf",
            "domain": "binary_sensor",
            "metadata": {
                "secondary": false
            }
        },
        "capabilities": [],
        "outputProperties": [
            {
                "property": "payload",
                "propertyType": "msg",
                "value": "",
                "valueType": "eventData"
            },
            {
                "property": "topic",
                "propertyType": "msg",
                "value": "",
                "valueType": "triggerId"
            }
        ],
        "x": 110,
        "y": 120,
        "wires": [
            [
                "e95c71125e8d4071"
            ]
        ]
    },
    {
        "id": "e95c71125e8d4071",
        "type": "api-current-state",
        "z": "7d5a4fb9f0859c47",
        "name": "",
        "server": "b09c67db78d4f4b1",
        "version": 3,
        "outputs": 1,
        "halt_if": "",
        "halt_if_type": "str",
        "halt_if_compare": "is",
        "entity_id": "light.work_table_bulb",
        "state_type": "str",
        "blockInputOverrides": false,
        "outputProperties": [
            {
                "property": "payload",
                "propertyType": "msg",
                "value": "",
                "valueType": "entityState"
            },
            {
                "property": "data",
                "propertyType": "msg",
                "value": "",
                "valueType": "entity"
            }
        ],
        "for": "0",
        "forType": "num",
        "forUnits": "minutes",
        "override_topic": false,
        "state_location": "payload",
        "override_payload": "msg",
        "entity_location": "data",
        "override_data": "msg",
        "x": 360,
        "y": 120,
        "wires": [
            [
                "981847fc9cb1f0bd"
            ]
        ]
    },
    {
        "id": "981847fc9cb1f0bd",
        "type": "debug",
        "z": "7d5a4fb9f0859c47",
        "name": "debug 4",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "false",
        "statusVal": "",
        "statusType": "auto",
        "x": 590,
        "y": 120,
        "wires": []
    },
    {
        "id": "16b238840b42f80e",
        "type": "inject",
        "z": "7d5a4fb9f0859c47",
        "name": "",
        "props": [
            {
                "p": "payload"
            },
            {
                "p": "topic",
                "vt": "str"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "",
        "payloadType": "date",
        "x": 100,
        "y": 200,
        "wires": [
            [
                "e95c71125e8d4071"
            ]
        ]
    }
]
```

### Environment Information

Version: 0.73.0

Home Assistant version: 2024.9.3
Companion version: 4.1.1

Node-RED version: 4.0.3
Docker: yes
Add-on: no

Node.js version: v20.17.0 arm64 linux
OS: Linux 6.6.31+rpt-rpi-v8 arm64

### Additional context

I would be happy to record any diagnostics for you if you show me how. I had thoughts about debugging the websocket, but I don't know how to turn that on.

**Comment by zvirja** [comment]
Or another example right after reboot:
![image](https://github.com/user-attachments/assets/9319af01-9673-4c4a-85ae-bf0487de2e0f)

It doesn't return a real state of the light - it returns just static `on`. So weird :)

**Comment by zvirja** [comment]
Okay! It works though if I add the Change node between trigger and state evaluation to set `msg.payload` to empty value. It looks like node is not happy with the input from the trigger :thinking:

**Comment by zachowj** [comment]
The current state node allows config overrides via the [input message](https://zachowj.github.io/node-red-contrib-home-assistant-websocket/node/current-state.html#inputs). If you attach a debug node to the device node, you'll see that `msg.payload` is populated with properties that override the current state node by default.

To resolve this, either disable the output to `msg.payload` in the device node or enable "Block input overrides" in the current state node. This effectively achieves the same result as using a change node, without needing the extra step.

**Comment by zvirja** [comment]
@zachowj Hey! thanks for a really fast response! Yes, you are completely right. The moment I checked the "Block input overrides" - it solved my issue completely 🎉 

I spent so much time debugging it locally and it was so frustrating. The flow I was doing was very trivial, so the behavior is quite unexpected. So I thought a bit about it - would it makes sense to check that box by default? I would imagine most people are not using it - so those who need it must know what they are doing.

Another option would be to set it for the newly created nodes. This way you could keep intact the old ones. But I am not sure whether you have such an API.

**Comment by zvirja** [comment]
@zachowj Just out of curiosity - you seem to not like my idea of changing the defaults. Could you share the reasons? I am a software engineer myself and I know by heart what trade-offs are. Am curious about your reasoning :wink:

**Comment by zachowj** [comment]
Changing the default is fine and could help prevent unexpected behavior for some users. In the Node-RED paradigm, most nodes do have input overrides, though it's less common for them to override a local config value. Feel free to submit a PR with this change, but I'll add it to my list as well.
