### ISSUE TITLE
Editing Action Node - Targets / Output properties configuration missing

### ISSUE THREAD

**Issue by Marus** [zachowj/node-red-contrib-home-assistant-websocket#1629]
### Describe the bug

Upon editing an action node after it has been configured initially the targets and output properties configuration sections are missing. Data field also becomes a plain text field instead of a JSONata/JSON editor enabled field

### To Reproduce

1. Create a new action type node
2. Double click it to open for initial configuration - select an action (optionally set a target or output properties)
3. Click on the `Done` button to close the node
4. Double click on the same node to edit a second time
5. The "Targets" and "Output properties" sections will be missing

### Expected behavior

Would expect to get the initial editing form back to modify the complete configuration.

### Screenshots

![initial-config](https://github.com/user-attachments/assets/c62b4ad1-9d8a-4a38-93fa-c1d32069e897)

![edit-interface](https://github.com/user-attachments/assets/a43aa31f-386e-4e48-aee4-2bc90c186c95)

### Environment Information

Version: 0.73.0

Home Assistant version: 2024.3.3
Companion version: 2.2.0

Node-RED version: 4.0.3
Docker: no
Add-on: no

Node.js version: v22.9.0 x64 linux
OS: Linux 6.5.13-1-pve x64

**Comment by zachowj** [comment]
Please check the console in your browser’s developer tools for any errors.

**Comment by Marus** [comment]
Only errors that show (and this is before interacting with the nodes at all) is that a particular source map failed to load (`purify.min.js.map`) - which shouldn't effect any actual functionality - just debugging.

**Comment by Marus** [comment]
Sorry - deleted that last comment - didn't notice my console was filtered to actual "Errors". Do get a message:

oneditprepare"976fb9db28e85370""api-call-service""TypeError: undefined is not an object (evaluating 'e')"

m — Script Element 1:1:50326
Ht — Script Element 1:1:50475
Ft — Script Element 1:1:47866
oneditprepare — Script Element 1:1:58292
t — red.min.js:18:431978
x — red.min.js:18:433348
open — red.min.js:18:447932
n — red.min.js:19:45728
show — red.min.js:19:46969
edit — red.min.js:18:448752
mt — red.min.js:18:237433
i — vendor.js:28:7949

**Comment by zachowj** [comment]
Try hard-refreshing the page.

---

To hard reset a webpage and load it without using cached data, try the following:

- **Windows/Linux:** Press `Ctrl + F5` or `Ctrl + Shift + R`.
- **Mac:** Press `Cmd + Shift + R`.

This forces the browser to reload the page from the server instead of using cached content.

**Comment by Marus** [comment]
Sorry - was away so couldn't respond earlier - tried forcing refresh without cached data and other browsers - still get the same behaviour.

**Comment by Marus** [comment]
Closing this ticket - determined that this was because I hadn't properly updated the node-red component through HACS - now that I've updated the node-red editing is working properly.
