### ISSUE TITLE
Unable to upgrade from 14.2 to 15.0

### ISSUE THREAD

**Issue by fabnavigator** [zachowj/node-red-contrib-home-assistant-websocket#163]
Hi,

I'm getting the following error when I try to upgrade:

npm WARN deprecated @hapi/hoek@6.2.4: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
+ node-red-contrib-home-assistant-websocket@0.14.2
updated 1 package and audited 191 packages in 8.378s
found 0 vulnerabilities

**To Reproduce**
sudo npm install node-red-contrib-home-assistant-websocket

**Comment by zachowj** [comment]
There's really no error there it's just informing you of a deprecated package. The npm registry has the latest package version [0.15.0](https://www.npmjs.com/package/node-red-contrib-home-assistant-websocket).
