### ISSUE TITLE
TRIGGER MISSING

### ISSUE THREAD

**Issue by ryan1984w** [zachowj/node-red-contrib-home-assistant-websocket#1639]
### Describe the bug

hi using node red in HA, i am running the lastest node red on a new ha and when i use device trigger then select the trigger thats fine but when i go back to look at the node the trigger info is missing and cant edit it. this is strange since the other version of node red works fine 
thank you
ryan

### Screenshots

<img width="467" alt="Screenshot 2024-10-08 at 07 29 29" src="https://github.com/user-attachments/assets/dc181671-1396-4bce-aff4-289fbbdd97b3">

### Environment Information

,

**Comment by zachowj** [comment]
duplicate #1621
