### ISSUE TITLE
Unable to upgrade to 0.16.3

### ISSUE THREAD

**Issue by ironslow** [zachowj/node-red-contrib-home-assistant-websocket#164]
**Describe the bug**
I got the following error message when trying to upgrade to 0.16.3

29 Oct 07:52:29 - [info] Upgrading module: node-red-contrib-home-assistant-websocket to version: 0.16.3
29 Oct 07:52:49 - [warn] Installation of module node-red-contrib-home-assistant-websocket failed:
29 Oct 07:52:49 - [warn] ------------------------------------------
29 Oct 07:52:49 - [warn] npm WARN node-red-project@0.0.1 No repository field.
npm WARN node-red-project@0.0.1 No license field.
npm ERR! code EEXIST
npm ERR! path /home/pi/.node-red/node_modules/.bin/mustache
npm ERR! Refusing to delete /home/pi/.node-red/node_modules/.bin/mustache: is outside /home/pi/.node-red/node_modules/mustache and not a link
npm ERR! File exists: /home/pi/.node-red/node_modules/.bin/mustache
npm ERR! Move it away, and try again.
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2019-10-29T11_52_49_020Z-debug.log
29 Oct 07:52:49 - [warn] ------------------------------------------

**Environment (please complete the following information):**

- Node Red Version: 1.0.2
- Node.js Version: 0.17.0
- NR Home Assistant Plugin Version: 0.15.0
- Is Node Red running in Docker: no

**Comment by zachowj** [comment]
This isn't an error with this package but an npm error. You could try doing what the log tells you to do or just remove the whole node_modules directory and run `npm install`
