### ISSUE TITLE
Bug or doc error

### ISSUE THREAD

**Issue by tikismoke** [zachowj/node-red-contrib-home-assistant-websocket#1646]
### Describe the bug

I see in doc that in theory i could check if a sensor value start_with something:
https://zachowj.github.io/node-red-contrib-home-assistant-websocket/guide/conditionals.html#starts-with

But i don't see this option in the node itself

### To Reproduce

add a state node and select a sensor.somtehing

### Expected behavior

drop down list show start_with option

### Screenshots

![{FC7C1A11-7537-46B6-BC86-818AE5096934}](https://github.com/user-attachments/assets/bff76e62-8bc0-42c2-8eec-003b8008399e)

### Environment Information

Version: 0.74.0

Home Assistant version: 2024.10.0
Companion version: 0.0.0

Node-RED version: 4.0.3
Docker: no
Add-on: no

Node.js version: v20.18.0 x64 linux
OS: Linux 6.8.12-2-pve x64

**Comment by zachowj** [comment]
Not all conditional options are available for each node. The node you're showing looks like an events-state node, which doesn't have that option. However, the get-entities node does. If you want to use "starts with" in the events-state node, you can use a regex expression, which it does support:

```
^text_to_start_with
```

![image](https://github.com/user-attachments/assets/f9e5fa8a-3600-4eb8-87c9-92184db48625)

**Comment by tikismoke** [comment]
Ha ok thank's.
Sorry I'll close this.
