### ISSUE TITLE
After updating the trigger field seems disabled / greyed out

### ISSUE THREAD

**Issue by KevinHurts** [zachowj/node-red-contrib-home-assistant-websocket#1647]
### Describe the bug

When going from the alpha version to the beta version the trigger fields all are disabled but in the background they still seem to be working.

### To Reproduce

1. Create device node
2. Select device
3. Select trigger
4. Save node by pressing done
5. Edit node again

### Expected behavior

Trigger should be present but it is disabled / greyed out

### Screenshots

![Screenshot 2024-10-10 at 20 38 17](https://github.com/user-attachments/assets/5917739e-64f8-4c5e-80cc-eeaf19b5a3b5)
![Screenshot 2024-10-10 at 20 38 33](https://github.com/user-attachments/assets/eee14c1a-c304-4e05-ba81-729f1e578b23)

### Environment Information

Version: 0.73.0

Home Assistant version: 2024.10.1
Companion version: 4.1.1

Node-RED version: 4.0.3
Docker: yes
Add-on: 18.1.1

Node.js version: v18.20.4 arm64 linux
OS: Linux 6.6.31-haos-raspi arm64

**Comment by zachowj** [comment]
duplicate #1621
