### ISSUE TITLE
Node Red fails to connect to HA with error

### ISSUE THREAD

**Issue by ahartman** [zachowj/node-red-contrib-home-assistant-websocket#165]
All latest versions:
Node-Red 1.0.2
HA: 0.101.3
This plugin: 0.16.3

I defined a config with a valid HA token.
The only node that I see in Node-Red is the URL for a calendar integration in HA.

And an error message in the Node-red log about an 'UnhandledPromiseRejectionWarning'.

All help is appreciated.
Regards, ahartman, belgium

[NodeRedLog.txt](https://github.com/zachowj/node-red-contrib-home-assistant-websocket/files/3835814/NodeRedLog.txt)

**Comment by zachowj** [comment]
The handling of that error should be more graceful. I would assume that you don't have a valid connection to Home Assistant. Is the log showing connected to HA? If you drop in one of the event nodes, does it show connected?

**Comment by ahartman** [comment]
Dear Jason,
Thank you for the quick reaction, hope you can help.

A dropped in node says 'disconnected' but that is probably because I cannot enter an entity-ID; there is no drop down of entities
What also surprise me is the only thing visible as entity-ID dropdown is the URL from the calendar component that I am running in Home-Assistant.
Please see attached screen image and Node-RED log.

Regards, ahartman, belgium

[Node-RED-log.txt](https://github.com/zachowj/node-red-contrib-home-assistant-websocket/files/3841014/Node-RED-log.txt)
<img width="788" alt="Schermafbeelding 2019-11-13 om 13 05 26" src="https://user-images.githubusercontent.com/688316/68762931-7975d000-0617-11ea-87cd-ad75b2234244.png">

**Comment by zachowj** [comment]
If the event nodes are showing disconnected you either have an incorrect URL or long-lived access token in the server config. Once the event node is showing connected in the status text the current-state node autocomplete should start working.

**Comment by ahartman** [comment]
I did one thing which brought successful connection:
The URL to use is suggested in light print in the Server setup dialog as 'http://localhost:8123'; I was under the impression that this would be used as default if you did not enter something else. Apparently, this is not the case and you have to enter the URL in all cases. This light be with mentioning in the documentation.

Having done that, Node-RED is now connected and for instance the 'get history node' returns results. However, I can type in entity-IDs but I still do not get auto-complete of entity-IDs, even after some 15 minutes of connection time, nothing. Any ideas? 

Regards, ahartman, belgium

**Comment by ahartman** [comment]
The auto-complete suddenly started working!
No idea why.
