### ISSUE TITLE
Device node not working

### ISSUE THREAD

**Issue by ep1cman** [zachowj/node-red-contrib-home-assistant-websocket#1661]
### Describe the bug

Today I did a fresh home assistant install using HAOS. I installed the node-red add-on and have made sure I am running the latest version of the add-on and this plugin via the pallet manager.

When I create an automation directly in HA using a device trigger, it works as expected. If I try the same thing with node-red it doesnt work.

Does anyone have any suggestions on what might be the issue here? I notice there is a warning message about versions, but as far as I can tell I meet the requirement listed.

### To Reproduce

Add a device node
Configure it to be a trigger from a button

### Expected behavior

I expected to see output from the node

### Screenshots

<img width="1440" alt="image" src="https://github.com/user-attachments/assets/0f13ce43-d9d0-4573-8f16-aa82801ee91b">
<img width="385" alt="image" src="https://github.com/user-attachments/assets/5f9ace65-d792-4dda-804d-6a629dd97617">

### Example Flow

```json
[{"id":"868c733e4886ad62","type":"tab","label":"Flow 1","disabled":false,"info":"","env":[]},{"id":"e9c4416c9f8ca7d5","type":"debug","z":"868c733e4886ad62","name":"debug 1","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","statusVal":"","statusType":"auto","x":300,"y":200,"wires":[]},{"id":"db6f3195032e8158","type":"ha-device","z":"868c733e4886ad62","name":"","server":"f61bf0f66c40cfa9","version":1,"exposeAsEntityConfig":"","inputs":0,"deviceType":"trigger","device":"10e98be14011c7f27a3d29154eaa5fff","event":{"platform":"device","domain":"mqtt","device_id":"10e98be14011c7f27a3d29154eaa5fff","type":"action","subtype":"single","metadata":{}},"capabilities":[],"outputProperties":[{"property":"payload","propertyType":"msg","value":"","valueType":"eventData"},{"property":"topic","propertyType":"msg","value":"","valueType":"triggerId"}],"x":150,"y":200,"wires":[["e9c4416c9f8ca7d5"]]},{"id":"f61bf0f66c40cfa9","type":"server","name":"Home Assistant","version":5,"addon":true,"rejectUnauthorizedCerts":true,"ha_boolean":"y|yes|true|on|home|open","connectionDelay":false,"cacheJson":true,"heartbeat":false,"heartbeatInterval":"30","areaSelector":"friendlyName","deviceSelector":"friendlyName","entitySelector":"friendlyName","statusSeparator":": ","statusYear":"hidden","statusMonth":"short","statusDay":"numeric","statusHourCycle":"default","statusTimeFormat":"h:m","enableGlobalContextStore":false}]
```

### Environment Information

Version: 0.74.1

Home Assistant version: 2024.10.3
Companion version: 0.0.0

Node-RED version: 4.0.3
Docker: yes
Add-on: 18.1.1

Node.js version: v18.20.4 x64 linux
OS: Linux 6.6.54-haos x64

**Comment by ep1cman** [comment]
Ah! I needed to install the "node-red companion" from HACS!

**Comment by peetzweg** [comment]
@ep1cman Having the same issue. Installed the node-red add-on first. Now installed HACS and than added Node-RED Companion via HACS. Restarted a couple of times. Restarted node-red, made sure Node-RED Companion is "Downloaded" in HACS tab. Still does nothing on device trigger. 

Any ideas how to fix it?

<img width="1313" alt="Image" src="https://github.com/user-attachments/assets/2697f313-bf2e-4dc6-80ea-47df1096acd5" />

**Comment by peetzweg** [comment]
Nevermind, I forgot to add the actual HACS installed `Node-RED Companion` as a `Device & Services` integration. I glanced over this last step of the setup guide as I thought it just mentioned to install the `Node-Red Add-on` 🤦
