### ISSUE TITLE
Long-Lived Access Tokens stopped working

### ISSUE THREAD

**Issue by MichaelBitard** [zachowj/node-red-contrib-home-assistant-websocket#167]
**Describe the bug**
Impossible to connect to home assistant using long-lived access tokens

**To Reproduce**

1. Create a long-lived access token on your home assistant instance
2. Add this long-lived access token to your node-red home assistant component

**Expected behavior**
Should be able to connect

**Environment:**

- Node Red Version: 1.0.2
- Node.js Version: 10.16.3
- NR Home Assistant Plugin Version: 0.16.3
- Is Node Red running in Docker:yes

- Have you searched previous issues for duplicates?: yes

**Additional context**
In order to debug, how can I see the request sent by this to home assistant?
I can see on my nginx frontend that the request is triggered

```
192.168.0.1 - - [20/Nov/2019:14:15:30 +0000] "GET /api/history/period/2019-11-19T14:15:30.249Z?filter_entity_id=sensor.sacha_s_bedroom_temperature HTTP/1.1" 401 17 "-" "axios/0.19.0" "-"
```
But I can't see if the bearer is correctly set.

**Comment by zachowj** [comment]
What do the node-red logs show for a connection status? If it's connected the history node will be sending the correct bearer.

**Comment by MichaelBitard** [comment]
I receive an HTTP 401 Unauthorized.

With the same token if I do a curl request, it works fine.

```
curl -H 'Accept: application/json' -H "Authorization: Bearer ${TOKEN}" https://${URL}/api/states
```

**Comment by MichaelBitard** [comment]
Ok, I'm stupid, I forgot to redeploy :(

Sorry and thanks for your awesome contribution to nodered!
