### ISSUE TITLE
Home-assistant websocket wont connect with callback must be function error.

### ISSUE THREAD

**Issue by merc1031** [zachowj/node-red-contrib-home-assistant-websocket#168]
**Describe the bug**
Home-assistant websock wont connect with callback must be function error. this was working before, and all of a sudden doesnt seem to even try to connect. The Error in the logs seems to be fired by the Home Assistant Configuration.

```
24 Nov 21:38:46 - [debug] [server:Home Assistant Local] instantiated node, name: Home Assistant Local
24 Nov 21:38:46 - [error] [server:1e5b4a01.dd2f96] Error: Callback must be a function
24 Nov 21:38:46 - [debug] [position-config:Home] initialize latitude=37.36032 longitude=-121.98331 tzOffset=null tzDST=0
24 Nov 21:38:46 - [debug] [server:Home Assistant Local2] instantiated node, name: Home Assistant Local2
24 Nov 21:38:46 - [error] [server:d4f28c84.ef972] Error: Callback must be a function
```
 

```
home-assistant   /bin/entry.sh python3 -m h ...   Up
node-red         npm start -- --userDir /data     Up (healthy)   0.0.0.0:1880->1880/tcp, 0.0.0.0:9229->9229/tcp
```

**Screenshots**
<img width="329" alt="E1" src="https://user-images.githubusercontent.com/311356/69515456-8346df80-0f03-11ea-95a1-b740b2d28a96.PNG">
<img width="235" alt="E2" src="https://user-images.githubusercontent.com/311356/69515457-8346df80-0f03-11ea-8595-9b11a12566d0.PNG">
<img width="400" alt="E3" src="https://user-images.githubusercontent.com/311356/69515458-8346df80-0f03-11ea-81aa-79aa59e6edc9.PNG">
<img width="1658" alt="E4" src="https://user-images.githubusercontent.com/311356/69515459-83df7600-0f03-11ea-81e1-bd5d6e315af6.PNG">

**Example Flow**
If applicable, add an example of exported json of a flow exhibiting the issue to aid in reproduction.

**Environment (please complete the following information):**
Using nodered container    nodered/node-red:1.0.3-12   
                                                                              
- Node Red Version: 1.0.3
- Node.js Version: 12
- NR Home Assistant Plugin Version: 0.16.3
- Is Node Red running in Docker: [e.g. yes/no/hassio] docker-compose

**Comment by merc1031** [comment]
Interesting. I have boiled it down to the following.
With this configuration in my settings.js the websocket never attempts to connect and I get that Error callback message.
```
  contextStorage: {
      default: {
          module: "localfilesystem",
          config: {
              cache: false,
              dir: "/context"
          },
      },
  },
```

if i simply change it to the following. I can get everything to connect
```
  contextStorage: {
      default: {
          module: "memory",
      },
      persist: {
          module: "localfilesystem",
          config: {
              cache: false,
              dir: "/context"
          },
      },
  },
```

**Comment by zachowj** [comment]
At first glance, it seems to be a bug with Node-RED where localfilesystem requires a callback passed into the get function of a context call but memory does not.

If you want a quick fix you can modify the server config node.

https://github.com/zachowj/node-red-contrib-home-assistant-websocket/blob/a5a5e62e1e2caf7603cd4da473f76ece8159421c/nodes/config-server/config-server.js#L223

Replace with:
`let haCtx = this.context().global.get('homeassistant', () => {});`

https://github.com/zachowj/node-red-contrib-home-assistant-websocket/blob/a5a5e62e1e2caf7603cd4da473f76ece8159421c/nodes/config-server/config-server.js#L231

Replace with:
`let haCtx = this.context().global.get('homeassistant', () => {});`

**Comment by zachowj** [comment]
Currently, this package only supports synchronous context stores as the default.
