### ISSUE TITLE
Get entities label didn't work

### ISSUE THREAD

**Issue by kakou-fr** [zachowj/node-red-contrib-home-assistant-websocket#1686]
### Describe the bug

I just upgrated to the last version, and the Get entities, filter with label name, return all entities.
Before, it was just return the entities that == to the label name

### To Reproduce

1. Add get entities
2. Add label filter, and a label name, split output
3. Add debug node to display the entities

### Expected behavior

Only get the list of entities that match the label name

### Example Flow

```json
[{"id":"eeb76ebe4af2a4ef","type":"ha-get-entities","z":"f132e3ac120d2b3c","name":"Check","server":"c1b64b6e.ebdda8","version":1,"rules":[{"condition":"label_registry","property":"name","logic":"is","value":"Check","valueType":"str"}],"outputType":"split","outputEmptyResults":false,"outputLocationType":"msg","outputLocation":"payload","outputResultsCount":1,"x":370,"y":940,"wires":[["1a2214efe1b9fbfd"]]},{"id":"7c4786d2d36de8b7","type":"inject","z":"f132e3ac120d2b3c","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"600","crontab":"","once":true,"onceDelay":"10","topic":"","payload":"","payloadType":"date","x":190,"y":940,"wires":[["eeb76ebe4af2a4ef"]]},{"id":"1a2214efe1b9fbfd","type":"debug","z":"f132e3ac120d2b3c","name":"debug 173","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","statusVal":"","statusType":"auto","x":530,"y":940,"wires":[]},{"id":"c1b64b6e.ebdda8","type":"server","name":"Home Assistant","addon":true,"rejectUnauthorizedCerts":true,"ha_boolean":"","connectionDelay":true,"cacheJson":true,"heartbeat":false,"heartbeatInterval":"","statusSeparator":"","enableGlobalContextStore":false}]
```

### Environment Information

Version: 0.74.2

Home Assistant version: 2024.11.1
Companion version: 4.1.1

Node-RED version: 4.0.3
Docker: yes
Add-on: 18.1.1

Node.js version: v18.20.4 arm64 linux
OS: Linux 6.6.51+rpt-rpi-2712 arm64

**Comment by TheGeka** [comment]
Good to know i am not going crazy, i have the exact same issue. No matter what, the label filter on get entities always returns nothing
![image](https://github.com/user-attachments/assets/61b1a6a2-5ffb-4421-bfe5-0f7c910ffca6)

**Comment by wolfwander** [comment]
Same for me.

**Comment by Fertx0** [comment]
Isn't this problem considered a bug?

**Comment by dartzon** [comment]
I am having the exact same problem, the conditions to filter out entities based on their labels are not working at all.
