### ISSUE TITLE
Dynamic entity_id for Get History

### ISSUE THREAD

**Issue by rogersmj** [zachowj/node-red-contrib-home-assistant-websocket#169]
**Is your feature request related to a problem? Please describe.**
I'm trying to build a reusable subflow that involves the Get History node, but it looks like I can only hardcode an Entity ID in Get History. I would like to be able to feed it the Entity ID from a path I specify in the msg object.

**Describe the solution you'd like**
A selector that allow us to use a string OR the msg object when specifying the Entity ID on the Get History node (as most other nodes allow you to for inputs).

**Describe alternatives you've considered**
Writing my own function to get history from Home Assistant API, which I really don't know how to do.

**Additional context**
There might be some hidden way to do this that I'm not thinking of, but I haven't found it. No matter what I try to put in Entity ID -- {{msg.entity_id}}, ${msg.entity_id} -- it treats it as a literal string.

**Comment by zachowj** [comment]
<https://community.home-assistant.io/t/node-red-contrib-home-assistant-websocket/71032/384?u=kermit>

**Comment by rogersmj** [comment]
Thanks. Sorry I misunderstood the side panel documentation, I didn't realize that `entityid` was a reference to `msg.entityid`. Closing.
