### ISSUE TITLE
Mustache templates not working when provided in action

### ISSUE THREAD

**Issue by bkupidura** [zachowj/node-red-contrib-home-assistant-websocket#1697]
### Describe the bug

When trying to use mustache template in action, no action is triggered:
```
message: "InputError: Invalid action format: notify."
```

Used payload:
```
{"topic":"red/notify","qos":0,"retain":false,"_msgid":"27469928bfeb88cb","notify":{"destination":["bartosz"],"message":"example message","method":"ios","type":"normal","destinationApp":"mobile_app_iphone_bartosz"},"notify_payload":{"message":"example message","data":{}},"error":{"message":"InputError: Invalid action format: notify.","source":{"id":"854f481d.469568","type":"api-call-service","name":"IOS notify","count":1},"stack":"InputError: Invalid action format: notify.\n    at ActionController.onInput (/data/node_modules/node-red-contrib-home-assistant-websocket/dist/nodes/action/ActionController.js:58:19)\n    at ActionController._InputOutputController_preOnInput (/data/node_modules/node-red-contrib-home-assistant-websocket/dist/common/controllers/InputOutputController.js:61:76)\n    at /usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:214:26\n    at Object.trigger (/usr/src/node-red/node_modules/@node-red/util/lib/hooks.js:166:13)\n    at Node._emitInput (/usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:206:11)\n    at Node.emit (/usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:190:25)\n    at Node.receive (/usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:499:10)\n    at deliverMessageToDestination (/usr/src/node-red/node_modules/@node-red/runtime/lib/flows/Flow.js:803:40)\n    at Immediate.<anonymous> (/usr/src/node-red/node_modules/@node-red/r..."}}
```

Same flow was working with previous version of node-red-contrib-home-assistant.

### Screenshots

<img width="534" alt="Screenshot 2024-11-23 at 19 23 09" src="https://github.com/user-attachments/assets/d509fa03-005a-41b3-9286-5d61f39ab6bf">

### Environment Information

node-red-contrib-home-assistant-websocket 0.74.2
node-red 4.0.5
home-assistant 2024.10.4

**Comment by zachowj** [comment]
There's a current bug with mustache templates in the action field where the `action` property is converted to lowercase, causing variables with mixed or uppercase letters to fail.

**Comment by outworkAnton** [comment]
I still get this kind of error, even after fixing it. Using Developer Tools - > Action, I can send a command and it will execute correctly 
```
action: remote.send_command
target:
  entity_id: remote.bedroom_tv
data:
  command: DPAD_CENTER
```
However, I get an error in Node-Red "InputError: Invalid action format: DPAD_CENTER"

![Image](https://github.com/user-attachments/assets/cc300808-bb74-455d-a6f2-598c8f5bfdcc)

**Comment by zachowj** [comment]
If I understand correctly, you're passing a message object where `msg.payload.action` is set to a value. The action node allows config overrides via `msg.payload`, and `action` is one of those overrides. If you want to prevent local config from being overridden, there's a checkbox at the bottom of the action node to block input overrides.

**Comment by outworkAnton** [comment]
> [@outworkAnton](https://github.com/outworkAnton) If I understand correctly, you're passing a message object where `msg.payload.action` is set to a value. The action node allows config overrides via `msg.payload`, and `action` is one of those overrides. If you want to prevent local config from being overridden, there's a checkbox at the bottom of the action node to block input overrides.

Tnx! It turns out that the problem was not where I was looking for! Your advice really helped!
