### ISSUE TITLE
Action node has no target if switch.turn_on is chosen

### ISSUE THREAD

**Issue by wolfcam** [zachowj/node-red-contrib-home-assistant-websocket#1700]
### Describe the bug

In action Node if switch_turn_on is set in action field there's no more interface to set target even in last version. This happens in NodeRed and HA UI.

### To Reproduce

Drag an action node,
Open and choose switch.turn_on as action
The target field disappears

### Expected behavior

I was hoping to keep the target :-)

### Screenshots

<img width="1465" alt="image" src="https://github.com/user-attachments/assets/9eb45b46-4b27-49af-aa5c-23f405ffd433">
<img width="542" alt="image" src="https://github.com/user-attachments/assets/b68c2f06-b1ae-4708-9990-aedefad978d3">

### Environment Information

node-red-contrib-home-assistant-websocket 0.74.2
homeassistant:
Core
2024.11.3
Supervisor
2024.11.4
Operating System
13.2
Frontend
20241106.2

**Comment by zachowj** [comment]
Did you try restarting Home Assistant?  

You can use this flow to verify if Home Assistant is correctly loading the switch data:

![image](https://github.com/user-attachments/assets/bc041175-7c53-41ff-ac32-f151fdce3ef7)

```json
[{"id":"2c0ae0c533d34cf6","type":"ha-api","z":"c89d915bdff0f798","name":"get services","server":"","version":1,"debugenabled":false,"protocol":"websocket","method":"get","path":"","data":"{\"type\": \"get_services\"}","dataType":"jsonata","responseType":"json","outputProperties":[{"property":"payload","propertyType":"msg","value":"","valueType":"results"}],"x":498,"y":976,"wires":[["56897320f296595c"]]},{"id":"2dea4a0a42104480","type":"inject","z":"c89d915bdff0f798","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":330,"y":976,"wires":[["2c0ae0c533d34cf6"]]},{"id":"56897320f296595c","type":"debug","z":"c89d915bdff0f798","name":"print switch.turn_on","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"payload.switch.turn_on","targetType":"jsonata","statusVal":"","statusType":"auto","x":714,"y":976,"wires":[]}]
```

The action node can only display the data supplied by Home Assistant. In this case, Home Assistant isn't providing all the required information. Specifically, there should be a `target` property loaded directly from the `services.yaml` file in Home Assistant:  

<https://github.com/home-assistant/core/blob/dev/homeassistant/components/switch/services.yaml>

**Comment by wolfcam** [comment]
Yes, i tried several times to restart after some updates, but i had same error. Using the flow that you sent, i received this error:

12/31/2024, 8:31:35 AM[nó: get services](https://xxxxxx:8443/api/hassio_ingress/jIQoFB28tetPIFUaC1Tn7JO65oXGwXOwDGtluyapwZA/#)
msg : error
"Error: Invalid server config"

Trying to understand where this error was produced.

**Comment by wolfcam** [comment]
After the last update (2024.12.5), the issue has gone.
