### ISSUE TITLE
Sentence is not trigerring. 

### ISSUE THREAD

**Issue by alpaygani** [zachowj/node-red-contrib-home-assistant-websocket#1708]
### Describe the bug

After the update my sentence based nodes are not working. 
They are not triggering anything.

### To Reproduce

Nothing to write here.. 

### Expected behavior

I am expecteing to fix it with a new update

### Screenshots

![image](https://github.com/user-attachments/assets/82fdd55d-7bca-46d7-adc0-e01f3fd143da)

### Example Flow

```json
[
    {
        "id": "0cb79c75fd0405ad",
        "type": "ha-sentence",
        "z": "377c505ef0f66cc4",
        "name": "Radyo Gol Asist",
        "server": "d8dac50d.521218",
        "version": 2,
        "inputs": 0,
        "outputs": 1,
        "exposeAsEntityConfig": "",
        "mode": "trigger",
        "sentences": [
            "Radyo Gol Sende"
        ],
        "response": "",
        "responseType": "str",
        "triggerResponse": "Radyo Gol Çalınıyor",
        "triggerResponseType": "fixed",
        "responseTimeout": 1000,
        "outputProperties": [
            {
                "property": "topic",
                "propertyType": "msg",
                "value": "",
                "valueType": "triggerId"
            },
            {
                "property": "payload",
                "propertyType": "msg",
                "value": "",
                "valueType": "triggerId"
            }
        ],
        "x": 160,
        "y": 80,
        "wires": [
            [
                "d0eed8eb2d1e5bde"
            ]
        ]
    },
    {
        "id": "d8dac50d.521218",
        "type": "server",
        "name": "Home Assistant",
        "addon": true,
        "rejectUnauthorizedCerts": true,
        "ha_boolean": "",
        "connectionDelay": false,
        "cacheJson": false,
        "heartbeat": false,
        "heartbeatInterval": "",
        "statusSeparator": "",
        "enableGlobalContextStore": false
    }
]
```

### Environment Information

[
    {
        "id": "0cb79c75fd0405ad",
        "type": "ha-sentence",
        "z": "377c505ef0f66cc4",
        "name": "Radyo Gol Asist",
        "server": "d8dac50d.521218",
        "version": 2,
        "inputs": 0,
        "outputs": 1,
        "exposeAsEntityConfig": "",
        "mode": "trigger",
        "sentences": [
            "Radyo Gol Sende"
        ],
        "response": "",
        "responseType": "str",
        "triggerResponse": "Radyo Gol Çalınıyor",
        "triggerResponseType": "fixed",
        "responseTimeout": 1000,
        "outputProperties": [
            {
                "property": "topic",
                "propertyType": "msg",
                "value": "",
                "valueType": "triggerId"
            },
            {
                "property": "payload",
                "propertyType": "msg",
                "value": "",
                "valueType": "triggerId"
            }
        ],
        "x": 160,
        "y": 80,
        "wires": [
            [
                "d0eed8eb2d1e5bde"
            ]
        ]
    },
    {
        "id": "d8dac50d.521218",
        "type": "server",
        "name": "Home Assistant",
        "addon": true,
        "rejectUnauthorizedCerts": true,
        "ha_boolean": "",
        "connectionDelay": false,
        "cacheJson": false,
        "heartbeat": false,
        "heartbeatInterval": "",
        "statusSeparator": "",
        "enableGlobalContextStore": false
    }
]

**Comment by zachowj** [comment]
Duplicate https://github.com/zachowj/hass-node-red/issues/327
