### ISSUE TITLE
Node-RED Trigger from Automation doesn't trigger (right) output path

### ISSUE THREAD

**Issue by kristian** [zachowj/node-red-contrib-home-assistant-websocket#1712]
### Describe the bug

I noticed that when I use the `nodered.trigger` in automations, it doesn't seem to trigger the right output path. For as far as my testings go, it seems to always trigger `output_path` 1 if that makes any sense. I am not very familiar with your code base, but looking at:

https://github.com/zachowj/node-red-contrib-home-assistant-websocket/blob/43d3e091ea67eee51c84ea2c8c836b9dbb862e07/src/nodes/EventsHaNode.js#L142

I found that `output_path` seems to be parsed as a `boolean` instead of a `string` here:

https://github.com/zachowj/node-red-contrib-home-assistant-websocket/blob/43d3e091ea67eee51c84ea2c8c836b9dbb862e07/src/nodes/EventsHaNode.js#L157

And as every non-empty string evaluates to `true` in JavaScript, essentially the `output_path` is always "true" as the default is a string `"0"` so `true`. This results in always choosing output number 2. However also the rest of the code doesn't seem to match the documented behavior of being able to specify a comma-separated list of output paths. I started to suggest a PR (https://github.com/kristian/node-red-contrib-home-assistant-websocket/compare/main...kristian-automation-trigger-fix), but then I became confused, because the right logic seems to be implemented here:

https://github.com/zachowj/node-red-contrib-home-assistant-websocket/blob/43d3e091ea67eee51c84ea2c8c836b9dbb862e07/src/common/controllers/ExposeAsMixin.ts#L44

If I should go forward with my PR I would need some advise on why there are two different implementations (with some undocumented properties like `skip_condition` as well)? Any help would be appreciated! 👍 

### To Reproduce

Create a automation, use a node-red trigger, observe that mostly output path 1 is chosen.

### Expected behavior

The output paths should behave as documented.

### Environment Information

Version: 0.73.0

Home Assistant version: 2024.12.5
Companion version: 4.1.2

Node-RED version: 4.0.3
Docker: yes
Add-on: 18.1.1

Node.js version: v18.20.4 x64 linux
OS: Linux 6.6.66-haos x64

**Comment by zachowj** [comment]
`EventsHaNode.js` is exclusively used for the deprecated [entity node](https://github.com/zachowj/node-red-contrib-home-assistant-websocket/tree/main/src/nodes/entity). The new format, as [documented here](https://zachowj.github.io/node-red-contrib-home-assistant-websocket/guide/custom_integration/exposed-nodes.html), appears to be functioning correctly based on my tests.

**Comment by kristian** [comment]
Hey @zachowj, thanks for the quick response! Ah okay, so essentially also other nodes are exposee as switch entities to Home Assistant, I see.

I noticed that I can only select switch entities when I create a Node-RED trigger action. Thus I started to use [switches](https://zachowj.github.io/node-red-contrib-home-assistant-websocket/node/switch.html). Are you saying [switches](https://zachowj.github.io/node-red-contrib-home-assistant-websocket/node/switch.html) and stuff like [binary sensor](https://zachowj.github.io/node-red-contrib-home-assistant-websocket/node/binary-sensor.html) are deprecated and only the nodes you mention [here](https://zachowj.github.io/node-red-contrib-home-assistant-websocket/guide/custom_integration/exposed-nodes.html) are „current“? Or does your statement only apply to th`nodered.trigger`? Thanks!

**Comment by kristian** [comment]
Mhm, I just went through the list of nodes you mentioned [documented here](https://zachowj.github.io/node-red-contrib-home-assistant-websocket/guide/custom_integration/exposed-nodes.html). Maybe I don't get the idea, but essentially I just need an "input node" that can be triggered from [`nodered.trigger`](https://zachowj.github.io/node-red-contrib-home-assistant-websocket/guide/custom_integration/exposed-nodes.html#triggering-exposed-nodes-via-nodered-trigger), as I want to "call into" Node-RED from Home Assistant. So far I created a [switch](https://zachowj.github.io/node-red-contrib-home-assistant-websocket/node/switch.html) which was then exposed to HA as a switch entity and I was able to interact from my HA instance to Node-RED easily. Now with the new exposed nodes you shared, I don't get the idea yet? Is there a basic "placeholder" node available, that I can just use as a inbound trigger to Node-RED? Seems all exposed nodes fulfill a function that I don't need them to fulfill / have no use for. Or am I getting the wrong idea? Thanks!

**Comment by zachowj** [comment]
The switch node differs from other nodes exposed to Home Assistant because it retains its original structure and hasn't been updated to align with newer node types. The main distinction is that you can't select the output for the trigger data—it depends on the switch's state. If the state is "on," the data goes out the top output; if "off," it exits through the bottom output. You can find an example of using the `nodered.trigger` service [here](https://zachowj.github.io/node-red-contrib-home-assistant-websocket/node/switch.html#outputs). You can trigger the flow and send custom data but are unable to choose the path.

Do you need to only trigger the Node-RED flow from Home Assistant, or are you looking to send custom data as well? The button node allows you to initiate a flow directly from the Home Assistant UI using the "button.press" action. If custom data is required, you can fire an event in Home Assistant and use the events: all node in Node-RED to start a flow based on the event name, including the custom data.

**Comment by kristian** [comment]
Okay this explanation sheds some light on the current behavior! Thanks!

> Do you need to only trigger the Node-RED flow from Home Assistant, or are you looking to send custom data as well? The button node allows you to initiate a flow directly from the Home Assistant UI using the "button.press" action. If custom data is required, you can fire an event in Home Assistant and use the events: all node in Node-RED to start a flow based on the event name, including the custom data.

Ok, this makes things significantly easier. I thought too complicated and wanted to use the `nodered.trigger` by any means... I just thought "well I want to trigger a Node-RED flow, so let's use the built-in action from it". That I simply can use a native `button.press` action, didn't cross my mind at all. 👍 This is the most easy option in my opinion and as you said, also sending a custom event makes perfect sense.

For more complex use-cases a dummy "inbound trigger" node would have been nice. A node that you can specify the number of outputs on / without any inbound connectors, so you could use `nodered.trigger`, to choose which outputs to invoke, sending data. Maybe just as an idea for any future update.

Thanks again for the explanation. I will close the Issue & my PR. Have a good one @zachowj.
