### ISSUE TITLE
unable to connect HA after update to Home Assistant Operating System 14.1

### ISSUE THREAD

**Issue by 18802496555** [zachowj/node-red-contrib-home-assistant-websocket#1715]
### Describe the bug

unable to connect HA after update to Home Assistant Operating System 14.1

### Environment Information

Node-RED version:v4.0.6
Node.js version:v20.18.1

**Comment by zachowj** [comment]
What do your Node-RED logs show during startup?

**Comment by GaryTill** [comment]
I think I'm having the same issue. Tried reinstalling the hacs integration but in NodeRed all HA nodes are missing

**Comment by 18802496555** [comment]
<{"log":"\n","stream":"stdout","time":"2024-12-23T00:55:12.091771759Z"}
{"log":"Welcome to Node-RED\n","stream":"stdout","time":"2024-12-23T00:55:12.091795929Z"}
{"log":"===================\n","stream":"stdout","time":"2024-12-23T00:55:12.09181704Z"}
{"log":"\n","stream":"stdout","time":"2024-12-23T00:55:12.091836721Z"}
{"log":"23 Dec 08:55:12 - [info] Node-RED version: v4.0.6\n","stream":"stdout","time":"2024-12-23T00:55:12.091859121Z"}
{"log":"23 Dec 08:55:12 - [info] Node.js  version: v20.18.1\n","stream":"stdout","time":"2024-12-23T00:55:12.091899503Z"}
{"log":"23 Dec 08:55:12 - [info] Linux 6.6.44-production+truenas x64 LE\n","stream":"stdout","time":"2024-12-23T00:55:12.091976175Z"}
{"log":"23 Dec 08:55:12 - [info] Loading palette nodes\n","stream":"stdout","time":"2024-12-23T00:55:12.193676442Z"}
{"log":"23 Dec 08:55:12 - [info] Node-RED Contrib Theme Collection version: v4.0.11\n","stream":"stdout","time":"2024-12-23T00:55:12.42378475Z"}
{"log":"spawnSync locale ENOENT\n","stream":"stdout","time":"2024-12-23T00:55:13.279185941Z"}
{"log":"23 Dec 08:55:13 - [info] Dashboard version 3.6.5 started at /ui\n","stream":"stdout","time":"2024-12-23T00:55:13.39039753Z"}
{"log":"23 Dec 08:55:13 - [info] node-red-contrib-home-assistant-websocket v0.74.2 nodes initialized\n","stream":"stdout","time":"2024-12-23T00:55:13.658547786Z"}
{"log":"23 Dec 08:55:13 - [info] Settings file  : /data/settings.js\n","stream":"stdout","time":"2024-12-23T00:55:13.757046661Z"}
{"log":"23 Dec 08:55:13 - [info] Context store  : 'memoryOnly' [module=memory]\n","stream":"stdout","time":"2024-12-23T00:55:13.757586226Z"}
{"log":"23 Dec 08:55:13 - [info] Context store  : 'file' [module=localfilesystem]\n","stream":"stdout","time":"2024-12-23T00:55:13.758565944Z"}
{"log":"23 Dec 08:55:13 - [info] User directory : /data\n","stream":"stdout","time":"2024-12-23T00:55:13.761465657Z"}
{"log":"23 Dec 08:55:13 - [warn] Projects disabled : editorTheme.projects.enabled=false\n","stream":"stdout","time":"2024-12-23T00:55:13.761491018Z"}
{"log":"23 Dec 08:55:13 - [info] Flows file     : /data/flows.json\n","stream":"stdout","time":"2024-12-23T00:55:13.761884399Z"}
{"log":"23 Dec 08:55:13 - [info] Server now running at http://127.0.0.1:1880/\n","stream":"stdout","time":"2024-12-23T00:55:13.769029033Z"}
{"log":"23 Dec 08:55:13 - [warn] \n","stream":"stdout","time":"2024-12-23T00:55:13.780471851Z"}
{"log":"\n","stream":"stdout","time":"2024-12-23T00:55:13.780514642Z"}
{"log":"---------------------------------------------------------------------\n","stream":"stdout","time":"2024-12-23T00:55:13.780528342Z"}
{"log":"Your flow credentials file is encrypted using a system-generated key.\n","stream":"stdout","time":"2024-12-23T00:55:13.780540142Z"}
{"log":"\n","stream":"stdout","time":"2024-12-23T00:55:13.780551993Z"}
{"log":"If the system-generated key is lost for any reason, your credentials\n","stream":"stdout","time":"2024-12-23T00:55:13.780563413Z"}
{"log":"file will not be recoverable, you will have to delete it and re-enter\n","stream":"stdout","time":"2024-12-23T00:55:13.780574663Z"}
{"log":"your credentials.\n","stream":"stdout","time":"2024-12-23T00:55:13.780586204Z"}
{"log":"\n","stream":"stdout","time":"2024-12-23T00:55:13.780597284Z"}
{"log":"You should set your own key using the 'credentialSecret' option in\n","stream":"stdout","time":"2024-12-23T00:55:13.780608215Z"}
{"log":"your settings file. Node-RED will then re-encrypt your credentials\n","stream":"stdout","time":"2024-12-23T00:55:13.780619275Z"}
{"log":"file using your chosen key the next time you deploy a change.\n","stream":"stdout","time":"2024-12-23T00:55:13.780632075Z"}
{"log":"---------------------------------------------------------------------\n","stream":"stdout","time":"2024-12-23T00:55:13.780643525Z"}
{"log":"\n","stream":"stdout","time":"2024-12-23T00:55:13.780654896Z"}
{"log":"23 Dec 08:55:13 - [info] Starting flows\n","stream":"stdout","time":"2024-12-23T00:55:13.81964836Z"}
{"log":"23 Dec 08:55:14 - [info] Started flows\n","stream":"stdout","time":"2024-12-23T00:55:14.102915337Z"}
{"log":"23 Dec 08:55:14 - [info] [server:truenas HAOS] Connecting to http://192.168.1.172:8123\n","stream":"stdout","time":"2024-12-23T00:55:14.104684898Z"}
{"log":"23 Dec 08:55:14 - [info] [mqtt-broker:truenas docker compose mqtt] Connected to broker: truenas-nodered@mqtt://192.168.1.221:1883\n","stream":"stdout","time":"2024-12-23T00:55:14.116942188Z"}
{"log":"23 Dec 08:57:33 - [info] [server:truenas HAOS] Connecting to http://192.168.1.172:8123\n","stream":"stdout","time":"2024-12-23T00:57:33.105341717Z"}>

**Comment by zachowj** [comment]
Are you sure the IP address `192.168.1.172` is accessible from Node-RED? 

Try using an HTTP request node in Node-RED to test the connection and see if you receive a response.

![image](https://github.com/user-attachments/assets/9d48434b-92dd-45d2-84ca-26a65227f6a5)

```
[{"id":"7b6b7734614e8e7c","type":"inject","z":"c89d915bdff0f798","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":218,"y":1120,"wires":[["0a2fe132f304afd0"]]},{"id":"ec0b60f72a9c8465","type":"debug","z":"c89d915bdff0f798","name":"debug 1","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","statusVal":"","statusType":"auto","x":564,"y":1120,"wires":[]},{"id":"0a2fe132f304afd0","type":"http request","z":"c89d915bdff0f798","name":"","method":"GET","ret":"txt","paytoqs":"ignore","url":"http://192.168.1.172:8123","tls":"","persist":false,"proxy":"","insecureHTTPParser":false,"authType":"","senderr":false,"headers":[],"x":394,"y":1120,"wires":[["ec0b60f72a9c8465"]]}]
```

**Comment by 18802496555** [comment]
You're right, my docker network bridge were blocking the communication, problem solved by reseting the docker network bridge
