### ISSUE TITLE
Mustache Templates in Action Node

### ISSUE THREAD

**Issue by snakeeyes5** [zachowj/node-red-contrib-home-assistant-websocket#1718]
### Describe the bug

Mustache templates stopped working after 2024.10 HA upgrade.

Have this in the Data field for Action Node (notify.push_notify_devices_all):

`{	  "title": "Alarm is {{ states('alarm_control_panel.our_home').replace('_', ' ')|title }}",	  "message": "Zones Violated: {{ states('sensor.alarm_zones_violated_list') }}",	  "data": {	    "url": "/alarm-status/dashboard"	  }	}`

The notification just shows the literal mustaches i.e "{{ entity.light.hs_basement_bar_pendants }}"

### Environment Information

Version: 0.74.2

Home Assistant version: 2024.12.1
Companion version: 4.1.2

Node-RED version: 4.0.5
Docker: no
Add-on: no

Node.js version: v23.4.0 x64 linux
OS: Linux 5.15.0-126-generic x64

**Comment by zachowj** [comment]
Those are Jinja2 templates, not Mustache, and they’re rendered by Home Assistant after the data is sent. However, Home Assistant recently removed the ability for the `notify` domain to render Jinja2 templates.

I’d recommend switching to JSONata, which is rendered before the action call is sent to Home Assistant.

```
{
  "title": "Alarm is " & $uppercase($substring($entities("alarm_control_panel.our_home").state, 0, 1)) & $lowercase($substring($entities("alarm_control_panel.our_home").state, 1)).replace('_', ' '),
  "message": "Zones Violated: " & $entities('sensor.alarm_zones_violated_list').state,
  "data": {
    "url": "/alarm-status/dashboard"
  }
}
```

https://zachowj.github.io/node-red-contrib-home-assistant-websocket/guide/jsonata/
