### ISSUE TITLE
Current State Node: How to Use If State: In

### ISSUE THREAD

**Issue by tompijls** [zachowj/node-red-contrib-home-assistant-websocket#172]
**Describe the bug**
Hi,

I would like to check if my entity is either in state “Home” (depicted below) or “Just Arrived”.
Rather than using the “Is” condition, could I use the “In” condition in the “Is State:” field? I tried to find this in the documentation but was unsuccessful. Any help or workaround would be appreciated.

Using "Home","Just Arrived" does not work.

**Screenshots**
![Screenshot 2019-12-02 at 15 14 15](https://user-images.githubusercontent.com/831240/69966409-9b77b980-1516-11ea-8d28-fb1ecc8d6d20.png)

Thanks!

**Comment by zachowj** [comment]
https://community.home-assistant.io/t/current-state-node-how-to-use-if-state-in/152178/7?u=kermit
