### ISSUE TITLE
home assitant connection in docker

### ISSUE THREAD

**Issue by PierreMacherel** [zachowj/node-red-contrib-home-assistant-websocket#174]
**Describe the bug**
the message  
`WARNING (MainThread) [homeassistant.components.websocket_api.http.connection.XXXXXXX] Disconnected: Did not receive auth message within 10 seconds`
is emitted every 13 seconds in home assistant. Note that the flows work as expected (I receive events and I can call service).

**To Reproduce**
Start Home assistant
Deploy a flow (I don't know how to disable flow, so I can't tell if the problem would persist if no `node-red-contrib-home-assistant-websocket` node is used).

**Expected behavior**
No warning message

**Environment:**
- Node Red Version: 1.0.3
- Node.js Version: 10.17.0
- NR Home Assistant Plugin Version: 0.17.0
- Is Node Red running in Docker: yes (with network_mode: host, as home assistant container)
- Home Assistant Version:  0.104.0.dev20191209

**Other:**
- Have you searched previous issues for duplicates?: 
Yes. I found this [issue](https://github.com/zachowj/node-red-contrib-home-assistant-websocket/issues/77), but unlike dkruyt, I use token instead of password.

**Additional context**
The home assistant and node red docker are ruining on the same computer, in host network.
In node red, the home assistant is configured as follows:
[ ]  I use Hass.io
Base URL: http://127.0.0.1:8123
Access Token: <my token>
[ ]  Use Legacy API Password
[x]  Accept Unauthorized SSL Certificates
State Boolean: y|yes|true|on|home|open
[x] Cache Autocomplete Results

Shunting down the node red container stop the warnings in home assistant container.

**Comment by zachowj** [comment]
Do you still get this after a reboot of NR? I tried to reproduce this and have been unable to do so.

**Comment by PierreMacherel** [comment]
I still get this after a reboot.
I found a way to get ride of the error message :
- export flow by flow the flows in node red
- delete the node red container
- create a new node red container
- import flow by flow
the warning still appears with import/export all.
