### ISSUE TITLE
Adding valueType variable key to Home Assistant Config name

### ISSUE THREAD

**Issue by hulkhaugen** [zachowj/node-red-contrib-home-assistant-websocket#175]
**Is your feature request related to a problem? Please describe.**
N/A or Unknown

**Describe the solution you'd like**
I'm a Node-RED n00b, so maybe my request is stupid and easy to work-around. I'm currently trying to make a scrape sensor for stock fund data. I want to use the `valueType:msg` for my HA sensor's `name/entity_id`. I tried to force in `"valueType": "msg"` in the node import, but it's discarded. 

**Describe alternatives you've considered**
I don't see any alternatives, but my knowledge is also very limited in this field.

**Additional context**
Here's the sequence i'm working on, there is a template node that i'm supposed to use to loop through several URLs also, but that's not integrated yet:
`[{"id":"85776cea.2a018","type":"template","z":"4f7a68fe.44caa8","name":"Funds","field":"payload","fieldType":"msg","format":"handlebars","syntax":"mustache","template":"{\n    \"global\": \"F00000JORS\",\n    \"norge\": \"F00000JORR\",\n    \"usa\": \"F0GBR04OTI\",\n    \"healthcare\": \"F00000ZFFV\",\n    \"teknologi\": \"F00000ZFG1\"\n}","output":"json","x":170,"y":200,"wires":[[]]},{"id":"30cdee7.0c63112","type":"inject","z":"4f7a68fe.44caa8","name":"POST id","topic":"","payload":"F0GBR04NGU","payloadType":"str","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":100,"y":140,"wires":[["34ea4898.030bb8"]]},{"id":"34ea4898.030bb8","type":"change","z":"4f7a68fe.44caa8","name":"","rules":[{"t":"set","p":"post","pt":"msg","to":"payload","tot":"msg"}],"action":"","property":"","from":"","to":"","reg":false,"x":250,"y":140,"wires":[["eff86bb0.4dd408","fbd3baa.4f2d348"]]},{"id":"eff86bb0.4dd408","type":"http request","z":"4f7a68fe.44caa8","name":"GET Main","method":"GET","ret":"txt","paytoqs":false,"url":"https://www.morningstar.no/no/funds/snapshot/snapshot.aspx?id={{{post}}}","tls":"","persist":false,"proxy":"","authType":"","x":420,"y":100,"wires":[["b4130d6.7e481f","c4aa1a4a.19cac8","a52fdedc.cc052"]]},{"id":"fbd3baa.4f2d348","type":"http request","z":"4f7a68fe.44caa8","name":"GET History","method":"GET","ret":"txt","paytoqs":false,"url":"https://www.morningstar.no/no/funds/snapshot/snapshot.aspx?id={{{post}}}&tab=1","tls":"","persist":false,"proxy":"","authType":"","x":430,"y":180,"wires":[["a576ce16.8b778","5120fffe.dd8b1","9cd280d1.6cc38","9f3328a5.e32f78"]]},{"id":"c4aa1a4a.19cac8","type":"html","z":"4f7a68fe.44caa8","name":"Title","property":"payload","outproperty":"payload","tag":"h1","ret":"text","as":"multi","x":590,"y":20,"wires":[["7bac34f9.8a751c"]]},{"id":"a52fdedc.cc052","type":"html","z":"4f7a68fe.44caa8","name":"Date","property":"payload","outproperty":"payload","tag":"#overviewQuickstatsDiv tr:nth-child(2) td.line.heading span","ret":"text","as":"multi","x":590,"y":60,"wires":[["4a8bac12.fe9be4"]]},{"id":"b4130d6.7e481f","type":"html","z":"4f7a68fe.44caa8","name":"Price","property":"payload","outproperty":"payload","tag":"#overviewQuickstatsDiv tr:nth-of-type(2) td:nth-of-type(3)","ret":"text","as":"single","x":590,"y":100,"wires":[["32496c07.ab8f64"]]},{"id":"a576ce16.8b778","type":"html","z":"4f7a68fe.44caa8","name":"1 Day","property":"payload","outproperty":"payload","tag":"#returnsTrailingDiv tr:nth-child(3) td.col2.value.number","ret":"text","as":"single","x":590,"y":140,"wires":[["dd4fbafb.021548"]]},{"id":"5120fffe.dd8b1","type":"html","z":"4f7a68fe.44caa8","name":"1 Week","property":"payload","outproperty":"payload","tag":"#returnsTrailingDiv tr:nth-child(4) td.col2.value.number","ret":"text","as":"single","x":600,"y":180,"wires":[["71d3f223.2727cc"]]},{"id":"9cd280d1.6cc38","type":"html","z":"4f7a68fe.44caa8","name":"1 Month","property":"payload","outproperty":"payload","tag":"#returnsTrailingDiv tr:nth-child(5) td.col2.value.number","ret":"text","as":"single","x":600,"y":220,"wires":[["3f2c0d28.20fb42"]]},{"id":"9f3328a5.e32f78","type":"html","z":"4f7a68fe.44caa8","name":"1 Year","property":"payload","outproperty":"payload","tag":"#returnsTrailingDiv tr:nth-child(9) td.col2.value.number","ret":"text","as":"single","x":590,"y":260,"wires":[["38032aee.c1e206"]]},{"id":"37e1e02.3bf122","type":"function","z":"4f7a68fe.44caa8","name":"String>Float","func":"msg.payload = /(?:[^A-z]+)/.exec(msg.payload)[0].replace(\",\",\".\");\nmsg.payload = parseFloat(msg.payload);\nreturn msg;","outputs":1,"noerr":0,"x":930,"y":200,"wires":[["bdd00546.fec1f8"]]},{"id":"1df05d04.5c5aa3","type":"debug","z":"4f7a68fe.44caa8","name":"","active":true,"tosidebar":true,"console":true,"tostatus":false,"complete":"payload","targetType":"msg","x":940,"y":80,"wires":[]},{"id":"bdd00546.fec1f8","type":"join","z":"4f7a68fe.44caa8","name":"","mode":"custom","build":"object","property":"payload","propertyType":"msg","key":"topic","joiner":"\\n","joinerType":"str","accumulate":false,"timeout":"","count":"7","reduceRight":false,"reduceExp":"","reduceInit":"","reduceInitType":"num","reduceFixup":"","x":910,"y":140,"wires":[["1df05d04.5c5aa3","e5900f64.3399c"]]},{"id":"dd4fbafb.021548","type":"change","z":"4f7a68fe.44caa8","name":"day","rules":[{"t":"set","p":"topic","pt":"msg","to":"day","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":730,"y":140,"wires":[["37e1e02.3bf122"]]},{"id":"71d3f223.2727cc","type":"change","z":"4f7a68fe.44caa8","name":"week","rules":[{"t":"set","p":"topic","pt":"msg","to":"week","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":730,"y":180,"wires":[["37e1e02.3bf122"]]},{"id":"3f2c0d28.20fb42","type":"change","z":"4f7a68fe.44caa8","name":"month","rules":[{"t":"set","p":"topic","pt":"msg","to":"month","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":730,"y":220,"wires":[["37e1e02.3bf122"]]},{"id":"38032aee.c1e206","type":"change","z":"4f7a68fe.44caa8","name":"year","rules":[{"t":"set","p":"topic","pt":"msg","to":"year","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":730,"y":260,"wires":[["37e1e02.3bf122"]]},{"id":"7bac34f9.8a751c","type":"change","z":"4f7a68fe.44caa8","name":"title","rules":[{"t":"set","p":"topic","pt":"msg","to":"title","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":730,"y":20,"wires":[["bdd00546.fec1f8"]]},{"id":"4a8bac12.fe9be4","type":"change","z":"4f7a68fe.44caa8","name":"date","rules":[{"t":"set","p":"topic","pt":"msg","to":"date","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":730,"y":60,"wires":[["bdd00546.fec1f8"]]},{"id":"32496c07.ab8f64","type":"change","z":"4f7a68fe.44caa8","name":"price","rules":[{"t":"set","p":"topic","pt":"msg","to":"price","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":730,"y":100,"wires":[["37e1e02.3bf122"]]},{"id":"e5900f64.3399c","type":"ha-entity","z":"4f7a68fe.44caa8","name":"","server":"e707d943.9c83a8","version":1,"debugenabled":false,"outputs":1,"entityType":"sensor","config":[{"property":"name","value":"payload.title"},{"property":"device_class","value":""},{"property":"icon","value":""},{"property":"unit_of_measurement","value":"kr"}],"state":"payload.price","stateType":"msg","attributes":[{"property":"dag","value":"payload.day","valueType":"msg"},{"property":"uke","value":"payload.week","valueType":"msg"},{"property":"mnd","value":"payload.month","valueType":"msg"},{"property":"aar","value":"payload.year","valueType":"msg"},{"property":"dato","value":"payload.date","valueType":"msg"}],"resend":true,"outputLocation":"","outputLocationType":"none","x":1090,"y":140,"wires":[[]]},{"id":"e707d943.9c83a8","type":"server","z":"","name":"Home Assistant","legacy":false,"hassio":true,"rejectUnauthorizedCerts":true,"ha_boolean":"y|yes|true|on|home|open","connectionDelay":true,"cacheJson":true}]`

**Comment by zachowj** [comment]
You are unable to set any HA config options from input because these values have to be sent when deploying the node and can't be changed unless you deploy it again. This means that each sensor in HA needs a corresponding sensor node in NR. 

There's a way around this using the API node. <https://community.home-assistant.io/t/help-merging-2-node-red-flows-in-1/154642/23?u=kermit>

Here's a possible solution to your problem: <https://pastebin.com/pHiXZ4ns>
