### ISSUE TITLE
Current State/History Node - Ability to get entity id from root flow / global state or template

### ISSUE THREAD

**Issue by niemyjski** [zachowj/node-red-contrib-home-assistant-websocket#177]
I'd like to be able to just set `flow.entity_id` and have it be able to be read off the current state node or use a template inside of entity_id to control it. I can't do this today and it seems like it should work but it doesn't.

**Comment by zachowj** [comment]
Same thing as I said in #176. I believe you're running an older version of this package.

![image](https://user-images.githubusercontent.com/37859597/71502405-e4284700-2824-11ea-80bc-38b195e08122.png)

```
[{"id":"945d1d53.3bbe3","type":"inject","z":"ffbd7f06.4a014","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":220,"y":832,"wires":[["6994058e.e42a6c"]]},{"id":"6994058e.e42a6c","type":"change","z":"ffbd7f06.4a014","name":"","rules":[{"t":"set","p":"entity_id","pt":"flow","to":"sun.sun","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":380,"y":832,"wires":[["b4d5fc92.845f6"]]},{"id":"b4d5fc92.845f6","type":"api-current-state","z":"ffbd7f06.4a014","name":"","version":1,"outputs":1,"halt_if":"","halt_if_type":"str","halt_if_compare":"is","override_topic":false,"entity_id":"{{flow.entity_id}}","state_type":"str","state_location":"payload","override_payload":"msg","entity_location":"data","override_data":"msg","blockInputOverrides":false,"x":622,"y":832,"wires":[["292f49e9.b48da6"]]},{"id":"292f49e9.b48da6","type":"debug","z":"ffbd7f06.4a014","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"data","targetType":"msg","x":840,"y":832,"wires":[]}]
```

**Comment by niemyjski** [comment]
I'm using version 0.10.2 with hassio. I did notice that this also applies to history node. I want to specify an entity_id via a template or even it in the payload.

**Comment by niemyjski** [comment]
I upgraded it the latest version and I don't see it in the docs but I'll try it.

**Comment by zachowj** [comment]
<https://github.com/zachowj/node-red-contrib-home-assistant-websocket/commit/94142109e1128f0a52360e2cee066d8a0660395b>
