### ISSUE TITLE
Call Service: Ability to determine the domain from entity_id.

### ISSUE THREAD

**Issue by niemyjski** [zachowj/node-red-contrib-home-assistant-websocket#178]
When I pass in an entity_id it already has the domain that needs to be passed through. It would be nice if this defaulted to the domain on the entity_id. This would make turning off fans, switches and lights much much easier in a more generic sub flow.

**Comment by zachowj** [comment]
Can't this be accomplished by using `homeassistant` as the domain in the call-service call?

**Comment by niemyjski** [comment]
I don't even think that's an option, you must set the domain to the correct thing. I somewhat got around this by stripping the domain off the entity id in a function node.

**Comment by zachowj** [comment]
https://www.home-assistant.io/docs/scripts/service-calls/#homeassistant-services
