### ISSUE TITLE
Override data control in current state

### ISSUE THREAD

**Issue by thejta** [zachowj/node-red-contrib-home-assistant-websocket#18]
**Is your feature request related to a problem? Please describe.**
The current-state node allows control of topic and payload override, but not the data.

**Describe the solution you'd like**
Add support for control of override data

**Describe alternatives you've considered**

**Additional context**
In the original node-red-contrib-home-assistant, I had modified the current-state node to fix a logic bug that was in a PR but not merged.  While in there, I also added override data control to the node.  I found this useful to be able to halt a flow based on a condition, but otherwise let whatever the input to the current-state was continue on through.

One simple example is I have all my door sensors (server-state-change nodes) flow into a single current-state node that checks an input_boolean that controls if that flow should run.  It halts if off, but otherwise doesn't override anything and the flow continues.

This should be able to be added and not break anything with the right default.  If this sounds useful, happy to put up the PR.  If I'm missing something, happy to be educated :)

**Comment by zachowj** [comment]
If I am understanding you correctly I don't see any issue with adding another checkbox to not overwrite the msg.data object for the current-state node. My question is do we just drop the current-state data altogether or move it to a different property and if so what property.

We could also take the route where we have the option to choose which message property the data object gets written to for most of the nodes. Could default to msg.data or you could choose msg.sensor for example.

**Comment by thejta** [comment]
I put up PR #20 with my proposed changes, which I had been running locally.

I'm not well versed in all the current-state use cases.  In my use case to date, just dropping the current-state data (via the PR control) has been fine.  I haven't had case where I need both the input data and the current-state data passed along.
