### ISSUE TITLE
debug() calls within `ha-websocket.js` aren't going to the logs.

### ISSUE THREAD

**Issue by guice** [zachowj/node-red-contrib-home-assistant-websocket#181]
**Describe the bug**
Debug messages within `ha-websocket.js` aren't showing up within the logs. See attached screenshots of two terminal windows. You can see where I added manual `console.debug` to the output (tracing an error with connectivity). And you can see the `debug([...])` messages never show up:

![Screen Shot 2020-01-01 at 2 10 18 PM](https://user-images.githubusercontent.com/205378/71646179-f2e98080-2ca0-11ea-82c3-f6f8190f8356.png)

![Screen Shot 2020-01-01 at 2 10 24 PM](https://user-images.githubusercontent.com/205378/71646180-f54bda80-2ca0-11ea-854e-5c2ba1ef14ea.png)

**Environment (please complete the following information):**

- Node Red Version: 1.0.3
- NR Home Assistant Plugin Version: 5.0.7
- Is Node Red running in Docker: yes - HA and NR are docker containers running on an Ubuntu system.

**Comment by zachowj** [comment]
Are you setting the environment variable? `DEBUG=home-assistant*`

<https://github.com/visionmedia/debug>

**Comment by guice** [comment]
No. I did not know of that variable. I'm setting the `log_level` within Node Red, [as documented](https://github.com/hassio-addons/addon-node-red/blob/v5.0.7/README.md#option-log_level). 

I had no idea there was an ENV variable. How come the Node Red debug works for calls _within_ `node/config-server/config-server.js` but not within `lib/ha-websocket.js`?

You're mixing debug methods. Now that's confusing.

**Comment by zachowj** [comment]
The majority of files in `lib` should be broken out into their own package. They don't have access to the NR runtime so they can't use NR logging.

**Comment by guice** [comment]
How can one enable those logs while using the NR Hass.io addon (docker env)? It _might_ work using `DEBUG=home-assistant* s6-srv -r nodered` .. I hadn't tried that, yet. But that requires one to have the knowledge of Docker cli and `s6`.

**Comment by guice** [comment]
> It might work using `DEBUG=home-assistant* s6-svc -r nodered` .. I hadn't tried that, yet. But that requires one to have the knowledge of Docker cli and s6.

Just tried that. Didn't work. :/

**Comment by zachowj** [comment]
Not a hass.io user but you might be able to use [init_commands](https://github.com/hassio-addons/addon-node-red#option-init_commands) to set environment variables.
