### ISSUE TITLE
No events emitted with token from HomeAssistant user in scope "User"

### ISSUE THREAD

**Issue by cybrox** [zachowj/node-red-contrib-home-assistant-websocket#185]
**Describe the bug**
Looks like a successful connection but does not emit any ecents.

Installed the integration and set up the connection to HomeAssistant with a token from an existing account. I connected the all event node to a debugger and this was the output:
```
1/9/2020, 1:13:25 PMnode: HomeAssistantDebugger
home_assistant_client:connecting : msg.payload : string[10]
"connecting"
1/9/2020, 1:13:25 PMnode: HomeAssistantDebugger
home_assistant_client:connected : msg.payload : string[9]
"connected"
1/9/2020, 1:13:26 PMnode: HomeAssistantDebugger
home_assistant_client:states_loaded : msg.payload : string[13]
"states_loaded"
1/9/2020, 1:13:26 PMnode: HomeAssistantDebugger
home_assistant_client:services_loaded : msg.payload : string[15]
"services_loaded"
```
However, it did not emit any events afterwards. Changing the user scope from `User` to `Administrator` in Home Assistant solved the issue. The home assistant log showed:
```
Jan 09 07:57:03 raspberrypi docker[13027]: 2020-01-09 08:57:03 WARNING (zeroconf-ServiceBrowser__googlecast._tcp.local.) [zeroconf] Exception occurred:
Jan 09 07:57:03 raspberrypi docker[13027]: Traceback (most recent call last):
Jan 09 07:57:03 raspberrypi docker[13027]:   File "/usr/local/lib/python3.7/site-packages/zeroconf/__init__.py", line 2531, in send
Jan 09 07:57:03 raspberrypi docker[13027]:     bytes_sent = s.sendto(packet, 0, (real_addr, port))
Jan 09 07:57:03 raspberrypi docker[13027]: OSError: [Errno 22] Invalid argument
Jan 09 08:07:33 raspberrypi docker[13027]: 2020-01-09 09:07:33 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.2929785232] Error handling message: Unauthorized

```

**To Reproduce**
Follow all the steps in the [Getting Started](https://zachowj.github.io/node-red-contrib-home-assistant-websocket/guide/#installation) guide but use a Home Assistant user  with the scope `User` (not `Administrator`)

**Expected behavior**
The node should emit an error when attempting to connect or subscribe for events where it receives an unauthorized.

**Environment (please complete the following information):**
- Node Red Version: 1.0.3
- Node.js Version: 10.18.0
- NR Home Assistant Plugin Version: 0.19.3
- Is Node Red running in Docker: yes

**Screenshot**
![https://i.ibb.co/YTfvFJP/2020-01-09-13-15-29.png](https://i.ibb.co/YTfvFJP/2020-01-09-13-15-29.png)

- Have you searched previous issues for duplicates?:
Yes

**Comment by zachowj** [comment]
You won't be able to use a non-admin account to use the node-red integration because all the WebSocket commands require admin privileges because they modify entities in Home Assistant.

**Comment by cybrox** [comment]
That's OK, I don't mind using an admin account. I do think the node should send an error and/or have a hint added to the Getting Started guide.

**Comment by zachowj** [comment]
<https://github.com/zachowj/node-red-contrib-home-assistant-websocket/commit/2ef21668529ed69b0e7c1b02cecff14fe2c5922e>
