### ISSUE TITLE
Is "halt if" still available? if not, how do I do something similar to that?

### ISSUE THREAD

**Issue by jfrux** [zachowj/node-red-contrib-home-assistant-websocket#186]
I'm trying to follow some guides, some of them dated - some not... but I'm not seeing any "halt if" select boxes anymore... or in the docs.

Any tips?

**Comment by zachowj** [comment]
Have them update their guides.

Changed to `if state`

https://github.com/zachowj/node-red-contrib-home-assistant-websocket/releases/tag/v0.12.0
