### ISSUE TITLE
Ignore 'unavailable' state changes

### ISSUE THREAD

**Issue by fenderle** [zachowj/node-red-contrib-home-assistant-websocket#187]
**Is your feature request related to a problem? Please describe.**
Everytime my ESPHome sensors get disconnected from the WiFi their state changes from 'on' or 'off' to 'unavailable' and after the device is back online the state changes again from 'unavailable' back to 'on' or 'off'. This state change triggers my flow and toggles lights which is obviously unintended.

I fixed this behaviour by adding a function node which detects the change to 'unavailable' and blocks the unavailable message as well as the following message, so no unintended changes are relayed to the flow. However, this is very untidy and I had to add this function node after each 'state changed' input.

**Describe the solution you'd like**
I would like to have a checkbox in the 'state changed' node which says 'ignore unavailable states' which then does not send the unavailble state change, plus the follwing state change back to the original value.

**Describe alternatives you've considered**
I tried using the filtering of the 'state changed' node (only let pass on and off states) but still the transitions back from unavailable to on or off get relayed, triggering the flow. I also tried then to add an rbe node, but that didn't work as well (and also is as untidy as using a function node)

**Additional context**
If this can be solved in aother way I would appreciate a pointer to a good solution which doesn't include to add everywhere addtional filter nodes

**Comment by zachowj** [comment]
You could probably get the same logic in a trigger-state node.

**Comment by zachowj** [comment]
Something like:

![image](https://user-images.githubusercontent.com/37859597/72148255-32753400-3355-11ea-8cb6-873869b4f828.png)

**Comment by fenderle** [comment]
Works beautifully! Thanks!
