### ISSUE TITLE
Set entity by using curly braces in WAIT-Node

### ISSUE THREAD

**Issue by sti0** [zachowj/node-red-contrib-home-assistant-websocket#189]
**Describe the bug**
If you set an entity from the message object by using {{myentity}} the WAIT node does not use this entity id. Instead it times out.

**To Reproduce**

1. set a HA entity to the message object -> msg.myentity
2. in WAIT-Node put {{myentity}} into the entity id field
3. choose a timeout
4. let it run

**Expected behavior**

The setting a entity with curly braces should act like it does in current state node etc.

**Screenshots**

**Example Flow**
If applicable, add an example of exported json of a flow exhibiting the issue to aid in reproduction.
`[{"id":"6cd8fb5e.a45c24","type":"inject","z":"57431f00.86456","name":"","topic":"","payload":"hallo","payloadType":"str","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":90,"y":3900,"wires":[["54139f0f.fc6ca"]]},{"id":"54139f0f.fc6ca","type":"change","z":"57431f00.86456","name":"","rules":[{"t":"set","p":"myentity","pt":"msg","to":"input_boolean.gastmodus","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":250,"y":3900,"wires":[["31f60443.2a404c","c7d2d46a.757578"]]},{"id":"31f60443.2a404c","type":"ha-wait-until","z":"57431f00.86456","name":"","server":"4d2776f1.5d8f58","outputs":2,"entityId":"{{myentity}}","property":"state","comparator":"is","value":"on","valueType":"str","timeout":"30","timeoutUnits":"seconds","entityLocation":"","entityLocationType":"none","checkCurrentState":true,"blockInputOverrides":true,"x":420,"y":3900,"wires":[["408be72d.65cd28"],["7aa3493c.1d1888"]]},{"id":"408be72d.65cd28","type":"debug","z":"57431f00.86456","name":"on","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":550,"y":3880,"wires":[]},{"id":"7aa3493c.1d1888","type":"debug","z":"57431f00.86456","name":"timed out","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":560,"y":3940,"wires":[]},{"id":"c7d2d46a.757578","type":"api-current-state","z":"57431f00.86456","name":"","server":"4d2776f1.5d8f58","version":1,"outputs":1,"halt_if":"","halt_if_type":"str","halt_if_compare":"is","override_topic":false,"entity_id":"{{myentity}}","state_type":"str","state_location":"payload","override_payload":"msg","entity_location":"data","override_data":"msg","blockInputOverrides":false,"x":350,"y":3980,"wires":[["43d2a822.00a1e8"]]},{"id":"43d2a822.00a1e8","type":"debug","z":"57431f00.86456","name":"entity state","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":570,"y":3980,"wires":[]},{"id":"4d2776f1.5d8f58","type":"server","z":"","name":"Home Assistant","legacy":false,"hassio":true,"rejectUnauthorizedCerts":true,"ha_boolean":"y|yes|true|on|home|open","connectionDelay":true}]`

**Environment (please complete the following information):**

- Node Red Version: v1.0.3
- Node.js Version: ??
- NR Home Assistant Plugin Version: v.6.0.1
- Is Node Red running in Docker: hassio

**Other (please complete the following information):**

- Have you searched previous issues for duplicates?:

**Additional context**

**Comment by zachowj** [comment]
Not really a bug as that feature is not currently available for the wait-until node.

You can currently pass the entity id as `msg.payload.entityId`

<https://zachowj.github.io/node-red-contrib-home-assistant-websocket/node/wait-until.html#payload>

**Comment by sti0** [comment]
Than it's a feature request :-)

I thought all nodes should handle this feature.
