### ISSUE TITLE
Ignore SSL

### ISSUE THREAD

**Issue by bjohnson8949** [zachowj/node-red-contrib-home-assistant-websocket#19]
I am having issues with being able to use a certificate signed by my root certificate. I have tested and I can curl https:\\homeassitanturl:8123\ from node-red server without a error but soon as I add it to node-red it fails. 

I found in node-red-contrib-home-assistant-websocket/lib/ha-websocket.js
Line 242: 
`const socket = new WebSocket(url); `

I had wondered about a config option to do this:

```
const socket = new WebSocket(url, {
  rejectUnauthorized: false
});

```
I would love for it to recognize my root certificate but I have yet to find why it can't verify it.

**Comment by zachowj** [comment]
Let me do some research on what is all needed to be able to add TLS like the default mqtt nodes or even if it is possible to work with self-signed certs, my quick google searches say no. Might just add this in for the interim until I can find a different solution.
