### ISSUE TITLE
Support Mustache templates in History node

### ISSUE THREAD

**Issue by sti0** [zachowj/node-red-contrib-home-assistant-websocket#190]
**Is your feature request related to a problem? Please describe.**
The history node supports no mustache templates like some other nodes (current state, wait, trigger) do. It passes the mustache template as a string without any errors.
![image](https://user-images.githubusercontent.com/18382402/72329974-04c21f00-36b6-11ea-901d-2dbf854e9446.png)

**Describe the solution you'd like**
Implement it like for the wait node ( https://github.com/zachowj/node-red-contrib-home-assistant-websocket/issues/189)

**Comment by zachowj** [comment]
<https://github.com/zachowj/node-red-contrib-home-assistant-websocket/commit/94142109e1128f0a52360e2cee066d8a0660395b>
