### ISSUE TITLE
Call-service API error. Error Message: this.RED.util.parseContextStore is not a function

### ISSUE THREAD

**Issue by 127yjs** [zachowj/node-red-contrib-home-assistant-websocket#192]
![$GO0Y_39Z@(Z}A(TNVF77E1](https://user-images.githubusercontent.com/34150768/72429024-ea796580-37c9-11ea-8acb-48048cf3c257.png)

**Comment by 127yjs** [comment]
Example Flow
If applicable, add an example of exported json of a flow exhibiting the issue to aid in reproduction.
`[{"id":"42e3e858.6f2118","type":"api-call-service","z":"9a12c69e.619158","name":"关闭阳台灯 ","server":"2374780d.879908","version":1,"debugenabled":true,"service_domain":"light","service":"turn_off","entityId":"light.ketingdeng","data":"{\"entity_id\":\"light.yangtaideng\"}","dataType":"json","mergecontext":"","output_location":"","output_location_type":"none","mustacheAltTags":true,"x":790,"y":120,"wires":[[]]},{"id":"f0a0048e.3119a8","type":"inject","z":"9a12c69e.619158","name":"light.yushideng","topic":"light.yushideng","payload":"entity_id","payloadType":"flow","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":560,"y":120,"wires":[["42e3e858.6f2118"]]},{"id":"2374780d.879908","type":"server","z":"","name":"Home Assistant","legacy":false,"hassio":false,"rejectUnauthorizedCerts":true,"ha_boolean":"y|yes|true|on|home|open","connectionDelay":true,"cacheJson":true}]`

**Comment by zachowj** [comment]
You need to update Node-RED to v0.19 or newer preferably version 1.x as I don't test prior to v1 anymore.

<https://github.com/zachowj/node-red-contrib-home-assistant-websocket#prerequisites>

**Comment by 127yjs** [comment]
![1579318075(1)](https://user-images.githubusercontent.com/34150768/72657938-9fd43500-39e5-11ea-872e-01443b47ee58.jpg)

**Comment by zachowj** [comment]
The Node-RED version, not this package version.

![image](https://user-images.githubusercontent.com/37859597/72658072-cbf9a280-3960-11ea-8854-b939dae87962.png)

**Comment by 127yjs** [comment]
> Node-RED版本，而不是此程序包版本。
> 
> ![图片](https://user-images.githubusercontent.com/37859597/72658072-cbf9a280-3960-11ea-8854-b939dae87962.png)

Thank you very much. That's the question.
