### ISSUE TITLE
Feature Request - Add support for triggering entity state to state / service control types.

### ISSUE THREAD

**Issue by niemyjski** [zachowj/node-red-contrib-home-assistant-websocket#193]
_For context please reference the picture below._

I know state can be a very complex thing and this may not be possible but it would be super cool. With that said it would be nice if I could trigger the service|state|trigger node I'm physically looking at in a series so I can see it running. 

Currently today, I need to **open two tabs and trigger a light from on to off to on again to see it in my flow**. But what if I could **toggle the node like an inject node like on `Main Bedroom Lights Turned On/Off` or `Switch Turned On/Off` and it gets activated**! That would be **super useful**. I was thinking that if you defined the entity id we could trigger state based on the domain and known states (but even then this may be hard). One could even potentially use the defined conditions and set the state based on that or maybe we just define what state we want when we toggle it!

![image](https://user-images.githubusercontent.com/1020579/72614093-ff9fe280-38f6-11ea-80be-17ae8e22d757.png)

**Comment by zachowj** [comment]
This is already possible using the trigger-state node, take a look at the docs. But it has been on my todo list to expand on this feature.

**Comment by zachowj** [comment]
Feature requests are moving to the [discussion section](https://github.com/zachowj/node-red-contrib-home-assistant-websocket/discussions) on Github. If this still is a needed feature please open a new [discussion](https://github.com/zachowj/node-red-contrib-home-assistant-websocket/discussions/new) under the category "Feature Request".

Thank you for your contribution.
