### ISSUE TITLE
Feature Request - Add option to every component type to dump the full msg to debug log

### ISSUE THREAD

**Issue by niemyjski** [zachowj/node-red-contrib-home-assistant-websocket#194]
It would be super useful for debugging to dump the full outgoing msg to the debug window. I think this could be a simple checkbox or as complex of checkbox and a template so you could output a specific path.

This would really help keep the flows clean. 

**Bonus**: Allow this debug flag to be controlled from flow or global state so you could enable it at a global level and start seeing debug messages.

**Comment by zachowj** [comment]
How is this different from using a debug node attached to the output? If this is just because you don't want debug nodes around your flows I don't feel is something I want to add to this project.

If you wanted to control a set of debug nodes from a single global variable you could use a  subflow that consists of a switch statement to check the global and debug node.

**Comment by niemyjski** [comment]
I think it's a little of the first part, but I think it's generally useful to have a debug checkbox like a few other nodes I've came across. You already have a named node and so just outputting a state makes debugging it even easier and it should be all about the ease of use and developer experience. Especially when we could be setting and getting states from flow state and the debug nodes don't cover that.

**Comment by zachowj** [comment]
I try to follow the NR paradigm when adding features and new nodes but I do fail repeatedly at it. Using a debug node is standard practice for finding information about a flow. Debug output options have been added to several nodes but they are outputting information that is not available via the output of a node such as data sent to Home Assistant. 

Here are some advantages I see for using a debug node over integrating it within the HA nodes. Once you have debug nodes setup up in your flow it's one click to enable/disable them from the workspace without having to edit a node and redeploy. There's also a visual cue of what debug messages are enabled.

> Especially when we could be setting and getting states from flow state and the debug nodes don't cover that.

You can output any data from a debug node including global and flow context variables.
