### ISSUE TITLE
Feature Request - Add time-range-switch like node

### ISSUE THREAD

**Issue by niemyjski** [zachowj/node-red-contrib-home-assistant-websocket#195]
It would be super useful to have a node that is pretty much a clone of (https://flows.nodered.org/node/node-red-contrib-time-range-switch) that automatically populates lat/long based on your HA config! I don't want to be putting my lat/long in every place and this doesn't really work for HA users who are operating out of a camper :).

![image](https://user-images.githubusercontent.com/1020579/72615027-54445d00-38f9-11ea-9494-097d83835fea.png)

**Comment by zachowj** [comment]
This is already possible with the current time-range-switch node using environment variables and for people on the move you could always read in your lat and long from a config API call and pass it to the node. A guess glance at thier repo show there's a fork for this exact ability.
