### ISSUE TITLE
Feature Request - Ability to consume secrets

### ISSUE THREAD

**Issue by niemyjski** [zachowj/node-red-contrib-home-assistant-websocket#196]
I ran into a situation this week where I find myself in a spot I don't want to be in.... Specifying secrets in my node red config flow to do a service call to disarm my house. I like to share all my configs on GitHub and as a general process use secret for anything p2 related. I'd really like to have a pattern for specifying things like lat/long or codes like this in a secret and have them be resolved before a service call / logic takes place.

Is there a better way todo this without requiring code changes to this project?

![image](https://user-images.githubusercontent.com/1020579/72615192-b43b0380-38f9-11ea-9fa4-3baa2581d878.png)

**Comment by zachowj** [comment]
If your NR instance has access to your HA secrets file all you have to do it is read the file in parse the data and save it in the global scope. If it doesn't have access to the file I am unaware of anything that can be done.
