### ISSUE TITLE
Feature Request - Ability to compare If State without converting State Type

### ISSUE THREAD

**Issue by niemyjski** [zachowj/node-red-contrib-home-assistant-websocket#197]
NOTE: I've reviewed the code and had to do this in previous versions (not sure if it's changed but it's my understanding that it hasn't).

I like to work with boolean values and not string for comparison (to me it's more logical and better to reason about across entity types). So I started converting my code to use the If State is a bool but found out that comparison doesn't work unless I set the State Type to a boolean which converts the state type and causes havoc on the remaining series (as it's now getting a boolean instead of a string or object value.

![image](https://user-images.githubusercontent.com/1020579/72617607-f581e200-38fe-11ea-9638-fbe06bfb561b.png)

Looking at https://github.com/zachowj/node-red-contrib-home-assistant-websocket/blob/dev/nodes/current-state/current-state.js#L113-L122 and https://github.com/zachowj/node-red-contrib-home-assistant-websocket/blob/8f25ef61c14972cdea61f93ad5f631cf47a64ae1/lib/base-node.js#L338-L340

It appears that the state type isn't converted to a boolean if selected but does happen in other comparisons. **I don't wish to change the state type just do the if logic** and convert it based on `Boolean will be converted to true based on if the string is equal by default to (y|yes|true|on|home|open). Original value stored in msg.data.original_state`

Also, what if the incoming state is an object? This control doesn't handle it and should probably error out instead of trying to convert it.

**Comment by zachowj** [comment]
> It appears that the state type isn't converted to a boolean if selected but does happen in other comparisons.

So I can attempt to alleviate further confusion for users where did the assumption that changing the if state value type to boolean would convert it based on state value? Or is it that it doesn't say it will use javascript non–strict comparison?

> unless I set the State Type to a boolean which converts the state type and causes havoc on the remaining series

You don't lose the actual state value is as it is just moved and still can be referenced at any point in your flow.


> Also, what if the incoming state is an object? This control doesn't handle it and should probably error out instead of trying to convert it.

As far as my understanding goes Home Assistant states are always going to be strings. Even states that are numbers or booleans are converted and stored as strings.

**Comment by zachowj** [comment]
Feature requests are moving to the [discussion section](https://github.com/zachowj/node-red-contrib-home-assistant-websocket/discussions) on Github. If this still is a needed feature please open a new [discussion](https://github.com/zachowj/node-red-contrib-home-assistant-websocket/discussions/new) under the category "Feature Request".

Thank you for your contribution.
