### ISSUE TITLE
Feature Request - Expand string to boolean conversions for all entity state types.

### ISSUE THREAD

**Issue by niemyjski** [zachowj/node-red-contrib-home-assistant-websocket#198]
It would be super nice if the state node and other nodes covered all the default known states and converted them to a boolean value.

> Convert the state of the entity to the selected type. Boolean will be converted to true based on if the string is equal by default to (y|yes|true|on|home|open). Original value stored in msg.data.original_state

See here for a pretty good list of all state constants:
https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/const.py#L198-L225

I think maybe we sync this list with what is on toggle state for HA. like `locked`, etc.

**Comment by zachowj** [comment]
`locked` is probably one of few left off that list that could be considered black and white. I made this list customizable for this exact reason so each user could tailor it to their needs. 

If you didn't notice it is editable from the server config node.

**Comment by niemyjski** [comment]
I know it's editable but I feel we should be as complete as possible so every user can benefit from it. I can try and submit a pr if you agree. You think lock is the only one? I would have considered `locked`, `playing` maybe arming (this one is a bit more tricky).

**Comment by zachowj** [comment]
Looking at the base media player component it has 5 different states: `STATE_IDLE, STATE_OFF, STATE_ON, STATE_PAUSED, STATE_PLAYING`.

`on` is already on the list, is the media_player on if it’s `idle`? If you add `playing` where does `paused` fit in? 

I think the media player states are very ambiguous so I think to leave it up to the end-user for their use case on what should be `true` is a better option then defining something at all.

`STATE_LOCKED` is definitely one I think could be added.

**Comment by niemyjski** [comment]
bump
