### ISSUE TITLE
Unrecoverable crash with bad server URL

### ISSUE THREAD

**Issue by Slyke** [zachowj/node-red-contrib-home-assistant-websocket#199]
**Describe the bug**
Unrecoverable crash with bad server URL if protocol is not included.

**To Reproduce**
1. Add a server to the Home Assistant 'get_entities' object.
2. Add 'localhost:8123' as the server.
3. Inject some flow into it and deploy.

**Expected behavior**
NodeRed to report an error to fix.

**Environment (please complete the following information):**

- Node Red Version: v1.0.3
- Node.js Version: v10.18.0
- NR Home Assistant Plugin Version: 0.19.3 
- Is Node Red running in Docker: Docker

```
17 Jan 03:34:44 - Error: Invalid URL: wslhost:8123/api/websocket
    at initAsClient (/data/node_modules/ws/lib/websocket.js:484:11)
    at new WebSocket (/data/node_modules/ws/lib/websocket.js:72:7)
    at connect (/data/node_modules/node-red-contrib-home-assistant-websocket/lib/ha-websocket.js:352:28)
    at Timeout.setTimeout [as _onTimeout] (/data/node_modules/node-red-contrib-home-assistant-websocket/lib/ha-websocket.js:416:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-red-docker@1.0.3 start: `node $NODE_OPTIONS node_modules/node-red/red.js $FLOWS "--userDir" "/data"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-red-docker@1.0.3 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-01-17T03_34_44_716Z-debug.log
```

- Have you searched previous issues for duplicates?:
I initially reported this bug on the NodeRed Github: https://github.com/node-red/node-red/issues/2427

**Additional context**
In order to get NodeRed running again, I had to edit the actual flow.json file in vim, and remove the offending server entry. Docker kept restarting it otherwise.

**Comment by zachowj** [comment]
<https://github.com/zachowj/node-red-contrib-home-assistant-websocket/commit/2ef21668529ed69b0e7c1b02cecff14fe2c5922e>
