### ISSUE TITLE
Feature Request - Ignore `unknown` state when Node-RED + HA start up

### ISSUE THREAD

**Issue by aav7fl** [zachowj/node-red-contrib-home-assistant-websocket#202]
## Is your feature request related to a problem? Please describe.

I'm running Home Assistant (`homeassistant/home-assistant:0.105.2`) and Node-RED (`nodered/node-red:latest`) in Docker (along with another dozen or so containers). 

Pretty reliably, when I restart my host system, `Node-RED` and `Home Assistant` will start back up in docker roughly around the same time. Right now it looks like `Node-RED` gets kicked off last but finishes starting before `Home Assistant`. So when the web socket connection connects to `Home Assistant` (because HA hasn't finished starting) the _very first_ response that HA returns to `Node-RED` returns a state of `unknown` until HA finishes initializing. 

This _only_ happens when the host system starts because HA is only in an unknown state for a short time during initialization (along with the rest of my containers), but it's long enough to set off the `changes state` option in `Node-RED`.

Since I have a few flows that are written like `isState=true/else`, the `unknown` state always follows the `else` flow and I end up with a bunch of weirdly timed automations. 

## Describe the solution you'd like

- Add a checkbox option for the Node-RED HA Server Config to ignore `unknown` 
-or- 
- Add a checkbox option to the `state nodes` to ignore `unknown`.

## Describe alternatives you've considered

My alternative for the time being is setting a `Switch Node` after every `HA Node` to ignore all input of `unknown`. It's an _ok_ solution, but it gets repeated everywhere to help guard against the `unknown` starting state.

I seem to recall there _used to be_ `haltIf`, but since that isn't here anymore I can't really add it to each node.

## Additional context

I'm using `Docker Compose v3.6`. After v2, you can no longer wait for another container to _finish_, but instead you can only set it to wait until another container _starts_ by using [`depends_on`](https://docs.docker.com/compose/compose-file#depends_on). It's kinda lame, but I have `node_red` set to `depends_on` `homeassistant`.

**Comment by zachowj** [comment]
Another solution is to use a trigger: state node as described in #187.

**Comment by aav7fl** [comment]
Thanks! I'll check out this idea soon!
