### ISSUE TITLE
Hass.io -> Home Assistant

### ISSUE THREAD

**Issue by frenck** [zachowj/node-red-contrib-home-assistant-websocket#204]
**Describe the bug**

Hass.io is now Home Assistant.
What previously was Home Assistant, is now Home Assistant Core.

The node should be updated to reflect that.

New internal URL to reach Home Assistant Core:

`http://hassio/homeassistant` -> `http://supervisor/core`

Since this URL might be stored in the user's flow. We should check which one is used by the user. Ideally, we should update the URL, or at least, detect them both as a Home Assistant (previously Hass.io) user.

Hass.io does not exist as a term anymore. I think the current setting toggle "I use Hass.io" should be changed and reversed.

E.g., "I use Home Assistant Core" should open up all settings, while not checked should be limited & automated.

Furthermore, the authentication against the supervisor changed.

The environment variable `HASSIO_TOKEN` became `SUPERVISOR_TOKEN`.

Currently, the Home Assistant Supervisor implements backward compatibility for a while, but that will be removed in the future. Hence, right now, everything works, but it should be migrated.

**Comment by zachowj** [comment]
https://github.com/zachowj/node-red-contrib-home-assistant-websocket/commit/b0df6d50407d856d49c10e08b5f59f83162abf87

**Comment by frenck** [comment]
Awesome! 👍 

Thanks!
