### ISSUE TITLE
Output only on state change for trigger node

### ISSUE THREAD

**Issue by sti0** [zachowj/node-red-contrib-home-assistant-websocket#205]
**Is your feature request related to a problem? Please describe.**
I need to ignore unavailable states (unavailable -> off/on or on/off -> unavailable). Because of this I use the trigger node instead the event node.

The trigger node outputs on every update. There is no option like at the event node( Output only on state change).

**Describe the solution you'd like**
Add the option "Output only on state change"

**Describe alternatives you've considered**

**Additional context**

**Comment by zachowj** [comment]
This can be accomplished using another constraint.

![image](https://user-images.githubusercontent.com/37859597/74346753-e575ea80-4d64-11ea-9d07-f9555c2b3ae2.png)

**Comment by sti0** [comment]
That's quite simple. Thank you.
