### ISSUE TITLE
template node does not work correctly with person

### ISSUE THREAD

**Issue by ciB89** [zachowj/node-red-contrib-home-assistant-websocket#208]
**Describe the bug**
I found a bug in the ‘get template’ node:

`{{ is_state("person.bob", "home") }}` returns `True` in the template editor in Home Assistant, but when I use the ‘get template’ node it returns `False` instead of `True`. I tested it with other persons too and it’s the same.

**To Reproduce**

Create a person with device tracker in HA. Create a 'get template' node in node-red and enter` { is_state("person.X", "home") }}` and output to debug node and compare to actual results from template editor.

**Expected behavior**
`{ is_state("person.bob", "home") }`} should return `True` when the person is home.

**Screenshots**

**Example Flow**

**Environment (please complete the following information):**

- NR Home Assistant Plugin Version: 6.1.0 
- Is Node Red running in Docker: hassio

**Other (please complete the following information):**

- Have you searched previous issues for duplicates?:
yes

**Additional context**

**Comment by zachowj** [comment]
This is working as expected for me. The template node does nothing special it takes the string entered passes it to HA and returns the direct value that HA responded with.

**Comment by ciB89** [comment]
It works with the device tracker and the mac of the phone, but as soon I use the person it's not working anymore as expected (at least for me).

**Comment by zachowj** [comment]
What do these three flows output?

![image](https://user-images.githubusercontent.com/37859597/75313954-4399d780-5813-11ea-93fe-dec9df1f8710.png)

```
[{"id":"b0acb69.9238f48","type":"inject","z":"56b1c979.b2c618","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":252,"y":512,"wires":[["3583af17.84d1c"]]},{"id":"e90d35bf.842b58","type":"inject","z":"56b1c979.b2c618","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":248,"y":560,"wires":[["57d3ef6c.50ed1"]]},{"id":"57d3ef6c.50ed1","type":"api-render-template","z":"56b1c979.b2c618","name":"","template":"{{ is_state('person.jason', 'home')}}","resultsLocation":"payload","resultsLocationType":"msg","templateLocation":"template","templateLocationType":"msg","x":518,"y":560,"wires":[["28ce1896.140578"]]},{"id":"3583af17.84d1c","type":"ha-api","z":"56b1c979.b2c618","name":"","debugenabled":false,"protocol":"http","method":"post","path":"template","data":"{\t   \"template\": \"{{ is_state('person.jason', 'home')}}\"\t}","dataType":"jsonata","location":"payload","locationType":"msg","responseType":"json","x":398,"y":512,"wires":[["28ce1896.140578"]]},{"id":"28ce1896.140578","type":"debug","z":"56b1c979.b2c618","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":588,"y":512,"wires":[]},{"id":"5447b292.bfcfbc","type":"inject","z":"56b1c979.b2c618","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":248,"y":464,"wires":[["98b4d5c8.e1ce58"]]},{"id":"98b4d5c8.e1ce58","type":"api-current-state","z":"56b1c979.b2c618","name":"","version":1,"outputs":1,"halt_if":"","halt_if_type":"str","halt_if_compare":"is","override_topic":false,"entity_id":"person.jason","state_type":"habool","state_location":"payload","override_payload":"msg","entity_location":"","override_data":"none","blockInputOverrides":false,"x":468,"y":464,"wires":[["28ce1896.140578"]]}]
```

**Comment by ciB89** [comment]
So I found my mistake; I was using a 'get template'-node somewhen earlier in the flow which then overrode the msg.template; my template I was asking for was never rendered. The weird thing though is that when I entered a different template (the one for the device_tracker) it still rendered the template for the latest 'get template'-node and did not take the msg.template as the template input for whatever reason.
