### ISSUE TITLE
Wait Until node is stuck on waiting

### ISSUE THREAD

**Issue by SentryMax** [zachowj/node-red-contrib-home-assistant-websocket#211]
Wait Until node configured to check whether the state of a input boolean is on, after the last update it is stuck on waiting while the input boolean is on and, only send payload if the boolean is turn off and then on again and, after that it gets stuck on waiting again. Timeout is blank, Entity ID is set to Exact and Check against current state is checked

**Comment by zachowj** [comment]
Please fill out the issue template information and make sure you're using the latest version 0.21.3
