### ISSUE TITLE
Node Red still broken after HA update (0.106.1)

### ISSUE THREAD

**Issue by wiggitamoo** [zachowj/node-red-contrib-home-assistant-websocket#212]
# Problem/Motivation

Ever since the 0.105.2 upgrade, my Node-Red has been stuck in a connecting state. 
I keep seeing `[info] [server:Home Assistant] WebSocket Connecting http://supervisor/core` in the node-red logs.

Before the upgrade, everything was working. I have seen other users experiencing problems, but I haven't seen a fix that works for me yet.

## Expected behavior

Node-Red should connect to Home Assistant when checking the checkbox that says "I use the Home Assistant Add-On". 

## Actual behavior

Node-Red stays in a 'connecting' state.
![image](https://user-images.githubusercontent.com/1783757/75499752-fcd5ea00-5998-11ea-8edd-647b56af523c.png)

## Steps to reproduce

Upgrade to 
Home Assistant 0.106.0
Node-Red 6.1.1
Supervisor: 201
HassOS 3.11

**Comment by zachowj** [comment]
Try and see if this solves your issue?

https://github.com/zachowj/node-red-contrib-home-assistant-websocket/issues/209#issuecomment-592392331

**Comment by wiggitamoo** [comment]
That did not, but it helped me fin my problem. For some reason, the Mosquitto client in node-red wasn't using ssh anymore. Checking the box to allow this again fixed my problem.
