### ISSUE TITLE
Add option to update existing sensor if it already exists

### ISSUE THREAD

**Issue by rebmemer** [zachowj/node-red-contrib-home-assistant-websocket#213]
**Is your feature request related to a problem? Please describe.**
For my example, I intend to pass "events" from several flows that manage home alerts, plex updates and other things.  I'm re-using the "sensor" node but currently, although the node is identical in each flow it creates a secondary node with a number appended such as;

sensor.events_feed
sensor.events_feed_2

Because of the way the sensor is created after the node connects to HA, I can't predict which flow will create it first so without splitting all of my notifications into two subsets (such as events_feed_plex and events_feed_home_notif (etc).  It'd be easier to just have some sort of "does it already exist" check.

I've read through the documentation already but appreciate I may have misunderstood some of the existing functionality, so if this exists ...my apologies in advance :)

**Describe the solution you'd like**
Checkbox to "update existing sensor", if not selected - the default behaviour of creating new sensors with id's appended to the end.

If the checkbox is selected, check to see if the sensor exists already - if so, just update it's state.

**Describe alternatives you've considered**
Looked at adding a function to check to see if the sensor exists before attempting to update it, but this will result in a lot of additional node/sub-flow duplication across several higher level nodes.

**Additional context**

**Comment by zachowj** [comment]
A sensor node is a one to one relationship to a sensor in HA because it uses the nodes id as it HA reference. If you need to update a sensor from multiple locations in NR use a link node.
