### ISSUE TITLE
Feature request: add option "is between" to list of options for wait_until node

### ISSUE THREAD

**Issue by recklessnl** [zachowj/node-red-contrib-home-assistant-websocket#214]
**Is your feature request related to a problem? Please describe.**
Similarly to what you can use in the switch node, it would be great to use the ``is between`` option to have the ``wait_until`` node wait for values in between whatever values you put in. For example: wait until temperature is between 70 and 71 degrees (rather than an exact, perfect integer number that with temperatures you may very well not hit).

**Describe the solution you'd like**
See above.

**Describe alternatives you've considered**
I usually use the switch node in a roundabout way to achieve this.

**Comment by zachowj** [comment]
Adding `between` to all conditionals is somewhere on my list but this can currently be done in most places using JSONata.

`$number($entity().state) > 70 and $number(entity().state) < 71`

**Comment by recklessnl** [comment]
That's a smart solution for sure, but obviously would be easier for most if it was baked in the nodes already. Looking forward to seeing it in an update in the future.

**Comment by zachowj** [comment]
Feature requests are moving to the [discussion section](https://github.com/zachowj/node-red-contrib-home-assistant-websocket/discussions) on Github. If this still is a needed feature please open a new [discussion](https://github.com/zachowj/node-red-contrib-home-assistant-websocket/discussions/new) under the category "Feature Request".

Thank you for your contribution.
