### ISSUE TITLE
Much longer time before HA becomes available after upgrade

### ISSUE THREAD

**Issue by ahartman** [zachowj/node-red-contrib-home-assistant-websocket#215]
I recently upgraded to Node-Red 1.0.4 and your plugin 0.21.3 and I am since experiencing much longer times before HA becomes available in Node-Red. After each deploy or restart:
1. Several "Call-Service attempted without connection to server" messages while trying to set Tradfri and Shelly components in HA before things start behaving normally. This never happened before the upgrade.
2. I have an initialisation flow, see attached flows.json. That fired after 0,5 seconds and gets the states of a number of components in HA. I find I now have to set the firing delay from 0,5 seconds to 7 seconds or the get-entities node does not do anything at all.
 
**Environment (please complete the following information):**

- Node Red Version: 1.0.4
- Node.js Version: 10.18.1
- NR Home Assistant Plugin Version: 0.21.3
- Is Node Red running in Docker: no

Hope you can find this issue, thanks in advance
ahartman, belgium

[flows.json.txt](https://github.com/zachowj/node-red-contrib-home-assistant-websocket/files/4297209/flows.json.txt)

**Comment by zachowj** [comment]
Yes, when I changed the rebranding of hass.io to HA addon I had accidentally enabled the 5-second delay that was only supposed to be for hass.io for all.

It was already fixed here, https://github.com/zachowj/node-red-contrib-home-assistant-websocket/commit/18063a51e79abfc8875e48c41a0c93b01283df09, and I thought it had made it into a release but I guess not.  I'll get a new release pushed out today.

**Comment by ahartman** [comment]
Dear Jason,

Installed the new release, problem gone, thank you.

Met vriendelijke groeten, Kind regards, Meilleures salutations,
André Hartman
