### ISSUE TITLE
Alternate entity node to manage multiple entities

### ISSUE THREAD

**Issue by cerebrate** [zachowj/node-red-contrib-home-assistant-websocket#222]
### Is your feature request related to a problem? Please describe.

I'm using Node-RED with Home Assistant to manage the antlets (VMs/containers) running on my Antsle, using its API, and am looking at doing something similar to track docker swarm services. The trouble with this is that to use this information in Home Assistant, I really need to be able to set up one sensor per antlet/service, as most device integrations do.

At the moment, as far as I can tell, the only way to do this is to switch on the name of the antlet/service in Node-RED, and direct the messages to one entity node per name, which in addition to being a bulky kluge, does not respond automatically to configuration changes; new antlets/services won't be monitorable until and unless they're manually added to the Node-RED flow.

### Describe the solution you'd like

I'd like a variant entity node which allows sensors in HA to be created dynamically, based on a parameter (say, msg.topic) of the incoming message, and a template or prefix set in the node configuration. Such that, for example, I could set the latter to "myrmidon_antlet_", and then an arriving state/attribute message with the former set to "hass" would create the entity "sensor.myrmidon_antlet_hass" in Home Assistant.

### Describe alternatives you've considered

Apart from the abovementioned kluge, I have also considered sending the received information to HA as events and sorting it out into pseudo-entities on that end. If anything, this is even more of a kluge.

### Additional context

None that occurs.

**Comment by zachowj** [comment]
This can be accomplished using direct calls to the API of the custom component.

Example:
<https://community.home-assistant.io/t/help-merging-2-node-red-flows-in-1/154642/23?u=kermit>

Break down of the API calls:
<https://community.home-assistant.io/t/two-new-nodes-with-custom-integration-looking-for-testers/150736/7?u=kermit>

If you want a better example make a new post on the HA forums and tag me @ kermit and I'll help you with your specific use case.
