### ISSUE TITLE
v0.22.0     Flows stopped due to missing node types.      server

### ISSUE THREAD

**Issue by ianfretwell** [zachowj/node-red-contrib-home-assistant-websocket#225]
### Describe the bug

Having upgraded the component (through 'manage palette') to 0.22.0 I'm getting the error here -

Flows stopped due to missing node types.

    server

If I go to the component in the palette I can see that 'server' is greyed out unlike all the other elements (screenshot pasted below although I'm not sure I've done this correctly).

Upgraded many times in the past without issue.

### To Reproduce

1. Upgrade from 0.21.5 to 0.22.0

### Expected behavior

Clean upgrade with no issues.

### Screenshots

![image](https://user-images.githubusercontent.com/52041704/77907894-6724c780-7282-11ea-80fa-d8a62b02c0d5.png)

### Example Flow

n/a

### Environment (please complete the following information):

- Node Red Version: 1.0.4.2
- Node.js Version: [e.g. 12.16.1]
- NR Home Assistant Plugin Version: 0.22.0
- Is Node Red running in Docker: yes

### Other (please complete the following information):
Yes

### Additional context

n/a

**Comment by ianfretwell** [comment]
From the docker console 👍 

![image](https://user-images.githubusercontent.com/52041704/77908800-17df9680-7284-11ea-80ce-3aedcc63d00c.png)

**Comment by Wibias** [comment]
+

**Comment by gregg098** [comment]
I also had issues and reverted back to 0.21.5.  A lot of my nodes went to "NaN" inside of NodeRed, but others seemed to work. I was not able to capture logs.

**Comment by zachowj** [comment]
It's working with node v10 but not v12

**Comment by gregg098** [comment]
@zachowj I'm running Node Red in Docker with the latest-10 tag. I didn't do a ton of testing since I just wanted things to work again, but it seemed like the issue was just in the trigger:state nodes.

**Comment by Wibias** [comment]
Yea the "server" missing message is gone with node 10. But now almost all nodes are showing "NaN".

**Comment by Wibias** [comment]
For me the nodes "current state" and "events state" are showing "NaN".

**Comment by zachowj** [comment]
@gregg098 @Wibias Try v0.22.1 when I release it in a bit and see if that resolves any issues you're seeing. If not please create a new issue as I believe it's not related to this one.

**Comment by zaneclaes** [comment]
Yikes. What a bug. I use this package to drive the HVAC system in my house. Since it stopped parsing states, it could not turn on the heat when a switch was toggled. Good thing I programmed redundancy into the Arduino relay controller, or our pipes would have frozen and burst. 

Given that some of us use this package for mission-critical things... maybe some unit tests are in order?

**Comment by wsidl** [comment]
This is a breaking issue. Running on a vanilla RPi not in docker with other node applications requiring a newer nodejs. I cannot run this module without supporting at least nodejs v12
