### ISSUE TITLE
Input to and output from switch-type entity node

### ISSUE THREAD

**Issue by rianadon** [zachowj/node-red-contrib-home-assistant-websocket#228]
### Is your feature request related to a problem? Please describe.

I'm trying to control the output of a switch with node-red. A very simple example of how I'd like to accomplish this is below:
<img src="https://user-images.githubusercontent.com/18223213/78510582-1104c800-774b-11ea-84eb-e345f988f91b.png" height="150" />

When the `inject` node is triggered, I'd like the switch to turn off. However, it still stays on within home assistant. The two outputs of the node also don't seem to change when I toggle the switch within home assistant.

The goal of the flow is to create something very similar to Home Assistant's groups within node-red. A switch created by an `entity` node will control a set of entities. If all of the entities are off, the switch will have the state of `off`. If any entity is on, the switch will have the state of `on`. If the switch is `on` and it is then turned off, all entities will turn off. However, my flow differs from a group in that if the switch is `off` and then turned on, I do not want every entity to be turned on. Instead, I want only a few entities to be turned on.

### Describe the solution you'd like

Similar to the `binary_switch` type `entity` node, `switch` type nodes should also change their output depending the input passed in. Also, if home assistant toggles the switch, the outputs of the node should change.

### Describe alternatives you've considered

One alternative is to have no node connected to the `entity` node and then use the `events: state` node to listen to changes in the entity's output and `call service` node to change the node's state. However, I'd like a way to update the state of the entity without the outputs changing.

To put this in the context of my use case, let's say all entities are off. I turn one on. I want the state of the switch to turn on. However, I don't want the flow that says "when switch turns on many entities" to trigger because I didn't flip the switch within home assistant: the switched flipped due to a change in one of the entity's states.

The only working alternative I can think of would be to use Node-RED's MQTT blocks in addition to Home Assistant's auto-discovery of devices over MQTT. I would have one flow to create the discovery message for my switch, another to handle publishing a message to update the switch state whenever one of the entities I'm monitoring changes, and another to subscribe to the topic for monitoring the state and setting the entities accordingly. It would be great if this repository had something similar built in though since the MQTT alternative is less convenient than simply dropping an `entity` node in :slightly_smiling_face:.

### Additional context

Nope!

**Comment by fenderle** [comment]
Was wondering exactly the same thing...

**Comment by Jpsy** [comment]
Same here. 
As soon as I set an Entity node to type "Switch" it is more or less dead on its inputs and outputs.
Its state (as displayed below the graphical representation below the node) still syncs with changes of the switch state through HA, but it is not possible to change the state through the node's inputs or get state changes from the node's outputs.
I tried with a simple `"on"` as well as with a payload object of `{ "state":"on" }`.
When injecting any of these msgs, the status text of the node changes to "input" (!), but the status icon stays in the old state (on or off = filled or ring).
When I inject an input, this input is in fact channeled to the output that corresponds to the current state. But as said, the state does not actually change, and also the outputs do not return anything when the state is changed through HA.

![image](https://user-images.githubusercontent.com/1806058/81039607-d5742f80-8ea9-11ea-8657-5c18c96dd6f0.png)

`[{"id":"35e46e41.6b5db2","type":"debug","z":"e20da7d5.68a9a8","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","x":510,"y":100,"wires":[]},{"id":"d1a48e0c.c8b43","type":"ha-entity","z":"e20da7d5.68a9a8","name":"Switch \"a\"","server":"cb38d2a3.10198","version":1,"debugenabled":false,"outputs":2,"entityType":"switch","config":[{"property":"name","value":"a"},{"property":"device_class","value":""},{"property":"icon","value":""},{"property":"unit_of_measurement","value":""}],"state":"payload","stateType":"msg","attributes":[],"resend":true,"outputLocation":"","outputLocationType":"none","inputOverride":"allow","x":350,"y":120,"wires":[["35e46e41.6b5db2"],["d8e00b79.dd3da8"]]},{"id":"934098ee.6cd4c8","type":"inject","z":"e20da7d5.68a9a8","name":"","topic":"","payload":"{\"state\":\"on\"}","payloadType":"json","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":170,"y":140,"wires":[["d1a48e0c.c8b43"]]},{"id":"f77baf6b.47b6","type":"inject","z":"e20da7d5.68a9a8","name":"","topic":"","payload":"\"on\"","payloadType":"json","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":150,"y":100,"wires":[["d1a48e0c.c8b43"]]},{"id":"d8e00b79.dd3da8","type":"debug","z":"e20da7d5.68a9a8","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","x":510,"y":140,"wires":[]},{"id":"cb38d2a3.10198","type":"server","z":"","name":"Home Assistant"}]`

**Comment by thehaxxa** [comment]
This is an issue I have experienced as well. I am calling a service to turn on/off the switch but its not ideal. It would be nice if this feature was coupled to its inputs/outputs.

**Comment by keniji** [comment]
I also encountered this issue, now under version 0.24.1 and I am still unable to find a way to trigger the switch-type node in NR... Hoping anyone will fix it... thanks o_0

**Comment by michalk-k** [comment]
I have to join the party.
But because current behaviour is inconsistent with other modes offered by the node, in my opinion the issue should be raised as a bug.

**Comment by Swiftnesses** [comment]
Same issue here... I expected the node itself to output upon switch change, but I need to add another node to do that...

Am I misunderstanding the issue, or how to use it?

<img width="405" alt="Screenshot 2021-01-06 at 10 08 10" src="https://user-images.githubusercontent.com/1001877/103756908-ea402e80-5007-11eb-8e01-167645f14b73.png">

**Comment by Jpsy** [comment]
Heureka!!! 👍 ❤️ 🥂

**Comment by ljmerza** [comment]
for anyone looking for the actual solution the input to a switch entity needs to be:

```
return {
    enable: boolean
};
```

**Comment by etherfi** [comment]
I appreciate the commit... But I still can't get it to respond to anything. Working example please?

**Comment by michalk-k** [comment]
> I appreciate the commit... But I still can't get it to respond to anything. Working example please?

AFAIK it doesn't respond do anything. It works like an gateway, which works in regard to a switch state. 
If you want to control the switch state, you have to use service node

I agree it's not consistent with other nodes from the family, but I don't think there is anything we can do in that matter.
