### ISSUE TITLE
Event data is cut off

### ISSUE THREAD

**Issue by inputd** [zachowj/node-red-contrib-home-assistant-websocket#229]
### Describe the bug

When listening for event data, the full event data is not displayed. In my case, I'm listening to mobile_app_notification_action.

### To Reproduce

1. Create an "Events:all" node, hooked into a "debug:all msg data" node
2. Fire a notification that's actionable
3. Respond to the action on your android device

### Expected behavior

If you listen to the event on Home Assistant, you see:

{
    "event_type": "mobile_app_notification_action",
    "data": {
        "message": "Something happened at home!",
        "action_1_title": "Title",
        "action_1_key": "alarm",
        "action": "alarm"
    },
    "origin": "REMOTE",
    "time_fired": "2020-04-06T20:01:25.856135+00:00",
    "context": {
        "id": "verylongidstringgoeshere",
        "parent_id": null,
        "user_id": "verylonguserIDgoeshere"
    }
}

### Screenshots

Node-red's debug cuts off prior to origin and the other data that proceeds it:

object
event_type: "mobile_app_notification_action"
topic: "mobile_app_notification_action"
payload: object
event_type: "mobile_app_notification_action"
event: object
message: "Something happened at home!"
action_1_title: "Title"
action_1_key: "alarm"
action: "alarm"
_msgid: "3e0def51.4ade9"

### Example Flow

```
Sorry, can't figure out how to export without also exporting my HA system data
```

### Environment (please complete the following information):

- HASS.io, node-red plugin 6.1.4

### Other (please complete the following information):

- Have you searched previous issues for duplicates?: Yes

**Comment by zachowj** [comment]
It's not really cut off, originally it was just never added to the output of the node. The output is a custom object built from the event object sent from HA. The docs should probably be updated to reference this.

https://github.com/zachowj/node-red-contrib-home-assistant-websocket/blob/338dd9b9438dc196e69357b1d7f8d70e48f1c541/nodes/events-all/events-all.js#L43-L47

Is this data that you would like to see in the events: all node output?

**Comment by inputd** [comment]
I can't say how useful it is in other applications/events, but the user_id field not included in this instance is the identifier that lets you automate based on who sent an actionable text.
