### ISSUE TITLE
First item from GetHistory has incorrect last_changed and last_updated dates

### ISSUE THREAD

**Issue by karlssmg** [zachowj/node-red-contrib-home-assistant-websocket#230]
### Describe the bug

The  last_changed and last_updated timestamps seems to be set to the start date of the search.
### To Reproduce
Trigger GetHistory with an Inject. Configure start date or relative time. Verify date of last_changed is same as requested start date of GetHistory

### Expected behavior

Dates should reflect actual history of node

### Screenshots

![image](https://user-images.githubusercontent.com/54910677/78600890-139f1480-7854-11ea-9b46-8161c2db30e3.png)

### Example Flow

```
export goes here
[{"id":"87d5f6b8.6fede8","type":"tab","label":"test","disabled":false,"info":""},{"id":"ef3050eb.c69d6","type":"debug","z":"87d5f6b8.6fede8","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":730,"y":520,"wires":[]},{"id":"94144d30.1103c","type":"api-get-history","z":"87d5f6b8.6fede8","name":"Bubbelpumpen","server":"3b40f010.169c","startdate":"2020-04-06T19:38:11+00:00","enddate":"2020-05-06T18:30:11+00:00","entityid":"sensor.bubbeltemp_temperature","entityidtype":"is","useRelativeTime":false,"relativeTime":"1 hour","flatten":true,"output_type":"split","output_location_type":"msg","output_location":"payload","x":500,"y":520,"wires":[["ef3050eb.c69d6"]]},{"id":"5535c2b4.62764c","type":"inject","z":"87d5f6b8.6fede8","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":180,"y":520,"wires":[["94144d30.1103c"]]},{"id":"3b40f010.169c","type":"server","z":"","name":"Home Assistant"}]
```

### Environment (please complete the following information):

- Node Red Version: [e.g. 1.0.4] 1.0.4
- Node.js Version: [e.g. 12.16.1] unknown
- NR Home Assistant Plugin Version: [e.g. 0.21.3] 6.1.4
- Is Node Red running in Docker: [e.g. yes/no/HA addon] HA Addon

### Other (please complete the following information):

- Have you searched previous issues for duplicates?:
Yes

**Comment by zachowj** [comment]
The get-history does no data manipulation other than filtering the array. It just dumps whatever it receives from HA to the output of the node.

This can be confirmed using the API node
```
[{"id":"aa6ad704.8793c8","type":"ha-api","z":"ffbd7f06.4a014","name":"","debugenabled":true,"protocol":"http","method":"get","path":"history/period/2020-04-06T19:38:11+00:00","data":"{\"filter_entity_id\":\"light.night_light\",\"end_time\":\"2020-04-06T19:38:11+00:00\"}","dataType":"json","location":"payload","locationType":"msg","responseType":"json","x":386,"y":912,"wires":[["b2a0b792.5efa88"]]},{"id":"d1c290d0.b1991","type":"inject","z":"ffbd7f06.4a014","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":224,"y":912,"wires":[["aa6ad704.8793c8"]]},{"id":"b2a0b792.5efa88","type":"debug","z":"ffbd7f06.4a014","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":550,"y":912,"wires":[]}]
```

**Comment by karlssmg** [comment]
Ah! Okay? Could it be a bug in the API on the HA side then? I will look into that. 
Thanks!

**Comment by karlssmg** [comment]
Verified to be an incorrect behavior in the HA API. Issue raised with HA project.
