### ISSUE TITLE
History Node also providing attribute change not only state change

### ISSUE THREAD

**Issue by ServusNL** [zachowj/node-red-contrib-home-assistant-websocket#231]
### Is your feature request related to a problem? Please describe.

Request. Currently the History node only provides history of a node when the state changed.
### Describe the solution you'd like

I would like to also fetch data from attribute change.

**Example:** A RGB Lightstrip which changes color. Currently the color changes are not reflected in the history only when the on off state is changed. In that case RGB is part of the response.

### Describe alternatives you've considered

Storing attribute changes in a database. Attribute / color changes are captured by the events state node.

### Additional context
Example showing the current response of history node. In-between the on and off are allot of changes for the rgb_color.
`
[{
	"attributes": {
		"brightness": 255,
		"friendly_name": "Lightstrip",
		"hs_color": [30, 57.143],
		"rgb_color": [255, 182, 109],
		"supported_features": 17,
		"xy_color": [0.491, 0.39]
	},
	"context": {
		"id": "3e0b0356602d4cc681184e0e3b8d55c0",
		"parent_id": null,
		"user_id": "b97943c1b2904a54a325a5c41bd7929f"
	},
	"entity_id": "light.koogeek_ls1_7721d5",
	"last_changed": "2020-04-11T18:38:08.180000+00:00",
	"last_updated": "2020-04-11T18:38:08.180000+00:00",
	"state": "on"
}, {
	"attributes": {
		"friendly_name": "Lightstrip",
		"supported_features": 17
	},
	"context": {
		"id": "d8c64caf49b74fd7addf61fcdf76c8a0",
		"parent_id": null,
		"user_id": "b97943c1b2904a54a325a5c41bd7929f"
	},
	"entity_id": "light.koogeek_ls1_7721d5",
	"last_changed": "2020-04-11T18:39:50.759069+00:00",
	"last_updated": "2020-04-11T18:39:50.759069+00:00",
	"state": "off"
}, {
	"attributes": {
		"brightness": 255,
		"friendly_name": "Lightstrip",
		"hs_color": [30, 57.143],
		"rgb_color": [255, 182, 109],
		"supported_features": 17,
		"xy_color": [0.491, 0.39]
	},
	"context": {
		"id": "f317a74da2954a9db8b5254a69c20a16",
		"parent_id": null,
		"user_id": "b97943c1b2904a54a325a5c41bd7929f"
	},
	"entity_id": "light.koogeek_ls1_7721d5",
	"last_changed": "2020-04-11T18:45:19.737977+00:00",
	"last_updated": "2020-04-11T18:45:19.737977+00:00",
	"state": "on"
}, {
	"attributes": {
		"friendly_name": "Lightstrip",
		"supported_features": 17
	},
	"context": {
		"id": "7a5e126088cb4bf480813d5d3c139fc1",
		"parent_id": null,
		"user_id": null
	},
	"entity_id": "light.koogeek_ls1_7721d5",
	"last_changed": "2020-04-11T20:45:45.044603+00:00",
	"last_updated": "2020-04-11T20:45:45.044603+00:00",
	"state": "off"
}, {
	"attributes": {
		"brightness": 255,
		"friendly_name": "Lightstrip",
		"hs_color": [240, 100],
		"rgb_color": [0, 0, 255],
		"supported_features": 17,
		"xy_color": [0.136, 0.04]
	},
	"context": {
		"id": "b148dcec55624c949a04c44186503d06",
		"parent_id": null,
		"user_id": "b97943c1b2904a54a325a5c41bd7929f"
	},
	"entity_id": "light.koogeek_ls1_7721d5",
	"last_changed": "2020-04-12T11:19:24.054065+00:00",
	"last_updated": "2020-04-12T11:19:24.054065+00:00",
	"state": "on"
}, {
	"attributes": {
		"friendly_name": "Lightstrip",
		"supported_features": 17
	},
	"context": {
		"id": "9fff4404bc7245a19998cbff98c82bbd",
		"parent_id": null,
		"user_id": "3f1fe0e2492e4b45baf602574b19eee9"
	},
	"entity_id": "light.koogeek_ls1_7721d5",
	"last_changed": "2020-04-12T12:14:28.235893+00:00",
	"last_updated": "2020-04-12T12:14:28.235893+00:00",
	"state": "off"
}, {
	"attributes": {
		"brightness": 255,
		"friendly_name": "Lightstrip",
		"hs_color": [0, 100],
		"rgb_color": [255, 0, 0],
		"supported_features": 17,
		"xy_color": [0.701, 0.299]
	},
	"context": {
		"id": "6117a6d3ccf340008f8a58b1176ed8b3",
		"parent_id": null,
		"user_id": null
	},
	"entity_id": "light.koogeek_ls1_7721d5",
	"last_changed": "2020-04-12T15:24:54.073125+00:00",
	"last_updated": "2020-04-12T15:24:54.073125+00:00",
	"state": "on"
}, {
	"attributes": {
		"friendly_name": "Lightstrip",
		"supported_features": 17
	},
	"context": {
		"id": "9418b682be7e4012879e910211075530",
		"parent_id": null,
		"user_id": "3f1fe0e2492e4b45baf602574b19eee9"
	},
	"entity_id": "light.koogeek_ls1_7721d5",
	"last_changed": "2020-04-12T15:27:53.384377+00:00",
	"last_updated": "2020-04-12T15:27:53.384377+00:00",
	"state": "off"
}, {
	"attributes": {
		"brightness": 255,
		"friendly_name": "Lightstrip",
		"hs_color": [0, 100],
		"rgb_color": [255, 0, 0],
		"supported_features": 17,
		"xy_color": [0.701, 0.299]
	},
	"context": {
		"id": "314efc6270c44d689ae9302c87e815fd",
		"parent_id": null,
		"user_id": "3f1fe0e2492e4b45baf602574b19eee9"
	},
	"entity_id": "light.koogeek_ls1_7721d5",
	"last_changed": "2020-04-12T18:10:55.958136+00:00",
	"last_updated": "2020-04-12T18:10:55.958136+00:00",
	"state": "on"
}]
`

**Comment by zachowj** [comment]
The history node doesn't do any data storage it outputs only what the history component in HA contains. If you want to track an attribute of an entity with the history component I would make a template sensor of that attribute and then you can use the get-history node on that template sensor.
