### ISSUE TITLE
Feature Request: HA Device Triggers

### ISSUE THREAD

**Issue by cannfoddr** [zachowj/node-red-contrib-home-assistant-websocket#234]
### Is your feature request related to a problem? Please describe.

I have started playing with the HUE Switches now exposed by the latest HUE integration.  Based on the Automation.yaml automations created from the HA UI it looks like these are using DEVICE Triggers rather than event triggers.

### Describe the solution you'd like

It would be great if node-red had a device trigger object in addiiton to the existing event trigger object where I could select the device and the device actions that I want capture into a node red flow.

### Describe alternatives you've considered

he only option at the moment seems to be to use YAML automations inside of HA

**Comment by zachowj** [comment]
This is currently not possible.
