### ISSUE TITLE
Entity could not be found in cache

### ISSUE THREAD

**Issue by hendmele** [zachowj/node-red-contrib-home-assistant-websocket#237]
### Describe the bug

NodeRed giving error 'Entity could not be found in cache for entity_id: switch.whatever"'.
Error just happens right after deploying. If I wait for around 10 seconds, problem goes away.

It seems to be the same as issue #156 that was closed without, in my opinion, a solution. If after deploying, it takes time for the connection to happen, nodered should wait to start pulling data.
The way it is it breaks some of my automations, as the 'inject node' will trigger right after deploying, so first HA connection will failure and everything that comes next on the flow won't work.
I have to delay injection node for 10 seconds as a workaround. But is 10 seconds enough? Will it always be enough? Does it happen on restarts also? or only deploys?

A user apparently found the cause and fixed here.
https://github.com/Spartan-II-117/node-red-contrib-home-assistant-llat/issues/34
Maybe to same can be done here on websocket contrib?

### To Reproduce

Just put a injection node, some get state node, a debug message, deploy and inject data right after deploy.

### Expected behavior

Nodered to wait until connection with HA is stablished, so won't give connection errors when deploying/restarting.

### Screenshots

No need.

### Example Flow

Simple flow will replicate issue, as stated above.

### Environment (please complete the following information):

- NR Home Assistant Plugin Version 6.2.0

### Other (please complete the following information):

Yes. Issue #156, not solved.

**Comment by mhuca** [comment]
Having the same issue. 

Updated to 0.108.9 of the supervisor and the 1.0.5 of Node Red.

Are you any closer to getting a resolution?

> ### Describe the bug
> NodeRed giving error 'Entity could not be found in cache for entity_id: switch.whatever"'.
> Error just happens right after deploying. If I wait for around 10 seconds, problem goes away.
> 
> It seems to be the same as issue #156 that was closed without, in my opinion, a solution. If after deploying, it takes time for the connection to happen, nodered should wait to start pulling data.
> The way it is it breaks some of my automations, as the 'inject node' will trigger right after deploying, so first HA connection will failure and everything that comes next on the flow won't work.
> I have to delay injection node for 10 seconds as a workaround. But is 10 seconds enough? Will it always be enough? Does it happen on restarts also? or only deploys?
> 
> A user apparently found the cause and fixed here.
> [Spartan-II-117/node-red-contrib-home-assistant-llat#34](https://github.com/Spartan-II-117/node-red-contrib-home-assistant-llat/issues/34)
> Maybe to same can be done here on websocket contrib?
> 
> ### To Reproduce
> Just put a injection node, some get state node, a debug message, deploy and inject data right after deploy.
> 
> ### Expected behavior
> Nodered to wait until connection with HA is stablished, so won't give connection errors when deploying/restarting.
> 
> ### Screenshots
> No need.
> 
> ### Example Flow
> Simple flow will replicate issue, as stated above.
> 
> ### Environment (please complete the following information):
> * NR Home Assistant Plugin Version 6.2.0
> 
> ### Other (please complete the following information):
> Yes. Issue #156, not solved.
> 
> ### Additional context

**Comment by hrmele** [comment]
@mhuca not really. the only workaround is delaying every start node.
