### ISSUE TITLE
Allow manually setting Sensor node Unique ID

### ISSUE THREAD

**Issue by carlos-sarmiento** [zachowj/node-red-contrib-home-assistant-websocket#240]
### Is your feature request related to a problem? Please describe.
I have a set of flows (one per person) that I use to automatically unlock doors in my house depending on who is arriving. I'd like to encapsulate them into subflows so I can keep a single "subflow" and then add parameters as environmental variables. Part of these flows use Sensor Node's to create entities on HA, which means that based on the current implementation cannot be used on a Subflow.

### Describe the solution you'd like
I'd like to be able to manually set a unique_id on the sensor node that would then be transferred to Home Assistant. That way I could add parametrized Sensor node's to subflows and reuse my logic without having the entities in HA recreated every time node-red restart.

### Describe alternatives you've considered
Right now I'm running the subflows with an output node on which I add the sensor (so it is outside the subflow). But it is limiting (using more than one sensor node inside the subflow would mean adding a switch statement and redirecting stuff to different sensor nodes).

**Comment by zachowj** [comment]
I am currently not going to do anything with the exposed event and entity nodes until I have some time to refactor the system to use config nodes instead of relying on the node id of the given node to register itself with HA.

You can accomplish this now using the API node from within a subflow and sending the correct data to HA. If this is something you want to try let me know I can do a quick write up for it.

**Comment by carlos-sarmiento** [comment]
@zachowj I'm willing to try doing that.

**Comment by zachowj** [comment]
Here's a post I did a while back which show's how to register an entity and then update it using the API node.

https://community.home-assistant.io/t/help-merging-2-node-red-flows-in-1/154642/23?u=kermit

**Comment by zachowj** [comment]
Feature requests are moving to the [discussion section](https://github.com/zachowj/node-red-contrib-home-assistant-websocket/discussions) on Github. If this still is a needed feature please open a new [discussion](https://github.com/zachowj/node-red-contrib-home-assistant-websocket/discussions/new) under the category "Feature Request".

Thank you for your contribution.
