### ISSUE TITLE
MQTT Discovered entities not showing up in autocomplete

### ISSUE THREAD

**Issue by Villhellm** [zachowj/node-red-contrib-home-assistant-websocket#242]
### Describe the bug

Entities that are created via MQTT discovery are not showing up in autocomplete results. They show up in the homeAssistant.states object, but not autocomplete. It looks like this might actually be an issue with HA not reporting the entities, but I'm not sure I'm interpreting the common.js logic for getting autocomplete results correctly.

My cache autocomplete results option is unchecked, and I have cleared cache several times. If I add entities through other means and restart HA they show up in NR autocomplete, but the MQTT discovered devices still do not (when I added my 2 discovered lights to a HA light group and restarted, the light group entity shows up in autocomplete).

### To Reproduce
Use HA MQTT discovery, check autocomplete results for the entities.

### Expected behavior
Entities show up in autocomplete if they are in homeAssistant.states

### Environment (please complete the following information):

- Node Red Version: 1.0.3
- Node.js Version: [e.g. 12.16.1]
- NR Home Assistant Plugin Version: 0.22.3
- Is Node Red running in Docker: yes

### Other (please complete the following information):

- Have you searched previous issues for duplicates?: yes

### Additional context
I'm using zwave2mqtt discovery specifically. Not sure why this would matter, but just in case.

**Comment by zachowj** [comment]
> They show up in the homeAssistant.states object,

If you mean they are present is the global context object in NR then NR is getting the info from HA. The global context and autocomplete list pull for the same data source so if they show in one they will show in the other. I would guess this is still a caching issue of some sort.

You could try load the autocomplete URL and doing a hard refresh to see if that will show the entities.

`http://IP:1880/homeassistant/<SERVER NODE ID>/entities`

**Comment by Villhellm** [comment]
The entities weren't showing up with with a cleared cache or in a private browser window. Loading the autocomplete URL showed a list that did not have the entities either (in incognito).

The only thing that made them show up was a full restart of Node Red. It's just strange that *other* entities would show up without restarting Node Red, just not the mqtt discovered entities. I haven't had any issues with autocomplete in the year that I've been using these nodes

**Comment by zachowj** [comment]
I looked into this a bit more and found that when entities are removed from the entities list they are not removed from the global context object. So this might explain why they show up in the global context but not the autocomplete. I don't use any MQTT auto-discovered entities so I'll have to set up something to test it but this at least explains why you see it in one place and not the other.

**Comment by Villhellm** [comment]
Closing this as neither of us can currently reproduce it. I'll keep an eye out the next time I add a zwave node.
