### ISSUE TITLE
HomeAssistant 0.111 firing state_changed events during startup, affects state listeners

### ISSUE THREAD

**Issue by ronaldheft** [zachowj/node-red-contrib-home-assistant-websocket#246]
### Describe the bug

Since HomeAssistant 0.111, the WebSocket API now initializes first during startup. This allows integrations that initialize their state during startup to sometimes fire invalid `state_changed` events (i.e. a light was on before HomeAssistant restarted, the integration initializes as off, then throws a new `state_changed` event to on when the integration starts up).

Previously, these events never affected Node-RED, as the WebSocket API was not started until all integrations initialized. Now, flows can fire during startup for event listeners being mis-triggered by startup.

### To Reproduce

1. Setup a `state_changed` listener for an integration with a debug node.
2. Restart HomeAssistant.
3. Note `state_changed` events being thrown during startup, even with output on connect disabled.

### Expected behavior

`state_changed` events (and possibly all events?) should be ignored until HomeAssistant is finished starting up.

### Environment (please complete the following information):

- Node Red Version: 1.0.6
- Node.js Version: running in Docker
- NR Home Assistant Plugin Version: 0.22.5
- Is Node Red running in Docker: yes

### Other (please complete the following information):

- Have you searched previous issues for duplicates?: Yes

### Additional context

Also logged a bug against HomeAssistant core (since this was a breaking change on their end): https://github.com/home-assistant/core/issues/36763

**Comment by ronaldheft** [comment]
Guidance from the HA core team [recommends the following be changed for any service connecting via WebSocket](https://github.com/home-assistant/core/issues/36763#issuecomment-643807473):

> Fetch the config of Home Assistant and see if config.state="running". If not, listen for homeassistant_started or core_config_updated and fetch config again.

**Comment by balloob** [comment]
This helper will work with 0.111.3+:

```ts
export const waitUntilStarted = async (conn: Connection): Promise<unknown> =>
  new Promise((resolve) => {
    subscribeConfig(conn, (config) => {
      if (config.state === "RUNNING") {
        resolve();
      }
    });
  });
```

**Comment by eyeson** [comment]
This has detonated the way all my flows work, for example, I use presence detection based on groups.
If bobs is away and therefore group.bob is not_home
and alice is also away group.alice is not_home

On a home assistant reboot, or complete server reboot (so including Node Red)

the nodes watching for state changes will forever stay as "running" until either Alice or Bob comes home. However I need to know the state of them before they get home, as they may not be home for days.
Likewise in reverse, if they're home during the reboot, they will stay as "running" until they leave, but that ruins any node red flow I've got that only work if Node Red knows they're home too.

**Comment by ronaldheft** [comment]
@eyeson Have you tried the “Output on Connect” option? That should output the current state after Node-RED connects.

**Comment by eyeson** [comment]
> @eyeson Have you tried the “Output on Connect” option? That should output the current state after Node-RED connects.

Yep, they were all already on "Output on Connect". They either all get stuck on "unknown" or "running"

I imagine the unknown is the issue with HAs new starting method, collecting the state before it's ready.

**Comment by balloob** [comment]
Home Assistant collectino of the states before it is ready has not changed. We just allowed people to read the states earlier.

**Comment by zachowj** [comment]
@eyeson Try adding a debug node after an event node and have it log to console and you should see that it updates when the first connection is made the HA after a deploy or reboot. If this isn't the case please create a separate issue.

Example:
```
[{"id":"de778073.76432","type":"server-state-changed","z":"56b1c979.b2c618","name":"","version":1,"exposeToHomeAssistant":false,"haConfig":[{"property":"name","value":""},{"property":"icon","value":""}],"entityidfilter":"sun.sun","entityidfiltertype":"exact","outputinitially":true,"state_type":"str","haltifstate":"","halt_if_type":"str","halt_if_compare":"is","outputs":1,"output_only_on_state_change":true,"x":836,"y":704,"wires":[["376026ba.79c24a"]]},{"id":"376026ba.79c24a","type":"debug","z":"56b1c979.b2c618","name":"sun","active":true,"tosidebar":true,"console":true,"tostatus":false,"complete":"payload","targetType":"msg","x":1026,"y":704,"wires":[]}]
```

**Comment by eyeson** [comment]
> @eyeson Try adding a debug node after an event node and have it log to console and you should see that it updates when the first connection is made the HA after a deploy or reboot. If this isn't the case please create a separate issue.
> 
> Example:
> 
> ```
> [{"id":"de778073.76432","type":"server-state-changed","z":"56b1c979.b2c618","name":"","version":1,"exposeToHomeAssistant":false,"haConfig":[{"property":"name","value":""},{"property":"icon","value":""}],"entityidfilter":"sun.sun","entityidfiltertype":"exact","outputinitially":true,"state_type":"str","haltifstate":"","halt_if_type":"str","halt_if_compare":"is","outputs":1,"output_only_on_state_change":true,"x":836,"y":704,"wires":[["376026ba.79c24a"]]},{"id":"376026ba.79c24a","type":"debug","z":"56b1c979.b2c618","name":"sun","active":true,"tosidebar":true,"console":true,"tostatus":false,"complete":"payload","targetType":"msg","x":1026,"y":704,"wires":[]}]
> ```

Hit and miss, on a deploy it picks it up and the debug message is as expected. 

On a home assistant reboot, it stalls at "running"
 Tried with both my group.alice nodes with a debug attached, and copied in your sun.sun state node and tried with that in case it was me being dense - both exactly the same. 
That is currently sat "running" I guess waiting until the sun sets this evening. I will create a bug report then and link it from here
