### ISSUE TITLE
State nodes stuck at "running" on HA reboot

### ISSUE THREAD

**Issue by eyeson** [zachowj/node-red-contrib-home-assistant-websocket#248]
### Describe the bug

Created on the back of this: [https://github.com/zachowj/node-red-contrib-home-assistant-websocket/issues/246#issuecomment-650500798]

Essentially since the most recent update, state nodes with or without "output on connect" or "output only on state change" (tried all combinations - same results) can get stuck at "running" until the state changes.

### To Reproduce

Steps to reproduce the behaviour:

1. Create a state change watching node
2. Reboot Home Assistant
3. Stuck at "running" until state changes.`

### Expected behaviour

As previous behaviour, on reboot, pick up the state of the node on connect (assuming that that is selected)

### Example Flow

```
[{"id":"147bf5f8.d6d80a","type":"server-state-changed","z":"53543c5.8dfb1c4","name":"","server":"77dcd3d0.5db86c","version":1,"exposeToHomeAssistant":false,"haConfig":[{"property":"name","value":""},{"property":"icon","value":""}],"entityidfilter":"sun.sun","entityidfiltertype":"exact","outputinitially":true,"state_type":"str","haltifstate":"","halt_if_type":"str","halt_if_compare":"is","outputs":1,"output_only_on_state_change":true,"x":1100,"y":80,"wires":[["12560ed5.30c2f1"]]},{"id":"12560ed5.30c2f1","type":"debug","z":"53543c5.8dfb1c4","name":"sun","active":true,"tosidebar":true,"console":true,"tostatus":false,"complete":"payload","targetType":"msg","x":1290,"y":80,"wires":[]},{"id":"74812843.15c368","type":"server-state-changed","z":"53543c5.8dfb1c4","name":"","server":"77dcd3d0.5db86c","version":1,"exposeToHomeAssistant":false,"haConfig":[{"property":"name","value":""},{"property":"icon","value":""}],"entityidfilter":"sun.sun","entityidfiltertype":"exact","outputinitially":true,"state_type":"str","haltifstate":"","halt_if_type":"str","halt_if_compare":"is","outputs":1,"output_only_on_state_change":false,"x":1100,"y":140,"wires":[["12560ed5.30c2f1"]]},{"id":"77906d2a.f61e54","type":"server-state-changed","z":"53543c5.8dfb1c4","name":"","server":"77dcd3d0.5db86c","version":1,"exposeToHomeAssistant":false,"haConfig":[{"property":"name","value":""},{"property":"icon","value":""}],"entityidfilter":"sun.sun","entityidfiltertype":"exact","outputinitially":false,"state_type":"str","haltifstate":"","halt_if_type":"str","halt_if_compare":"is","outputs":1,"output_only_on_state_change":false,"x":1100,"y":260,"wires":[["12560ed5.30c2f1"]]},{"id":"8d41431d.12ce8","type":"server-state-changed","z":"53543c5.8dfb1c4","name":"","server":"77dcd3d0.5db86c","version":1,"exposeToHomeAssistant":false,"haConfig":[{"property":"name","value":""},{"property":"icon","value":""}],"entityidfilter":"sun.sun","entityidfiltertype":"exact","outputinitially":false,"state_type":"str","haltifstate":"","halt_if_type":"str","halt_if_compare":"is","outputs":1,"output_only_on_state_change":true,"x":1100,"y":200,"wires":[["12560ed5.30c2f1"]]},{"id":"77dcd3d0.5db86c","type":"server","z":"","name":"Home Assistant","legacy":false,"addon":false,"rejectUnauthorizedCerts":true,"ha_boolean":"y|yes|true|on|home|open","connectionDelay":true,"cacheJson":true}]
```

### Environment (please complete the following information):

- Node Red Version: [e.g. 1.0.6]
- Node.js Version: [unsure]
- NR Home Assistant Plugin Version: [e.g. 0.22.6]
- Is Node Red running in Docker: [yes]

### Additional context

This happens 100% of the time I've tried it by solely rebooting home assistant, I've also managed to reproduce whilst taking Node Red & Home assistant docker environments down and back up together - although that has worked correctly a couple of times.

**Comment by zachowj** [comment]
[Output on connect](https://zachowj.github.io/node-red-contrib-home-assistant-websocket/node/events-state.html#output-on-connect) only outputs on the first connection to HA after a restart of NR or on deploy of the node. This is why you're not seeing it the node status change from running after rebooting HA.

**Comment by eyeson** [comment]
> [Output on connect](https://zachowj.github.io/node-red-contrib-home-assistant-websocket/node/events-state.html#output-on-connect) only outputs on the first connection to HA after a restart of NR or on deploy of the node. This is why you're not seeing the node status change from running after rebooting HA.

Appreciate that, however I tried it with all 4 variations of the same node, and all of them just say running well after I can get the state using  a current state node. This also is not the behaviour that used to happen prior to the most recent update.

**Comment by damusmf** [comment]
Noticing the same thing here on version 0.22.6.  They used to grab the state and say "connected" now they are in running indefinitely until the state actually changes.  I tested with output on connect and got the same thing even though actually using output on connect is not a viable option for me for some of my flows because a simple restart would actually trigger it.

**Comment by orickcorreia** [comment]
Acontecendo a mesma coisa aqui. Começou acontecer depois da última atualização do Node-RED no Home Assistant. Antes os nós disparavam os estados das entidades quando marcado a opção "Output on connect". Está opção agora não tem nenhum efeito.

**Comment by orickcorreia** [comment]
The same thing happening here. It started to happen after the last update of Node-RED in the Home Assistant.

**"Output on connect" before:**

- The Nodes triggered the state of the entity when starting HA
- They also fired when clicking on Deploy

**"Output on connect" now:**

- The Nodes did NOT trigger the state of the entity when starting HA
- But they still do it by clicking on Deploy.

**Comment by ctrl50** [comment]
same thing here.. and I deleted my home assistant server config. 

How can I readd the server to all 1200 nodes??? without clicking each one

**Comment by mspace00** [comment]
Another observation of "Output on connect" unexpected behavior is that it will now also trigger on a state change (event state node), even if "Output only on state change" is not selected.

**Comment by ctleng76** [comment]
It's now 2023 and this bug still exists.  Is there any plan for it to be fixed?

**Comment by Nikotine1** [comment]
2025 and still an issue. I use poll state nodes instead of change nodes because of this, but polling every x seconds isn't optimal.
