### ISSUE TITLE
ifState.js not loaded

### ISSUE THREAD

**Issue by Squashyware** [zachowj/node-red-contrib-home-assistant-websocket#251]
After installing and setting up the home assistant server connection I can add any node except a Events State node. This shows the message ifstate.js not loaded just below the if field.

![image](https://user-images.githubusercontent.com/68014257/86922060-024ff780-c124-11ea-85cb-0a41b3b350d8.png)

I dont know how this can be replicated as I am assuming it is some kind of installation issue.

### Environment (please complete the following information):

- Ubuntu Server 20.04 VM on Proxmox
- Node Red Version: 1.1.0
- Node.js Version: 12.18.2
- NR Home Assistant Plugin Version: 0.22.6
- Is Node Red running in Docker: No

### Other (please complete the following information):

- Have you searched previous issues for duplicates?: Yes

**Comment by zachowj** [comment]
How did you install this package? This shouldn't be possible if you use npm because the package is built before publishing it to npm. If you cloned it using git you would have to manually run the build script.

**Comment by Squashyware** [comment]
I tried through both the palette manager and through npm.
I even created a new container and tried fresh and I got the same thing!

**Comment by zachowj** [comment]
Is there any errors in your browser console when you open the node editor?

**Comment by Squashyware** [comment]
![image](https://user-images.githubusercontent.com/68014257/87005285-ad10f600-c1b6-11ea-9f04-8d31a3ce0f0b.png)

**Comment by Squashyware** [comment]
The entity auto populate doesnt work on this node. If I type it manually the node itself seems to function properly

**Comment by zachowj** [comment]
What's the browser and version of the browser that you are using? Does the current-state node function correctly without errors?

**Comment by Squashyware** [comment]
Chrome 83.0.4103.116 (Official Build) (64-bit)
Yes the node itself functions fine. It seems that it is just effecting the node editor.

**Comment by Squashyware** [comment]
Apart from a lot of restarting home assistant service and node red service I havent changed anything on the server and now the message is not coming up!
I have no idea why but its clearly not an issue with your code.
