### ISSUE TITLE
Websocket issues crashing node-red

### ISSUE THREAD

**Issue by weirders** [zachowj/node-red-contrib-home-assistant-websocket#252]
### Describe the bug

Websocket issues crashing node-red, crashing around 20+ times an hour. In hindsight, it might have been for a few updates already but its hard to backtrack.

### To Reproduce

Unknown at this point. Unsure where to start..

### Expected behavior

Ideally no websocket isses, but even on websocket issues, Node-red should not crash fully and keep non HA flows up. Node / connection should fail safe.

### Environment (please complete the following information):

- Node Red Version: 7.0.0
- Node.js Version: UNK / latest HA version

- NR Home Assistant Plugin Version: 7.0.0
- Is Node Red running in Docker: in hassio, latest update
- HassOS: 4.11
- supervisor: 228

### Other (please complete the following information):

Yes, checked for duplicates, couldnt find a match.

### Additional context

Log from HA addon attached. 
[NRlog.txt](https://github.com/zachowj/node-red-contrib-home-assistant-websocket/files/4927513/NRlog.txt)

Here's 1 hours worth of node red restarts to give an idea:
7/15/2020, 7:00:10 PM
7/15/2020, 7:02:48 PM
7/15/2020, 7:05:24 PM
7/15/2020, 7:08:01 PM
7/15/2020, 7:10:36 PM
7/15/2020, 7:13:12 PM
7/15/2020, 7:15:47 PM
7/15/2020, 7:18:24 PM
7/15/2020, 7:21:00 PM
7/15/2020, 7:23:37 PM
7/15/2020, 7:26:13 PM
7/15/2020, 7:28:49 PM
7/15/2020, 7:31:24 PM
7/15/2020, 7:34:00 PM
7/15/2020, 7:36:37 PM
7/15/2020, 7:39:15 PM
7/15/2020, 7:41:51 PM
7/15/2020, 7:44:28 PM
7/15/2020, 7:47:05 PM
7/15/2020, 7:49:41 PM
7/15/2020, 7:52:16 PM
7/15/2020, 7:54:54 PM
7/15/2020, 7:57:30 PM

**Comment by zachowj** [comment]
From the stack trace, it doesn't look like this package is causing your error.

```
    at SentimentNode.Node.send (/opt/node_modules/@node-red/runtime/lib/nodes/Node.js:410:61)
    at /opt/node_modules/node-red-node-sentiment/72-sentiment.js:15:26
```
