### ISSUE TITLE
Wait Until node does not properly handle templates or passed payloads for the entity_id value

### ISSUE THREAD

**Issue by dozminic** [zachowj/node-red-contrib-home-assistant-websocket#254]
### Describe the bug

The Wait Until node performs incorrectly if the entity_id is passed via msg.payload.entity_id or template flow variable. It immediately triggers without waiting for the condition to be met.

### To Reproduce

1. Import the example flow.
2. Modify the Template node with your entity_id of choice.
3. Modify the Wait Until node to wait for a state which isn't current true.
4. Deploy the new flow.
5. Trigger via inject timestamp node. Wait Until will **not** wait and output will immediately be written to the debug log.

### Expected behavior

Wait Until should pause until the passed entity_id meets the desired condition.

### Example Flow

```
[{"id":"d4f327a5.5b7a18","type":"debug","z":"5e8c1e75.509e9","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":1210,"y":60,"wires":[]},{"id":"abde8cbd.47695","type":"ha-wait-until","z":"5e8c1e75.509e9","name":"","server":"3f726465.ba0bec","outputs":1,"entityId":"","entityIdFilterType":"exact","property":"state","comparator":"is_not","value":"idle","valueType":"str","timeout":0,"timeoutType":"num","timeoutUnits":"seconds","entityLocation":"","entityLocationType":"msg","checkCurrentState":true,"blockInputOverrides":true,"x":1080,"y":60,"wires":[["d4f327a5.5b7a18"]]},{"id":"11b0a90b.72a0b7","type":"inject","z":"5e8c1e75.509e9","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":800,"y":60,"wires":[["59a7f29b.53a8fc"]]},{"id":"59a7f29b.53a8fc","type":"template","z":"5e8c1e75.509e9","name":"","field":"payload","fieldType":"msg","format":"json","syntax":"mustache","template":"{\n    \"entity_id\":\"media_player.example\"\n}","output":"json","x":940,"y":60,"wires":[["abde8cbd.47695"]]},{"id":"3f726465.ba0bec","type":"server","z":"","name":"Home Assistant","legacy":false,"addon":true,"rejectUnauthorizedCerts":true,"ha_boolean":"y|yes|true|on|home|open","connectionDelay":true}]
```

### Environment (please complete the following information):

- Node Red Version: 1.1.0
- Node.js Version: 12.17.0
- NR Home Assistant Plugin Version: 0.22.6
- Is Node Red running in Docker: Yes, via HA add-on

### Other (please complete the following information):

- Have you searched previous issues for duplicates? Yes

**Comment by dozminic** [comment]
I should note, the [documentation ](https://zachowj.github.io/node-red-contrib-home-assistant-websocket/node/wait-until.html)states that the Wait Until node should accept templates and payload objects for the entity_id, but it doesn't perform in this way. I've tried both mustache templates and payloads.

**Comment by zachowj** [comment]
In your exported flow you have `Block Input Overrides` checked. This will stop the node from checking any input value.

**Comment by dozminic** [comment]
Well derp. I could've sworn that was one of the things I checked and unchecked multiple times when I was trying to get it to work. Unchecking that works, so it must have been something else I was doing. Thanks for taking the time to help!
