### ISSUE TITLE
Stuck at "connecting" after a reboot

### ISSUE THREAD

**Issue by danecreekphotography** [zachowj/node-red-contrib-home-assistant-websocket#255]
### Describe the bug

NodeRed no longer seems to be able to connect to HA on reboot. I get the following in the NodeRed:

```
26 Jul 21:06:33 - [info] [server:Home Assistant] WebSocket Connecting http://supervisor/core
26 Jul 21:06:38 - [info] [server:Home Assistant] WebSocket Connecting http://supervisor/core
26 Jul 21:06:43 - [info] [server:Home Assistant] WebSocket Connecting http://supervisor/core
26 Jul 21:06:48 - [info] [server:Home Assistant] WebSocket Connecting http://supervisor/core
26 Jul 21:06:53 - [info] [server:Home Assistant] WebSocket Connecting http://supervisor/core
26 Jul 21:06:58 - [info] [server:Home Assistant] WebSocket Connecting http://supervisor/core
26 Jul 21:07:03 - [info] [server:Home Assistant] WebSocket Connecting http://supervisor/core
26 Jul 21:07:08 - [info] [server:Home Assistant] WebSocket Connecting http://supervisor/core
```

I also see this in the HA logs:

```
2020-07-26 20:36:46 WARNING (MainThread) [homeassistant.components.webhook] Received message for unregistered webhook e61482eb491b871d9873d80ee6b535d2e9e5a53f812a9be47f1404deff6320bf from 192.168.1.1
```

### To Reproduce

Honestly I'm not entirely sure, but it's been like this since I rebooted and manually restarting NodeRed after HA's been running for an hour or so doesn't seem to make any difference. None of my NodeRed/HA flows are working anymore.

### Environment (please complete the following information):

- Node Red Version: 7.0.0
- NR Home Assistant Plugin Version: 0.22.6
- Is Node Red running in Docker: HA addon
- HA version: 0.113.1

### Other (please complete the following information):

The symptoms seem similar to #250 although the log messages I'm seeing are different.

I found someone with the same error in #209 however I don't have any HA logs showing an invalid token was used.

**Comment by danecreekphotography** [comment]
It's possible this is related to https://github.com/home-assistant/core/issues/38274?

**Comment by danecreekphotography** [comment]
I downgraded to 0.112.4 by doing the following from an ssh prompt:

`ha core update --version 0.112.4`

And that seems to have solved the issue. The HA nodes in my flows now show as connected.

**Comment by zachowj** [comment]
> It's possible this is related to [home-assistant/core#38274](https://github.com/home-assistant/core/issues/38274)?

I just glanced through the hass.io proxy [code](https://github.com/home-assistant/supervisor/blob/e509c804ae2d46b943d9a8ada3f9633eaeb21882/supervisor/api/proxy.py#L160) and looks like it refuses the connection until HA is in a running state. So yes, I would say that could be the cause.

A possible temporary solution would be to skip the hass.io proxy and connect directly to HA using its non-docker IP and long-lived access token.

**Comment by danecreekphotography** [comment]
I'm running directly on a RPI4 with no Docker involved, and have forced a fixed IP address for the RPI in my networking gear. Hard coding the IP address and a long-lived token wouldn't be a problem.

I'm just going to stick on 0.112.4 for now. I have no need for the stuff in 0.113 and I prefer my system running 😁

**Comment by zachowj** [comment]
What I meant is you're running NR as a hass.io addon, or whatever it's called today, which is a docker container. So instead of using the hass.io proxy http://supervisor/core as the HA host address, you would use http://192.168.0.1 or whatever your HA instance local address is.

**Comment by danecreekphotography** [comment]
Ah. Yeah, I might give that a go. I think you can close this as outside of your control. HA's got some issues to work through here...
