### ISSUE TITLE
Function node not working after HA reboot

### ISSUE THREAD

**Issue by DirkMu** [zachowj/node-red-contrib-home-assistant-websocket#257]
### Describe the bug

Similar to #250 I have an issue with my function nodes using the connection to HA. I thought it will be fixed when #250 is fixed. Unfortunately it is not. 

Once HA was restarted I get the error "TypeError: Cannot read property 'state' of undefined" when running through the function nodes. When I open the configuration node of 'Home Assistant' and hit 'Update' and 'deploy' everything works fine. 

### To Reproduce

1. Create a function node
For instance:
```
const ha = global.get('homeassistant').homeAssistant.states;
const season = ha['sensor.season'].state;

if (season == "spring" || season == "summer") {
    msg.payload = true;
} else {
    msg.payload = false;
}

node.status({fill:"blue",shape:"ring",text:season});
return msg;
```

2. Connect it with an inject and debug node
3. Deploy
4. Inject --> Result in msg.payload is supposed to be summer
5. Restart HA
6. Once HA finished restart, inject again
7. Debug node throws error message

In order to correct the behavior, after each restart, I have to go to the Home Assistant configuration node, updaten and re-deploy.

### Expected behavior

Connection can be made by node red without re-dploying.

### Screenshots

![image](https://user-images.githubusercontent.com/53949754/89120632-22bb6980-d4b8-11ea-983b-3f3d004a6fcc.png)

### Example Flow

```
[{"id":"3c12e6de.7aaa3a","type":"debug","z":"fe9bbb1e.f286e8","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","statusVal":"","statusType":"auto","x":928,"y":352,"wires":[]},{"id":"741f9b39.016794","type":"inject","z":"fe9bbb1e.f286e8","name":"","repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":636,"y":320,"wires":[["4da102d7.77d18c"]]},{"id":"4da102d7.77d18c","type":"function","z":"fe9bbb1e.f286e8","name":"Spring or Summer","func":"const ha = global.get('homeassistant').homeAssistant.states;\nconst season = ha['sensor.season'].state;\n\nif (season == \"spring\" || season == \"summer\") {\n    msg.payload = true;\n} else {\n    msg.payload = false;\n}\n\nnode.status({fill:\"blue\",shape:\"ring\",text:season});\nreturn msg;\n","outputs":1,"noerr":0,"initialize":"","finalize":"","x":746,"y":400,"wires":[["3c12e6de.7aaa3a"]]}]
```

### Environment (please complete the following information):

- Node Red Version: 1.1.2
- Node.js Version: don't know
- NR Home Assistant Plugin Version: 0.23
- Is Node Red running in Docker: yes
- Home Assistant Core (Home Assistant Container): 0.113.3

### Other (please complete the following information):

- Have you searched previous issues for duplicates?: yes #250

**Comment by zachowj** [comment]
This really isn't a bug. You're are trying to access information before it's available in NR. 

A couple of solutions come to mind:

1. start the flow from the events: all node and listen for the `home_assistant_client` event and wait until the `running` event is fired.
2. check if `global.get('homeassistant').homeAssistant.states` if is undefined then wait a second loop back to the function node.

**Comment by DirkMu** [comment]
Thanks for your help. The issue occurs after HA finished the restart. 

home_assistant_client is running:
![image](https://user-images.githubusercontent.com/53949754/89129897-39d27980-d501-11ea-9762-53d86d6d9d2b.png)

I check a trigger state node and it worked:
![image](https://user-images.githubusercontent.com/53949754/89129909-55d61b00-d501-11ea-9013-1ba531af5f56.png)

However, in a function node it is still throwig the error message: 
![image](https://user-images.githubusercontent.com/53949754/89129921-7900ca80-d501-11ea-9422-bbc0342c6f88.png)

`global.get('homeassistant').homeAssistant.states` seems to be defined. However, season (as an example; it can be reproduced with every entity) is still undefined.

**Comment by zachowj** [comment]
![image](https://user-images.githubusercontent.com/37859597/89130317-ca389c00-d4b8-11ea-9dc5-e945db9f54ec.png)
```
[{"id":"bf6e63dc.7a48d","type":"server-events","z":"ffbd7f06.4a014","name":"","event_type":"home_assistant_client","exposeToHomeAssistant":false,"haConfig":[{"property":"name","value":""},{"property":"icon","value":""}],"x":214,"y":1104,"wires":[["17984f0e.1e4c91"]]},{"id":"17984f0e.1e4c91","type":"function","z":"ffbd7f06.4a014","name":"","func":"if(msg.payload !== \"running\") return;\n\nconst ha = global.get('homeassistant').homeAssistant.states;\nconst season = ha['sensor.season'].state;\n\nif (season == \"spring\" || season == \"summer\") {\n    msg.payload = true;\n} else {\n    msg.payload = false;\n}\n\nnode.status({fill:\"blue\",shape:\"ring\",text:season});\nreturn msg;\n","outputs":1,"noerr":0,"initialize":"","finalize":"","x":428,"y":1104,"wires":[["86bad18e.d4cd3"]]},{"id":"86bad18e.d4cd3","type":"debug","z":"ffbd7f06.4a014","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","statusVal":"","statusType":"auto","x":598,"y":1104,"wires":[]}]
```

![image](https://user-images.githubusercontent.com/37859597/89130323-d6bcf480-d4b8-11ea-9b73-6d0b0294de31.png)

```
[{"id":"1a584222.e5acfe","type":"inject","z":"ffbd7f06.4a014","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":170,"y":1184,"wires":[["76de65d5.0291ac"]]},{"id":"76de65d5.0291ac","type":"function","z":"ffbd7f06.4a014","name":"","func":"const ha = global.get('homeassistant').homeAssistant\nif(!ha.isRunning) {\n    return [null,{}];\n}\n\nconst season = ha.states['sensor.season'].state;\n\nif (season == \"spring\" || season == \"summer\") {\n    msg.payload = true;\n} else {\n    msg.payload = false;\n}\n\nnode.status({fill:\"blue\",shape:\"ring\",text:season});\nreturn msg;\n","outputs":2,"noerr":0,"initialize":"","finalize":"","x":332,"y":1184,"wires":[["da2979e1.a5fe58"],["5222fcca.4015d4"]]},{"id":"da2979e1.a5fe58","type":"debug","z":"ffbd7f06.4a014","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","statusVal":"","statusType":"auto","x":486,"y":1184,"wires":[]},{"id":"5222fcca.4015d4","type":"delay","z":"ffbd7f06.4a014","name":"","pauseType":"delay","timeout":"1","timeoutUnits":"seconds","rate":"1","nbRateUnits":"1","rateUnits":"second","randomFirst":"1","randomLast":"5","randomUnits":"seconds","drop":false,"x":476,"y":1232,"wires":[["76de65d5.0291ac"]]}]
```

**Comment by DirkMu** [comment]
Really appreciate your help. However, your flow throws the same error message once `home_assistant_client` is running.

![image](https://user-images.githubusercontent.com/53949754/89130416-efeb9280-d504-11ea-9da3-8bbfbdb2bfcb.png)

**Comment by zachowj** [comment]
Are you sure `sensor.season` exists in HA? Does it show the correct state if you just output a current-state node with `sensor.season` as the entity id?

**Comment by DirkMu** [comment]
Yes, it does. If I update the configuration node, it is working. Your flow and mine. 

![image](https://user-images.githubusercontent.com/53949754/89130620-9f753480-d506-11ea-9ee9-82f76968fdd4.png)

**Comment by DirkMu** [comment]
Or Server node. I need to hit Update (here Aktualisieren) and Deploy

![image](https://user-images.githubusercontent.com/53949754/89130677-16123200-d507-11ea-8b0b-26684f1070dc.png)

**Comment by zachowj** [comment]
it's a race condition from when the `running` event is fired to when it updates the global scope.

![image](https://user-images.githubusercontent.com/37859597/89130933-10442e80-d4be-11ea-8040-0c5f59af0662.png)
```
[{"id":"89668b5e.5d4c88","type":"server-events","z":"ffbd7f06.4a014","name":"","event_type":"home_assistant_client","exposeToHomeAssistant":false,"haConfig":[{"property":"name","value":""},{"property":"icon","value":""}],"x":264,"y":1120,"wires":[["bb0c6cd5.0083a"]]},{"id":"2ec4bcfe.1c43e4","type":"function","z":"ffbd7f06.4a014","name":"","func":"const ha = global.get('homeassistant').homeAssistant.states;\nconst season = ha['sensor.season'].state;\n\nif (season == \"spring\" || season == \"summer\") {\n    msg.payload = true;\n} else {\n    msg.payload = false;\n}\n\nnode.status({fill:\"blue\",shape:\"ring\",text:season});\nreturn msg;\n","outputs":1,"noerr":0,"initialize":"","finalize":"","x":732,"y":1120,"wires":[["ff9570b0.6e942"]]},{"id":"ff9570b0.6e942","type":"debug","z":"ffbd7f06.4a014","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","statusVal":"","statusType":"auto","x":886,"y":1120,"wires":[]},{"id":"bb0c6cd5.0083a","type":"switch","z":"ffbd7f06.4a014","name":"","property":"payload","propertyType":"msg","rules":[{"t":"eq","v":"running","vt":"str"}],"checkall":"true","repair":false,"outputs":1,"x":450,"y":1120,"wires":[["39d6eefb.65cb02"]]},{"id":"39d6eefb.65cb02","type":"delay","z":"ffbd7f06.4a014","name":"","pauseType":"delay","timeout":"1","timeoutUnits":"seconds","rate":"1","nbRateUnits":"1","rateUnits":"second","randomFirst":"1","randomLast":"5","randomUnits":"seconds","drop":false,"x":588,"y":1120,"wires":[["2ec4bcfe.1c43e4"]]}]
```

**Comment by DirkMu** [comment]
It is not working.

![image](https://user-images.githubusercontent.com/53949754/89131114-af8f1300-d50a-11ea-8a28-f57b6298105a.png)

Are you able to reproduce the issue in your environment?

I just need to restart HA and wait for the events all node to be updated. Once it returns running the function node throws the error.

**Comment by zachowj** [comment]
Adding the one-second delay allows it function correctly for me. The delay might need to be longer for you. When I get a chance I'll look into fixing the race condition.
> ![image](https://user-images.githubusercontent.com/37859597/89130323-d6bcf480-d4b8-11ea-9b73-6d0b0294de31.png)
> 
> ```
> [{"id":"1a584222.e5acfe","type":"inject","z":"ffbd7f06.4a014","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":170,"y":1184,"wires":[["76de65d5.0291ac"]]},{"id":"76de65d5.0291ac","type":"function","z":"ffbd7f06.4a014","name":"","func":"const ha = global.get('homeassistant').homeAssistant\nif(!ha.isRunning) {\n    return [null,{}];\n}\n\nconst season = ha.states['sensor.season'].state;\n\nif (season == \"spring\" || season == \"summer\") {\n    msg.payload = true;\n} else {\n    msg.payload = false;\n}\n\nnode.status({fill:\"blue\",shape:\"ring\",text:season});\nreturn msg;\n","outputs":2,"noerr":0,"initialize":"","finalize":"","x":332,"y":1184,"wires":[["da2979e1.a5fe58"],["5222fcca.4015d4"]]},{"id":"da2979e1.a5fe58","type":"debug","z":"ffbd7f06.4a014","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","statusVal":"","statusType":"auto","x":486,"y":1184,"wires":[]},{"id":"5222fcca.4015d4","type":"delay","z":"ffbd7f06.4a014","name":"","pauseType":"delay","timeout":"1","timeoutUnits":"seconds","rate":"1","nbRateUnits":"1","rateUnits":"second","randomFirst":"1","randomLast":"5","randomUnits":"seconds","drop":false,"x":476,"y":1232,"wires":[["76de65d5.0291ac"]]}]
> ```

the flow I post above should work

**Comment by DirkMu** [comment]
Unfortunately, the second flow does not work. Your check returns true because global.get('homeassistant').homeAssistant is running. Even if it is running the entity cannot be read. 

If I get you right, you assume it is a matter of seconds that causes the entity cannot be read. My experience is different. If I do not update my configuration node all of my function nodes will not work at all. 

In this example I waited more than 10 minutes:
![image](https://user-images.githubusercontent.com/53949754/89148244-8ba6ee00-d559-11ea-9999-18ae2a76cf4a.png)

**Comment by zachowj** [comment]
ok, then at the moment not sure what it could be. Try one more thing for me so I can narrow it down to the front or backend. 

```
[{"id":"9e39a583.0b3c58","type":"server-events","z":"ffbd7f06.4a014","name":"","event_type":"home_assistant_client","exposeToHomeAssistant":false,"haConfig":[{"property":"name","value":""},{"property":"icon","value":""}],"x":232,"y":1120,"wires":[["ef74c6e5.17b5e8"]]},{"id":"7b12c808.21f648","type":"debug","z":"ffbd7f06.4a014","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","statusVal":"","statusType":"auto","x":838,"y":1120,"wires":[]},{"id":"ef74c6e5.17b5e8","type":"switch","z":"ffbd7f06.4a014","name":"","property":"payload","propertyType":"msg","rules":[{"t":"eq","v":"running","vt":"str"}],"checkall":"true","repair":false,"outputs":1,"x":418,"y":1120,"wires":[["6362a0a9.22d94"]]},{"id":"6362a0a9.22d94","type":"api-current-state","z":"ffbd7f06.4a014","name":"","version":1,"outputs":1,"halt_if":"","halt_if_type":"str","halt_if_compare":"is","override_topic":false,"entity_id":"sensor.season","state_type":"str","state_location":"payload","override_payload":"msg","entity_location":"data","override_data":"msg","blockInputOverrides":false,"x":616,"y":1120,"wires":[["7b12c808.21f648"]]}]
```

Also, do you recall when this last work correctly for you? The version of this package and HA?

**Comment by DirkMu** [comment]
A flow that consist of home assistant nodes, in contrast, works fine. It's only a function node that uses `global.get('homeassistant').homeAssistant.states` and attempts to read a value from an HA entity that issue. 

As a result your flow works as expected. 

As far as I remember, it worked fine before HA 0.111. That is why I assumed #250 refers to the same issue. The package of the node red ha websocket package was 0.22.X (?). Maybe < 0.22.5 I guess.

**Comment by zachowj** [comment]
I might have fixed it on the latest dev build. If you want to try it you can install it using npm from your config directory.

```
npm install node-red-contrib-home-assistant-websocket@next
```

**Comment by DirkMu** [comment]
Thanks! Unfortunately, I am not familiar with npm or github. Do have a guide or documenation I can use? I am running bith home assitant core and node red in Docker on my Synnology NAS.

**Comment by zachowj** [comment]
Try the new release v0.24.0

**Comment by DirkMu** [comment]
Looks good. No issues so far. Seems you found the root cause. 👌
