### ISSUE TITLE
@hapi/joi dependency is deprecated - not able to install this plugin

### ISSUE THREAD

**Issue by ronnyandre** [zachowj/node-red-contrib-home-assistant-websocket#258]
This package is dependent of @hapi/joi, which now has been deprecated and moved back to 'joi'. This renders this plugin not able to install in Node RED.

https://github.com/sideway/joi/issues/2411

**Comment by DeviousPenguin** [comment]
I'm getting the same issue:

`"Installation of module node-red-contrib-home-assistant-websocket failed: module not found"`
