### ISSUE TITLE
How to use trigger:state object

### ISSUE THREAD

**Issue by ihulsbus** [zachowj/node-red-contrib-home-assistant-websocket#26]
Hi, 

I'm struggling to turn nodes in HA on or off with the trigger: state object. According to the input documentation I should be able to change the state of an node when the "incoming payload or message is a string and equal to 'enable' or 'disable'". For this I've created the following setup: 
![image](https://user-images.githubusercontent.com/11390889/47927765-83250d80-dec4-11e8-9120-9d5a91556a17.png)
The `enable` function contains the following:
```
msg.payload = "enable";
return msg;
```
the `disable` function is the same, but then with "disable" in the payload. 

Unfortunately, I do not manage to turn the HA node on or off.

How can I utilise this object to interact with HA nodes? 

Cheers, 
Ian

**Comment by zachowj** [comment]
You are correct if msg.payload is 'enable' or 'disable' that should work. Give the below a try and when you disable the node it should show (DISABLED) next to the status.

```
[{"id":"ada6311c.f5196","type":"inject","z":"caad1953.456cd8","name":"","topic":"","payload":"enable","payloadType":"str","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":90,"y":360,"wires":[["138e40f0.01b49f"]]},{"id":"138e40f0.01b49f","type":"trigger-state","z":"caad1953.456cd8","name":"","server":"2dad33ee.42bf5c","entityid":"sun.sun","debugenabled":false,"constraints":[],"constraintsmustmatch":"all","outputs":2,"customoutputs":[],"outputinitially":false,"x":300,"y":360,"wires":[[],[]]},{"id":"a72372c5.3883d","type":"inject","z":"caad1953.456cd8","name":"","topic":"","payload":"disable","payloadType":"str","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":90,"y":400,"wires":[["138e40f0.01b49f"]]}]
```

https://i.imgur.com/Z5lmLOJ.png

**Comment by ihulsbus** [comment]
I think I'm starting to understand how it works. To check: This does only disable the node in node-red, and not in Home Assistant? 

How can I turn a light on / off in home assistant with this?

**Comment by zachowj** [comment]
Yes, use the call-service node for that.

**Comment by zachowj** [comment]
If you're just starting to learn node-red some great resources for general questions:
Forums - https://community.home-assistant.io/c/third-party/node-red
Discord - https://discord.gg/c5DvZ4e

**Comment by ihulsbus** [comment]
Thanks zachowj! That gave me the hint I was looking for :)
