### ISSUE TITLE
Disabled nodes become "running" after HA restart or deploying flow

### ISSUE THREAD

**Issue by ffm777** [zachowj/node-red-contrib-home-assistant-websocket#261]
### Describe the bug

When either redeploying a flow or restarting HA, then nodes such as “trigger: state” nodes which were previously set to “DISABLED” now become running and will trigger when the state changes.

### To Reproduce

1.	Implement a “trigger: state” node
2.	Push a message into the node with msg.payload set to “disable”
3.	Now change the flow and deploy OR just restart Home Assistant
4.	Node now changes to “running”

### Expected behavior

The node should stay “DISABLED” even after deploy or restarting HA

### Screenshots

NA

### Example Flow

NA

### Environment (please complete the following information):

•	Node Red Version: v1.1.3
•	NR Home Assistant Add-on version 7.1.0

### Other (please complete the following information):

- Have you searched previous issues for duplicates?:

**Comment by zachowj** [comment]
I tried deploying the flow and restarting HA and both don't show a change in the status of the disabled node.

![Gd0Rh5A16u](https://user-images.githubusercontent.com/37859597/91906238-b40b3080-ec5c-11ea-96b7-5a76b3fe7701.gif)

If you're seeing the status change, it's only the connection status not the status of the node that changes. Does the node still function as it is disabled or do events pass through it?

**Comment by ffm777** [comment]
In my case, events pass through it. Have you checked that the disabled node is still disabled after a restart? In my case it also says "running" after the restart and it triggers when the state which is monitored by the node actually changes. So it is not disabled anymore.

**Comment by zachowj** [comment]
Happens when you don't have the custom component installed.
