### ISSUE TITLE
Output on Connect no longer works

### ISSUE THREAD

**Issue by SentryMax** [zachowj/node-red-contrib-home-assistant-websocket#262]
### Describe the bug

Output on Connect no longer works on any node

### To Reproduce

1. Go to any node that have Output on Connect option
2. Click on Output on Connect check mark
3. Hit deploy
4. See that Output on Connect don't work

### Expected behavior

Expect Output on Connect to works on any node that have the option as always

### Screenshots

![Output on connect](https://user-images.githubusercontent.com/57269475/92536403-e6f38c80-f239-11ea-9648-56da40608fe5.PNG)

### Environment (please complete the following information):

- Node Red Version: Current version: 7.1.1
- Node.js Version: [e.g. 12.16.1]
- NR Home Assistant Plugin Version: [e.g. 0.21.3]
- Is Node Red running in Docker: HA addon
### Other (please complete the following information):

- Have you searched previous issues for duplicates?:

**Comment by zachowj** [comment]
Another one that works when the custom integration is installed and doesn't work when it isn't.

**Comment by SentryMax** [comment]
Output on connect still not working.
Current version 7.2.2

**Comment by zachowj** [comment]
I can't reproduce this anymore. What is the status of the event node after the connection is made the HA?

**Comment by SentryMax** [comment]
The status of the event node after a HA restart is running. Output on
connect will not work, If after the restart you select/unselect it manually
and deploy it will work

**Comment by sstratoti** [comment]
I'm having this same issue.

Node Red Version: 1.2.9
Node.js Version: 10.23.2
NR Home Assistant Plugin Version: 30.1
Is Node Red running in Docker: Yes, image is nodered/node-red

Looks like I'm having this same issue. I just updated my node-red and this contrib palate to the latest versions and now none of my automations are outputting whenever I make changes and re-deploy. From reading another issue on "output on connect" I've read that this only occurs on the first connection from node-red to HA, and that if HA restarts or becomes unavailable, it wont output again. However, redeploying my nodes wipes their current state. Doing a redeploy lists the status as "running" for the state node. I need to somehow force a refresh of the value in order for things to start back up in some of my automations/flows.

For instance, I have an air humidifier in my kids room. I want to start a timer if the humidifier is ON and turn it OFF after an hour, then after another hour, turn it back ON. Basically manage this with a switch in HA. If I redeploy in NR, the state node just lists "running" and unless I manually flip the switch in HA, it wont register the current value.

I've also tried to restart my node-red container to see if it outputs on connect to HA. Still says "running" and doesn't adjust unless I adjust the switch in HA manually. Not sure what I'm doing wrong here.

**Comment by sstratoti** [comment]
@zachowj - I think I've figured it out. It looks like it's a bug with the "For xx Minutes" value in the state node. If this has a value in it, even if its just a Zero, it'll continually say "running" and will not output the state. It also will not start the "Waiting for x minutes" message unless the state changes. It'll just continually say "running".

To get around this, I have to clear the value, click "Done" in the node and then deploy. Zero defaults into this field when dropping it into a flow, so it was causing an issue with my NEW flows, not my older ones. I realized this when my older flows were reporting an on/off value below them and when I compared them to my newer flow for the humidifier.

**Comment by sstratoti** [comment]
@NemesisFN - Can you confirm this works for you, too?

**Comment by NemesisFN** [comment]
I have old and newly setup event state nodes, some have the zero and some
don’t and it makes no difference; Output on Connect still not working.
Owner commented “Another one that works when the custom integration is
installed and doesn’t when it isn’t” si y’all can try that, I don’t want
the integration and I don’t really care if they fix it anymore. Good luck

**Comment by knightjoel** [comment]
@zachowj, some of us are still noticing a problem with this. I notice the same behavior that @sstratoti described above: If "For XX minutes/seconds" is left blank, Output on Connect works as expected. I think it's worth re-opening this issue (or happy to create a new one if you'd prefer).

- Node-Red HA addon 9.1.2
