### ISSUE TITLE
Make it easy to use "for: x hours" in a node

### ISSUE THREAD

**Issue by jschwalbe** [zachowj/node-red-contrib-home-assistant-websocket#263]
### Is your feature request related to a problem? Please describe.

In HA automations, it's stupid simple to create an automation that fires after x minutes, i.e. "send alert after water sensor has been on for 5 minutes", "turn off fan after it's been on for 3 hours", etc. Currently, it seems quite difficult to do this with Node Red and it's a pretty frustrating thing to figure out for a newbie who is trying to transfer automations from HA to NR.

I'm not alone:
https://community.home-assistant.io/t/for-minute-in-trigger/160662/1
https://community.home-assistant.io/t/node-red-equivalent-of-for/53715
https://www.reddit.com/r/homeassistant/comments/hsffup/node_red_for_trigger/
https://www.reddit.com/r/homeassistant/comments/gmxhzj/node_red_for_condition/
https://www.reddit.com/r/homeassistant/comments/ffhyiy/im_still_relatively_new_at_this_and_am_trying_to/fjzyvy6?utm_source=share&utm_medium=web2x&context=3
https://www.reddit.com/r/homeassistant/comments/bdehvb/nodered_emulate_hasss_for/
https://community.home-assistant.io/t/turn-light-off-after-minutes/135795/4
https://community.home-assistant.io/t/for-minute-in-trigger/160662

I've read through these and each explanation/solution seems quite convoluted and (for lack of better words) _ugly_, whereas the solution below would be elegant and easy to understand.

### Describe the solution you'd like
I would love to have a `for` box within the `events: state` node. A mockup might look like this:

![image](https://user-images.githubusercontent.com/8005921/92670817-d5b28a80-f2e2-11ea-891f-325bfb53b21b.png)

### Describe alternatives you've considered
I've considered just keeping certain automations in HA.

### Additional context
I'm a newbie at this. :) Please be gentle.

**Comment by legomind** [comment]
Consider using trigger for this. Just set msg.reset = true when you want to prevent the delayed message from being set (eg. when switch is turned off)

**Comment by zachowj** [comment]
<https://github.com/zachowj/node-red-contrib-home-assistant-websocket/commit/61021a80aad0d47af7e51b9694e2e7630e0ee2f6>
