### ISSUE TITLE
Hass.io support URL/Token fields

### ISSUE THREAD

**Issue by frenck** [zachowj/node-red-contrib-home-assistant-websocket#27]
**Is your feature request related to a problem? Please describe.**

I've learned, especially the last couple of days, a lot of users have issues with the concept of `http://hassio/homeassistant` is actually a valid and recommended URL to use.

This causes people to change it, and end up having difficulties (while it worked out of the box.)

And even if they keep the correct URL, they have no clue what to put into the API Token field.

**Describe the solution you'd like**

Add a checkbox for: I use Hass.io (or something) and hide both URL & API token fields.

**Describe alternatives you've considered**

Hide the API Token field if the `http://hassio/homeassistant` URL is used.

**Additional context**

n/a

**Comment by zachowj** [comment]
I was originally going to add that in when I put in support of importing the token but figured it wasn't going to be that hard for people to figure it out. Guess I was wrong.

**Comment by frenck** [comment]
Awesome work @zachowj 🎉
