### ISSUE TITLE
Error in new version

### ISSUE THREAD

**Issue by mihail4anov** [zachowj/node-red-contrib-home-assistant-websocket#273]
After update of NR my function node started to give ma an error in debug window.
**const start = states['input_datetime.alarm1'].attributes;**
Gives me smth which says that states is undefined. As I understand it stopped to get attributes from input_datetime. I checked this entity and it seems ok.

**Comment by zachowj** [comment]
With the little bit of information, you provided I can only guess that you're attempting to access the global variable before the connection to HA has been made and the entities have been received. If you were previously using a version of HA that didn't allow WebSocket connections before HA was completely loaded this is probably what is happening.

**Comment by mihail4anov** [comment]
> With the little bit of information, you provided I can only guess that you're attempting to access the global variable before the connection to HA has been made and the entities have been received. If you were previously using a version of HA that didn't allow WebSocket connections before HA was completely loaded this is probably what is happening.

I am ready to give you any information you want.

My function node is:
```
const states = global.get('homeassistant').homeAssistant.states;
const now = new Date();
const alarm = states['input_datetime.checkbattery'].attributes;

if(now.getHours() === alarm.hour && now.getMinutes() === alarm.minute) {
    return msg;
}
```

My NR version **Current version: 7.2.2** and it works, but **Node-RED 7.2.3** has this problem.
I am running **HA** in docker. HA version was **115**. Now updated to **116** (have not checked if the problem is gone on 116 yet)

**Comment by zachowj** [comment]
This might be related to something that was already fixed, https://github.com/zachowj/node-red-contrib-home-assistant-websocket/commit/4676c08c808bca1aebff0049fa7577dbcafca9bc, but the hass.io addon hasn't been updated from what I can see.

You can manually tell the hass.io addon to use the latest version of this package.

<https://community.home-assistant.io/t/nodered-7-2-3-switch-node-not-evaluating-attribute/233553>

**Comment by mihail4anov** [comment]
> This might be related to something that was already fixed, [4676c08](https://github.com/zachowj/node-red-contrib-home-assistant-websocket/commit/4676c08c808bca1aebff0049fa7577dbcafca9bc), but the hass.io addon hasn't been updated from what I can see.
> 
> You can manually tell the hass.io addon to use the latest version of this package.
> 
> https://community.home-assistant.io/t/nodered-7-2-3-switch-node-not-evaluating-attribute/233553

**npm_packages:
  - node-red-contrib-home-assistant-websocket@latest**
Says **Invalid YAML** to me and I cant press SAVE

**Comment by mihail4anov** [comment]
> This might be related to something that was already fixed, [4676c08](https://github.com/zachowj/node-red-contrib-home-assistant-websocket/commit/4676c08c808bca1aebff0049fa7577dbcafca9bc), but the hass.io addon hasn't been updated from what I can see.
> 
> You can manually tell the hass.io addon to use the latest version of this package.
> 
> https://community.home-assistant.io/t/nodered-7-2-3-switch-node-not-evaluating-attribute/233553

Done
```
npm_packages:
  - node-red-contrib-home-assistant-websocket@latest
```
version: 7.2.3
[Screen](https://drive.google.com/file/d/1OvsPmp_gWF4PI6d9MahmWkOE8DPb8VxU/view?usp=sharing)

**Comment by mihail4anov** [comment]
Now came back to 7.2.2 and the error is not gone.
What is going on? :-)

**Comment by mihail4anov** [comment]
Found the problem I guess. I renamed my Server: Home Assistant to Server: **My** Home Assistant in NR.
But I don't know how to change my function node to make it match the new Server name.

const states = global.get('myhomeassistant').myhomeAssistant.states; ?

**Comment by zachowj** [comment]
You can find it under the context data menu in the global namespace.

`const states = global.get('homeassistant').myHomeAssistant.states;`

**Comment by mihail4anov** [comment]
> You can find it under the context data menu in the global namespace.
> 
> `const states = global.get('homeassistant').myHomeAssistant.states;`

Is it ok that I have 2 objects: homeAssistant and myHomeAssistant?
[Screen](https://drive.google.com/file/d/1EdTNgEd7ylslpHYnfX75OrTNa3UKXnRZ/view?usp=sharing)

**Comment by mihail4anov** [comment]
Reinstalled NR now everything is fine)
