### ISSUE TITLE
Breaking change for some data?

### ISSUE THREAD

**Issue by blair287** [zachowj/node-red-contrib-home-assistant-websocket#276]
### Describe the bug

Have I missed a breaking change somewhere?
Noticed some node red flows were not working where i was using switch nodes with properties like "data.old_state.state" which is for manual alarm and noticed that new data is now shown at "data.event.old_state.state".
changed all my flows to now contain the .event after data and are back working again however i also noticed on a flow thats monitoring a lamps brightness the data had moved too from "data.new_state.attributes.brightness" to "data.event.new_state.attributes.brightness".

still curious if this extra .event and also some attributes are in a completely different place was mentioned anywhere as breaking change? probably was im just blind. sorry

### To Reproduce

2. Click on '...'
3. Scroll down to '...'

### Screenshots

![event node red](https://user-images.githubusercontent.com/44187409/95661364-96b46680-0b26-11eb-8e48-09386c4c0573.JPG)

### Example Flow

```
export goes here
```

### Environment (please complete the following information):

- Node Red Version: [e.g. 1.0.4]
- Node.js Version: [e.g. 12.16.1]
- NR Home Assistant Plugin Version: [e.g. 0.21.3]
- Is Node Red running in Docker: [e.g. yes/no/HA addon]

### Other (please complete the following information):

- Have you searched previous issues for duplicates?:

**Comment by zachowj** [comment]
It was [fixed](https://github.com/zachowj/node-red-contrib-home-assistant-websocket/commit/4676c08c808bca1aebff0049fa7577dbcafca9bc) the same day. I guess the addon hasn't released a new version with the fix.

You can always have the addon install the latest version.

<https://community.home-assistant.io/t/breaking-change-for-events-state-node-or-just-me/234003?u=kermit>
