### ISSUE TITLE
Most nodes missing in palette / slice is not a function

### ISSUE THREAD

**Issue by rbm78bln** [zachowj/node-red-contrib-home-assistant-websocket#285]
### Describe the bug

After installing node-red-contrib-home-assistant-websocket using npm and restarting Node-RED only two types of nodes become available in the palette plus the server config node:
* api-call-service
* ha-webhook
* server

The nodes mentioned above are working fine.

All other nodes are not available.

### To Reproduce

1. Stop Node-RED
1. `cd ~/.node_red`
1. `npm install node-red-contrib-home-assistant-websocket`
1. Start Node-RED
1. See attached screenshot :-)
1. See Node-RED logfile

Syslog:

    Welcome to Node-RED
    ===================
    31 Oct 00:54:33 - [info] Node-RED version: v1.2.2
    31 Oct 00:54:33 - [info] Node.js  version: v12.19.0
    31 Oct 00:54:33 - [info] Linux 4.15.0-118-generic x64 LE
    31 Oct 00:54:35 - [info] Loading palette nodes
    31 Oct 00:54:49 - [info] Dashboard version 2.23.5 started at /
    31 Oct 00:54:50 - [warn] ------------------------------------------------------
    31 Oct 00:54:50 - [warn] [node-red-contrib-home-assistant-websocket/server-events] TypeError: this.$_terms[key].slice is not a function
    31 Oct 00:54:50 - [warn] [node-red-contrib-home-assistant-websocket/server-state-changed] TypeError: this.$_terms[key].slice is not a function
    31 Oct 00:54:50 - [warn] [node-red-contrib-home-assistant-websocket/trigger-state] TypeError: this.$_terms[key].slice is not a function
    31 Oct 00:54:50 - [warn] [node-red-contrib-home-assistant-websocket/poll-state] TypeError: this.$_terms[key].slice is not a function
    31 Oct 00:54:50 - [warn] [node-red-contrib-home-assistant-websocket/ha-zone] TypeError: this.$_terms[key].slice is not a function
    31 Oct 00:54:50 - [warn] [node-red-contrib-home-assistant-websocket/ha-entity] TypeError: this.$_terms[key].slice is not a function
    31 Oct 00:54:50 - [warn] [node-red-contrib-home-assistant-websocket/ha-fire-event] TypeError: this.$_terms[key].slice is not a function
    31 Oct 00:54:50 - [warn] [node-red-contrib-home-assistant-websocket/api-current-state] TypeError: this.$_terms[key].slice is not a function
    31 Oct 00:54:50 - [warn] [node-red-contrib-home-assistant-websocket/ha-get-entities] TypeError: this.$_terms[key].slice is not a function
    31 Oct 00:54:50 - [warn] [node-red-contrib-home-assistant-websocket/api-get-history] TypeError: this.$_terms[key].slice is not a function
    31 Oct 00:54:50 - [warn] [node-red-contrib-home-assistant-websocket/api-render-template] TypeError: this.$_terms[key].slice is not a function
    31 Oct 00:54:50 - [warn] [node-red-contrib-home-assistant-websocket/ha-wait-until] TypeError: this.$_terms[key].slice is not a function
    31 Oct 00:54:50 - [warn] [node-red-contrib-home-assistant-websocket/ha-api] TypeError: this.$_terms[key].slice is not a function
    31 Oct 00:54:50 - [warn] ------------------------------------------------------
    31 Oct 00:54:50 - [info] Settings file  : /home/pi/.node-red/settings.js
    ...

### Expected behavior

All nodes contained in the module should show up in th palette.

### Screenshots

![screenshot](https://user-images.githubusercontent.com/43565949/97766987-91d94600-1b19-11eb-8b68-ca7a56e67359.png)

### Example Flow

Does not apply.

### Environment (please complete the following information):

- Node Red Version: 1.2.2
- Node.js Version: v12.19.0
- NR Home Assistant Plugin Version: 0.27.4
- Custom Integration: v0.4.4
- Docker: nope

### Other (please complete the following information):

- Have you searched previous issues for duplicates?:

Yup, I did.
`/me a good boy ;)`

### Additional context

Does not apply.

**Comment by zachowj** [comment]
If you run `npm view joi` in `~/.node-red` what version does it show for the joi package?

**Comment by rbm78bln** [comment]
Sry, saw your question just now.

Here you go:

    pi@mqtt:~/.node-red$ npm view joi
    
    joi@17.3.0 | BSD-3-Clause | deps: 5 | versions: 204
    Object schema validation
    https://github.com/sideway/joi#readme
    
    keywords: schema, validation
    
    dist
    .tarball: https://registry.npmjs.org/joi/-/joi-17.3.0.tgz
    .shasum: f1be4a6ce29bc1716665819ac361dfa139fff5d2
    .integrity: sha512-Qh5gdU6niuYbUIUV5ejbsMiiFmBdw8Kcp8Buj2JntszCkCfxJ9Cz76OtHxOZMPXrt5810iDIXs+n1nNVoquHgg==
    .unpackedSize: 515.9 kB
    
    dependencies:
    @hapi/hoek: ^9.0.0        @hapi/topo: ^5.0.0        @sideway/address: ^4.1.0  @sideway/formula: ^3.0.0  @sideway/pinpoint: ^2.0.0 
    
    maintainers:
    - hueniverse <eran@hammer.io>
    
    dist-tags:
    9-beta: 9.0.0-9   latest: 17.3.0    node-0.x: 6.10.1  
    
    published a week ago by hueniverse <eran@hammer.io>
    pi@mqtt:~/.node-red$

**Comment by zachowj** [comment]
Try reinstalling this package using `npm install --force node-red-contrib-home-assistant-websocket`. At this moment I can't really think of a reason that the joi dependencies would be through this error.
