### ISSUE TITLE
Failure to load Server config node on Node v12

### ISSUE THREAD

**Issue by wsidl** [zachowj/node-red-contrib-home-assistant-websocket#286]
### Describe the bug

Not able to load package into NodeRed due to a few errors related to the Server config.

First is when nodes as saved and deployed to a flow, I get a few error messages about an incomplete GET request:

> You probably haven't deployed since adding a server. Do that for autocomplete to work.
> Cannot GET /homeassistant/<id>/entities

Second is when the changes are deployed, an error messages relating to the missing server node appears:

> Flows stopped due to missing node types.
>    server

After deployment, I return to the server config and all parameters are removed.

### To Reproduce

Steps to reproduce the behavior (using person state polling):

1. Add Poll State node to a flow
2. Edit for "Add New Server"
3. Following Form values:
  - "I am using the Home Assistant Add-on" = false
  - "Base URL" = "http://ip:8123"
  - "Access Token" = Generated from user profile under Advanced Settings
  - "Use Legacy API Password" = false
  - "Accept Unauthorized SSL Certificates" = false
  - "State Boolean" = "y|yes|true|on|home|open"
  - "Cache Autocomplete Results" = true

4. See first error appear (Cannot GET ...)
5. Set Properties in Node:
  - "Server" = "Home Assistant"
  - "Entity ID" = "person.name"
  - "Update Interval" = "60 seconds"
  - "If State" = "Is Not (alpha)a"
  - "Output on Changed" = true
  - "Output on Connect" = true
  - "Expose to Home Assistant" = false
6. Deploy
7. See second error appear ("Flows stopped... "). Debug window also displays the following message:
> "Credential type 'server' is not registered"
+
It's at this point the HA server properties are removed.

### Expected behavior

Expect to have a response from the poll state node to an attached debug node with a connection status under the poll state node.

### Screenshots

![image](https://user-images.githubusercontent.com/6453466/98139368-f9c0c100-1e78-11eb-8239-b91fabf76582.png)
![image](https://user-images.githubusercontent.com/6453466/98139431-0fce8180-1e79-11eb-8db2-0715da6c4ead.png)
![image](https://user-images.githubusercontent.com/6453466/98139991-b74bb400-1e79-11eb-9c4a-50f2daa22adf.png)

### Example Flow

[{"id":"717dbc5a.5d376c","type":"tab","label":"People","disabled":false,"info":""},{"id":"724722ed.7968bc","type":"debug","z":"717dbc5a.5d376c","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":510,"y":100,"wires":[]},{"id":"e0275529.7db748","type":"debug","z":"717dbc5a.5d376c","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":400,"y":480,"wires":[]},{"id":"485b2bd6.9fcbe4","type":"debug","z":"717dbc5a.5d376c","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":490,"y":300,"wires":[]},{"id":"70b723d9.2f637c","type":"catch","z":"717dbc5a.5d376c","name":"","scope":null,"uncaught":false,"x":260,"y":480,"wires":[["e0275529.7db748"]]},{"id":"a04bdf31.3afbf8","type":"debug","z":"717dbc5a.5d376c","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":490,"y":340,"wires":[]},{"id":"e3bf7645.83117","type":"poll-state","z":"717dbc5a.5d376c","name":"","server":"58cfb726.028608","version":1,"exposeToHomeAssistant":false,"haConfig":[{"property":"name","value":""},{"property":"icon","value":""}],"updateinterval":"60","updateIntervalUnits":"seconds","outputinitially":true,"outputonchanged":true,"entity_id":"person.name","state_type":"str","halt_if":"a","halt_if_type":"str","halt_if_compare":"is_not","outputs":2,"x":300,"y":320,"wires":[["485b2bd6.9fcbe4"],["a04bdf31.3afbf8"]]},{"id":"58cfb726.028608","type":"server","z":"","name":"Home Assistant","legacy":false,"addon":false,"rejectUnauthorizedCerts":true,"ha_boolean":"y|yes|true|on|home|open","connectionDelay":true,"cacheJson":true}]

### Environment (please complete the following information):

- Package Version: 0.27.4
- Node Red Version: 1.0.4
- Node.js Version: 12.16.1
- NR Home Assistant Plugin Version: N/A (not plugin)
- Is Node Red running in Docker: no

### Other (please complete the following information):

Possible duplicate: #225, but using much older version (last comment refers to #226, but this is not the same issue)

### Additional context

Logs from startup
```
4 Nov 08:46:45 - [info] Node-RED version: v1.0.4
4 Nov 08:46:45 - [info] Node.js  version: v12.16.1
4 Nov 08:46:45 - [info] Linux 4.19.97-v7+ arm LE
4 Nov 08:46:47 - [info] Loading palette nodes
4 Nov 08:46:54 - [warn] ------------------------------------------------------
4 Nov 08:46:54 - [warn] [node-red-contrib-home-assistant-websocket/server] Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /home/pi/.node-red/node_modules/home-assistant-js-websocket/dist/haws.umd.js
require() of ES modules is not supported.
require() of /home/pi/.node-red/node_modules/home-assistant-js-websocket/dist/haws.umd.js from /home/pi/.node-red/node_modules/node-red-contrib-home-assistant-websocket/lib/ha-websocket.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename haws.umd.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /home/pi/.node-red/node_modules/home-assistant-js-websocket/package.json.

```

**Comment by zachowj** [comment]
It all stems from one thing which has two possible causes that I can think of at the moment maybe more.

1. The home-assistant-js-websocket dependencies didn't get upgraded. You can test this by running `npm view home-assistant-js-websocket` in the `/home/pi/.node-red` directory. This should show version 5.7.0 installed. If not you can try reinstalling this package.

2. Node.js version 12.16.1 is not excepting conditional dist imports. This can be solved by upgrade node.js to the latest LTS for v12 or just upgrading to v14 LTS.

**Comment by wsidl** [comment]
1. ```
$ npm view home-assistant-js-websocket

home-assistant-js-websocket@5.7.0 | Apache-2.0 | deps: none | versions: 72
Home Assistant websocket client
```
2. Upgraded to v14 through NodeSource and now it works
