### ISSUE TITLE
Spamming my pihole dns server

### ISSUE THREAD

**Issue by Nobeernogman** [zachowj/node-red-contrib-home-assistant-websocket#288]
### Describe the bug

It seems to be that node-red-contrib-home-assistant-websocket is spamming my dns server. It started a few days ago. 
Pihole screenshot:
https://i.imgur.com/DJTdyRZ.png

### Expected behavior

No dns spam.

### Screenshots

https://i.imgur.com/DJTdyRZ.png

### Environment (please complete the following information):

- Node Red Version: 1..2.3
- Node.js Version: not sure?
- NR Home Assistant Plugin Version: 0.27.4
- Is Node Red running in Docker: Yes,
NR and HA core in docker (unraid server)

### Other (please complete the following information):

yes

### Additional context

A guy on reddit told me to file a bug here:
https://www.reddit.com/r/nodered/comments/jr3r8w/nodered_is_spamming_my_dns_server/

**Comment by zachowj** [comment]
When this started happening did you import a flow from someone else that may have contained another server config? Check the number of server configs you have in NR.
