### ISSUE TITLE
"for" duration in the current state node

### ISSUE THREAD

**Issue by jschwalbe** [zachowj/node-red-contrib-home-assistant-websocket#289]
### Is your feature request related to a problem? Please describe.

The `events: state` node had a `for: ` value added and it's absolutely amazing. I think it'd be amazing to have it in the `current state` node, or in any node that can be the second node. 
The reason is that I have a flow in which I would like to ask the question "If the light is on for 5 minutes (currently possible with the `events: state` node) then ask if the motion sensor has been **off for 4 minutes** and if yes -> turn off the light". Currently it's not possible to use the `for` other than the first node in the flow.
Make sense? It's hard to convey so pls let me know if it didn't and I can try again.
Thank you!

### Describe the solution you'd like

`for: ` duration for the `current state` node
### Describe alternatives you've considered

haven't thought of any

### Additional context

none

**Comment by jschwalbe** [comment]
fixed?

**Comment by zachowj** [comment]
![image](https://user-images.githubusercontent.com/37859597/99034199-79adf180-2531-11eb-8fcb-49aa1c5bdd6c.png)

```
[{"id":"75d248ed.adbb58","type":"server-state-changed","z":"ffbd7f06.4a014","name":"","version":1,"exposeToHomeAssistant":false,"haConfig":[{"property":"name","value":""},{"property":"icon","value":""}],"entityidfilter":"light.light1","entityidfiltertype":"exact","outputinitially":false,"state_type":"str","haltifstate":"on","halt_if_type":"str","halt_if_compare":"is","outputs":2,"output_only_on_state_change":true,"for":"5","forType":"num","forUnits":"minutes","ignorePrevStateNull":false,"ignorePrevStateUnknown":false,"ignorePrevStateUnavailable":false,"ignoreCurrentStateUnknown":false,"ignoreCurrentStateUnavailable":false,"x":254,"y":1856,"wires":[["d244f0b4.35f23"],[]]},{"id":"d244f0b4.35f23","type":"api-current-state","z":"ffbd7f06.4a014","name":"","version":1,"outputs":1,"halt_if":"","halt_if_type":"str","halt_if_compare":"is","override_topic":false,"entity_id":"sensor.motion","state_type":"str","state_location":"","override_payload":"none","entity_location":"data","override_data":"msg","blockInputOverrides":false,"x":520,"y":1856,"wires":[["60a0144.33cbbec"]]},{"id":"60a0144.33cbbec","type":"switch","z":"ffbd7f06.4a014","name":"off for 5 mins?","property":"data.timeSinceChangedMs","propertyType":"msg","rules":[{"t":"gte","v":"300000","vt":"str"}],"checkall":"true","repair":false,"outputs":1,"x":736,"y":1856,"wires":[["ac581ef0.80b22"]]},{"id":"ac581ef0.80b22","type":"debug","z":"ffbd7f06.4a014","name":"do stuff","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"payload","targetType":"msg","statusVal":"","statusType":"auto","x":892,"y":1856,"wires":[]}]
```

**Comment by jschwalbe** [comment]
That's a good workaround! Thank you so much

**Comment by jschwalbe** [comment]
Sorry to revive a super old issue but if someone were to fork your code and try to add an a `for duration` to the current state or Trigger state nodes, where would they begin? I am not the best with coding, but I can sometimes figure my way through things. I think having a "for" duration would be so awesome for these two nodes and I'm willing to try to make it work!
