### ISSUE TITLE
Events: State: Can we add a conditional group feature

### ISSUE THREAD

**Issue by a120578270** [zachowj/node-red-contrib-home-assistant-websocket#291]
### Is your feature request related to a problem? Please describe.

Multiple human bodies in the bedroom can be turned off only when they are fully unmanned！

### Describe the solution you'd like

stay events:state You can add multiple entity IDs to the component, and add any and all options. The function is to execute when multiple entity IDs are satisfied and execute when all of them are satisfied!

### Describe alternatives you've considered

none

### Additional context
![image](https://user-images.githubusercontent.com/58241282/99771574-56440180-2b44-11eb-9a05-41ea716cec23.png)

**Comment by zachowj** [comment]
If I understand you correctly this can already be accomplished using the trigger-state node.

Any:
![image](https://user-images.githubusercontent.com/37859597/99834148-f9caed00-2b17-11eb-92a9-9eb8b757ef49.png)

All:
![image](https://user-images.githubusercontent.com/37859597/99834203-0f401700-2b18-11eb-8dc5-8d322ddf374d.png)

**Comment by a120578270** [comment]
> 如果我理解正确，那么可以使用触发状态节点来完成此操作。
> 
> 任何：
> ![图片](https://user-images.githubusercontent.com/37859597/99834148-f9caed00-2b17-11eb-92a9-9eb8b757ef49.png)
> 
> 所有：
> ![图片](https://user-images.githubusercontent.com/37859597/99834203-0f401700-2b18-11eb-8dc5-8d322ddf374d.png)

If the plug-in can implement the above work, can you add a time to the plug-in to keep!
![image](https://user-images.githubusercontent.com/58241282/99836278-cf714200-2ba0-11eb-91db-68dbf2656030.png)

**Comment by zachowj** [comment]
I have no plans to add `For` to the trigger-state node due to the complexities that it will add to the node. Using a `trigger` node can accomplish the same thing that the `For` accomplishes in the event-state node.

![image](https://user-images.githubusercontent.com/37859597/99837037-ce4a0180-2b1b-11eb-8041-41ec9a91dd86.png)

```
[{"id":"6f585dca.67cd34","type":"trigger-state","z":"ffbd7f06.4a014","name":"","exposeToHomeAssistant":false,"haConfig":[{"property":"name","value":""},{"property":"icon","value":""}],"entityid":"sensor.one,sensor.two","entityidfiltertype":"exact","debugenabled":false,"constraints":[{"targetType":"entity_id","targetValue":"sensor.one","propertyType":"current_state","comparatorType":"is","comparatorValueDatatype":"str","comparatorValue":"off","propertyValue":"new_state.state"},{"targetType":"entity_id","targetValue":"sensor.two","propertyType":"current_state","comparatorType":"is","comparatorValueDatatype":"str","comparatorValue":"off","propertyValue":"new_state.state"}],"outputs":2,"customoutputs":[],"outputinitially":false,"state_type":"str","x":204,"y":2176,"wires":[["b775b624.ebb3a8"],["b775b624.ebb3a8"]]},{"id":"d64b66dc.39c358","type":"debug","z":"ffbd7f06.4a014","name":"do things","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"payload","targetType":"msg","statusVal":"","statusType":"auto","x":572,"y":2176,"wires":[]},{"id":"b775b624.ebb3a8","type":"trigger","z":"ffbd7f06.4a014","name":"","op1":"","op2":"","op1type":"nul","op2type":"payl","duration":"1","extend":false,"overrideDelay":false,"units":"s","reset":"on","bytopic":"all","topic":"topic","outputs":1,"x":428,"y":2176,"wires":[["d64b66dc.39c358"]]}]
```

**Comment by a120578270** [comment]
> ```
> [{"id":"6f585dca.67cd34","type":"trigger-state","z":"ffbd7f06.4a014","name":"","exposeToHomeAssistant":false,"haConfig":[{"property":"name","value":""},{"property":"icon","value":""}],"entityid":"sensor.one,sensor.two","entityidfiltertype":"exact","debugenabled":false,"constraints":[{"targetType":"entity_id","targetValue":"sensor.one","propertyType":"current_state","comparatorType":"is","comparatorValueDatatype":"str","comparatorValue":"off","propertyValue":"new_state.state"},{"targetType":"entity_id","targetValue":"sensor.two","propertyType":"current_state","comparatorType":"is","comparatorValueDatatype":"str","comparatorValue":"off","propertyValue":"new_state.state"}],"outputs":2,"customoutputs":[],"outputinitially":false,"state_type":"str","x":204,"y":2176,"wires":[["b775b624.ebb3a8"],["b775b624.ebb3a8"]]},{"id":"d64b66dc.39c358","type":"debug","z":"ffbd7f06.4a014","name":"do things","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"payload","targetType":"msg","statusVal":"","statusType":"auto","x":572,"y":2176,"wires":[]},{"id":"b775b624.ebb3a8","type":"trigger","z":"ffbd7f06.4a014","name":"","op1":"","op2":"","op1type":"nul","op2type":"payl","duration":"1","extend":false,"overrideDelay":false,"units":"s","reset":"on","bytopic":"all","topic":"topic","outputs":1,"x":428,"y":2176,"wires":[["d64b66dc.39c358"]]}]
> ```

Trigger: State is not a plug-in that can be used as a trigger node. What node should he use in front of him?

**Comment by a120578270** [comment]
> If I understand you correctly this can already be accomplished using the trigger-state node.
> 
> Any:
> ![image](https://user-images.githubusercontent.com/37859597/99834148-f9caed00-2b17-11eb-92a9-9eb8b757ef49.png)
> 
> All:
> ![image](https://user-images.githubusercontent.com/37859597/99834203-0f401700-2b18-11eb-8dc5-8d322ddf374d.png)

![image](https://user-images.githubusercontent.com/58241282/99926024-2894cd80-2d7b-11eb-8f43-d0b1de3ce95a.png)
Why Entity ID cannot be filled in the conditions?

**Comment by a120578270** [comment]
> If I understand you correctly this can already be accomplished using the trigger-state node.
> 
> Any:
> ![image](https://user-images.githubusercontent.com/37859597/99834148-f9caed00-2b17-11eb-92a9-9eb8b757ef49.png)
> 
> All:
> ![image](https://user-images.githubusercontent.com/37859597/99834203-0f401700-2b18-11eb-8dc5-8d322ddf374d.png)
Why Entity ID cannot be filled in the conditions?
![image](https://user-images.githubusercontent.com/58241282/99926147-9f31cb00-2d7b-11eb-8a0a-e86aff299fc5.png)

**Comment by a120578270** [comment]
Why Entity ID cannot be filled in the conditions?
![image](https://user-images.githubusercontent.com/58241282/99926923-57f90980-2d7e-11eb-90e3-e19a94bd0b23.png)

**Comment by a120578270** [comment]
Why Entity ID cannot be filled in the conditions?
![image](https://user-images.githubusercontent.com/58241282/99926986-9393d380-2d7e-11eb-9ed8-b6496d6cc55d.png)

**Comment by zachowj** [comment]
> Trigger: State is not a plug-in that can be used as a trigger node. What node should he use in front of him?

The input of a trigger-state node is for testing or enable/disabling the node. It will trigger based on events like the events-state node.

> Why Entity ID cannot be filled in the conditions?

Do you have any javascript errors in the browsers?

**Comment by a120578270** [comment]
> > Trigger: State is not a plug-in that can be used as a trigger node. What node should he use in front of him?
> 
> The input of a trigger-state node is for testing or enable/disabling the node. It will trigger based on events like the events-state node.
> 
> > Why Entity ID cannot be filled in the conditions?
> 
> Do you have any javascript errors in the browsers?

Uncaught (in promise) DOMException: Failed to execute 'define' on 'CustomElementRegistry': the name "dom-module" has already been used with this registry
    at https://unpkg.com/@polymer/polymer@3.4.1/lib/elements/dom-module.js?module:164:16

Uncaught (in promise) TypeError: Cannot read property 'querySelector' of null
    at HTMLElement._updateElement (secondaryinfo-entity-row.js:38)

I don't know if this is an error, the input field is a prohibited sign!

**Comment by a120578270** [comment]
After updating version 0.27.6, trigger: The Conditions option in the State interface is not found
![image](https://user-images.githubusercontent.com/58241282/100992489-3292a980-358f-11eb-9995-2dbdd41c8131.png)

**Comment by zachowj** [comment]
> Uncaught (in promise) DOMException: Failed to execute 'define' on 'CustomElementRegistry': the name "dom-module" has already been used with this registry
> at https://unpkg.com/@polymer/polymer@3.4.1/lib/elements/dom-module.js?module:164:16
> 
> Uncaught (in promise) TypeError: Cannot read property 'querySelector' of null
> at HTMLElement._updateElement (secondaryinfo-entity-row.js:38)

Those errors are from the HA page. I am assuming you're using the NR add-on and when you view it on the HA page it's in an iframe which is where you would have to look for javascript errors or open NR in a standard page and check there.

**Comment by a120578270** [comment]
> I have no plans to add `For` to the trigger-state node due to the complexities that it will add to the node. Using a `trigger` node can accomplish the same thing that the `For` accomplishes in the event-state node.
> 
> ![image](https://user-images.githubusercontent.com/37859597/99837037-ce4a0180-2b1b-11eb-8041-41ec9a91dd86.png)
> 
> ```
> [{"id":"6f585dca.67cd34","type":"trigger-state","z":"ffbd7f06.4a014","name":"","exposeToHomeAssistant":false,"haConfig":[{"property":"name","value":""},{"property":"icon","value":""}],"entityid":"sensor.one,sensor.two","entityidfiltertype":"exact","debugenabled":false,"constraints":[{"targetType":"entity_id","targetValue":"sensor.one","propertyType":"current_state","comparatorType":"is","comparatorValueDatatype":"str","comparatorValue":"off","propertyValue":"new_state.state"},{"targetType":"entity_id","targetValue":"sensor.two","propertyType":"current_state","comparatorType":"is","comparatorValueDatatype":"str","comparatorValue":"off","propertyValue":"new_state.state"}],"outputs":2,"customoutputs":[],"outputinitially":false,"state_type":"str","x":204,"y":2176,"wires":[["b775b624.ebb3a8"],["b775b624.ebb3a8"]]},{"id":"d64b66dc.39c358","type":"debug","z":"ffbd7f06.4a014","name":"do things","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"payload","targetType":"msg","statusVal":"","statusType":"auto","x":572,"y":2176,"wires":[]},{"id":"b775b624.ebb3a8","type":"trigger","z":"ffbd7f06.4a014","name":"","op1":"","op2":"","op1type":"nul","op2type":"payl","duration":"1","extend":false,"overrideDelay":false,"units":"s","reset":"on","bytopic":"all","topic":"topic","outputs":1,"x":428,"y":2176,"wires":[["d64b66dc.39c358"]]}]
> ```

Through testing, this process cannot be completed when multiple device states meet the conditions and remain for a certain amount of time!

**Comment by a120578270** [comment]
> > I have no plans to add `For` to the trigger-state node due to the complexities that it will add to the node. Using a `trigger` node can accomplish the same thing that the `For` accomplishes in the event-state node.
> > ![image](https://user-images.githubusercontent.com/37859597/99837037-ce4a0180-2b1b-11eb-8041-41ec9a91dd86.png)
> > ```
> > [{"id":"6f585dca.67cd34","type":"trigger-state","z":"ffbd7f06.4a014","name":"","exposeToHomeAssistant":false,"haConfig":[{"property":"name","value":""},{"property":"icon","value":""}],"entityid":"sensor.one,sensor.two","entityidfiltertype":"exact","debugenabled":false,"constraints":[{"targetType":"entity_id","targetValue":"sensor.one","propertyType":"current_state","comparatorType":"is","comparatorValueDatatype":"str","comparatorValue":"off","propertyValue":"new_state.state"},{"targetType":"entity_id","targetValue":"sensor.two","propertyType":"current_state","comparatorType":"is","comparatorValueDatatype":"str","comparatorValue":"off","propertyValue":"new_state.state"}],"outputs":2,"customoutputs":[],"outputinitially":false,"state_type":"str","x":204,"y":2176,"wires":[["b775b624.ebb3a8"],["b775b624.ebb3a8"]]},{"id":"d64b66dc.39c358","type":"debug","z":"ffbd7f06.4a014","name":"do things","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"payload","targetType":"msg","statusVal":"","statusType":"auto","x":572,"y":2176,"wires":[]},{"id":"b775b624.ebb3a8","type":"trigger","z":"ffbd7f06.4a014","name":"","op1":"","op2":"","op1type":"nul","op2type":"payl","duration":"1","extend":false,"overrideDelay":false,"units":"s","reset":"on","bytopic":"all","topic":"topic","outputs":1,"x":428,"y":2176,"wires":[["d64b66dc.39c358"]]}]
> > ```
> 
> Through testing, this process cannot be completed when multiple device states meet the conditions and remain for a certain amount of time!

When a hold is triggered, other device state changes do not interrupt the hold time!

**Comment by mdegat01** [comment]
Not sure if you're still looking for an answer here or moved on but just an FYI, in regex the `|` symbol means "or". So I think you can use that to solve the problem I believe you're trying to solve like this:
![Screen Shot 2021-01-14 at 1 37 57 AM](https://user-images.githubusercontent.com/2037026/104553723-288dad00-5609-11eb-9d9b-258fa4f0ed45.png)
```json
[{"id":"bd1b8071.6f57c","type":"trigger-state","z":"d32305d3.34daf8","name":"Multi-sensor triggering","server":"cc03735a.94933","exposeToHomeAssistant":false,"haConfig":[{"property":"name","value":""},{"property":"icon","value":""}],"entityid":"sensor\\.a|sensor\\.b|sensor\\.c","entityidfiltertype":"regex","debugenabled":false,"constraints":[{"targetType":"entity_id","targetValue":"sensor.a","propertyType":"current_state","comparatorType":"is","comparatorValueDatatype":"str","comparatorValue":"desired_state","propertyValue":"new_state.state"},{"targetType":"entity_id","targetValue":"sensor.b","propertyType":"current_state","comparatorType":"is","comparatorValueDatatype":"str","comparatorValue":"desired_state","propertyValue":"new_state.state"},{"targetType":"entity_id","targetValue":"sensor.c","propertyType":"current_state","comparatorType":"is","comparatorValueDatatype":"str","comparatorValue":"desired_state","propertyValue":"new_state.state"}],"outputs":2,"customoutputs":[],"outputinitially":false,"state_type":"str","x":530,"y":380,"wires":[[],[]]},{"id":"cc03735a.94933","type":"server","name":"Home Assistant","legacy":false,"addon":true,"rejectUnauthorizedCerts":true,"ha_boolean":"y|yes|true|on|home|open","connectionDelay":true,"cacheJson":true}]
```

What this will do is listen for changes in state to `sensor.a`, `sensor.b` or `sensor.c`. But it will only send a message to its `allowed` output if all 3 sensors are in the correct state.

I know the syntax is a bit wonky since its regex instead of normal text so you have to do things like escape periods with a backslash. But I think it meets your use case, no?

**Comment by a120578270** [comment]
I'm glad you reply to my confusion I just try to use | symbol, but the result is still the same! The problem is that once all three sensor states are triggered correctly, if I need to hold all three sensor states for 30 seconds before I execute, and one of the sensor states changes in the middle of the process, the hold plugin will not terminate the process, but continue executing, causing an error!

**Comment by mdegat01** [comment]
Ah I understand, missed that. So I think I see the confusion then. The trigger node has this option here:
![Screen Shot 2021-01-14 at 2 42 38 AM](https://user-images.githubusercontent.com/2037026/104559407-59beab00-5612-11eb-8e91-543896b88a75.png)

What this option does is when the trigger node receives a message with `payload` set to a specific state then it will reset the trigger which prevents it from sending the second message after the specified amount of time. This is what Kermit was using in the example to try and block the trigger from continuing. That's also why the example connected both the `allowed` and `blocked` outputs to the trigger node since the `payload` is set to the state of the entity that triggered it.

Since I'm guessing your entities aren't actually `sensor.one`, `sensor.two`, etc. you are going to have to set this field yourself. If your sensors have exactly two possible states (like a binary sensor for example) then set the conditionals in the trigger node to the good state and set the `reset if payload equals` field in the trigger node to the bad state.

If your sensors have more then two possible states then you'll need to leverage the other mechanism for resetting the trigger node, by passing it a message that has the `reset` field set to something. Continuing off my example above you can do that like this:
![Screen Shot 2021-01-14 at 2 51 06 AM](https://user-images.githubusercontent.com/2037026/104560113-642d7480-5613-11eb-98ab-2dd43d394196.png)
```json
[{"id":"bd1b8071.6f57c","type":"trigger-state","z":"a74fee2d.ac9068","name":"Multi-sensor triggering","server":"cc03735a.94933","exposeToHomeAssistant":false,"haConfig":[{"property":"name","value":""},{"property":"icon","value":""}],"entityid":"sensor\\.a|sensor\\.b|sensor\\.c","entityidfiltertype":"regex","debugenabled":false,"constraints":[{"targetType":"entity_id","targetValue":"sensor.a","propertyType":"current_state","comparatorType":"is","comparatorValueDatatype":"str","comparatorValue":"desired_state","propertyValue":"new_state.state"},{"targetType":"entity_id","targetValue":"sensor.b","propertyType":"current_state","comparatorType":"is","comparatorValueDatatype":"str","comparatorValue":"desired_state","propertyValue":"new_state.state"},{"targetType":"entity_id","targetValue":"sensor.c","propertyType":"current_state","comparatorType":"is","comparatorValueDatatype":"str","comparatorValue":"desired_state","propertyValue":"new_state.state"}],"outputs":2,"customoutputs":[],"outputinitially":false,"state_type":"str","x":920,"y":1060,"wires":[["bd81d4d4.518fd"],["97580a87.c8ee28"]]},{"id":"bd81d4d4.518fd","type":"trigger","z":"a74fee2d.ac9068","name":"30 seconds","op1":"","op2":"","op1type":"nul","op2type":"payl","duration":"30","extend":false,"overrideDelay":false,"units":"s","reset":"","bytopic":"all","topic":"topic","outputs":1,"x":1270,"y":1060,"wires":[["94848cfb.536af8"]]},{"id":"97580a87.c8ee28","type":"change","z":"a74fee2d.ac9068","name":"Set reset","rules":[{"t":"set","p":"reset","pt":"msg","to":"true","tot":"bool"}],"action":"","property":"","from":"","to":"","reg":false,"x":1100,"y":1100,"wires":[["bd81d4d4.518fd"]]},{"id":"94848cfb.536af8","type":"debug","z":"a74fee2d.ac9068","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","statusVal":"","statusType":"auto","x":1450,"y":1060,"wires":[]},{"id":"cc03735a.94933","type":"server","name":"Home Assistant","legacy":false,"addon":true,"rejectUnauthorizedCerts":true,"ha_boolean":"y|yes|true|on|home|open","connectionDelay":true,"cacheJson":true}]
```

Now when a message comes out of the `blocked` output `reset` gets added which then stops the trigger node from proceeding.

**Comment by a120578270** [comment]
That's OK. Thank you very much! But I still hope that this form of trigger keeping can be integrated into the plug-in to have a better experience! There is also the previous srigger: state node entity ID still can't be filled in normally. I didn't find the error you said I read. Now I can only write it by directly changing the code on the page!
![image](https://user-images.githubusercontent.com/58241282/104562378-3d0e8b80-5683-11eb-9c5d-6427633c9c0f.png)

**Comment by a120578270** [comment]
That's OK. Thank you very much! But I still hope that this form of trigger keeping can be integrated into the plug-in to have a better experience! There is also the previous srigger: state node entity ID still can't be filled in normally. I didn't find the error you said I read. Now I can only write it by directly changing the code on the page!
![image](https://user-images.githubusercontent.com/58241282/104562378-3d0e8b80-5683-11eb-9c5d-6427633c9c0f.png)

**Comment by zachowj** [comment]
In the screenshot above I noticed you're still running version 0.20.8 of Node-RED. Try upgrade to the version 1 branch and see if that fixes any of your UI issues. I don't test on that version of NR anymore.
