### ISSUE TITLE
Output on Connect do not work after restart of HA

### ISSUE THREAD

**Issue by RestOp** [zachowj/node-red-contrib-home-assistant-websocket#293]
### Describe the bug

I used Event Node with any input boolean to detect that HA or Node-Red or both were restarted
![image](https://user-images.githubusercontent.com/46259141/99878339-f19cab80-2c04-11eb-9813-953c76c4dd83.png)
![image](https://user-images.githubusercontent.com/46259141/99878369-29a3ee80-2c05-11eb-9188-b5c4aa0647a7.png)
on connect i get message, send me a telegram and make a lot of actions after restart.
I know for sure that it works till 114 HA and this NR (currently i have working raspberry with this version and it works there)
![image](https://user-images.githubusercontent.com/46259141/99878385-49d3ad80-2c05-11eb-8966-00691627b8bb.png)

Now i made new install HA 118 and NR  7.2.10 on new Rapsberry and it do not work. 
It works only if i make FULL Deloy. On restart i get yellow CONNECTING and then RUNNING with no further message
![image](https://user-images.githubusercontent.com/46259141/99878426-87d0d180-2c05-11eb-9dad-627ce1cf995d.png)

### To Reproduce

1. Restart Home Assistant
2. Wait till node connects
3. Wait for message with actual state
4. See that there is no message came and node is just running

### Expected behavior

Node sent message after restart of РФ on connect with NR

### Screenshots

Above in describtion

### Example Flow

```
`[{"id":"6580c804.984c68","type":"server-state-changed","z":"93133afd.ad6e88","name":"Fake Node","server":"f39df34a.e72b7","version":1,"exposeToHomeAssistant":false,"haConfig":[{"property":"name","value":""},{"property":"icon","value":""}],"entityidfilter":"input_boolean.fake","entityidfiltertype":"exact","outputinitially":true,"state_type":"str","haltifstate":"","halt_if_type":"str","halt_if_compare":"is","outputs":1,"output_only_on_state_change":false,"for":"","forType":"num","forUnits":"minutes","ignorePrevStateNull":false,"ignorePrevStateUnknown":false,"ignorePrevStateUnavailable":false,"ignoreCurrentStateUnknown":false,"ignoreCurrentStateUnavailable":false,"x":1180,"y":1000,"wires":[[]]},{"id":"f39df34a.e72b7","type":"server","name":"Home Assistant Websocket","legacy":false,"addon":false,"rejectUnauthorizedCerts":true,"ha_boolean":"y|yes|true|on|home|open","connectionDelay":true,"cacheJson":true}]`
```

### Environment (please complete the following information):

- Node Red Version: 1.2.5
- NR Home Assistant Plugin Version: 7.2.10
- Is Node Red running in Docker: HA addon

### Other (please complete the following information):

Yes, but found nothing

### Additional context

Maybe you could advice me another way to detect that NR and HA are ready (after restart of HA or NR or both)?

Thanks a lot

**Comment by zachowj** [comment]
Assuming `input_boolean.fake` is a real entity in HA then this should still work. I just want to confirm the understanding that `Output on Connect` only outputs the first time NR connects to HA after NR has been started, not on each reconnection to HA, or on a redeploy of that event node.

The way I would recommend checking if HA has restarted after a reconnection to HA is <https://zachowj.github.io/node-red-contrib-home-assistant-websocket/cookbook/starting-flow-after-home-assistant-restart.html>

To see when NR has restart use an inject node.

![image](https://user-images.githubusercontent.com/37859597/100363714-fcaf5d00-2fb1-11eb-8a82-ffc806d7b42f.png)
```
[{"id":"4d781321.ffc70c","type":"inject","z":"56b1c979.b2c618","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":true,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":164,"y":1328,"wires":[["1cf3ac41.a9a154"]]},{"id":"1cf3ac41.a9a154","type":"debug","z":"56b1c979.b2c618","name":"NR has restarted","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"payload","targetType":"msg","statusVal":"","statusType":"auto","x":360,"y":1328,"wires":[]}]
```

**Comment by RestOp** [comment]
> Assuming `input_boolean.fake` is a real entity in HA then this should still work. I just want to confirm the understanding that `Output on Connect` only outputs the first time NR connects to HA after NR has been started, not on each reconnection to HA, or on a redeploy of that event node.

Yes real entity.
But it do not work ((( It was warking **always** when i soft restarted HA, i got new message, but now it shows only running...

One mor proof, there is a member that have the same issure, more to say i saw on some other place the same problem.
https://community.home-assistant.io/t/output-on-connect-do-not-work-after-restart-of-ha/247455

> The way I would recommend checking if HA has restarted after a reconnection to HA is https://zachowj.github.io/node-red-contrib-home-assistant-websocket/cookbook/starting-flow-after-home-assistant-restart.html
> 
> To see when NR has restart use an inject node.
> 
> ![image](https://user-images.githubusercontent.com/37859597/100363714-fcaf5d00-2fb1-11eb-8a82-ffc806d7b42f.png)

I use it as trigger, but it is not a solution, because i have lot of nodes, for a small example
![image](https://user-images.githubusercontent.com/46259141/100669845-4acfb200-335e-11eb-99b0-35a5852f001c.png)
that needs to be checked at start.

**Comment by sphanley** [comment]
I'm experiencing the same issue - "Output on Connect" works on the initial connection when I hit Deploy, but if the connection to Home Assistant is disconnected and reconnected due to a reboot, it does not re-emit. I'm looking into workarounds, but it would be really helpful if it output on every reconnect.

**Comment by zachowj** [comment]
@sphanley `Output on Connect` only outputs on the first connection from NR to HA. If the connection is dropped for some reason, HA restart, net goes down between hosts, it doesn't output again.

<https://zachowj.github.io/node-red-contrib-home-assistant-websocket/node/events-state.html#output-on-connect>

If you want to run a flow every time NR connects to HA there are several options:
- Use a status node to watch the status of an HA event node and then trigger when it's `connected` or `running`
- Use an events: all node with the event type `ha_client` and then trigger when it's `connected` or `running`

**Comment by RestOp** [comment]
> only outputs on the first connection from NR to HA
In this case this function makes no sense! ;-((


> only outputs on the first connection from NR to HA. If the connection is dropped for some reason, HA restart, net goes down between hosts, it doesn't output again.

The problem, that it worked on HA 114 (and before) on NR 7.1.0 (i have actually one more have the system with this versions) fine as expected - also if HA rebooted!


> If you want to run a flow every time NR connects to HA there are several options:
> 
> * Use a status node to watch the status of an HA event node and then trigger when it's `connected` or `running`
> * Use an events: all node with the event type `ha_client` and then trigger when it's `connected` or `running`

So, please explain i do not undersnand how to do it.
I understand that i can use this node to check if it is connected
![image](https://user-images.githubusercontent.com/46259141/105489884-3fd93400-5cb4-11eb-853d-e39742342180.png)
it is ok.

But how do i tigger my State Node on this connect, for example this one
![image](https://user-images.githubusercontent.com/46259141/105489744-056f9700-5cb4-11eb-9487-8f56b53d3257.png)
?

**Comment by RestOp** [comment]
@zachowj Thanks! I know that way, but do not use it.
So i need to make 2 triggers for same operation, instead of one check mark? Oh, 2021 year outside and we make programing this way...  It's a pity!

Is there no way to make like it was before NR 7.1.0? It is really logical to start it every new connect.
In that way how it made now - it makes no sense, i can find no case how can be really used only on first connect.

**Comment by zachowj** [comment]
Could it output on an ever re-connection to HA? I don't see why not. Add a feature request to [discussions](https://github.com/zachowj/node-red-contrib-home-assistant-websocket/discussions/categories/feature-request).

The functionality of the `Output on connect` has changed since Oct 2018. It was changed to wait for `services_loaded` and `running` when HA changed but other than that it has always only outputted on the connection after NR has loaded. You can use git blame to flow it back.

 https://github.com/zachowj/node-red-contrib-home-assistant-websocket/blob/5ecbc7f120968b774e9b9a5dcc0b12b8c6559c1a/nodes/events-state-changed/events-state-changed.js#L55

I rolled back a test setup to v0.22.3, the version the add-on was running on v6.3, to grab these screenshots.

Setup:
- This package: 0.22.3
- NR: 1.0.6
- HA: 2021.2.0.dev0

**After a deployment**

![chrome_IDbC6unm7D](https://user-images.githubusercontent.com/37859597/106219694-c8f9da80-618e-11eb-9e85-b61b5d3e24b7.png)

**After a restart of only HA**

![chrome_bQRua7DBDv](https://user-images.githubusercontent.com/37859597/106219740-e333b880-618e-11eb-9022-c9cb73dd185c.png)

**After a restart of only NR**

![chrome_OBQRdurLjl](https://user-images.githubusercontent.com/37859597/106219768-f181d480-618e-11eb-938f-7b2ebede3516.png)

**Comment by RestOp** [comment]
Thanks, made it https://github.com/zachowj/node-red-contrib-home-assistant-websocket/discussions/347
