### ISSUE TITLE
Current State node - state type boolean incorret if compared against number

### ISSUE THREAD

**Issue by DirkMu** [zachowj/node-red-contrib-home-assistant-websocket#295]
### Describe the bug

I am using the current state node to compare against a number (e.g. If state is lower than X). As state type I use boolean. Result will always be false although outputted to the true port. 

### To Reproduce

1. Wire an inject node to a current stat node
2. Use a numeric sensor from HA and use an if state that will be true
3. Set State type to boolean
4. Inject

### Expected behavior

I expected the current value to be compared against the value of the if state and in case of state type boolean a true if the comparison is true. Don't know if this a bug or rather a feature request. 
### Screenshots

![image](https://user-images.githubusercontent.com/53949754/100479840-aea07380-30ef-11eb-9203-90c24572b134.png)

![image](https://user-images.githubusercontent.com/53949754/100479850-b9f39f00-30ef-11eb-88c2-7e88754ab3a1.png)

### Example Flow

```
[{"id":"debaf620.834d88","type":"inject","z":"fa521260.40c1c","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":252,"y":592,"wires":[["1e82c2ad.6cca7d"]]},{"id":"1e82c2ad.6cca7d","type":"api-current-state","z":"fa521260.40c1c","name":"Dusk roof <2","server":"97a02c30.758c8","version":1,"outputs":2,"halt_if":"2","halt_if_type":"num","halt_if_compare":"lt","override_topic":false,"entity_id":"sensor.ws_dach_max_hell_daem","state_type":"habool","state_location":"payload","override_payload":"msg","entity_location":"data","override_data":"msg","blockInputOverrides":false,"x":454,"y":592,"wires":[["5e8b6208.1cef1c"],[]]},{"id":"5e8b6208.1cef1c","type":"debug","z":"fa521260.40c1c","name":"Dark","active":true,"tosidebar":true,"console":false,"tostatus":true,"complete":"true","targetType":"full","statusVal":"payload","statusType":"auto","x":626,"y":592,"wires":[]},{"id":"97a02c30.758c8","type":"server","name":"Home Assistant","legacy":false,"addon":false,"rejectUnauthorizedCerts":true,"ha_boolean":"y|yes|true|on|home|open","connectionDelay":true,"cacheJson":true}]
```

### Environment (please complete the following information):

- Node Red Version: 1.2.5
- Node.js Version: 10.23.0
- NR Home Assistant Plugin Version: 0.27.5
- Is Node Red running in Docker: yes

### Other (please complete the following information):

- Have you searched previous issues for duplicates?: yes

**Comment by zachowj** [comment]
State type is casting the state of the entity, not what the comparison is. If that is what you want can simply use a change node after each output to change the payload.

**Comment by DirkMu** [comment]
Yes and no. 

If it just casts the state why isn't outputted to the true port if the condition is met? Maybe I don't get. I assumed the condition is checked before casting and if met put to the true port. 

In my case, the brightness drops below 2 the payload should be put to the true port, right? Currently it is either not outputted at all or outputted to the false port. Looks like casting happens before comaprison?

**Comment by zachowj** [comment]
> I assumed the condition is checked before casting and if met put to the true port.

I thought it was in the documentation but I can't find it. The state is changed before the conditional is checked.

The original use case for state type was if you had multiple types of entities with different "on" states you could use it to convert them to `true` and in the conditional check if the state is true and not have to have multiple event nodes.

**Comment by DirkMu** [comment]
ok. If I get you right we are able to use multiple entity ids in an event node? Was not aware of that and cannot imagine how it will behave. 

Apparently it is not working in a current state node, right? However state type is used there, too. 

Nevertheless, I misunderstood the usage of the state type.
