### ISSUE TITLE
How to migrate to this module?

### ISSUE THREAD

**Issue by GoSpursGoNL** [zachowj/node-red-contrib-home-assistant-websocket#3]
Hi, thanks for creating this module. Could you explain how to migrate from node-red-contrib-home-assistant (with existing nodes using that module)? Because when I install your module, it tries to register nodes that already exist because the names are identical. And then I also can't uninstall the module anymore from the NR interface as it reports being 'in use'.

**Comment by zachowj** [comment]
Take a look at my post of the Home Assistant Forums 
https://community.home-assistant.io/t/node-red-contrib-home-assistant-websocket/71032/7

**Comment by GoSpursGoNL** [comment]
Thanks, that is clear. The problem I'm facing after that is that every time I want to edit a (re-imported) node, or add a new node related to HA, it says 'Cannot GET /undefinedhomeassistant/services' in a red popup/layover

I already fixed the credentials for the server.

**Comment by zachowj** [comment]
Are you running version 0.0.4? that was a bug back in version 0.0.2

**Comment by GoSpursGoNL** [comment]
Yes, I have 0.0.4. After rebooting NR the error is gone. Next issue is 'Error: [Home Assistant] Invalid access token or password.' with either the access token (copy/pasted from HA popup dialog right after generating) or the API password (copied from secrets.yaml and with the checkbox ticked).

I don't have IP-banning enabled in HA. How to debug this?

**Comment by GoSpursGoNL** [comment]
By the way, if I add 127.0.0.1 to the trusted networks of HA, and don't enter any password/key in NR, the connection to HA succeeds. So that confirms that I'm connecting to the correct HA url.

**Comment by GoSpursGoNL** [comment]
And finally after migrating, it mostly seems to work fine (still without key/token though). Except that I get one error: 'entity could not be found in cache for entity_id: light.huiskamer_kleurenlamp, sending empty payload'. I can confirm that the entity does exist in HA.

And when I create a new node, no prefilling is happening for the fields like 'domain', 'service' and 'entity id'.

**Comment by zachowj** [comment]
There's definitely at least something not right going on there. I believe most of the errors you are having have to do with node-RED not authenicating with Home Assistant. Not sure why when you entered an access token or password it won't connect. I get a new version out with possibly some better error reporting.

You found a bug. When it tries to connect to Home Assistant with a blank access token/password. From version 0.77.1 onward Home Assistant requires an access token or password to be able to authenticate via the WebSocket. So when you use a trusted network without a password the module is not catching the error and moving on as it has connected and authenticated. But really the connection has been rejected and it's not reacting to that. So I need to fix that and possibly just make the access token/password required. This is why it's probably showing connected on the nodes but the call service node is failing.

What version of nodejs are you running?
Are you running in docker?

**Comment by GoSpursGoNL** [comment]
I don't use docker and have nodejs 8.12. Node-Red is connected correctly to HA (but still without key/token) since my automations are working properly. Ok, I'll wait for your new version to first get the authentication with access token working and then we look into the other things.

I do think though that NR is connected properly to HA since I did see automations working.

**Comment by zachowj** [comment]
While working on your problem I found another bug. Can I confirm some things? 

Are you using a secure connection, https://, to connect to Home Assistant?
Let's use https://test.example.com:8123 as the address you normally use to connect to Home Assistant in a browser. Are you putting the whole URL, 'https://test.example.com:8123', into the Base URL field in node-RED? If you are not connecting via a secure HTTP connection do you have the whole 'http://test.example.com:8123' in the Base URL field?

Just checking because the bug I found was if you connect to a secure HTTP connection normally and forget the 's' or don't have the http:// at all on the Base Address it returns 'Error: [Home Assistant] Invalid access token or password.' even though it actually never makes it you actually trying to authenticate.

Just trying to hunt down these bugs thanks for the help.

**Comment by GoSpursGoNL** [comment]
I don't have https, I connect to http://localhost:8123 in the base url field.

**Comment by GoSpursGoNL** [comment]
No problems with authenticating anymore. I removed the trusted_network setting from Home Assistant and now in NR I can't connect without a access token, and can connect just fine with the access token. Thanks.

I do still 3 error messages after a full deploy, but it doesn't hurt, since the nodes that produce those errors are functioning just fine when they are triggered when needed later on.
