### ISSUE TITLE
Feature Request: show the seconds in the "called at" time

### ISSUE THREAD

**Issue by jschwalbe** [zachowj/node-red-contrib-home-assistant-websocket#305]
### Is your feature request related to a problem? Please describe.

When debugging, it's nice to know exactly when someone was triggered. Currently, the "called on" at the bottom of the node is only HH:mm, not HH:mm:ss. 

Also brought up here a few mo ago: https://discourse.nodered.org/t/show-seconds-on-last-trigger-time/31653

### Describe the solution you'd like
Show the "called at" with seconds.

**Comment by zachowj** [comment]
Feature requests are moving to the [discussion section](https://github.com/zachowj/node-red-contrib-home-assistant-websocket/discussions) on Github. If this still is a needed feature please open a new [discussion](https://github.com/zachowj/node-red-contrib-home-assistant-websocket/discussions/new) under the category "Feature Request".

Thank you for your contribution.
