### ISSUE TITLE
It seems boolean state isn't correctly processed for input_boolean types

### ISSUE THREAD

**Issue by ernout** [zachowj/node-red-contrib-home-assistant-websocket#312]
### Describe the bug

When you create a current state node or an event state node, and you select an input_boolean type entity, and then compare it with a boolean true/false, it seems to always evaluate to false.

This is also the case when you set State Type to boolean.

It works fine if I use strings and use on/off. But it feels a bit nicer to compare with booleans. No chance on typo's or spaces etc.

### To Reproduce

1. Create an input boolean
2. Create a flow that reads that input booleans value with an event input or current state node
3. Configure it like in the picture
4. Even if the state changes to on, it will output on the false output channel from the node

### Expected behavior

I would expect true to be routed to the true output, and false to be routed to the false output.

### Screenshots

<img width="517" alt="Screenshot 2020-12-22 at 21 55 27" src="https://user-images.githubusercontent.com/31383786/102932420-89114a80-44a0-11eb-8e10-9d191430aee8.png">

### Environment (please complete the following information):

- Node Red Version: 1.2.5
- Node.js Version: don't know
- NR Home Assistant Plugin Version: 0.27.8
- Is Node Red running in Docker: Ha addon 7.2.11

### Other (please complete the following information):

I searched for duplicates.

### Additional context
Not applicable

**Comment by zachowj** [comment]
There was an issue like this for the event state node prior to 0.27.9 which has been fixed. I'm currently getting the expected result using an input_boolean.

Update this package in NR and see if you still see the issues.

**Comment by ernout** [comment]
Thanks for the swift reply! You are totally right, its resolved now after I updated.
(next time I'll update first before I create a ticket).

Thanks!
