### ISSUE TITLE
Call Service doesn't work with multiple entity IDs in input_datetime.set_datetime

### ISSUE THREAD

**Issue by 0nikola1** [zachowj/node-red-contrib-home-assistant-websocket#323]
### Describe the bug
If there is multiple Entity ids in call service node HA doesn't do anything with it. 
In Ha log there is 
```Unable to find referenced entities input_datetime.room_left_turn_on,input_datetime.room_right_turn_on``` If I remove input_datetime.room_right_turn_on from call service it works.

### To Reproduce

1. Create a Call Service node. Set Domain: input_datetime, Service: set_datetime
2. Put multiple items in the Entity ID list. For example, input_datetime.room_left_turn_on,input_datetime.room_right_turn_on
3. Trigger call service node
### Expected behavior

All items in the Entity ID list would be sent to HA and it will show that info.

### Example Flow

```
[{"id":"803a2c11.cf7d9","type":"api-call-service","z":"2a6e9a55.34e7ae","name":"ON","server":"b39150fe.42f48","version":1,"debugenabled":true,"service_domain":"input_datetime","service":"set_datetime","entityId":"[\"input_datetime.room_left_turn_on\", \"input_datetime.room_right_turn_on\"]","data":"{\"time\":\"21:25:00\"}","dataType":"json","mergecontext":"","output_location":"","output_location_type":"none","mustacheAltTags":false,"x":1090,"y":2220,"wires":[[]]},{"id":"8abcbfe4.f38c08","type":"inject","z":"2a6e9a55.34e7ae","name":"","repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":940,"y":2220,"wires":[["803a2c11.cf7d9"]]},{"id":"b39150fe.42f48","type":"server","name":"Home Assistant","legacy":false,"addon":true,"rejectUnauthorizedCerts":true,"ha_boolean":"y|yes|true|on|home|open","connectionDelay":true,"cacheJson":true}]
```
### Environment (please complete the following information):

- Node Red Version: 1.2.5
- Node.js Version: [e.g. 12.16.1] not sure
- NR Home Assistant Plugin Version:    0.27.5(also tested with 0.29.0)
- Is Node Red running in Docker: HA addon v7.2.11

### Other (please complete the following information):

- Have you searched previous issues for duplicates?: Yes
### Additional context
Doesn't work from 0.115.6

**Comment by zachowj** [comment]
The entity id field is just a comma-delimited string. It doesn't need brackets or quotes.

```
input_datetime.room_left_turn_on, input_datetime.room_right_turn_on
```

**Comment by 0nikola1** [comment]
> 
> 
> The entity id field is just a comma-delimited string. It doesn't need brackets or quotes.
> 
> ```
> input_datetime.room_left_turn_on, input_datetime.room_right_turn_on
> ```

Oh, I forgot to deploy flow before copying it. I was trying other ways as it was working before this way.

```    [{"id":"6ed849c.137d638","type":"api-call-service","z":"5468228f.a83e5c","name":"ON","server":"b39150fe.42f48","version":1,"debugenabled":true,"service_domain":"input_datetime","service":"set_datetime","entityId":"input_datetime.room_left_turn_on, input_datetime.room_right_turn_on","data":"{\"time\":\"21:25:00\"}","dataType":"json","mergecontext":"","output_location":"","output_location_type":"none","mustacheAltTags":false,"x":490,"y":100,"wires":[[]]},{"id":"30d7fdbb.d4d8c2","type":"inject","z":"5468228f.a83e5c","name":"","repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":340,"y":100,"wires":[["6ed849c.137d638"]]},{"id":"b39150fe.42f48","type":"server","name":"Home Assistant","legacy":false,"addon":true,"rejectUnauthorizedCerts":true,"ha_boolean":"y|yes|true|on|home|open","connectionDelay":true,"cacheJson":true}]```

**Comment by zachowj** [comment]
looks like input_datetime is like the home assistant domain and it doesn't accept a comma-delimited string but only an array.

You can currently get around this by adding the array to the data field instead of the entity id field

```
{
  "entity_id":["input_datetime.room_left_turn_on","input_datetime.room_right_turn_on"],
  "time":"21:25:00"
}
```

**Comment by 0nikola1** [comment]
> 
> 
> looks like input_datetime is like the home assistant domain and it doesn't accept a comma-delimited string but only an array.
> 
> You can currently get around this by adding the array to the data field instead of the entity id field
> 
> ```
> {
>   "entity_id":["input_datetime.room_left_turn_on","input_datetime.room_right_turn_on"],
>   "time":"21:25:00"
> }
> ```

Thanks, it works this way.

**Comment by 0nikola1** [comment]
I just tested and it's same for input_number domain. Can you add that to fix too?
