### ISSUE TITLE
History node returns all entities when using "is" entity ID filter

### ISSUE THREAD

**Issue by sibbl** [zachowj/node-red-contrib-home-assistant-websocket#33]
**Describe the bug**
I'm using the package's get history node to get the last 15 min min of a specific entity.
When using the `entity ID` `is` `sensor.mysensor`, then all HA events from the last 15 min are returned.
The `includes` filter works as expected, but I'd love to make my requests faster with the API `filter_entity_id` URL parameter.

**To Reproduce**
1. Add a history node in Node RED
2. Configure it with a specific entity ID and the "is" filter
3. Specify a valid start and end time
4. All events from all entities within the time span are returned

**Expected behavior**
Only the events from the specified entity within the time span are returned.

**Environment (please complete the following information):**
 - Node Red Version: 0.19.5
 - NR Home Assistant Plugin Version: 0.1.3
 - Is Node Red running in Docker: yes, via the official HassIO addon in version 1.0.1

Thanks a lot! :)

**Comment by zachowj** [comment]
I really haven't looked that closely at the get-history node since starting to maintain this fork, but I did just take a quick glance at it and all the logic seems to be correct for the `is` selector to work correctly.

Could you try this simple flow and let me know if you only get `sun.sun` results. It should return the last 24 hours of `sun.sun` changes.

```
[{"id":"c57ec0c0.eefa4","type":"inject","z":"caad1953.456cd8","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":200,"y":480,"wires":[["bc540a0e.f36c58"]]},{"id":"8639cbbd.80a4b8","type":"debug","z":"caad1953.456cd8","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","x":490,"y":480,"wires":[]},{"id":"bc540a0e.f36c58","type":"api-get-history","z":"caad1953.456cd8","name":"","server":"2dad33ee.42bf5c","startdate":"","enddate":"","entityid":"sun.sun","entityidtype":"is","x":350,"y":480,"wires":[["8639cbbd.80a4b8"]]}]
```

Also, can you check if you happen to be passing in an empty `entityid` into the node because that will cause it to override the `entityid` of the node and show all events?

**Comment by sibbl** [comment]
The posted flow shows the same problem I described above. I get an array of the size of my entities, which appears to include all states from the last 24 hours of all entities:

![image](https://user-images.githubusercontent.com/866535/48155966-88bb9280-e2cc-11e8-91a9-9fea245e030c.png)

What else would help finding the problem? The following log output is shown within the HassIO log. I'm not sure if it's supposed to show query parameters though.

`18-11-07 19:29:17 INFO (MainThread) [hassio.api.proxy] /homeassistant/api/history/period/2018-11-06T19:29:17.728Z access from a0d7b954_nodered`

**Comment by sibbl** [comment]
Just a quick update: it seems that `end time` is also ignored when setting it.  Furthermore, I then tried to query HA via the "http response" node.

As it turns out, this also doesn't work. So I assume this works fine here. I guess there might be an issue with the HassIO proxy, so my next step was creating this issue there: https://github.com/home-assistant/hassio/issues/800

I'm looking forward to getting it resolved soon, but as far as it seems the problem is not part of this project. Thanks for your help and time though! :)

**Comment by zachowj** [comment]
A solution that may work for you in the interim is creating a second connection to Home Assistant just for the get-history nodes but setup it using a Long-Lived Access Tokens and an external IP address, e.g. 192.168.1.x.

**Comment by JumpMaster** [comment]
I've also ran into the same issue when trying to get the history of a node 30 seconds prior.

Using IS returns all entities for the specified time period.  Using includes ignores the end date.

**Comment by zachowj** [comment]
If you're using hass.io it looks like everything still applies and the ticket has no comments on it from hass.io. If you're not using hass.io please create a new issue.
