### ISSUE TITLE
Webhook created within Node-RED not visible in Home Assistant

### ISSUE THREAD

**Issue by wi8duy** [zachowj/node-red-contrib-home-assistant-websocket#337]
### Describe the bug

I have created a webhook as part of a node-red flow, and it is working, I can post to it, and see the "Received at" updating below the node. 

I however cannot see a similar event in Home Assistant's logbook, actually there is no webhook entity at all. The home-assistant logs themselves do not mention any webhook, apart from the `[custom_components.nodered.websocket] Webhook created: xxx`.

### To Reproduce

1. Create a sample webhook. 
2. Send a request.
3. Watch Home Assistant logbook and logs.

### Expected behavior

When watching the logbook, the webhook call should appear.

### Environment (please complete the following information):

- Node Red Version: 1.2.7
- Node.js Version: v10.23.1
- NR Home Assistant Plugin Version: 0.4.4
- Is Node Red running in Docker: yes

**Comment by zachowj** [comment]
Last I looked webhooks created in HA don't have a logbook entry.

If you want this functionality you can use the `logbook.log` service call.

<https://www.home-assistant.io/integrations/logbook/#custom-entries>

**Comment by wi8duy** [comment]
You are right, I confused the webhook trigger with the automation, and automations do have a logbook entry "XX has been triggered", while webhooks themselves are hidden from the interface.
