### ISSUE TITLE
Invalid format of Base URL: undefined

### ISSUE THREAD

**Issue by lemonka** [zachowj/node-red-contrib-home-assistant-websocket#338]
### Describe the bug

Cannot add HA server in Node RED

### To Reproduce

1. Place an Events: all node onto the workspace and edit the node. 
2. Click on the pencil icon next to the Server field.
3. Fill Base URL/API Pass, click Update
4. Error appear in form of Node-RED notification "Invalid format of Base URL: undefined"

### Expected behavior

HA server data is accepted

### Screenshots

N/A

### Example Flow

N/A

```
export goes here
```

### Environment (please complete the following information):
Node-RED version: v1.2.7
Node.js  version: v10.23.1
Linux 5.4.0-62-generic x64 LE

Node Red is running in Docker (image: nodered/node-red:latest)

### Other (please complete the following information):

- Have you searched previous issues for duplicates?:
Yes https://github.com/zachowj/node-red-contrib-home-assistant-websocket/issues/235

### Additional context

N/A

**Comment by zachowj** [comment]
What's the format of the URL you entered?

**Comment by lemonka** [comment]
I have tried different versions
http://10.1.1.100:48123
10.1.1.100:48123
domainname:48123

pon., 18 sty 2021, 23:21 użytkownik Jason <notifications@github.com>
napisał:

**Comment by lemonka** [comment]
I dont know why but I have reinstalled image and plugin and now plugin server window looks differently and connects to HA actually as it suppose to. It looks like for some reason, despite the fact that I have installed plugin from pallete which was for sure marked are recently updated it was downloading some old version....
