### ISSUE TITLE
poll-state runs at irregular intervals

### ISSUE THREAD

**Issue by cpiekacz** [zachowj/node-red-contrib-home-assistant-websocket#342]
### Describe the bug

poll-state node set to run every minute executes at irregular intervals, usually every 2 or 3 minutes 

### To Reproduce

1. Create input_number helper of max 60
2. Create a flow similar to example provided below
3. Look at history of changes

### Screenshots

History of the state changes to input_number invoked by poll-state node:

Changed to 25.0 by service input_number.decrement
11:26:43 PM - 15 minutes ago
Changed to 26.0 by service input_number.decrement
11:23:57 PM - 17 minutes ago
Changed to 27.0 by service input_number.decrement
11:20:44 PM - 21 minutes ago
Changed to 28.0 by service input_number.decrement
11:17:22 PM - 24 minutes ago
Changed to 29.0 by service input_number.decrement
11:14:13 PM - 27 minutes ago
Changed to 30.0 by service input_number.decrement
11:11:05 PM - 30 minutes ago
Changed to 31.0 by service input_number.decrement
11:09:42 PM - 32 minutes ago
Changed to 32.0 by service input_number.decrement
11:07:10 PM - 34 minutes ago
Changed to 33.0 by service input_number.decrement
11:04:57 PM - 36 minutes ago
Changed to 34.0 by service input_number.decrement
11:01:47 PM - 40 minutes ago
Changed to 35.0 by service input_number.decrement
10:58:43 PM - 43 minutes ago
Changed to 36.0 by service input_number.decrement
10:55:18 PM - 46 minutes ago
Changed to 37.0 by service input_number.decrement
10:51:54 PM - 49 minutes ago
Changed to 38.0 by service input_number.decrement
10:48:35 PM - 53 minutes ago
Changed to 39.0 by service input_number.decrement
10:45:31 PM - 56 minutes ago
Changed to 40.0 by service input_number.decrement
10:43:19 PM - 58 minutes ago
Changed to 41.0 by service input_number.decrement
10:39:58 PM - 1 hour ago
Changed to 42.0 by service input_number.decrement
10:36:34 PM - 1 hour ago
Changed to 43.0 by service input_number.decrement
10:33:17 PM - 1 hour ago
Changed to 44.0 by service input_number.decrement
10:30:23 PM - 1 hour ago
Changed to 45.0 by service input_number.decrement
10:27:09 PM - 1 hour ago
Changed to 46.0 by service input_number.decrement
10:23:53 PM - 1 hour ago
Changed to 47.0 by service input_number.decrement
10:21:49 PM - 1 hour ago
Changed to 48.0 by service input_number.decrement
10:18:33 PM - 1 hour ago
Changed to 49.0 by service input_number.decrement
10:15:31 PM - 1 hour ago
Changed to 50.0 by service input_number.decrement
10:11:51 PM - 1 hour ago
Changed to 51.0 by service input_number.decrement
10:09:44 PM - 2 hours ago
Changed to 52.0 by service input_number.decrement
10:07:52 PM - 2 hours ago
Changed to 53.0 by service input_number.decrement
10:06:10 PM - 2 hours ago
Changed to 54.0 by service input_number.decrement
10:02:27 PM - 2 hours ago
Changed to 55.0 by service input_number.decrement
10:00:18 PM - 2 hours ago
Changed to 56.0 by service input_number.decrement
9:57:12 PM - 2 hours ago
Changed to 57.0 by service input_number.decrement
9:55:02 PM - 2 hours ago
Changed to 58.0 by service input_number.decrement
9:51:46 PM - 2 hours ago
Changed to 59.0 by service input_number.decrement
9:48:47 PM - 2 hours ago

### Example Flow

```
[{"id":"dd48dcb1.4448c","type":"poll-state","z":"13d87d3c.2b8b43","name":"","server":"ba0d3ced.3f2b6","version":1,"exposeToHomeAssistant":false,"haConfig":[{"property":"name","value":""},{"property":"icon","value":""}],"updateinterval":"60","updateIntervalUnits":"seconds","outputinitially":false,"outputonchanged":false,"entity_id":"input_number.youtube_timer","state_type":"str","halt_if":"0","halt_if_type":"num","halt_if_compare":"gt","outputs":2,"x":270,"y":540,"wires":[["fc2ddac2.189698"],[]]},{"id":"fc2ddac2.189698","type":"api-call-service","z":"13d87d3c.2b8b43","name":"","server":"ba0d3ced.3f2b6","version":1,"debugenabled":false,"service_domain":"input_number","service":"decrement","entityId":"input_number.youtube_timer","data":"","dataType":"json","mergecontext":"","output_location":"","output_location_type":"none","mustacheAltTags":false,"x":590,"y":540,"wires":[[]]},{"id":"ba0d3ced.3f2b6","type":"server","name":"Home Assistant","addon":true}]
```

### Environment (please complete the following information):

- Node Red Version: 1.2.5
- Node.js Version: ?
- NR Home Assistant Plugin Version: 7.2.11
- Is Node Red running in Docker: HA addon

### Other (please complete the following information):

- Have you searched previous issues for duplicates?: Yes

**Comment by zachowj** [comment]
Do you have heavy loads on the system you're running NR on?

**Comment by cpiekacz** [comment]
No, not really, although node-red is running inside a VM, load is around 0.4 with 25% of RAM used. I also noticed that there's the same problem with inject node (which seems not to trigger at all... puzzling...). The only thing that seems to runs reliably is cronplus node.

**Comment by zachowj** [comment]
The inject and poll-state node using the same technique with `setInterval`. So my guess would be you have a flow that's blocking the event loop. Do you have the ability to spin up another NR VM and have a single flow that's an inject node firing every minute?

**Comment by cpiekacz** [comment]
I would have to figure out how to connect Node red to the Home assistant instance running inside another VM, but that's doable I suppose. I also have problems with inject node (reported an issue [here](https://github.com/node-red/node-red/issues/2833)), but if both are using setInterval it's not surprising that I have issues with both. Maybe I'll run node red separately, outside of a VM, to rule out issues with VirtualBox. Thanks for the pointer.
