### ISSUE TITLE
Trigger state node wrong output

### ISSUE THREAD

**Issue by michalk-k** [zachowj/node-red-contrib-home-assistant-websocket#343]
### Describe the bug

The note outputs ON regardless the actual state of monitored node.
For example if it is set to be triggered by window sensor, and output has to be filtered to only "ON" state, it outputs "ON" to its first out on both events: sensor on and off.

### To Reproduce

1. add Trigger:state node to flow, to be triggered by some binary_sensor
2. Set condition to filter current state: "on"
3. Connect debug to the first output. 
4. Change state of the binary sensor.

On is outputted on each state of the sensor

### Expected behavior
On should be outputted only when sensor state changes to on

### Screenshots

Test flow. Code available below
You can see event and trigger node. Trigger node is configured to filter out "on" state only.
![obrazek](https://user-images.githubusercontent.com/7868445/105575374-7b830500-5d6b-11eb-9122-b6f3295ccd73.png)

See the result shown by debug node:
![obrazek](https://user-images.githubusercontent.com/7868445/105575409-c4d35480-5d6b-11eb-9553-4be5e03dec48.png)
Event node proves the state was "off" but it's still outputted by trigger node. Looking deeper into message unvails even more:

![obrazek](https://user-images.githubusercontent.com/7868445/105575467-2398ce00-5d6c-11eb-8695-de3b509ce2fb.png)

And there is respective log from event node:

![obrazek](https://user-images.githubusercontent.com/7868445/105575490-5ba01100-5d6c-11eb-825b-af9663f8fdf3.png)

### Example Flow

```
[{"id":"e9cdae5f.a9bed8","type":"server-state-changed","z":"76f630c8.5970b8","name":"","server":"6cdd0bc8.b8e434","version":1,"exposeToHomeAssistant":false,"haConfig":[{"property":"name","value":""},{"property":"icon","value":""}],"entityidfilter":"binary_sensor.doorsensor1_contact","entityidfiltertype":"exact","outputinitially":false,"state_type":"str","haltifstate":"","halt_if_type":"str","halt_if_compare":"is","outputs":1,"output_only_on_state_change":true,"for":0,"forType":"num","forUnits":"minutes","ignorePrevStateNull":false,"ignorePrevStateUnknown":false,"ignorePrevStateUnavailable":false,"ignoreCurrentStateUnknown":false,"ignoreCurrentStateUnavailable":false,"x":590,"y":600,"wires":[["28408aa2.77dae6"]]},{"id":"28408aa2.77dae6","type":"debug","z":"76f630c8.5970b8","name":"events","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":960,"y":600,"wires":[]},{"id":"9f71981d.1d1f98","type":"trigger-state","z":"76f630c8.5970b8","name":"","server":"6cdd0bc8.b8e434","exposeToHomeAssistant":false,"haConfig":[{"property":"name","value":""},{"property":"icon","value":""}],"entityid":"binary_sensor.doorsensor1_contact","entityidfiltertype":"exact","debugenabled":false,"constraints":[{"targetType":"this_entity","targetValue":"","propertyType":"current_state","comparatorType":"is","comparatorValueDatatype":"str","comparatorValue":"on","propertyValue":"new_state.state"}],"outputs":2,"customoutputs":[],"outputinitially":false,"state_type":"str","x":580,"y":700,"wires":[["1a424e2e.8b7402"],[]]},{"id":"1a424e2e.8b7402","type":"debug","z":"76f630c8.5970b8","name":"trigger","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":950,"y":700,"wires":[]},{"id":"6cdd0bc8.b8e434","type":"server","name":"Home Assistant"}]
```

### Environment (please complete the following information):

- Node Red Version: 1.2.5
- Node.js Version: 0.0.0
- NR Home Assistant Plugin Version: 0.30.1
- HA addon

### Other (please complete the following information):

yes

### Additional context
Actually I probably found the issue which causes somehow is related with one above. 
The trigger state node without any condition set outputs two messages while triggered by single sensor state.
If sensor changes from off to on, the trigger state sends off and on messages (and vice-versa). The first message sent has always old and new state set to the same value.
Those wrong values in old/new states somehow correlates with finding described in main issue description

**Comment by zachowj** [comment]
Try unchecking `Current state equals previous state` in the events:state node and see if you get the same result.

**Comment by michalk-k** [comment]
Yes. Surprisingly events:state node also outputs 2 messages when changing state. The first is previous state, then current state.
I suppose it's not proper behavior, isn't it?

**Comment by zachowj** [comment]
I would say it's working as intended. 

Your door sensor is reporting twice to HA which is causing two events to trigger. Check the attributes of old_state and new_state when the state of the sensor is the same and see if there are any differences.

If you only want the trigger node to output when the state changes like the events:state node you'll have to add that condition.

![image](https://user-images.githubusercontent.com/37859597/105613576-2e596000-5d78-11eb-92e2-dcc538d11967.png)

**Comment by michalk-k** [comment]
Now I've tried another sensor (different company, different technology) and it manifests the same behaviour.
They both have one common thing: both are created from. One is zigbee2mqtt registered with discover, second is Shelly manually added as sensor to configuartion.yaml

Now the part I don't understand: :Your door sensor is reporting twice to HA"
Why door sensor reports twice? Why it would send state just before change just prior to the new one?
And why it would be done by 2 independent sensors?
