### ISSUE TITLE
Connection on Log

### ISSUE THREAD

**Issue by soloam** [zachowj/node-red-contrib-home-assistant-websocket#345]
### Describe the bug

I keep getting this coonections on my log

```
│                                      ││ node-red > 27 Jan 23:09:01 - [info] [server:Home Assistant] Connecting to http://supervis  │
│                                      ││ node-red > 27 Jan 23:09:06 - [info] [server:Home Assistant] Connecting to http://supervis  │
│                                      ││ node-red > 27 Jan 23:09:11 - [info] [server:Home Assistant] Connecting to http://supervis  │
│                                      ││ node-red > 27 Jan 23:09:16 - [info] [server:Home Assistant] Connecting to http://supervis  │
│                                      ││ node-red > 27 Jan 23:09:21 - [info] [server:Home Assistant] Connecting to http://supervis 
```

This is linked to url:
https://www.buydomains.com/lander/supervis.com?domain=supervis.com&utm_source=supervis.com&utm_medium=click&utm_campaign=tdfs-AprTest&traffic_id=AprTest&traffic_type=tdfs&redirect=ono-redirect

Can you explain what is this?

### To Reproduce

1. I just have it instated and running

### Expected behavior

Would like to understand what is this communication

### Screenshots

None

### Example Flow

None

### Environment (please complete the following information):

- Node Red Version: 1.1.2
- Node.js Version: v10.21.0
- NR Home Assistant Plugin Version: 0.30.1
- Is Node Red running in Docker: no, Running in FreeNAS Jail

### Other (please complete the following information):

Yes

### Additional context

None

**Comment by zachowj** [comment]
You're running NR inside a HA add-on.

<https://developers.home-assistant.io/docs/add-ons/communication/#home-assistant-core>
