### ISSUE TITLE
EventState does not reflect the saved context when it is re-opened.

### ISSUE THREAD

**Issue by team-aniar** [zachowj/node-red-contrib-home-assistant-websocket#350]
### To Reproduce

1. Add a "Events:state" node to the flow
2. Add a sensor entity and in the "If State" choose a global variable stored in a not default context.
3. Click done
4. Open the node again and check the context store dropdown. It will show the default store and not the one you chose.

### Expected behavior
Opening a node for edit should load all saved settings on the node. Also the context store.

### Screenshots
This is set before "Done":
![2021-02-09 15_54_46-Supervisor - Home Assistant — Mozilla Firefox](https://user-images.githubusercontent.com/5383622/107382741-84583280-6af0-11eb-9382-db58e8f41139.png)

This is displayed after opening the node again:
![2021-02-09 15_55_09-Supervisor - Home Assistant — Mozilla Firefox](https://user-images.githubusercontent.com/5383622/107382803-9639d580-6af0-11eb-9612-23f3f08ad509.png)

### Example Flow

Saved node
```
[{"id":"a97eaae6.6ff718","type":"server-state-changed","z":"188e9d57.2a15fb","name":"Dark outside?","server":"b4994e00.6b7288","version":1,"exposeToHomeAssistant":false,"haConfig":[{"property":"name","value":""},{"property":"icon","value":""}],"entityidfilter":"sensor.sensative_strips_comfort_luminance","entityidfiltertype":"exact","outputinitially":false,"state_type":"str","haltifstate":"#:(store)::DefaultSettings.luxlevel_dark","halt_if_type":"global","halt_if_compare":"lt","outputs":2,"output_only_on_state_change":true,"for":0,"forType":"num","forUnits":"minutes","ignorePrevStateNull":false,"ignorePrevStateUnknown":false,"ignorePrevStateUnavailable":false,"ignoreCurrentStateUnknown":false,"ignoreCurrentStateUnavailable":false,"x":110,"y":380,"wires":[["191cb1f3.ca8bbe"],["86d119a3.0ea75"]],"outputLabels":["Ja","Nei"]},{"id":"b4994e00.6b7288","type":"server","name":"Home Assistant","legacy":false,"addon":true,"rejectUnauthorizedCerts":true,"ha_boolean":"y|yes|true|on|home|open","connectionDelay":true,"cacheJson":true}]
```

Opened node
```
[{"id":"a97eaae6.6ff718","type":"server-state-changed","z":"188e9d57.2a15fb","name":"Dark outside?","server":"b4994e00.6b7288","version":1,"exposeToHomeAssistant":false,"haConfig":[{"property":"name","value":""},{"property":"icon","value":""}],"entityidfilter":"sensor.sensative_strips_comfort_luminance","entityidfiltertype":"exact","outputinitially":false,"state_type":"str","haltifstate":"DefaultSettings.luxlevel_dark","halt_if_type":"global","halt_if_compare":"lt","outputs":2,"output_only_on_state_change":true,"for":0,"forType":"num","forUnits":"minutes","ignorePrevStateNull":false,"ignorePrevStateUnknown":false,"ignorePrevStateUnavailable":false,"ignoreCurrentStateUnknown":false,"ignoreCurrentStateUnavailable":false,"x":110,"y":380,"wires":[["191cb1f3.ca8bbe"],["86d119a3.0ea75"]],"outputLabels":["Ja","Nei"]},{"id":"b4994e00.6b7288","type":"server","name":"Home Assistant","legacy":false,"addon":true,"rejectUnauthorizedCerts":true,"ha_boolean":"y|yes|true|on|home|open","connectionDelay":true,"cacheJson":true}]
```

### Environment (please complete the following information):

- Supervised HA Installation.

- Node Red Version:
- Node.js Version: 
- NR Home Assistant Plugin Version: 
- Is Node Red running in Docker: HA addon 

### Other (please complete the following information):
Nope

### Additional context
Nope

**Comment by zachowj** [comment]
It will be fixed in NR 1.3 

https://github.com/node-red/node-red/commit/c37ea90206d3ac84dd4d94740909bc96f2307e2f
