### ISSUE TITLE
 events: state node output generates wrong timeSinceChangedMs #355 

### ISSUE THREAD

**Issue by muniter** [zachowj/node-red-contrib-home-assistant-websocket#356]
### Describe the bug

The events:state node outputs a wrong `data.new_state.timeSinceChangedMs` no matter what it always returns a value between 9ms and 13ms for me. Do not have this issue with the current state node. Looking at the source code seems like the problem is here. I believe it should be `event.old_state.last_changed` otherwise is measuring time between the state changed and when the node triggers.

https://github.com/zachowj/node-red-contrib-home-assistant-websocket/blob/1ab123efa98a79e2e5bce5f08e53768a00a4cc6d/src/nodes/EventsState.js#L195-L197

### To Reproduce

1. Configure a events:state node.
2. Trigger the entity
3. Look at  `data.new_state.timeSinceChangedMs`

### Expected behavior

The real `timeSinceChangedMs` should be in the output.

### Example Flow

```
[{"id":"34ed15a5.878f3a","type":"api-current-state","z":"8e5fc41c.857718","name":"","server":"df4ad754.d9c758","version":1,"outputs":1,"halt_if":"","halt_if_type":"str","halt_if_compare":"is","override_topic":false,"entity_id":"switch.ls_office_fan","state_type":"str","state_location":"payload","override_payload":"msg","entity_location":"data","override_data":"msg","blockInputOverrides":false,"x":1160,"y":3320,"wires":[["be1312ef.6142"]]},{"id":"76e070ec.656c68","type":"server-state-changed","z":"8e5fc41c.857718","name":"","server":"df4ad754.d9c758","version":1,"exposeToHomeAssistant":false,"haConfig":[{"property":"name","value":""},{"property":"icon","value":""}],"entityidfilter":"switch.ls_office_fan","entityidfiltertype":"exact","outputinitially":false,"state_type":"str","haltifstate":"","halt_if_type":"str","halt_if_compare":"is","outputs":1,"output_only_on_state_change":true,"for":0,"forType":"num","forUnits":"minutes","ignorePrevStateNull":false,"ignorePrevStateUnknown":false,"ignorePrevStateUnavailable":false,"ignoreCurrentStateUnknown":false,"ignoreCurrentStateUnavailable":false,"x":1160,"y":3380,"wires":[["a1b270ed.a7b728"]]},{"id":"be1312ef.6142","type":"debug","z":"8e5fc41c.857718","name":"Current State","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":1450,"y":3320,"wires":[]},{"id":"a1b270ed.a7b728","type":"debug","z":"8e5fc41c.857718","name":"State Changed","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":1460,"y":3380,"wires":[]},{"id":"eb95ca43.473e3","type":"inject","z":"8e5fc41c.857718","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":900,"y":3320,"wires":[["34ed15a5.878f3a"]]},{"id":"df4ad754.d9c758","type":"server","name":"Home Assistant","addon":true}]
```

### Environment (please complete the following information):

- Node Red Version: 1.2.9
- Node.js Version: 14.15.5
- NR Home Assistant Plugin Version: 0.30.1
- Is Node Red running in Docker: HA addon

### Other (please complete the following information):

- Have you searched previous issues for duplicates?:

Yes, don't see anything related to it.

### Additional context

Just try it, should be really easy to notice.

**Comment by zachowj** [comment]
> otherwise is measuring time between the state changed and when the node triggers.

This is correct. Probably not as helpful as the one in the current state node but it is reporting the intended value.

**Comment by muniter** [comment]
Oh well, didn't know that was an inteded feature. One most like wants the time since it changed **from the last state**. Rather than the time between It being registered in Home Assistant and actually triggering. Well I guess It's pretty easy to get the time difference between states.

I would still recommend on this returning the same as the state node. I believe a user my find it counter intuitive or confusing! Whatever you decide thank you for this project.

**Comment by zachowj** [comment]
It does return the same value as the current state node. `timeSinceChangedMs` returns the difference from now to when the entity was last changed. If you use an event state node and a current-state node in series and watching the same entity you will see the same value.

If you have something like a power monitoring plug that only triggers the update of the entity and not the changed event. You'll see that the `timeSinceChangedMs` is larger than a few milliseconds.
