### ISSUE TITLE
Does the new time node only fire once?

### ISSUE THREAD

**Issue by blair287** [zachowj/node-red-contrib-home-assistant-websocket#358]
Does the new time node only fire once? Once the events past it just stays at in the past.

Can it not reset and trigger again so you can use a input date time with just a time as a trigger in node red every time when the time is true?

![Screenshot_20210310-071637](https://user-images.githubusercontent.com/44187409/110591358-e26c4a00-8170-11eb-9a9c-2f4ed822d53b.png)

**Comment by zachowj** [comment]
Do you have `repeat daily` checked?

**Comment by blair287** [comment]
> Do you have `repeat daily` checked?

Sorry I'm an idiot I didn't see that option my bad sorry for wasting your time.

But by chance are you the same person as from this thread think same profile pic?

https://community.home-assistant.io/t/use-ha-date-time-input-has-the-time-on-the-inject-node-at-a-specific-time/121926/11

**Comment by zachowj** [comment]
> But by chance are you the same person as from this thread think same profile pic?

yep

**Comment by blair287** [comment]
> > But by chance are you the same person as from this thread think same profile pic?
> 
> yep

You couldn't by any chance help me with this please?

You gave me this code several months ago and it was working flawlessly but for some reason it's not working anymore.

`const states = global.get('homeassistant').homeAssistant.states;
const now = new Date();
const start = states['input_datetime.alarm1'].attributes;
const end = states['input_datetime.alarm2'].attributes;

if(now.getHours() >= start.hour && now.getMinutes() >= start.minute
   && now.getHours() <= end.hour && now.getMinutes() <= end.minute) {
    return msg;
}`
