### ISSUE TITLE
New timer node doesnt connect on restart

### ISSUE THREAD

**Issue by blair287** [zachowj/node-red-contrib-home-assistant-websocket#361]
### Describe the bug

The timer node even with repeat daily selected wont fire if node red or HA is restarted it just shows as running status but wont fire unless its redeployed or the input_datetime is changed.

### To Reproduce

1) add timer node use input date time etc and use repeat daily.

2) it should have a blue box and when it will trigger under it

3) now restart node red

4) it now shows as just running and wont fire.

### Expected behavior

should reconnect or have option to reconnect on server start so when using to fire event daily it continues after a HA restart like for an update etc.

### Screenshots

![timer node prop](https://user-images.githubusercontent.com/44187409/111272484-9c106280-862a-11eb-8727-7fb8fc7ee950.JPG)
![timer node](https://user-images.githubusercontent.com/44187409/111272499-a03c8000-862a-11eb-9952-52e44cf1fda3.JPG)

### Example Flow

```
export goes here
```

### Environment (please complete the following information):

- Node Red Version: [e.g. 1.0.4] Latest
- Node.js Version: [e.g. 12.16.1] Latest
- NR Home Assistant Plugin Version: [e.g. 0.21.3] Latest
- Is Node Red running in Docker: [e.g. yes/no/HA addon] HA addon

### Other (please complete the following information):

- Have you searched previous issues for duplicates?:
Yes

**Comment by aperture1988** [comment]
Also experiencing this issue

**Comment by zachowj** [comment]
I believe this is fixed in the current branch. Will have to wait for the next release.

**Comment by aperture1988** [comment]
> I believe this is fixed in the current branch. Will have to wait for the next release.

Would you happen to know when this will be pushed out? I noticed an update the other day was available but it doesn't seem to have addressed this issue. thanks

**Comment by zachowj** [comment]
> Updated to the latest node red add-on and this problem is still there. Timer node doesn't reconnect on restart.

The NR add-on is not this package it contains this package and I haven't released a new version of this package yet. Hoping to get a beta released in the next week.

**Comment by zachowj** [comment]
v0.31.0 has been released which should fix this. reopen if not.

**Comment by blair287** [comment]
> v0.31.0 has been released which should fix this. reopen if not.

All fixed thanks
