### ISSUE TITLE
current state node is not working

### ISSUE THREAD

**Issue by CODeRUS** [zachowj/node-red-contrib-home-assistant-websocket#362]
### Describe the bug

current state node is not working

### To Reproduce

1. add current state node to flow
2. deploy
3. wait for trigger

### Expected behavior

error like
```
"Entity could not be found in cache for entity_id: group.persons"
```
for each current state node

in nodered logs i see:
```
19 Mar 18:50:05 - [info] [server:Home Assistant] Connected to http://127.0.0.1:8123
(node:17) UnhandledPromiseRejectionWarning: #<Object>
(node:17) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:17) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

### Screenshots

n/a

### Example Flow

n/a

### Environment (please complete the following information):

Node-RED version: v1.2.9
Node.js  version: v10.23.2
Linux 5.4.0-62-generic x64 LE

node-red-contrib-home-assistant-websocket 0.30.1

NodeRed in docker started with `docker run -d --restart=always --network=host -v $HOME/.node-red:/data -e TZ=Europe/Moscow --name mynodered nodered/node-red`

### Other (please complete the following information):

HomeAssistant Core installation, no hass, etc.

### Additional context

n/a

**Comment by zachowj** [comment]
`Entity could not be found in cache` error normally occurs when you try to use the current-state node before the connection to Home Assistant has finished.

**Comment by mrwogu** [comment]
I have the same issue with Home Assistant Supervised System with checked " I Use The Home Assistant Add-On" and "Delay Connection Attempts". No one change has been made except upgrades.

Home Assistant 2021.5.5
Node-Red 9.1.1
