### ISSUE TITLE
After clicking Deploy the node cannot get the alarm from android phone

### ISSUE THREAD

**Issue by EdgardosReis** [zachowj/node-red-contrib-home-assistant-websocket#368]
### Describe the bug
I'm trying to use the sensor mobile next alarm entity and the attribute _attributes.Local Time_ to trigger an automation when the alarm from my android phone rings. It works fine when I set the alarm. the node gets the time and trigger at the alarm time as expected, it gets the next alarm too. The problem is when I have to make any change in any of my flows and click the Deploy button. Then, the node is always in state running, never gets the next alarm and in the debug tab displays the message "Invalid property".

I also use the sun.sun entity and next dusk attribute and this one works flawless. When I click Deploy, the node stays in the running state but after a while it gets the dusk time.

### To Reproduce

1. Create a time node
2. set the entity as sensor.[brand_model]_next_alarm
3. set the property to attributes.Local Time
4. set an alarm in your android phone
5. Click the Deploy button
6. the node never gets the alarm time

### Expected behavior

When Deploy is clicked, the node should eventually get the next alarm from the phone.

### Screenshots
The flow
![image](https://user-images.githubusercontent.com/3378616/113486389-5832af80-94aa-11eb-9d1f-5e1989e0f0d6.png)

The configuration
![image](https://user-images.githubusercontent.com/3378616/113486397-641e7180-94aa-11eb-93e0-7b2a505aa258.png)

The _invalid propery_ message when Deploy is clicked
![image](https://user-images.githubusercontent.com/3378616/113486418-80221300-94aa-11eb-9a90-2cb3f83b661e.png)

### Example Flow

```
[{"id":"298e3358.4d660c","type":"ha-time","z":"8c4cfc39.04659","server":"c3ade419.198328","name":"phone next alarm","exposeToHomeAssistant":false,"haConfig":[{"property":"name","value":""},{"property":"icon","value":""}],"entityId":"sensor.oneplus_a5010_next_alarm","property":"attributes.Local Time","offset":"0","offsetType":"num","offsetUnits":"minutes","randomOffset":false,"repeatDaily":false,"payload":"$entity().state","payloadType":"jsonata","debugenabled":true,"x":180,"y":80,"wires":[["7e37e8c5.de39a8"]]},{"id":"c3ade419.198328","type":"server","name":"Home Assistant","addon":true}]
```

### Environment (please complete the following information):

- Node Red Version: 1.2.9
- Node.js Version: not sure, the latest i guess
- NR Home Assistant Plugin Version: 8.2.1
- Is Node Red running in Docker: HA addon

### Other (please complete the following information):

- Have you searched previous issues for duplicates?: Yes

**Comment by zachowj** [comment]
Does it work if you use `state` or `attributes.Time In Milliseconds`?

**Comment by EdgardosReis** [comment]
Thanks for the response @zachowj 
Using `state` and `attributes.Time In Milliseconds `have the same behavior, it's updated just when I change one alarm.

**Comment by zachowj** [comment]
v0.31.0 just released should fix this. reopen if it doesn't.
