### ISSUE TITLE
Constant connection attempts to hosts

### ISSUE THREAD

**Issue by derekoharrow** [zachowj/node-red-contrib-home-assistant-websocket#389]
### Describe the bug

I'm running Node Red v1.3.4 and Home Assistant v2021.5.3 under docker, with the node-red-contrib-home-assistant-websocket v0.30.1 and HA Node-Red HACS Companion v0.5.2

Home Assistant runs locally at http://docker.lan:8123. I've setup Node RED to use this address with a long-lived access token (I did try checking the box which says "I use the Home Assistant Add-on", but that doesn't connect for me). This all works fine and Node RED can talk to HA.

But, Node Red is flooding my DNS with requests, and on looking in the Node Red logs I get:

```
12 May 09:54:53 - [info] [server:Home Assistant] Connecting to http://docker.lan:8123
12 May 09:54:53 - [info] [mqtt-broker:MQTT] Connected to broker: nodered@mqtt://mqtt.lan:1883
12 May 09:54:53 - [info] [server:Home Assistant] Connected to http://docker.lan:8123
12 May 09:54:54 - [info] [server:Home Assistant] Connecting to http://docker.lan
12 May 09:54:55 - [info] [server:Home Assistant] Connecting to http://docker.lan:8123
12 May 09:54:55 - [info] [server:Home Assistant] Connecting to http://supervisor/core
12 May 09:54:59 - [info] [server:Home Assistant] Connecting to http://docker.lan
12 May 09:55:00 - [info] [server:Home Assistant] Connecting to http://docker.lan:8123
12 May 09:55:00 - [info] [server:Home Assistant] Connecting to http://supervisor/core
12 May 09:55:04 - [info] [server:Home Assistant] Connecting to http://docker.lan
12 May 09:55:05 - [info] [server:Home Assistant] Connecting to http://docker.lan:8123
12 May 09:55:05 - [info] [server:Home Assistant] Connecting to http://supervisor/core
12 May 09:55:09 - [info] [server:Home Assistant] Connecting to http://docker.lan
12 May 09:55:10 - [info] [server:Home Assistant] Connecting to http://docker.lan:8123
12 May 09:55:10 - [info] [server:Home Assistant] Connecting to http://supervisor/core
12 May 09:55:14 - [info] [server:Home Assistant] Connecting to http://docker.lan
12 May 09:55:15 - [info] [server:Home Assistant] Connecting to http://docker.lan:8123
...
```

As you can see, it connects just fine to HA (3rd line above), but then goes on to keep trying connecting to http://docker.lan, http://docker.lan:8123 and http://supervisor/core.

### Expected behavior

- Once connected successfully, it shouldn't keep trying to connect.
- It shouldn't be trying to connect to http://docker.lan at all as I've not specified that anywhere
- It shouldn't be trying to connect to http://supervisor/core as I've not specified that anywhere either.

### Environment (please complete the following information):

- Node Red Version: v1.3.4
- Node.js Version: [e.g. 12.16.1] v12.22.1
- NR Home Assistant Plugin Version: 0.30.1
- Is Node Red running in Docker: Yes

**Comment by zachowj** [comment]
restart node-red and the other connections should go away. the clean up when changing ips needs some work
