### ISSUE TITLE
Node events: state does not output specified proberty

### ISSUE THREAD

**Issue by DirkMu** [zachowj/node-red-contrib-home-assistant-websocket#398]
### Describe the bug

I am using a events: state node that is supposed to output a specific property if the condition is met. Instead of outputting the specified property the entity state is outputted. 

### To Reproduce

1. create a events: state node
2. specifiy a output property

### Expected behavior

The specified output property is outputted. In case of boolean the opposite value.

![image](https://user-images.githubusercontent.com/53949754/119233792-e2060d00-bb2a-11eb-8d9c-fa3196bdd85f.png)

### Example Flow

```
[{"id":"9ff73902.ce3ba8","type":"debug","z":"fec495b0.bb3e68","name":"2","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"payload","targetType":"msg","statusVal":"","statusType":"auto","x":722,"y":560,"wires":[]},{"id":"8ff3f4ee.aefd28","type":"debug","z":"fec495b0.bb3e68","name":"1","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"payload","targetType":"msg","statusVal":"","statusType":"auto","x":690,"y":480,"wires":[]},{"id":"cf8c3264.fac56","type":"server-state-changed","z":"fec495b0.bb3e68","name":"Wind GW 1 an","server":"97a02c30.758c8","version":3,"exposeToHomeAssistant":false,"haConfig":[{"property":"name","value":""},{"property":"icon","value":""}],"entityidfilter":"binary_sensor.ws_dach_wind_gw1","entityidfiltertype":"exact","outputinitially":true,"state_type":"habool","haltifstate":"true","halt_if_type":"bool","halt_if_compare":"is","outputs":2,"output_only_on_state_change":true,"for":"0","forType":"num","forUnits":"minutes","ignorePrevStateNull":false,"ignorePrevStateUnknown":false,"ignorePrevStateUnavailable":false,"ignoreCurrentStateUnknown":false,"ignoreCurrentStateUnavailable":false,"outputProperties":[{"property":"payload","propertyType":"msg","value":"test","valueType":"str"}],"x":480,"y":560,"wires":[["8ff3f4ee.aefd28"],["9ff73902.ce3ba8"]]},{"id":"97a02c30.758c8","type":"server","name":"Home Assistant","version":1,"legacy":false,"addon":false,"rejectUnauthorizedCerts":true,"ha_boolean":"y|yes|true|on|home|open","connectionDelay":true,"cacheJson":true}]
```

### Environment (please complete the following information):

- Node Red Version: 1.3.4
- Node.js Version: 
- NR Home Assistant Plugin Version: 0.5.2
- Is Node Red running in Docker: yes

### Other (please complete the following information):

- Have you searched previous issues for duplicates?: yes

**Comment by DirkMu** [comment]
@zachowj  Thanks for the prompt fix. The Node Red library still shows version 0.31.3 instead of 0.31.4. Was is published already?

**Comment by zachowj** [comment]
<https://flows.nodered.org/node/node-red-contrib-home-assistant-websocket> is showing the correct version. Might take some time for it to populate, not sure.

**Comment by DirkMu** [comment]
It is avaiblable, now. I just tested it. What is the expected behavior, when checking a binary_sensor to be true or false (state type = boolean) and the output property is specified as a boolean with a fixed value? For instance, you check whether a binary_sensor is off (false and state type is boolean). Output property is boolean and true. I expected that in that specific case (using a boolean) true is sent to output port 1 when the condition is met and the opposite value (false) to output port 2.

**Comment by zachowj** [comment]
> What is the expected behavior, when checking a binary_sensor to be true or false (state type = boolean) and the output property is specified as a boolean with a fixed value?

When `state type` is set to `boolean` the state of the entity is converted to `true`/`false` based on the `State Boolean` list.
<https://zachowj.github.io/node-red-contrib-home-assistant-websocket/node/config-server.html#state-boolean>

The only value that the `state type` gets changed is the old and new `state` of the entity. If you're using a static value like in the screenshot above with "test" that is always going to be sent as a string no what `state type` is set to.

If you want an output of `true`/`false` setting `state type` to `boolean` and use an output property of `entity state`

![image](https://user-images.githubusercontent.com/37859597/119259317-89faf500-bb82-11eb-85d5-fd3e15902769.png)

or an JSONata expression `$entity().state`

**Comment by DirkMu** [comment]
I used "test" in order to test the output. Actually I want to turn the entity state value from true to false and vice versa leveraging both output ports.

![image](https://user-images.githubusercontent.com/53949754/119259475-c7856f80-bbce-11eb-89f6-97917c4bfb89.png)

I assume this is not possible. Using a JASONata expression, I assume, will only work properly if there is no condition check and thus only one output port is available:

![image](https://user-images.githubusercontent.com/53949754/119259560-234ff880-bbcf-11eb-9360-42850dfcea26.png)

**Comment by zachowj** [comment]
I would leave `state type` set to `string`. Use an `If state` condition `is` `on` then an output property `$entity().state = "on" ? false : true`

**Comment by zachowj** [comment]
My above should work by i was just trying to test it and it doesn't. So another but I missed when I was fixing this originally.

**Comment by zachowj** [comment]
fixed in next release

**Comment by DirkMu** [comment]
Sorry, didn't get your last response. It is not working, right? Someting you need to fix / will fix? 

I will test it also, but I how do you control what output port is used?

**Comment by zachowj** [comment]
if the `if state` is `true` it will output to the top output else to the bottom output

**Comment by DirkMu** [comment]
Yes, of course. You are right. So, it should also work using state type boolean, right?

**Comment by zachowj** [comment]
yes
