### ISSUE TITLE
Entity IDs as-you-type suggestion window not working

### ISSUE THREAD

**Issue by rsuplido** [zachowj/node-red-contrib-home-assistant-websocket#4]
**Describe the bug**
When entering an Entity ID on any HA node, it usually pops-up suggestions of entities as you type. It's not working

**To Reproduce**
1. Drag an open an _events: state_ node
2. On the Entity ID field, start typing 'switch'
3. A window showing entity ids that start with 'switch' should pop-up under the Entity ID field

**Expected behavior**
A window showing matching entity ids should pop-up under the Entity ID field as you type

**Environment (please complete the following information):**
 - Node Red Version: 0.19.4
 - NR Home Assistant Plugin Version: 0.7.0
 - node-red-contrib-home-assistant-websocket Version: 0.0.4
 - Is Node Red running in Docker: yes

**Comment by GoSpursGoNL** [comment]
I had the same issue yesterday after installing this module, but after one or two restarts of NR, it suddenly started working.

**Comment by zachowj** [comment]
Are you still having this issue on the latest release? 0.0.6
