### ISSUE TITLE
Exposed switches unailable after HA restart

### ISSUE THREAD

**Issue by DirkMu** [zachowj/node-red-contrib-home-assistant-websocket#404]
### Describe the bug

After restarting HA the exposed switches from NR become unavailable. This is regardless of the node type. I am using exposed time nodes es wall as entity nodes. 

### To Reproduce

1. For instance create a time node and expose it to HA 
2. Restart HA

### Expected behavior

HA entity still available and in same state as before restart

### Screenshots

![image](https://user-images.githubusercontent.com/53949754/119250013-6beebe00-bb9d-11eb-8afc-68fb00e6a2df.png)

### Example Flow

```
[{"id":"bc28b5d1.fe5588","type":"ha-time","z":"93117621.425f48","name":"Test","server":"97a02c30.758c8","version":0,"exposeToHomeAssistant":true,"haConfig":[{"property":"name","value":"nr_alarm_test"},{"property":"icon","value":"mdi:alarm"}],"entityId":"input_datetime.test","property":"","offset":0,"offsetType":"num","offsetUnits":"minutes","randomOffset":false,"repeatDaily":true,"payload":"$entity().state","payloadType":"jsonata","debugenabled":false,"x":82,"y":1008,"wires":[["56c609bc.8dd778"]]},{"id":"97a02c30.758c8","type":"server","name":"Home Assistant","version":1,"legacy":false,"addon":false,"rejectUnauthorizedCerts":true,"ha_boolean":"y|yes|true|on|home|open","connectionDelay":true,"cacheJson":true}]
```

### Environment (please complete the following information):

- Node Red Version: 1.3.4
- Node.js Version: 
- NR Home Assistant Plugin Version: 0.5.2]
- Is Node Red running in Docker: Docker

### Other (please complete the following information):

- Have you searched previous issues for duplicates?: y

**Comment by zachowj** [comment]
I can reproduce this on my production server but not any of my test setups.

**Comment by DirkMu** [comment]
Any idea when this issue will be investigated? Or was it fixed with the latest releases?
