### ISSUE TITLE
Current state node after an events: all node does not check correct state/payload

### ISSUE THREAD

**Issue by FuzzyMistborn** [zachowj/node-red-contrib-home-assistant-websocket#420]
### Describe the bug

This one is kinda hard to explain, but I'll try.  When using an `events: all` node to report when a timer is finished in HASS, the output payload/state is "active".  When it goes through a `current state` node, the state of the entity I'm trying to check isn't measured but rather the payload/state remains "active".  If I feed it through a second `current state` node it checks the correct state.

All my other `current state` nodes work fine, wonder if this is related to the output of the `events: all` node.

### To Reproduce

See above description and below screenshots/exported nodes.

### Expected behavior

The first `current state` node should accurately check the state of the entity I have in that node and not use the payload/state from the timer/event.

### Screenshots

![image](https://user-images.githubusercontent.com/16689090/120131422-7230fb80-c196-11eb-851f-e7ecc7a40f21.png)

Note the debug nodes/output on the right are in order of how they were processed.

### Example Flow

```
[{"id":"f2bbfcaf.2892a","type":"server-events","z":"b06c555f.69395","name":"Naptime Over","server":"63517380.eb951c","version":1,"event_type":"timer.finished","exposeToHomeAssistant":false,"haConfig":[{"property":"name","value":""},{"property":"icon","value":""}],"waitForRunning":true,"outputProperties":[{"property":"payload","propertyType":"msg","value":"","valueType":"eventData"},{"property":"topic","propertyType":"msg","value":"$outputData(\"eventData\").event_type","valueType":"jsonata"},{"property":"event_type","propertyType":"msg","value":"$outputData(\"eventData\").event_type","valueType":"jsonata"}],"x":510,"y":4060,"wires":[["28fe034.df1c4fc"]]},{"id":"28fe034.df1c4fc","type":"switch","z":"b06c555f.69395","name":"","property":"payload.entity_id","propertyType":"msg","rules":[{"t":"eq","v":"timer.nap","vt":"str"}],"checkall":"true","repair":false,"outputs":1,"x":650,"y":4060,"wires":[["e250301.b55715","cfb367cb.401698"]]},{"id":"b9e6b2cf.be32c","type":"api-current-state","z":"b06c555f.69395","name":"Sound","server":"63517380.eb951c","version":2,"outputs":2,"halt_if":"on","halt_if_type":"str","halt_if_compare":"is","entity_id":"switch.sound_machine","state_type":"str","blockInputOverrides":false,"outputProperties":[{"property":"payload","propertyType":"msg","value":"","valueType":"str"}],"x":970,"y":4060,"wires":[["d469b533.901a08"],[]]},{"id":"e250301.b55715","type":"api-current-state","z":"b06c555f.69395","name":"Sound","server":"63517380.eb951c","version":2,"outputs":2,"halt_if":"on","halt_if_type":"str","halt_if_compare":"is","entity_id":"switch.sound_machine","state_type":"str","blockInputOverrides":false,"outputProperties":[{"property":"payload","propertyType":"msg","value":"","valueType":"entityState"},{"property":"data","propertyType":"msg","value":"","valueType":"entity"}],"override_topic":false,"state_location":"payload","override_payload":"msg","entity_location":"data","override_data":"msg","x":790,"y":4060,"wires":[["b9e6b2cf.be32c"],["b9e6b2cf.be32c","de03aea6.50159"]]},{"id":"63517380.eb951c","type":"server","name":"Home Assistant","version":1,"legacy":false,"addon":false,"rejectUnauthorizedCerts":true,"ha_boolean":"y|yes|true|on|home|open","connectionDelay":true,"cacheJson":true}]
```

### Environment (please complete the following information):

- Node Red Version: 1.3.5
- Node.js Version: ? (I run in Docker)
- NR Home Assistant Plugin Version: 0.33.1
- Is Node Red running in Docker: yes, Docker

### Other (please complete the following information):

- Have you searched previous issues for duplicates?: Yes, didn't see anything exactly on point.

**Comment by zachowj** [comment]
One of the fundamentals of NR is the ability to override the config settings of a node from an input. This is exactly what is happening here. Take a look at the current state node docs <https://zachowj.github.io/node-red-contrib-home-assistant-websocket/node/current-state.html#payload-entity-id>, it accepts an entity id from the input at `msg.payload.entity_id`.

**Comment by FuzzyMistborn** [comment]
Got it, thank you.  Swear that was working before the last week or so, but maybe it wasn't and I just never noticed.  Added a change node before the current_state and it works fine.
