### ISSUE TITLE
Wait Until node not working with mustache template

### ISSUE THREAD

**Issue by michaelblight** [zachowj/node-red-contrib-home-assistant-websocket#424]
### Describe the bug

Issue 259 either seems to be back, or was not fully fixed.

### To Reproduce

The example below sets `msg.theEntity` to "switch.tp_link_111", and then passes to a wait-until node with the entity set to `{{theEntity}}`.

### Expected behavior

In my case, the entity is already in the 'on' state before the flow runs, so the wait-until should pass to the first output immediately. However, the timeout occurs and the message is passed to the second output.

### Example Flow

```
[{"id":"bbf8b875.950e68","type":"inject","z":"14d7530.3c9a1ad","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":730,"y":200,"wires":[["1768a898.e97e37"]]},{"id":"1768a898.e97e37","type":"change","z":"14d7530.3c9a1ad","name":"Entity","rules":[{"t":"set","p":"theEntity","pt":"msg","to":"switch.tp_link_111","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":890,"y":200,"wires":[["72d138ed.cf6128"]]},{"id":"72d138ed.cf6128","type":"ha-wait-until","z":"14d7530.3c9a1ad","name":"","server":"5c211963.f91a88","outputs":2,"entityId":"{{theEntity}}","entityIdFilterType":"exact","property":"state","comparator":"is","value":"on","valueType":"str","timeout":"5","timeoutType":"num","timeoutUnits":"seconds","entityLocation":"","entityLocationType":"none","checkCurrentState":false,"blockInputOverrides":true,"x":1040,"y":200,"wires":[["6a5aaa17.bbf844"],["6916d2e3.d181ac"]]},{"id":"6a5aaa17.bbf844","type":"debug","z":"14d7530.3c9a1ad","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":1175,"y":160,"wires":[],"l":false},{"id":"6916d2e3.d181ac","type":"debug","z":"14d7530.3c9a1ad","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":1175,"y":240,"wires":[],"l":false},{"id":"5c211963.f91a88","type":"server","z":"","name":"Home Assistant","legacy":false,"addon":false,"rejectUnauthorizedCerts":true,"ha_boolean":"y|yes|true|on|home|open","connectionDelay":false,"cacheJson":true}]
```

### Environment (please complete the following information):

- Node Red Version: 1.3.5
- Node.js Version: 12
- NR Home Assistant Plugin Version: 0.33.1
- Is Node Red running in Docker: Yes

### Other (please complete the following information):

- Have you searched previous issues for duplicates?: Yes, 259 is the same issue that has been closed

**Comment by michaelblight** [comment]
I also noticed that this node does not always correctly handle the situation where an entity is already in the desired state. All my switches seem to work properly, but lights don't. So, for example, I turn on a light and use the wait-until to check it came on. If it was off it's ok, but if already on, it will time-out. As mentioned, the behaviour with switches works, and if already on, a wait-until on will pass immediately. This is obviously easy to workaround - just put a `current state` node before this and only continue if the state `is not` the desired state.

**Comment by zachowj** [comment]
You're going to want to check the box for `Check Against Current State`

<https://zachowj.github.io/node-red-contrib-home-assistant-websocket/node/wait-until.html#check-against-the-current-state>

**Comment by michaelblight** [comment]
Ok, I will try that. In that case, the documentation is misleading. It says

> When an input is received it will check the comparator against the current state instead of waiting for a state change.

Given it says "instead of" it implies if the current state fails the comparator, it will not then wait for a state change.
