### ISSUE TITLE
New Dimmer support

### ISSUE THREAD

**Issue by KyleMoran138** [zachowj/node-red-contrib-home-assistant-websocket#434]
### Describe the bug

None of the button press events for the new dimmer model _9290023986_  are working. 
### To Reproduce

1. Create fake room in the hue app
2. Add dimmer to fake room
3. remove all lights from the fake room
4. Add `node-red-contrib-home-assistant-websocket : ha-device` device node to node-red 
5. Set the trigger to _"Turn On" button released_
6. Deploy the new flow
7. Press the on button on the dimmer
8. Observe no event firing from the node

### Expected behavior

1. Create fake room in the hue app
2. Add dimmer to fake room
3. remove all lights from the fake room
4. Add `node-red-contrib-home-assistant-websocket : ha-device` device node to node-red 
5. Set the trigger to _"Turn On" button released_
6. Deploy the new flow
7. Press the on button on the dimmer
8. Observe event firing from the node

### Environment (please complete the following information):

- Node Red Version: 1.3.5
- Node.js Version: 16(?) 
- NR Home Assistant Plugin Version: 9.1.4
- Is Node Red running in Docker: HA addon

### Other (please complete the following information):

- Have you searched previous issues for duplicates?: yes, I looked for any open/closed issue with the keyword dimmer and 9290023986

### Additional context

Just got a couple of these remotes and I only have 14 days to return them 😬 

### Example Flow

```
export goes here
```

### Environment (please complete the following information):

- Node Red Version: [e.g. 1.0.4]
- Node.js Version: [e.g. 12.16.1]
- NR Home Assistant Plugin Version: [e.g. 0.21.3]
- Is Node Red running in Docker: [e.g. yes/no/HA addon]

### Other (please complete the following information):

- Have you searched previous issues for duplicates?:

**Comment by zachowj** [comment]
Does the device trigger work in a Home Assistant automation?

**Comment by KyleMoran138** [comment]
I don't have any automation set up for triggers in HA. 
I have the older model hue dimmer and that one works if I follow the re-creation steps. But the new one does not

**Comment by KyleMoran138** [comment]
Just added an automation to my home assistant. Can confirm that the new dimmer triggers HA automation but does not trigger in node-red

**Comment by zachowj** [comment]
Anything in the logs of NR or HA? You have the custom component installed and work in HA?

You can try changing the HA log level to debug for the custom component.

```
logger:
  logs:
    custom_components.nodered: debug
```

**Comment by KyleMoran138** [comment]
No clue why it wasn't working before. But while trying to debug it with the logs it just started working. Sorry! 🤦‍♀️🤦‍♀️🤦‍♀️🤦‍♀️
Good to close the ticket for me. 

![facepalm](https://user-images.githubusercontent.com/6720187/123322516-6a991400-d502-11eb-88b8-1a1c0b5c401c.gif)

**Comment by KyleMoran138** [comment]
Just a note, not sure what I changed but I just started setting up 2 other dimmers similar to the first one I tried. They're not responding. I'll post back once I figure out what causes them to work

**Comment by KyleMoran138** [comment]
The new dimmers are also not working in the HAS automation scripts, I'm going to try a haas restart

**Comment by KyleMoran138** [comment]
Restarting HA ended up fixing the issue
