### ISSUE TITLE
Notify service node fails to escape unicode characters in string payload

### ISSUE THREAD

**Issue by AlexKalopsia** [zachowj/node-red-contrib-home-assistant-websocket#441]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

If I send the string `It's partly cloudy outside` - stored in a message (ie `msg.notification`) - via the Notify service node, using the `notify.matrix` or the `notify.discord` service, it shows up as `It&#39;s partly cloudy outside`. 

I have tried to extensively debug this as much as I could, and I currently got to these tests:

1. Send `{"message":" {{ notification }} "}` via nodered to `notify.matrix` -> message looks wrong
2. Send {"message":" {{ notification }}, "target": "xxxxxxxx"} via nodered to `notify.discord` -> message looks wrong
3. Send `It's partly cloudy outside` via hass ui to `notify.matrix` -> message looks correct
4. Send ` message: '{{ state_attr("sensor.test", "notification")` yaml via the hass ui -> message looks correct
5. Send `{"message":" It's partly cloudy outside"}` via nodered to `notify.matrix` -> message looks correct

Especially 1 and 5 make me think something weird is happening with the notify service node (especially because 3 seems to prove that the service itself works just fine. 

One of the weirdest things is that adding a Debug node before or after the Notify service node, shows that `notification` is looking intact, meaning that something wrong is happening with how the payload is handled. 

As an extra test, I have tried calling the `notify.matrix` service wit

### To Reproduce

1. Create a string payload containing special characters
2. Pass it to a Notify service node using `notify.matrix` service
3. Send the notification

### Expected behavior

The unicode characters should be escaped, so that `It's` doesn't show as `It&#39;s`

### Screenshots

![image](https://user-images.githubusercontent.com/706110/125176321-c9cd7880-e1d2-11eb-9b50-06a17fa25510.png)

Issue shows up storing the message as a string 
![image](https://user-images.githubusercontent.com/706110/125177986-b9bc9580-e1e0-11eb-96f9-be13871920e4.png)

Issue also shows up if I store the string inside JSON data
![image](https://user-images.githubusercontent.com/706110/125177971-909c0500-e1e0-11eb-848f-03ef43253659.png)

### Example Flow

```json
[{"id":"b1b927e2.ab0418","type":"inject","z":"e022927e.b9e14","name":"Trigger","props":[],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payloadType":"str","x":990,"y":40,"wires":[["ac52bbae.19c738"]]},{"id":"ac52bbae.19c738","type":"change","z":"e022927e.b9e14","name":"Create payload","rules":[{"t":"set","p":"notification","pt":"msg","to":"It's partly cloudy outside.","tot":"str"},{"t":"set","p":"notification2","pt":"msg","to":"{ \"info\": \"It's partly cloudy outside.\"}","tot":"json"},{"t":"set","p":"notification3","pt":"msg","to":"\"It's partly cloudy outside.\"","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":1160,"y":40,"wires":[["3cfc211e.387b2e"]]},{"id":"3cfc211e.387b2e","type":"api-call-service","z":"e022927e.b9e14","name":"Notify","server":"d0c1a869.0ef548","version":3,"debugenabled":false,"service_domain":"notify","service":"discord","entityId":"","data":"{\"message\": \"{{ notification }} {{ notification2.info }} {{ notification3 }} It's cloudy outside\", \"target\": \"863543277532741641\" }","dataType":"json","mergecontext":"","mustacheAltTags":false,"outputProperties":[],"queue":"none","x":1330,"y":40,"wires":[["7c7c6c06.1e40e4"]],"icon":"font-awesome/fa-envelope"},{"id":"7c7c6c06.1e40e4","type":"debug","z":"e022927e.b9e14","name":"Debug Test","active":true,"tosidebar":true,"console":true,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":1500,"y":100,"wires":[]},{"id":"d0c1a869.0ef548","type":"server","name":"Home Assistant","version":1,"legacy":false,"addon":false,"rejectUnauthorizedCerts":true,"ha_boolean":"y|yes|true|on|home|open","connectionDelay":true,"cacheJson":true}]
```

### This package's version

0.33.1

### Is Node-RED running in Docker?

Yes

### Node-RED version

1.3.5

### Node.js version

14.17.1

**Comment by zachowj** [comment]
https://zachowj.github.io/node-red-contrib-home-assistant-websocket/guide/mustache-templates.html

> By default, Mustache will replace certain characters with their HTML escape codes. To stop this happening, you can use triple braces: {{{payload}}}.

**Comment by AlexKalopsia** [comment]
Oh my god lol. Thanks, I guess 😅
