### ISSUE TITLE
Call service node with no Data field (null) will be processed with Data field on previouse node.

### ISSUE THREAD

**Issue by Aniroots** [zachowj/node-red-contrib-home-assistant-websocket#448]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I found on Call service node show some error about `extra key not allow` but i have no Data field on that node. After basic investigated, the extra data is coming from previous Node. 

Error message
![image](https://user-images.githubusercontent.com/23647566/127405754-2c2b7fc8-7613-480e-9139-ca032c4db926.png)

Call service node config
![image](https://user-images.githubusercontent.com/23647566/127405822-ce6009de-bf00-4624-b2a7-5223360b282b.png)

Found extra data
![image](https://user-images.githubusercontent.com/23647566/127406060-97816ccf-c139-4642-a555-decf2d24359c.png)

Previous node
![image](https://user-images.githubusercontent.com/23647566/127406097-896a0298-1e65-4b6d-b262-ebbea987e5c3.png)

### To Reproduce

1. Create Fire event node (N1) with some `Data field`.
2. Create Call service node (N2) with no `Data field` but specify `Json type`.
3. Link  N1 -> N2.
4. The data on N1 will add to N2.

### Expected behavior

The data should be function as input.

### Screenshots

![image](https://user-images.githubusercontent.com/23647566/127406417-ab6c3663-0f02-4ef0-bb96-f86976499c94.png)

### This package's version

-

### Is Node-RED running in Docker?

Home Assistant add-on

### Node-RED version

1.3.5

### Node.js version

-

**Comment by zachowj** [comment]
This is working as intended. The call-service node accepts inputs to override node configs.

<https://zachowj.github.io/node-red-contrib-home-assistant-websocket/node/call-service.html#input>

In this case where you don't want to override the call-service node. One option would be to use a change node to either move or delete `msg.payload`.

**Comment by Aniroots** [comment]
Could you plase suggest me that if i want to call some service that require no data parameter after i fire the event with some custom data? Becase now, i can call the service correctly by removing the data field on fire event node.
