### ISSUE TITLE
Device node does not see window sensor open /closed

### ISSUE THREAD

**Issue by Tsamsiyu1** [zachowj/node-red-contrib-home-assistant-websocket#480]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

i have a Window sensor out of deCONZ. DeCONZ and Home Assistant both see it within a second of status change. But the device node does notresponse at all.

### This package's version

0.33.1

### Is Node-RED running in Docker?

Home Assistant add-on

### Node-RED version

1.3.5

### Node.js version

14.17.1

**Comment by Tsamsiyu1** [comment]
if i go with the "current state node" it gives me this in the log: Entity could not be found in cache for entity_id: binary_sensor.openclose_7

**Comment by zachowj** [comment]
Do you have the custom component, https://github.com/zachowj/hass-node-red, installed and loaded in HA?

**Comment by Tsamsiyu1** [comment]
no i have not

**Comment by zachowj** [comment]
at the top of the device node you should see

![image](https://user-images.githubusercontent.com/37859597/135887470-3701b44d-943e-4be6-a6ca-3d355916c94e.png)

**Comment by Tsamsiyu1** [comment]
oh wow i am so stupid thanks.
Closed

**Comment by Tsamsiyu1** [comment]
i think i am doing something wrong here. i have the companion installed, did a restart and still the device trigger does not do anything

**Comment by zachowj** [comment]
Does the attention box still appear in the node editor?

Did you do step #8 in installation steps and does the box for NR show on the integrations page?

**Comment by Tsamsiyu1** [comment]
yeah now it works i was missing the  refresh after restart. thanks
