### ISSUE TITLE
Two hass instances problem

### ISSUE THREAD

**Issue by Misak** [zachowj/node-red-contrib-home-assistant-websocket#49]
**Describe the bug**
When using multiple home-assistant instances, Entity IDs are not loaded from selected server, but from the first one. Even if I select different server in node properties and hit deploy, entities are still pulled from the wrong server.

**To Reproduce**
1. add second hass server
2. add new hass node
3. select second hass server
4. try to find entity from the second server (only from first one are populated).

**Expected behavior**
Etities from new server should show up in EntityID selector.

**Environment (please complete the following information):**
 - Node Red Version: 0.19.5
 - NR Home Assistant Plugin Version: 0.3.1
 - Is Node Red running in Docker: yes

**Other (please complete the following information):**
- Have you searched previous issues for duplicates?: yes
- Did you attempt to reproduce the issue in the dev docker environment, if so what were results (See README.md): yes

**Comment by zachowj** [comment]
Yes, this was a bug on the original fork. I have this on my TODO list but since no one had brought it up it was a low priority. I'll bump it up now and get a fix in for it.

**Comment by marc-gist** [comment]
latest version exhibits this behavior still... you have to select the next server, click done, then go back into the node edit mode to get the other server's entity list.
