### ISSUE TITLE
system slow

### ISSUE THREAD

**Issue by matteos1** [zachowj/node-red-contrib-home-assistant-websocket#491]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

installing this version the system becomes unresponsive and very slow

### This package's version

0.36.0

### Is Node-RED running in Docker?

Home Assistant add-on

### Node-RED version

2.0.6

### Node.js version

0.0

**Comment by zachowj** [comment]
What was your last working version?

@dougle03 0.27.0 or 0.37.0?

**Comment by dougle03** [comment]
I think 0.33.1
Because NR does not notify of new versions of nodes I rarely check, I've now restored from a snapshot back a day and back to normal, but I'm unwilling now to update again as the restore process was not the easiest...
