### ISSUE TITLE
Stale development documentation

### ISSUE THREAD

**Issue by alfredopironti** [zachowj/node-red-contrib-home-assistant-websocket#511]
### Documentation URL

https://zachowj.github.io/node-red-contrib-home-assistant-websocket/guide/development.html

### The problem

The information provided in the Development section seems to be stale. It refers to running `npm run dev`, while recent commits in the .devcontainer folder seem to indicate development has moved over Visual Studio.

Also, at the bottom of the page are "Node Debugger via VSCode" instructions, which also seem to be stale. The current .vscode/launch.json file seems to indicate one should connect to port 9123.

As a matter of fact, I did clone the repo in VS, but I was unable to get started with debugging, and this hinders my ability to provide simple PRs to this project. Any chance guidance for aspiring contributors can be updated? Many thanks!

**Comment by zachowj** [comment]
Yes, it's very outdated. I'll see about getting something written up.

**Comment by alfredopironti** [comment]
Just saw the bot notification. Is there anything I can help with to keep this alive and make progress?
