### ISSUE TITLE
Supervisor token not found

### ISSUE THREAD

**Issue by NNois** [zachowj/node-red-contrib-home-assistant-websocket#517]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

from 2 days now I've got this message in debug.
Although all seems to be working fine...
`msg : string[73]
"node-red-contrib-home-assistant-websocket/all:Supervisor token not found."`

### This package's version

0.38

### Is Node-RED running in Docker?

Yes

### Node-RED version

2.1.3

### Node.js version

don't know (run on synology)

**Comment by zachowj** [comment]
Did you import a flow that has a different server config?

**Comment by NNois** [comment]
Hi, I do have copy pasted some nodes !!!
Do I need to check them one by one ?

**Comment by zachowj** [comment]
![image](https://user-images.githubusercontent.com/37859597/143661442-bd2c044c-7e50-41d2-985e-bbdb313aa1cd.png)

It would be a server config node

**Comment by NNois** [comment]
Hello,
I've reconfigured via the "configuration nodes" option... same error.
Do you think I can try to redo the docker container remove the config and check from that ?

**Comment by NNois** [comment]
In fact strangely each time I copy past some node this creates an another "home assistant" causing the errors...
I can disable them thought !
How can I delete them ?
![image](https://user-images.githubusercontent.com/2362053/145640949-851bbc31-f077-4794-a325-01f016c63d1c.png)

**Comment by zachowj** [comment]
Open each server config and there's a delete button, then deploy.

![image](https://user-images.githubusercontent.com/37859597/145644364-6e65741e-4b91-41f0-ad78-a5f75767c0cb.png)


You can use the scrubber to remove others server configs before importing.

https://zachowj.github.io/node-red-contrib-home-assistant-websocket/scrubber/
