### ISSUE TITLE
TypeError: Cannot read property 'state' of null

### ISSUE THREAD

**Issue by jonferreira** [zachowj/node-red-contrib-home-assistant-websocket#525]
### The problem

Hi all.

I've been fighting with some nasty errors with this node which immediately crash node-red. Think I've finally tracked it down:

![image](https://user-images.githubusercontent.com/7714292/145218151-1f3d28a5-7942-4389-ba2c-9af2545139aa.png)

This happens when I add a new device to HA. Today it happened me multiple times few seconds after a new device has been added to deconz which in turn is then picked up by HA.

Sounds like something is null at the time a device is added which is unexpected by the node and throws an exception?

**Comment by zachowj** [comment]
What version are you running?

**Comment by jonferreira** [comment]
oops my bad!

node-red 2.0.6
node-red-contrib-home-assistant-websocket 0.38.0
home-assistant 2021.9.2

this has been happening for a couple of months now and in between I've update everything multiple times with no change in behaviour

**Comment by jonferreira** [comment]
damn that was fast. thanks! will update as soon as it's published to npm
