### ISSUE TITLE
Call Service - Unknown Service

### ISSUE THREAD

**Issue by seaverd** [zachowj/node-red-contrib-home-assistant-websocket#527]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Up until 0.39, I have been able to use a call service node to call/set the effect of WLED prior to turning the light on (which I do in a separate node).  Please see attached screenshot.  I now get an API error on the call service node when I set the effect.  As shown in the screenshot it says: "Unknown Service"

Did something change with 0.39 that eliminates being able to call the effect in this manner?  Has worked flawlessly for past several months before update to current version.

### Screenshots

![wled_sunrise_call_service](https://user-images.githubusercontent.com/2743685/146097385-14c06542-832b-4753-91ab-b60ea249cdb7.jpg)

### This package's version

0.39.0

### Is Node-RED running in Docker?

Yes

### Node-RED version

2.1.4

### Node.js version

14.18.2

**Comment by zachowj** [comment]
https://github.com/home-assistant/core/pull/60537

**Comment by seaverd** [comment]
Got it, thanks for the prompt response.  Will close.

Dan
