### ISSUE TITLE
Time node doesn't trigger

### ISSUE THREAD

**Issue by My-userid** [zachowj/node-red-contrib-home-assistant-websocket#528]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When setting an alarm on my phone the Home Assistant app updates the sensor in HA and the node in nodered also updates with the right time.

However when the time comes the node does not trigger.

There is no error, not in the debug window or in the docker container log.

### Expected behavior

Expect the node to atleast write something to the debug node.

### Screenshots

![image](https://user-images.githubusercontent.com/25727555/146232465-fd118378-d75e-4834-b9d1-e6f5a79a0b2f.png)

### This package's version

0.39.0

### Is Node-RED running in Docker?

Yes

### Node-RED version

2.1.3

### Node.js version

14.18.1

**Comment by strikeir13** [comment]
Was there a fix for this or a settings configuration change? I'm experiencing the same behavior now. Node Red addon version 12.0.2
