### ISSUE TITLE
`(input_)select.select_option` doesn't accept data input

### ISSUE THREAD

**Issue by TheGroundZero** [zachowj/node-red-contrib-home-assistant-websocket#533]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

First, I fail to select an option in an `input_select` or `select` entity.
None of the input I try in the data field are accepted.

I tried
- `{"option":"Lava"}`
- `"Lava"`
- `Lava`

See https://github.com/hassio-addons/addon-node-red/issues/1220

### To Reproduce

1. Have a Home Assistant `select` or `input_select` entity
2. Setup a Node-RED flow with a Call Service node
3. Set the call_svc node up as follows:
  - Domain: select
  - Service: select_option
  - Entity id: <your select entity>
  - Data: `{ "option": "your wanted selection" }`
4. Trigger the flow
5. An API Error is thrown:  
   `"Call-service error. extra keys not allowed @ data['option']"`

![image](https://user-images.githubusercontent.com/2406013/146802085-ebd96c60-fffe-41a3-9cf8-ac09a7e20658.png)

Note: I also tried and failed using `Lava` and `"Lava"` as Data input.

### Expected behavior

Select the wanted option in the (input_)select entity

### Screenshots

![image](https://user-images.githubusercontent.com/2406013/146810318-0876ebba-51d3-4524-8b37-9f8ce72f1ccb.png)

![image](https://user-images.githubusercontent.com/2406013/146802118-86a94b16-34fb-4084-b9b7-789e2ca180ef.png)

### Example Flow

```json
[{"id":"4e4da9f9b0d84130","type":"api-call-service","z":"a84dd1437dd5ab38","name":"Intensity","server":"2ce15169.23b9de","version":3,"debugenabled":true,"service_domain":"number","service":"set_value","entityId":"number.wled_f6dafd_segment_1_intensity","data":"5","dataType":"json","mergecontext":"","mustacheAltTags":false,"outputProperties":[],"queue":"none","x":400,"y":280,"wires":[["6ba94590b53584ac"]]},{"id":"6ba94590b53584ac","type":"api-call-service","z":"a84dd1437dd5ab38","name":"Speed","server":"2ce15169.23b9de","version":3,"debugenabled":true,"service_domain":"number","service":"set_value","entityId":"number.wled_f6dafd_segment_1_speed","data":"5","dataType":"json","mergecontext":"","mustacheAltTags":false,"outputProperties":[],"queue":"none","x":530,"y":280,"wires":[["ce92a1328c61889c","c087381398c2157a"]]},{"id":"ce92a1328c61889c","type":"api-call-service","z":"a84dd1437dd5ab38","d":true,"name":"Palette","server":"2ce15169.23b9de","version":3,"debugenabled":true,"service_domain":"select","service":"select_option","entityId":"select.wled_f6dafd_segment_1_color_palette","data":"{\"option\":\"Lava\"}","dataType":"json","mergecontext":"","mustacheAltTags":false,"outputProperties":[],"queue":"none","x":660,"y":300,"wires":[["c087381398c2157a"]]},{"id":"c087381398c2157a","type":"api-call-service","z":"a84dd1437dd5ab38","name":"Sunrise","server":"2ce15169.23b9de","version":3,"debugenabled":true,"service_domain":"light","service":"turn_on","entityId":"light.wled_f6dafd_segment_1","data":"{\"effect\":\"Sunrise\"}","dataType":"json","mergecontext":"","mustacheAltTags":false,"outputProperties":[],"queue":"none","x":800,"y":280,"wires":[["b1abee6f295c1e8e","ffacfbfa8c418c51"]]},{"id":"2ce15169.23b9de","type":"server","name":"Home Assistant","version":1,"addon":true,"rejectUnauthorizedCerts":true,"ha_boolean":"y|yes|true|on|home|open","connectionDelay":true,"cacheJson":true}]
```

### This package's version

0.40.0

### Is Node-RED running in Docker?

Home Assistant add-on

### Node-RED version

2.1.4

### Node.js version

?

**Comment by zachowj** [comment]
WLED is a `select` not an `input_select` there's a difference. https://www.home-assistant.io/integrations/select/#services

**Comment by TheGroundZero** [comment]
As you can see in my screenshots, I'm actually using the `select` domain.

It works in the Developer Tools, but not in Node-RED.

![image](https://user-images.githubusercontent.com/2406013/146826121-6535b2f7-2ad7-4d55-a22d-0675224d940d.png)

**Comment by zachowj** [comment]
Here's a gif showing the call-service being called and the event state node showing `select` being updated.
https://i.imgur.com/keyqqeR.gif

![image](https://user-images.githubusercontent.com/37859597/146827167-dee7550d-9466-4116-ace4-f9f2ce9d4001.png)

What does the debug show being sent to HA? Is it what is expected?

**Comment by TheGroundZero** [comment]
The issue appears to have solved itself.

Yesterday, I kept getting API errors.
![Image](https://user-images.githubusercontent.com/2406013/146802118-86a94b16-34fb-4084-b9b7-789e2ca180ef.png)
