### ISSUE TITLE
Data field description/example doesn't match actually expected value

### ISSUE THREAD

**Issue by TheGroundZero** [zachowj/node-red-contrib-home-assistant-websocket#534]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The description and example data for the data field don't match with what's actually expected.
While the description/example is showing a JSON-object, the node actually expects an int or a string.
See screenshot with `number.set_value`

### To Reproduce

1. Add a 'call service' node and set it up as `number.set_value` or `select.select_option`
2. Load example data
3. Modify example to your needs
4. Trigger the flow
5. API Error

### Expected behavior

Triggering the flow should correctly call `number.set_value` or `select.select_option`

### Screenshots

![image](https://user-images.githubusercontent.com/2406013/146811043-34c62466-961d-4538-a24e-c776fb17822f.png)
![image](https://user-images.githubusercontent.com/2406013/146811354-b7bb6b78-2914-4a9e-9be9-0360ca8f4ef3.png)
![image](https://user-images.githubusercontent.com/2406013/146802118-86a94b16-34fb-4084-b9b7-789e2ca180ef.png)

### Example Flow

```json
[{"id":"4e4da9f9b0d84130","type":"api-call-service","z":"a84dd1437dd5ab38","name":"Intensity","server":"2ce15169.23b9de","version":3,"debugenabled":true,"service_domain":"number","service":"set_value","entityId":"number.wled_f6dafd_segment_1_intensity","data":"5","dataType":"json","mergecontext":"","mustacheAltTags":false,"outputProperties":[],"queue":"none","x":400,"y":280,"wires":[["6ba94590b53584ac"]]},{"id":"2ce15169.23b9de","type":"server","name":"Home Assistant","version":1,"addon":true,"rejectUnauthorizedCerts":true,"ha_boolean":"y|yes|true|on|home|open","connectionDelay":true,"cacheJson":true}]
```

### This package's version

0.40.0

### Is Node-RED running in Docker?

Home Assistant add-on

### Node-RED version

2.1.4

### Node.js version

?

**Comment by zachowj** [comment]
The example data is pulled directly from Home Assistant this package has no control over it other than displaying it.

**Comment by zachowj** [comment]
https://github.com/home-assistant/core/blob/dev/homeassistant/components/number/services.yaml

**Comment by TheGroundZero** [comment]
Calling the service in HA does require the data to be provded in a JSON object.
However, these nodes don't respect this and require me to enter the value straight in the data field.

If I don't pass the value for `number.set_value` as an int instead of `{ "value" : 5 }` I get an error
![image](https://user-images.githubusercontent.com/2406013/146826628-87429467-70f3-48d8-8206-fef38a82b5e4.png)


Also, `select.select_option` completely doesn't work (#533)

**Comment by zachowj** [comment]
I am not really sure what you think the bug here is. The data is always a JSON object.

![image](https://user-images.githubusercontent.com/37859597/146827983-0de7310a-364c-4156-9c6a-754e15368106.png)

and here's a gif of it in action

https://i.imgur.com/stFwHuv.gif

**Comment by TheGroundZero** [comment]
What is going on here?

Did things change between 0.33 and 0.40?
I spent a lot of time this afternoon before and after upgrading with this issue, and now all of a sudden it starts to work okay-ish?

![image](https://user-images.githubusercontent.com/2406013/146827918-5203896d-9b14-4888-aa87-9d611fb39422.png)

![image](https://user-images.githubusercontent.com/2406013/146828413-9da8ca36-bc17-459c-b5b4-7d4107c126d5.png)

![image](https://user-images.githubusercontent.com/2406013/146828391-6e26b20a-6747-46cf-827a-4d6e3bf6cb59.png)

**Comment by TheGroundZero** [comment]
> I am not really sure what you think the bug here is. The data is always a JSON object.
> 
> ![image](https://user-images.githubusercontent.com/37859597/146827983-0de7310a-364c-4156-9c6a-754e15368106.png)
> 
> and here's a gif of it in action
> 
> https://i.imgur.com/stFwHuv.gif

This afternoon, I got an API error if I used a JSON object instead of entering the value as a plain integer.
Now it's a JSON object

**Comment by TheGroundZero** [comment]
I don't know what or how, but it appears I've been chasing ghosts the whole afternoon ?! 👻

![image](https://user-images.githubusercontent.com/2406013/146828930-417193b1-879b-4860-9e35-db79d53a9f3c.png)

![image](https://user-images.githubusercontent.com/2406013/146828838-5563116b-dc61-440e-9153-712e8adb2033.png)
