### ISSUE TITLE
state_class not set to HA sensor

### ISSUE THREAD

**Issue by DirkMu** [zachowj/node-red-contrib-home-assistant-websocket#535]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I created a sensor entity in node red and set state_class to total_increasing. However, in HA state_class is not set

### To Reproduce

Create a sensor entity and set state_class to total_increasing. Deploy. Check the entity in HA. 

### Screenshots

![image](https://user-images.githubusercontent.com/53949754/147415690-d30ff980-f05d-46ed-b199-1d00d43ba083.png)

![image](https://user-images.githubusercontent.com/53949754/147415681-8d6c472d-a950-459b-9b63-334f29c948e7.png)

![image](https://user-images.githubusercontent.com/53949754/147415712-0bf0796e-c92e-4f1b-a684-d773053f68c5.png)

### This package's version

0.40.0

### Is Node-RED running in Docker?

Yes

### Node-RED version

2.1.4

### Node.js version

14.16.0

**Comment by zachowj** [comment]
What version of the custom component are you running?

**Comment by DirkMu** [comment]
I am running 0.5.4

**Comment by zachowj** [comment]
install the version from the `main` branch. I wanted to release the button entity when I released the current version but got busy for the holidays.

**Comment by DirkMu** [comment]
😊
`main` branch works fine 👌
I will close the issue.
