### ISSUE TITLE
High interval for poll state node causes poll state to trigger infinitely without any delay

### ISSUE THREAD

**Issue by kenni** [zachowj/node-red-contrib-home-assistant-websocket#551]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Setting a poll state node to an interval of 999 hours causes the poll state to trigger hundreds of times per second, leading to 100% CPU usage.

1 minute poll state works as expected (poll node triggers once every minute):
<img width="1046" alt="Screenshot 2022-01-10 at 15 17 23" src="https://user-images.githubusercontent.com/486971/148780902-5cec53ca-34c7-4c6a-b513-e65dd5fdb84e.png">

Changing its interval to 999 hours causes the poll state to trigger infinitely without any delay, causing 100% CPU usage:
<img width="1040" alt="Screenshot 2022-01-10 at 15 17 58" src="https://user-images.githubusercontent.com/486971/148780962-7fd92547-562b-45cc-b6aa-b6cfba449b50.png">

### To Reproduce

Install Home Assistant OS 7.1 with latest Node Red add on (v10.3.1) and add a poll state node with an interval of 999 hours. Or use exported example below.

### Example Flow

```json
[
    {
        "id": "2e043f81fe0f6b9f",
        "type": "poll-state",
        "z": "f6223e7b162da061",
        "name": "",
        "server": "6f851b75.a2fe24",
        "version": 2,
        "exposeToHomeAssistant": false,
        "haConfig": [
            {
                "property": "name",
                "value": ""
            },
            {
                "property": "icon",
                "value": ""
            }
        ],
        "updateinterval": "999",
        "updateIntervalType": "num",
        "updateIntervalUnits": "hours",
        "outputinitially": false,
        "outputonchanged": false,
        "entity_id": "light.sovevaerelse_bordlampe",
        "state_type": "str",
        "halt_if": "on",
        "halt_if_type": "str",
        "halt_if_compare": "is",
        "outputs": 2,
        "x": 1260,
        "y": 320,
        "wires": [
            [
                "19860ccab08b6425"
            ],
            []
        ]
    },
    {
        "id": "19860ccab08b6425",
        "type": "debug",
        "z": "f6223e7b162da061",
        "name": "",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "payload",
        "targetType": "msg",
        "statusVal": "",
        "statusType": "auto",
        "x": 1610,
        "y": 320,
        "wires": []
    },
    {
        "id": "6f851b75.a2fe24",
        "type": "server",
        "name": "Home Assistant",
        "version": 2,
        "addon": true,
        "rejectUnauthorizedCerts": true,
        "ha_boolean": "y|yes|true|on|home|open",
        "connectionDelay": true,
        "cacheJson": true,
        "heartbeat": false,
        "heartbeatInterval": 30
    }
]
```

### This package's version

0.41.3

### Is Node-RED running in Docker?

Home Assistant add-on

### Node-RED version

2.1.4

### Node.js version

16.13.1-r0

**Comment by zachowj** [comment]
It's a limitation of delay value in `setInterval`. 

> When delay is larger than 2147483647 or less than 1, the delay will be set to 1. Non-integer delays are truncated to an integer.

<https://nodejs.org/api/timers.html#setintervalcallback-delay-args>

Probably should be added to the docs of the node.
