### ISSUE TITLE
class 'custom_components.nodered.sensor.NodeRedSensor'>) implements device_state_attributes

### ISSUE THREAD

**Issue by hmorkemo** [zachowj/node-red-contrib-home-assistant-websocket#559]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I'm getting this warning in the Home Assistant log:
`sensor.total_electricity_price (<class 'custom_components.nodered.sensor.NodeRedSensor'>) implements device_state_attributes. Please report it to the custom component author.`
One for each of my node red sensors when restarting Home Assistant.

### To Reproduce

Restart Home Assistant, with one or more Node Red ha-entity nodes.

### Expected behavior

No messages

### This package's version

0.41.3

### Is Node-RED running in Docker?

Home Assistant add-on

### Node-RED version

2.1.6

### Node.js version

Don't know

**Comment by zachowj** [comment]
Update the custom component. https://github.com/zachowj/hass-node-red
