### ISSUE TITLE
Override input data when calling the service

### ISSUE THREAD

**Issue by rchl** [zachowj/node-red-contrib-home-assistant-websocket#56]
**Describe the bug**
I'm not sure it's me not knowing how to do things yet, or it's a missing feature. I'd like to be able to override input payload when using `call service` node.

**To Reproduce**
1. Chain two `call service` nodes. First that calls `timer.cancel` and second that calls `timer.start` with same entity_id

**Expected behavior**
That `timer.cancel` is called first and then `timer.start`

**Actual behavior**
`timer.cancel` is called twice as output payload from first node is passed and used by the second node.

**Example Flow**
```
[{"id":"679207b1.7ae398","type":"tab","label":"Flow 2","disabled":false,"info":""},{"id":"78d118ff.4a3a58","type":"trigger-state","z":"679207b1.7ae398","name":"On door opened","server":"88a88639.b89d78","entityid":"binary_sensor.telldus_tzdw100_magnet_switch_sensor","entityidfiltertype":"exact","debugenabled":false,"constraints":[{"id":"a3z34r1tall","targetType":"this_entity","targetValue":"","propertyType":"current_state","propertyValue":"new_state.state","comparatorType":"is","comparatorValueDatatype":"str","comparatorValue":"on"}],"constraintsmustmatch":"all","outputs":2,"customoutputs":[],"outputinitially":false,"x":100,"y":120,"wires":[["b02763eb.3ccd9","e04f42a6.3ec28"],[]]},{"id":"14045802.eba358","type":"api-call-service","z":"679207b1.7ae398","name":"Turn ON","server":"88a88639.b89d78","service_domain":"homeassistant","service":"turn_on","data":"{\"entity_id\":\"switch.kitchen_switch\"}","render_data":false,"mergecontext":"","x":580,"y":80,"wires":[[]]},{"id":"b02763eb.3ccd9","type":"api-current-state","z":"679207b1.7ae398","name":"If kitchen light OFF","server":"88a88639.b89d78","halt_if":"on","override_topic":true,"override_payload":true,"override_data":true,"entity_id":"switch.kitchen_switch","x":390,"y":80,"wires":[["14045802.eba358"]]},{"id":"fa5cf4bf.12a668","type":"api-call-service","z":"679207b1.7ae398","name":"Start timer","server":"88a88639.b89d78","service_domain":"timer","service":"start","data":"{\"entity_id\":\"timer.kitchen\"}","render_data":false,"mergecontext":"","x":1090,"y":160,"wires":[[]]},{"id":"64d6653c.52f83c","type":"api-current-state","z":"679207b1.7ae398","name":"timer.kitchen state","server":"88a88639.b89d78","halt_if":"","override_topic":true,"override_payload":true,"override_data":true,"entity_id":"timer.kitchen","x":670,"y":140,"wires":[["f7608503.c343b8"]]},{"id":"e04f42a6.3ec28","type":"api-current-state","z":"679207b1.7ae398","name":"If no kitchen movement","server":"88a88639.b89d78","halt_if":"on","override_topic":true,"override_payload":true,"override_data":true,"entity_id":"binary_sensor.aeotec_zw100_multisensor_6_sensor","x":430,"y":140,"wires":[["64d6653c.52f83c"]]},{"id":"f7608503.c343b8","type":"api-call-service","z":"679207b1.7ae398","name":"Cancel timer","server":"88a88639.b89d78","service_domain":"timer","service":"cancel","data":"{\"entity_id\":\"timer.kitchen\"}","render_data":false,"mergecontext":"","x":890,"y":160,"wires":[["fa5cf4bf.12a668"]]},{"id":"88a88639.b89d78","type":"server","z":"","name":"Home Assistant"}]
```

**Environment (please complete the following information):**
 - Node Red Version: 0.19.5
 - NR Home Assistant Plugin Version: 1.2.0
 - Is Node Red running in Docker: yes

**Other (please complete the following information):**
- Have you searched previous issues for duplicates?: yes
- Did you attempt to reproduce the issue in the dev docker environment, if so what were results (See README.md): yes

**Additional context**

**Comment by zachowj** [comment]
This is a known "feature" and trips up most new users. Currently, the way to handle this is either branch the two `call-service` nodes or to use a `change` node to delete the payload in between. Each method depends on your use case and if you need to wait for the `call-service` to finish before calling the next one.  I'll be adding in the ability to not send along a payload in the next release, probably have it put the data in `msg.data` instead of `msg.payload`.

![](https://i.imgur.com/DK1kXZ9.png)

![](https://i.imgur.com/yBLvn1b.png)

**Comment by rchl** [comment]
`call-service`, on the home assistant level, is a fire-and-forget type of call, that doesn't return any value. Wouldn't it make sense for nodes to match that conceptually?

It doesn't make sense to me that `call-service` node passes input data further and if that trips up new users, maybe it makes sense to disable that by default (or even remove that option completely).

**Comment by oakbrad** [comment]
This just tripped me up, I would also appreciate some way to not have the service pass along it's data to the next in the node.
