### ISSUE TITLE
Current State node does not seem to match documentation.

### ISSUE THREAD

**Issue by oblivionratula** [zachowj/node-red-contrib-home-assistant-websocket#561]
### Documentation URL

https://zachowj.github.io/node-red-contrib-home-assistant-websocket/node/current-state.html#configuration

### The problem

State Location, Entity Location, and Override Topic all seem to be missing from the GUI. I'm very new to Node-Red, so admit I'm probably doing something wrong, but I've googles and and kind of losing my mind as I'm trying to get the node not to overwrite the existing payload.  

![image](https://user-images.githubusercontent.com/9834921/151447846-08a806e3-9f0d-4544-aae3-a56a17b4a513.png)

**Comment by zachowj** [comment]
You are correct, the documentation is still referencing things that were removed when Output properties were added.  Those 3 things are now handled there.

**Comment by zachowj** [comment]
Click the little X and have it not output anything to `msg.payload`

![image](https://user-images.githubusercontent.com/37859597/151450077-8b192d00-d266-44d0-ba2a-3638a052a849.png)
