### ISSUE TITLE
z-wave device rollershutter3 missing integer field

### ISSUE THREAD

**Issue by Pabl0z** [zachowj/node-red-contrib-home-assistant-websocket#565]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

when adding device action: set device position [which range from 0=closed to 100=opened] to z-wave device rollershutter3 [[fibaro website](https://www.fibaro.com/en/products/smart-roller-shutter/)]
error is displayed: "Unknown field type: integer -- Report"

### To Reproduce

select zwave device action 

<img width="471" alt="Zrzut ekranu 2022-01-29 o 20 40 07" src="https://user-images.githubusercontent.com/19762095/151675306-5e6dace3-4209-441a-a9d8-02d452c1a453.png">
<img width="643" alt="Zrzut ekranu 2022-01-29 o 20 34 21" src="https://user-images.githubusercontent.com/19762095/151675332-ef22be7c-eb68-4c66-a04d-070496b7be07.png">
<img width="572" alt="Zrzut ekranu 2022-01-29 o 20 35 54" src="https://user-images.githubusercontent.com/19762095/151675348-7ec107a4-5bf1-4123-b3fb-ebadc0e08049.png">

### Expected behavior

field for integer input

### This package's version

0.33.1

### Is Node-RED running in Docker?

Home Assistant add-on

### Node-RED version

2.1.6

### Node.js version

14.17.1

## System Health

version | core-2021.12.10
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.7
os_name | Linux
os_version | 5.10.88
arch | x86_64
timezone | Europe/Warsaw

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 5000
Installed Version | 1.20.0
Stage | running
Available Repositories | 1031
Downloaded Repositories | 3

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 7.1
-- | --
update_channel | stable
supervisor_version | supervisor-2021.12.2
docker_version | 20.10.9
disk_total | 30.8 GB
disk_used | 8.0 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Studio Code Server (4.1.0), Z-Wave JS (0.1.52), Mosquitto broker (6.0.1), Samba share (9.5.1), Terminal & SSH (9.3.0), File editor (5.3.3), Node-RED (10.3.4)

</details>

<details><summary>Lovelace</summary>

dashboards | 3
-- | --
resources | 2
views | 6
mode | storage

</details>

**Comment by zachowj** [comment]
Yes, I need to add `integer` and `boolean` types to the device node. I'll try and get those in before the next release.

**Comment by Pabl0z** [comment]
Great, that's good news🙂
