### ISSUE TITLE
Call Service Tips and Tricks doesn't match Node

### ISSUE THREAD

**Issue by 3ative** [zachowj/node-red-contrib-home-assistant-websocket#574]
### Documentation URL

https://zachowj.github.io/node-red-contrib-home-assistant-websocket/guide/call-service.html

### The problem

None of these are referenced in the Docs
![image](https://user-images.githubusercontent.com/51385971/153724295-c6723d6d-866f-434d-81ef-83bf31d66185.png)

**Comment by zachowj** [comment]
The main call-service node documentation is found on a different page.

https://zachowj.github.io/node-red-contrib-home-assistant-websocket/node/call-service.html

**Comment by 3ative** [comment]
@zachowj Thanks 👍

### I was using this link:
![image](https://user-images.githubusercontent.com/51385971/154850172-2a517654-e9b6-41ff-9ce7-f3a466680824.png)

But that seems to have been updated too. 💖
