### ISSUE TITLE
Device node hide text on Action / Trigger combobox

### ISSUE THREAD

**Issue by danirebollo** [zachowj/node-red-contrib-home-assistant-websocket#581]
### Describe the bug

When drag "Device node" for the first time everything seems to work well in his configuration menu, but when close and open again configuration menu action combobox text is trimmed.

### To Reproduce

For example, I want to use some Frigate device to turn on detect mode: 

- Server: Home assistant
- Type: Action
- Device: House
- Action: "Turn on house detect"

But when close and open again it shows:
- Server: Home assistant
- Type: Action
- Device: House
- Action: "Turn on"

There is a lot of things with "turn on" at the beginning so I don't know what is the detect I'm looking for. The combobox now is:

- Turn on
- Turn off
- Turn on
- Turn off

### Expected behavior

- Turn on Terraza detect 
- Turn off Terraza detect
- Turn on Terraza recordings
- Turn off recordings

### Screenshots

![dn1](https://user-images.githubusercontent.com/4015490/153952031-58eb6c48-758a-4adc-a8bd-c0c43550f472.png)
![dn2](https://user-images.githubusercontent.com/4015490/153952038-73babbd4-8e5e-46d3-82a9-31b4936ee495.png)

### This package's version (not the Home Assistant add-on verison)

0

### Is Node-RED running in Docker?

No

### Node-RED version

2.2.0

### Node.js version

0

### Additional context

I'm not really sure about when this problem takes place. Sometimes the combobox text is ok and sometimes not.
Home Assistant node-red ver: 11.0.1

**Comment by zachowj** [comment]
Sort of a known issue. Every time the node editor is opened for the device node it has to retrieve the translations from HA. Which goes through the NR server then to the HA server and back. Something weird happens sometimes. The process needs to be made more robust.
