### ISSUE TITLE
Call to service fails from node-red

### ISSUE THREAD

**Issue by tlalos** [zachowj/node-red-contrib-home-assistant-websocket#582]
### Describe the bug

When i run a service call through node-red i get this error:
Call-service error. value should be a string for dictionary value @ data['entity_id']

This was working normally i dont know why now it shows this error.
The entity id is passed correct to the appropriate field.

### This package's version (not the Home Assistant add-on verison)

0.42.4

### Is Node-RED running in Docker?

No

### Node-RED version

11.0.1

### Node.js version

14,17,1

**Comment by zachowj** [comment]
https://github.com/home-assistant/core/issues/66545
