### ISSUE TITLE
ha-entity reverts attribute value type selector

### ISSUE THREAD

**Issue by CamSoper** [zachowj/node-red-contrib-home-assistant-websocket#583]
### Describe the bug

ha-entity reverts attribute value type selector upon load. See screenshot.

### To Reproduce

1. Add ha-entity to a flow
2. Set an attribute on the entity using `msg.` from the value type selector
3. Click done
4. Double-click the ha-entity node
5. Note the `msg.` has been reverted to a string.

### Expected behavior

ha-entity remembers attribute settings correctly

### Screenshots

![node-red-entity](https://user-images.githubusercontent.com/137648/154094619-53a9d604-0952-4b8d-b870-68bbdd0aa67f.gif)

### This package's version (not the Home Assistant add-on verison)

0.42.4

### Is Node-RED running in Docker?

Yes

### Node-RED version

2.1.6

### Node.js version

Whatever the docker container uses

**Comment by p0wertiger** [comment]
Stumbled upon this bug today, exactly the same behavior.
