### ISSUE TITLE
Events: State and Trigger: State nodes bugged

### ISSUE THREAD

**Issue by blackcult** [zachowj/node-red-contrib-home-assistant-websocket#586]
### Describe the bug

Events: State and Trigger: State nodes don't show entity, after switch to dropdown menu. I am not sure when exactly this happened, as it works fine after update and you notice it when changing workflows

### To Reproduce

Create any Events: State and Trigger: State node, select entity and deploy. When you open the node again, it won't show the entity. Also if you change anything in the node, it will actually switch to the first alphabetical entity in HA.

### Expected behavior

The entity_id should stay visible and permanent in the node view

### Screenshots

Workflow view
![image](https://user-images.githubusercontent.com/20770953/154266702-024cbc51-817c-413e-84da-d513a3b6ded7.png)
Node view (seems like no entity is selected. When click done, it will still show the picture above)
![image](https://user-images.githubusercontent.com/20770953/154266904-d49f852b-04f9-4874-966d-c7f59d6d32be.png)
But if I for example change in the same node "Output on connect" (or anything else) it will change to a first entity in the list
![image](https://user-images.githubusercontent.com/20770953/154267059-7dee89ce-b316-47ef-bc24-f5e71f49abb8.png)

Same applies for the trigger: state node

### This package's version (not the Home Assistant add-on verison)

0.42.4

### Is Node-RED running in Docker?

Home Assistant add-on

### Node-RED version

2.2.0

### Node.js version

16.14.0

**Comment by zachowj** [comment]
Do you have your deploy type set to "Full"?

**Comment by blackcult** [comment]
Hello Jason, 
I am not aware there would be such an option in the HA addon. Can you point me on what to check?

Adding the node-red addon logs.
I can't find any hint there though
```
[09:19:37] INFO: Starting Node-RED...
> start
> node $NODE_OPTIONS node_modules/node-red/red.js "--settings" "/etc/node-red/config.js"
17 Feb 09:19:38 - [info] 
Welcome to Node-RED
===================
17 Feb 09:19:38 - [info] Node-RED version: v2.2.0
17 Feb 09:19:38 - [info] Node.js  version: v16.14.0
17 Feb 09:19:38 - [info] Linux 5.10.98 x64 LE
17 Feb 09:19:38 - [info] Loading palette nodes
17 Feb 09:19:40 - [info] Dashboard version 3.1.5 started at /endpoint/ui
Traceback (most recent call last):
  File "/opt/node_modules/node-red-node-pi-gpio/testgpio.py", line 3, in <module>
    import RPi.GPIO as GPIO
  File "/usr/lib/python3.9/site-packages/RPi/GPIO/__init__.py", line 23, in <module>
    from RPi._GPIO import *
RuntimeError: This module can only be run on a Raspberry Pi!
17 Feb 09:19:40 - [warn] rpi-gpio : Raspberry Pi specific node set inactive
17 Feb 09:19:40 - [info] Settings file  : /etc/node-red/config.js
17 Feb 09:19:40 - [info] Context store  : 'default' [module=memory]
17 Feb 09:19:40 - [info] User directory : /config/node-red/
17 Feb 09:19:40 - [warn] Projects disabled : editorTheme.projects.enabled=false
17 Feb 09:19:40 - [info] Flows file     : /config/node-red/flows.json
17 Feb 09:19:40 - [info] Server now running at http://127.0.0.1:46836/
17 Feb 09:19:40 - [info] Starting flows
[09:19:40] INFO: Starting NGinx...
17 Feb 09:19:41 - [info] Started flows
17 Feb 09:19:41 - [info] [server:Home Assistant] Connecting to http://supervisor/core
17 Feb 09:19:41 - [info] [server:Home Assistant] Connected to http://supervisor/core
17 Feb 09:20:28 - [info] Stopping flows
17 Feb 09:20:28 - [info] [server:Home Assistant] Closing connection to http://supervisor/core
17 Feb 09:20:28 - [info] Stopped flows
17 Feb 09:20:28 - [info] Starting flows
17 Feb 09:20:28 - [info] Started flows
17 Feb 09:20:28 - [info] [server:Home Assistant] Connecting to http://supervisor/core
17 Feb 09:20:28 - [info] [server:Home Assistant] Connected to http://supervisor/core
```
