### ISSUE TITLE
State change not working

### ISSUE THREAD

**Issue by CypherMK** [zachowj/node-red-contrib-home-assistant-websocket#589]
### Describe the bug

If I have a light entity, and I switch it on or off within home assistant, there is no change of state within node red. It will show the state of the light on 'deploy'only.

### Screenshots

![image](https://user-images.githubusercontent.com/5131017/154488535-4ad33fe5-8557-45e6-96c4-bde3ee9e5766.png)
![image](https://user-images.githubusercontent.com/5131017/154488673-ba84e58c-3355-4c05-a3f8-e9397fb9bd0e.png)
![image](https://user-images.githubusercontent.com/5131017/154488714-ccd91f0b-15ce-4fc9-b29f-3d43993859c1.png)

### This package's version (not the Home Assistant add-on version)

0.42.5

### Is Node-RED running in Docker?

No

### Node-RED version

2.2.0

### Node.js version

14.19.0

**Comment by zachowj** [comment]
I can't reproduce this. Any errors in NR or HA logs?

![chrome_bNkLRL6lT7](https://user-images.githubusercontent.com/37859597/154595155-c121571e-65e6-4dd1-bae0-5206297f4e6a.gif)

**Comment by CypherMK** [comment]
> I can't reproduce this. Any errors in NR or HA logs?
> 
> ![chrome_bNkLRL6lT7](https://user-images.githubusercontent.com/37859597/154595155-c121571e-65e6-4dd1-bae0-5206297f4e6a.gif)

Copied your setup, but same issue. I'll check the logs.

**Comment by CypherMK** [comment]
Can't find anything in the logs. So the only clues are:

- the undefined message in node red
- the state_changed shows the state after deploy when checked

**Comment by zachowj** [comment]
> So the first entitie is: undefined. That seems weird.

That's normal. It would only be filled in for `state_changed` events.

If you use events: all node set to `state_changed` do you see the light change event?

**Comment by CypherMK** [comment]
> state_changed

Tried as you said, and yes I see them instantly.

**Comment by CypherMK** [comment]
@zachowj So if I use the events:all node it works, but if I use the state node it does not work. What else can we try?

**Comment by zachowj** [comment]
If you can see the `state_changed` event in the events:all node, not really sure what the issue could be as NR is receiving the event.

You could try changing the filter type to something other than `exact`

**Comment by CypherMK** [comment]
Tried exact, list, regex and substring. No change. Also messed a bit with output properties. No change.

Like I said previously, when I tick 'output on connect', it works on deploy only. So the state is displayed in node red under the node. When I toggle the light state it does not change the state node.

Can it be something with my installation? It's a fairly recent installation. Homeassistent is in docker and node red is installed with the bash script on their website.

**Comment by CypherMK** [comment]
Now I tried the 'poll state' node with 'output on changed' ticked. This gives an immediate change in the state of the light.

**Comment by CypherMK** [comment]
So why does the state change node not work?
