### ISSUE TITLE
Call Service node reporting API call error when populating Entity field if using Logbook/Log domain/service call.

### ISSUE THREAD

**Issue by mty17** [zachowj/node-red-contrib-home-assistant-websocket#590]
### Describe the bug

API error on 'Call Service' node when calling 'logbook/log' domain/service.
If 'Entity' field is populated the call to the API is unsuccessful and reports 'Call-service error'
If 'Entity' field is left blank it the call is successful.
'Call service' node works fine when using the 'switch' domain.

### To Reproduce

1 Create a 'call service' node
2 Use 'logbook' domain and the 'log' service
3 Populate the 'entity' field with any valid entity in your system. 
4 Use an inject node to activate the service all 
6 Trigger the inject node and you will get an API 'call-service' error

### Expected behavior

Keep the behavior as in the previous versions. 
Previously, I was able to use the 'Entity' field pass it to the log service to be correctly populated in the log entry.

### Example Flow

```json
`[{"id":"3411bfc6f0a7330f","type":"api-call-service","z":"f1b6eb10f8042de9","name":"Logging","server":"1680b843.4f7308","version":4,"debugenabled":false,"domain":"logbook","service":"log","target":{"areaId":[],"deviceId":[],"entityId":["switch.power_switch_02"]},"data":"{ \"name\": \"{{data_log.name}}\", \"message\": \"{{data_log.message}} [Node-RED_{{data_log.id}}]\", \"domain\": \"{{data_log.domain}}\", \"entity_id\": \"{{data_log.entity_id}}\" }","dataType":"json","mergeContext":"","mustacheAltTags":false,"outputProperties":[],"queue":"none","x":1140,"y":860,"wires":[[]]},{"id":"cee9084140327534","type":"inject","z":"f1b6eb10f8042de9","name":"","props":[{"p":"data_log.message","v":"has been turned ON or OFF by Node-RED automation","vt":"str"},{"p":"data_log.entity_id","v":"switch.power_switch_02","vt":"str"},{"p":"data_log.domain","v":"switch","vt":"str"},{"p":"data_log.name","v":"friendly_name","vt":"str"},{"p":"data_log.id","v":"your_own_ID_for_reference","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","x":950,"y":860,"wires":[["3411bfc6f0a7330f"]]},{"id":"1680b843.4f7308","type":"server","name":"Home Assistant","version":2,"addon":true,"rejectUnauthorizedCerts":true,"ha_boolean":"y|yes|true|on|home|open","connectionDelay":true,"cacheJson":true,"heartbeat":false,"heartbeatInterval":30}]`
```

### This package's version (not the Home Assistant add-on version)

0.42.5

### Is Node-RED running in Docker?

Home Assistant add-on

### Node-RED version

2.2.1

### Node.js version

16.14.0

**Comment by zachowj** [comment]
Are you sure you're running 0.42.5? The export shows that the call-service node is run a previous version.

I can't reproduce any errors with the entity field being filled or empty. One of the breaking changes to 0.42.0 was that the target fields, (area, device, entity) now overwrite any of those fields in the data field (area_id, device_id, entity_id).

**Comment by mty17** [comment]
> Are you sure you're running 0.42.5? The export shows that the call-service node is run a previous version.
> 
> I can't reproduce any errors with the entity field being filled or empty. One of the breaking changes to 0.42.0 was that the target fields, (area, device, entity) now overwrite any of those fields in the data field (area_id, device_id, entity_id).

I think I am, unless I didn't look in the right place. Here is a screen shot of where I got the version number
![Screenshot 2022-02-17 182214](https://user-images.githubusercontent.com/38573542/154605657-cb5c3767-ba98-456e-9309-06078f3bfdde.jpg)
:

**Comment by mty17** [comment]
Thanks a lot @zachowj.
I don't know what to tell you, I am testing again on the same export I included, and it seems to be working now.
I spend at least a solid hour trying everything I could think of, so I decided to bring it up to you here.

**Comment by mty17** [comment]
Did I look up the version in the correct place by the way?

**Comment by zachowj** [comment]
Yes, you had the version correct based on the palette version
