### ISSUE TITLE
TimeoutOverflowWarning when starting node-red

### ISSUE THREAD

**Issue by vandalon** [zachowj/node-red-contrib-home-assistant-websocket#6]
**Describe the bug**
When starting node-red i'm getting: TimeoutOverflowWarning: 315360000000 does not fit into a 32-bit signed integer. in the logs.

**To Reproduce**
restart node-red or just press deploy and observe the logs.

**Expected behavior**
see the following in the log:

0|node-red  | 13 Oct 17:18:41 - [info] [server:Home Assistant] New WebSocket http://localhost:8123
0|node-red  | 13 Oct 17:18:41 - [debug] [server:Home Assistant] config server event listener connected
0|node-red  | (node:20757) TimeoutOverflowWarning: 315360000000 does not fit into a 32-bit signed integer.
0|node-red  | Timeout duration was set to 1.

**Environment (please complete the following information):**
 - Node Red Version: 0.18.4
 - NR Home Assistant Plugin Version: 0.1.1
 - Is Node Red running in Docker: no

**Other (please complete the following information):**
- Have you searched previous issues for duplicates?: I have
- Did you attempt to reproduce the issue in the dev docker environment, if so what were results (See README.md): I did not, sorry.

**Comment by vandalon** [comment]
When looking to the long term tokens from hass, I think it's because of them:

`.storeage/auth: 315360000.0`

I think this is not a coincidence :)

**Comment by zachowj** [comment]
What platform are you running it on? 
Using Hass.io?
What version of node?

Just trying to get more info to be able to replicate your issue.
