### ISSUE TITLE
hassio Domain not available in api-call-service

### ISSUE THREAD

**Issue by mrosseel** [zachowj/node-red-contrib-home-assistant-websocket#60]
**Is your feature request related to a problem? Please describe.**
The problem has been described in this issue for the hassio node-red addon:
https://github.com/hassio-addons/addon-node-red/issues/99

**Describe the solution you'd like**
I would like to be able to call hassio related services such as 'hassio.snapshot_full'

**Describe alternatives you've considered**
no alternatives are known by me at this point.

**Comment by zachowj** [comment]
I haven't had a chance to look into this but it's only the autocomplete that isn't filling in for you. You still can manually type in `hassio` and `snapshot_full` into the correct fields and it will work in the interim.

**Comment by zachowj** [comment]
Are you still having this issue after a reboot? So far I'm unable to reproduce this.
