### ISSUE TITLE
Server settings are nog capt 

### ISSUE THREAD

**Issue by balou2311** [zachowj/node-red-contrib-home-assistant-websocket#61]
**Describe the bug**
I have e new docker container whit Node Red, install this HA component, select a Node, setup te server deploy it, Then is get a message server not found.. 

When i open the setup detail every thing is empty....

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/46167947/50454701-9cd55500-0949-11e9-8216-3d48aee0a166.png)

**Example Flow**
If applicable, add an example of exported json of a flow exhibiting the issue to aid in reproduction.

**Environment (please complete the following information):**

- Node Red Version:  0.19.5
- NR Home Assistant Plugin Version:  0.5.0
- Is Node Red running in Docker:  yes

**Other (please complete the following information):**

- Have you searched previous issues for duplicates?:

**Additional context**

**Comment by zachowj** [comment]
Are you using the node-red v8 tag docker image and if you are can you post your node-red log?

**Comment by zachowj** [comment]
try something like

`docker run -it -p 1880:1880 --name mynodered nodered/node-red-docker:v8`

**Comment by balou2311** [comment]
Thanks this works...

Op zo 30 dec. 2018 10:15 schreef Jason <notifications@github.com:
