### ISSUE TITLE
Opening a call service node settings triggers a change in the flow

### ISSUE THREAD

**Issue by bonanitech** [zachowj/node-red-contrib-home-assistant-websocket#611]
### Describe the bug

If you have a call service node in a flow, simply opening and closing the settings of that node triggers a change in the flow.

### To Reproduce

1. Double-click on a call service node to see its settings and click Done

### This package's version (not the Home Assistant add-on version)

0.43.0

### Is Node-RED running in Docker?

Yes

### Node-RED version

2.2.2

### Node.js version

16.13.1

**Comment by zachowj** [comment]
I think it's a bug with NR on how it handles select elements when multiple is set to true. Still looking through the NR code to find where the exact problem is.

**Comment by zachowj** [comment]
Can follow the status here: https://github.com/node-red/node-red/issues/3475

**Comment by bonanitech** [comment]
We can close this issue, right?

**Comment by zachowj** [comment]
It's been fixed up stream but I don't think it has made it into a release.
