### ISSUE TITLE
Groups no longer showing in entity list for Light domain

### ISSUE THREAD

**Issue by InstigatorX** [zachowj/node-red-contrib-home-assistant-websocket#615]
### Describe the bug

Groups I've configured in HA groups.yaml no longer show as entities when select the LIGHT domain. Not sure when the bug was introduced as I blindly upgraded to 43.1 and that's when I discovered the bug. My groups show up when I select the HOMEASSISTANT domain, this doesn't allow me to pass brightness and color to my lights in the group.

### To Reproduce

1. Create a CALL-SERVICE object
2. Change domain to LIGHT
3. Change service to TURN_ON
4. Type "group" in entity field and no groups show

Replace 2 with HOMEASSISTANT and voila groups show with caveat data isn't passed.

### Expected behavior

Groups show up as entities in the light domain.

### This package's version (not the Home Assistant add-on version)

43.1

### Is Node-RED running in Docker?

Home Assistant add-on

### Node-RED version

1.3.5

### Node.js version

no idea

**Comment by zachowj** [comment]
A workaround is to type the group id, `group.lights`, and then a `#`. This will allow you to at least enter the id.

**Comment by boriken72** [comment]
> A workaround is to type the group id, `group.lights`, and then a `#`. This will allow you to at least enter the id.

I tried this and when i close out and deploy it goes away:

![image](https://user-images.githubusercontent.com/24843834/159617085-e56c5d3d-e9d3-48ab-aac6-ce3f6ed3b149.png)
