### ISSUE TITLE
Event data msg structure of a device differs from event states node

### ISSUE THREAD

**Issue by DirkMu** [zachowj/node-red-contrib-home-assistant-websocket#618]
### Describe the bug

The message structure of the event data of a device doffers form the event data structure of the events nodes. 

E.g. in the events node the event data contains data.new_state or data_old_state whereas in for a device it is data.from_state and data.to_state. 

Can you please align the event data strutures. 

### To Reproduce

Just use the event data of a device and compare it of the event data of the events: state node. 

### Expected behavior

same structure for the event data output property

### This package's version (not the Home Assistant add-on version)

0.43.1

### Is Node-RED running in Docker?

Yes

### Node-RED version

2.2.2

### Node.js version

16.13.1

**Comment by DirkMu** [comment]
Is there anything, I can do? The issue / request is still valid.

**Comment by DirkMu** [comment]
This is still valid.

**Comment by zachowj** [comment]
Currently, most event data is a raw dump directly from Home Assistant. I'm currently undecided if I want to start changing that. I like the new property names for the device events, but changing to those would break too many things for people.
