### ISSUE TITLE
Device trigger node might not trigger

### ISSUE THREAD

**Issue by herve-thu** [zachowj/node-red-contrib-home-assistant-websocket#622]
### Describe the bug

Using a Device Node with a trigger type to listen to an event (for example turn a light on), then link the node to a Current State node doesn't  pass the event to a next node.
However if the initial Device Node with a trigger type is directly linked to another Device Node with an action type (for example that turn off a light) works.

**This does not "turn off the light":**
![image](https://user-images.githubusercontent.com/7817696/161366701-3dd85813-8e6f-408b-b121-7c976dc9116b.png)

**This works:**
![image](https://user-images.githubusercontent.com/7817696/161366882-4117995d-208e-4e5d-889d-95d2d1c3934a.png)

### To Reproduce

1. Create a Device Node with a trigger type to listen to an event
2. Link the Device Node to another node (I used a Current State node).
3. Link the Current State node to another Device Node with an action type. **This doesn't get triggered.**

### Expected behavior

The node (3) above should be triggered.

### Screenshots

![image](https://user-images.githubusercontent.com/7817696/161366746-c945bb5b-7bf8-4ea2-9052-3d2ab4601b69.png)
![image](https://user-images.githubusercontent.com/7817696/161366759-73689553-a2f9-4b80-9204-94dfac5b697f.png)
![image](https://user-images.githubusercontent.com/7817696/161366771-45d70649-d851-474b-869f-2d5a5c43b726.png)
![image](https://user-images.githubusercontent.com/7817696/161366778-04486a88-9ba4-4411-b565-39247b9b1a9e.png)

### This package's version (not the Home Assistant add-on version)

0.43.1

### Is Node-RED running in Docker?

Yes

### Node-RED version

2.2.2

### Node.js version

unknown

### Additional context

I also found a workaround. I noticed that a Device Node has "msg.payload" set to "event data" by default. If I remove the "msg.payload", everything works fine. If I pass the "event data" in a "msg.data", it also works.

**This works**
![image](https://user-images.githubusercontent.com/7817696/161366957-931bff49-f587-4560-a51d-e93cc91faf72.png)

**This also works**
![image](https://user-images.githubusercontent.com/7817696/161367003-fb021781-f0f1-40a9-9e99-e42f8a62ff39.png)

**Comment by zachowj** [comment]
This is working as intended. The current state node [accepts configuration values](https://zachowj.github.io/node-red-contrib-home-assistant-websocket/node/current-state.html#inputs) via `msg.payload`.

As you noticed the default configuration of a trigger device node is to output the event data to `msg.payload`. Part of the message object is the property `entity_id`. This value is overwriting the `entity_id` of the current state node. You see it working when you either delete this data or move it to a different property of the message object.

**Comment by herve-thu** [comment]
Thanks for the clarification. However the way it's design is misleading. Especially that the state node doc doesn't mention that the entity ID might be overriden.
<img width="807" alt="image" src="https://user-images.githubusercontent.com/7817696/161395432-92e3037e-8f03-41a5-b888-59cc1aaca92b.png">

**Comment by zachowj** [comment]
Scroll down a little more in the documentation.

https://zachowj.github.io/node-red-contrib-home-assistant-websocket/node/current-state.html#payload-entity-id

> payload.entity_id
> Type : string
>
> Overrides or sets the entity_id for which the current state is being fetched

**Comment by zachowj** [comment]
You can also you the "Block Input Overrides" option 

https://zachowj.github.io/node-red-contrib-home-assistant-websocket/node/current-state.html#block-input-overrides

**Comment by herve-thu** [comment]
Thanks... :) I guess we can close this ticket?
