### ISSUE TITLE
Does this break when updating to 2022.4.0

### ISSUE THREAD

**Issue by mash2k3** [zachowj/node-red-contrib-home-assistant-websocket#625]
### Describe the bug

After i update to 2022.4.0 all the ha-device(pink ones) nodes stop working. But all other homeassistant nodes do continue to work.
I know this is expected since its on alpha but just making you aware.

### To Reproduce

Any Node-Red flow with the node ha-device, especially ones that control lights

### Expected behavior

Turn on/off lights

### This package's version (not the Home Assistant add-on version)

0.43.1

### Is Node-RED running in Docker?

Home Assistant add-on

### Node-RED version

2.2.2

### Node.js version

2.2.2

**Comment by zachowj** [comment]
Do you have the latest version of the custom component installed?

**Comment by unix0r** [comment]
I also have some issues after the update:
node-red-contrib-home-assistant-websocket : 0.43.1
node-red: 2.2.2
nodered container: 11.1.1 
custom-component-nodered: 1.0.7 (did not work with 1.0.6 either).

I have several Ikea Trädfri Buttons and they are not triggering anymore.

Furthermore, I have the feeling that it somehow related to the running nodered container (my setup is hassio supervised on a rpi)
Sometimes the debug nodes are reporting button clicks, but after then nodered is reporting error 502 Bad Gateway and I think this is somehow the problem:

`#Button Press
8 Apr 08:52:53 - [red] Uncaught Exception:
8 Apr 08:52:53 - [error] UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "#<Object>".
2022/04/08 08:52:55 [error] 619#619: *563 connect() failed (111: Connection refused) while connecting to upstream, client: 172.30.32.2, server: a0d7b954-nodered, request: "GET /comms HTTP/1.1", upstream: "http://127.0.0.1:46836/comms", host: "home.domain.com"
[08:52:55] INFO: Starting Node-RED...
2022/04/08 08:52:56 [error] 619#619: *563 connect() failed (111: Connection refused) while connecting to upstream, client: 172.30.32.2, server: a0d7b954-nodered, request: "GET /comms HTTP/1.1", upstream: "http://127.0.0.1:46836/comms", host: "home.domain.com"

# Button Press
8 Apr 08:54:03 - [red] Uncaught Exception:
8 Apr 08:54:03 - [error] UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "#<Object>".
[08:54:04] INFO: Starting Node-RED...
2022/04/08 08:54:05 [error] 619#619: *860 connect() failed (111: Connection refused) while connecting to upstream, client: 172.30.32.2, server: a0d7b954-nodered, request: "GET /comms HTTP/1.1", upstream: "http://127.0.0.1:46836/comms", host: "home.domain.com"
> start
> node $NODE_OPTIONS node_modules/node-red/red.js "--settings" "/etc/node-red/config.js"`

I think it's more related to the nodered container?

**Comment by mash2k3** [comment]
I updated to 2022.4.1 and same issue, i have updated companion.
I only have issues with flows that use the pink ha-devices node. when i switch them to current states and call service nodes it operates as it should. So to summarize not all of node-red-contrib-home-assistant-websocket has issues just the ha-devices node.

**Comment by mash2k3** [comment]
unix0r is right after the event, via the homeassitant device, the plugin is crashing and restarts


8 Apr 11:08:43 - [red] Uncaught Exception:
8 Apr 11:08:43 - [error] UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "#<Object>".
[11:08:43] INFO: Starting Node-RED...
2022/04/08 11:08:44 [error] 611#611: *826 connect() failed (111: Connection refused) while connecting to upstream, client: 172.30.32.2, server: a0d7b954-nodered, request: "GET /comms HTTP/1.1", upstream: "http://127.0.0.1:46836/comms", host: "homeassistant.local:8123"
> start
> node $NODE_OPTIONS node_modules/node-red/red.js "--settings" "/etc/node-red/config.js"
2022/04/08 11:08:45 [error] 611#611: *826 connect() failed (111: Connection refused) while connecting to upstream, client: 172.30.32.2, server: a0d7b954-nodered, request: "GET /comms HTTP/1.1", upstream: "http://127.0.0.1:46836/comms", host: "homeassistant.local:8123"
8 Apr 11:08:45 - [info] 
Welcome to Node-RED
===================
8 Apr 11:08:45 - [info] Node-RED version: v2.2.2
8 Apr 11:08:45 - [info] Node.js  version: v16.14.0

**Comment by zachowj** [comment]
@mash2k3  are you also using a button as the device or something else?

**Comment by mash2k3** [comment]
Yes and no. I have button flows and motion flows and they both dont work.
Sometimes Node-red crashes and sometimes works but 100% of the time anything with ha-devices nodes does not work
I just restored back to an older snapshot until this is fixed, its unusable at the current state
I can always update again if i need to test something

**Comment by sipossz** [comment]
Same issue here after upgaded to 2022.4.0 and 2022.4.1

**Comment by mash2k3** [comment]
Same issue with 2022.4.2

**Comment by unix0r** [comment]
Same for 2022.4.3.
Some additional information:
The crash seems to happen only on the "trigger" event. I have an Ikea Trädfri Switch with multiple Buttons and the buttons for changing the brightness are working, but the button for turning the lights off and on is not working.

**Comment by zachowj** [comment]
@unix0r Can you turn on logging of the WebSocket API on the HA side and post the outputs sent to NR when the working and non-working trigger events occurs? It should have a `type` of `device_trigger`.

HA config
```
logger:
  logs:
    homeassistant.components.websocket_api: debug
```

**Comment by zachowj** [comment]
Pretty sure it was caused by this: <https://github.com/home-assistant/core/pull/69013>

Is the error occurring from the device node set to trigger or the device node set to action? Users who have some working flows and some not. Does the nonworking flow have a device node with the type set to `action`?

**Comment by gunr2171** [comment]
> Does the nonworking flow have a device node with the type set to `action`?

That's correct for me. I've got an ha-device with a a type of Trigger (motion sensor detected motion), and that node functions fine. Another ha-device node has a type of Action (turn on a switch), which does not operate.

I've switched out the Action ha-device nodes to api-call-service nodes to operate lights. That makes the flow work, even when the Trigger is a ha-device.

**Comment by zachowj** [comment]
Update your Node-Red custom integration for the fix.

**Comment by Airjys** [comment]
Since the last update it works again like a charm for me also !

**Comment by unix0r** [comment]
I think there is still some bug related to this issue here.
The previous bug was occurring with the toggle service or function of a ha entity. This is now working! I can toggle my lights and I can also turn on some scenes etc.

But there is still a problem with flashing?

After triggering some flashing the addon seems to not work as it supposed to work. The flashing is not stopping and I have to restart the addon or the core itself to stop this behavior.

As soon as I will find some time I can investigate a little bit more.
