### ISSUE TITLE
After upgrading HA past version 2022.4.1; NodeRed workflows stop working

### ISSUE THREAD

**Issue by pst11790** [zachowj/node-red-contrib-home-assistant-websocket#629]
### Describe the bug

After upgrading HomeAssistant version 2022.4.2 & newer; NodeRed workflows stop working. I have been able to fix it by rolling back HomeAssistant to 2022.4.1 from previous backup & functions continue to work but with HA 2022.4.2 & 2022.4.3 NodeRed functions stop working.
I tested this with NodeRed 2022.4.1 & the updated version of NodeRed 2.2.2 via HACS & everything works fine until updating HA.
----
Setup:
HomeAssistant x68_x86
Node-Red Companion: v1.0.7
HA Node-Red Add-on: v11.1.1
----
![Snag_174db4b](https://user-images.githubusercontent.com/101277928/163454496-13f285fb-d2c8-463b-9a29-9f4a22cab17e.png)
![Snag_174ed8b](https://user-images.githubusercontent.com/101277928/163454508-0704b4b6-e36e-49e6-9d37-b9c5dc11a264.png)
![Snag_174fc7f](https://user-images.githubusercontent.com/101277928/163454512-e216524e-e371-4ff2-940c-1db14a1ec338.png)
[home-assistant.log](https://github.com/zachowj/node-red-contrib-home-assistant-websocket/files/8491462/home-assistant.log)
[HA_NodeRed_Log.txt](https://github.com/zachowj/node-red-contrib-home-assistant-websocket/files/8491463/HA_NodeRed_Log.txt)
[NodeRed_Flows.txt](https://github.com/zachowj/node-red-contrib-home-assistant-websocket/files/8491464/NodeRed_Flows.txt)

### Expected behavior

Workflow to trigger as defined

### This package's version (not the Home Assistant add-on version)

11.1.1

### Is Node-RED running in Docker?

Home Assistant add-on

### Node-RED version

v2.2.2

### Node.js version

not sure

**Comment by zachowj** [comment]
duplicate #625
