### ISSUE TITLE
Events: State takes 5 seconds to open properties

### ISSUE THREAD

**Issue by ACrazyConcept** [zachowj/node-red-contrib-home-assistant-websocket#632]
### Describe the bug

Well maybe it is not a bug per se. But still an annoyance.
When opening the Events: State node it takes around 5 seconds before the properties panel actually opens.
I have not seen this behavior with any other nodes.

### To Reproduce

1. Add an Events: State node
2. Double click on it
3. Wait 5 seconds

### Expected behavior

It should preferably open up instantly like any other node.

### This package's version (not the Home Assistant add-on version)

0.43.1

### Is Node-RED running in Docker?

Yes

### Node-RED version

2.2.2

### Node.js version

14.17.3

### Additional context

Node-Red image used: https://github.com/node-red/node-red-docker
I have around 1800-1900 entities in HA if that is somehow related to this.

**Comment by ACrazyConcept** [comment]
Bump.

**Comment by ACrazyConcept** [comment]
@hillbicks Yes you're right. Wait until node is also affected. I didn't actually try all the HA nodes before, I was just talking node-red generally. But now I did, and the Trigger: state node is affected too.
I am using Brave browser btw.

**Comment by meanmrgreen** [comment]
Having the same issue with most of the nodes that lets me select entities. Can take upto 10 seconds for it to open

**Comment by meanmrgreen** [comment]
I'm running the node-red docker addon btw.

**Comment by Cafun** [comment]
Although this is closed, the issue still exists

**Comment by zachowj** [comment]
@Cafun what version of the NR are you running?

**Comment by Cafun** [comment]
> @Cafun what version of the HA nodes are you running?

I'm using the latest version: 0.49.0

**Comment by Cafun** [comment]
It appears this has been resolved (for me) with HA 2023.4.x
