### ISSUE TITLE
Call Service node doesn't have entity_id field when domain is set to media_player

### ISSUE THREAD

**Issue by salleq** [zachowj/node-red-contrib-home-assistant-websocket#635]
### Describe the bug

After updating to 0.43.1, all my Call Service nodes having "media_player" set as domain don't show "entity_id" field at all.
The existing nodes are working until I modify or even open them (I guess they are upgraded to latest version upon opening?)

It's a bit weird though because I don't remember if I had "update all HA nodes" on this version or not, and if I did, they didn't break down at that point. Only when I actually open the node once (and deploy afterwards).

I can of course add the entity_id to data field, but I'd have to go through all the nodes.

This probably is somehow connected to the already closed issue about not being able to use groups in "light" domain. Or, at least I noticed the issue at the same time. I've yet to notice any other similar issues but I guess that's possible too.

### To Reproduce

1. Create a call service -node.
2. Select media_player as domain.
3. Select any service.

### Expected behavior

Entity_id is selectable for media_player domain.

### Screenshots

![image](https://user-images.githubusercontent.com/1240177/167679623-e98b11f0-367f-43bd-9b87-a84d978efcdc.png)

### Example Flow

```json
[{"id":"4856acfd39b233d3","type":"api-call-service","z":"89039032.ef4c9","name":"","server":"6ae95f56.f585f","version":5,"debugenabled":false,"domain":"media_player","service":"media_play","areaId":[],"deviceId":[],"entityId":[],"data":"","dataType":"jsonata","mergeContext":"","mustacheAltTags":false,"outputProperties":[],"queue":"none","x":2530,"y":540,"wires":[[]]},{"id":"6ae95f56.f585f","type":"server","name":"Home Assistant ","version":2,"addon":false,"rejectUnauthorizedCerts":false,"ha_boolean":"y|yes|true|on|home|open","connectionDelay":true,"cacheJson":true,"heartbeat":false,"heartbeatInterval":"30"}]
```

### This package's version (not the Home Assistant add-on version)

0.43.1

### Is Node-RED running in Docker?

Yes

### Node-RED version

2.2.2

### Node.js version

?

**Comment by salleq** [comment]
Same thing happens when tts is selected as the domain and cloud_say is selected as the service.

![image](https://user-images.githubusercontent.com/1240177/172928134-ce176d3f-8fdd-47a4-9a50-97dc86eae8ca.png)

**Comment by zachowj** [comment]
This has been fixed

https://github.com/zachowj/node-red-contrib-home-assistant-websocket/commit/1d4f486c03152e09b48b3822a4111c28d37b19c3
