### ISSUE TITLE
Template Nodes broken in Node Red 3.0.0

### ISSUE THREAD

**Issue by gregg098** [zachowj/node-red-contrib-home-assistant-websocket#647]
### Describe the bug

Just upgraded to Node Red 3.0.0 and now template nodes don't allow me to edit the template. After double clicking an existing template node or a new one, the config box opens like normal, but the area where you would modify the template is almost like a broken icon. 

EDIT: Template nodes also don't run at all. I noticed a few flows that failed with an error now too.

### To Reproduce

Upgrade to NodeRed 3.0.0
See if template nodes are editable.

### Expected behavior

Edit template nodes.

### Screenshots

![image](https://user-images.githubusercontent.com/24879443/179248412-ce45d14d-1a18-498b-91a4-c61f4337252b.png)

### Example Flow

```json
Not necessary. Can drag a new template node into screen and attempt to edit to see the issue.
```

### This package's version (not the Home Assistant add-on version)

0.43.1

### Is Node-RED running in Docker?

Yes

### Node-RED version

3.0.0

### Node.js version

16.16.0 from Docker Container

### Additional context

None

**Comment by zachowj** [comment]
Follow https://github.com/node-red/node-red/issues/3774
