### ISSUE TITLE
NodeRED broken Entities Node - Sensor Attributes

### ISSUE THREAD

**Issue by franco-101** [zachowj/node-red-contrib-home-assistant-websocket#648]
### Describe the bug

I am unsure how long it’s been broken for but I used to be able to use the entities node in NodeRED too pass state and attribute values into HA. 
Currently I am not able to pass attribute information on the node.
Any ideas?

### Screenshots

![17327F80-6F91-4DC3-BE9A-92337A35B69A](https://user-images.githubusercontent.com/60199752/179393962-f689a892-82bc-4471-bbfe-0d62c773ca0f.png)

![1AC4C403-D181-4B23-81D2-DDBD9B60BBD7](https://user-images.githubusercontent.com/60199752/179394036-b7559f2a-7016-4d95-8cd7-eeaa8ad06d94.jpeg)

### This package's version (not the Home Assistant add-on version)

0.43.1

### Is Node-RED running in Docker?

Yes

### Node-RED version

3.3.3

### Node.js version

14.18.2

**Comment by zachowj** [comment]
Are you running the latest version of the custom component?

**Comment by franco-101** [comment]
Running the latest version of the NodeRED Companion / Custom Component version 13.0.0
I have nodeRED running in a docker on a different host 10.0.10.40 to my HA.

**Comment by zachowj** [comment]
The latest version of the [custom component](https://github.com/zachowj/hass-node-red) is version 1.0.9. Version 13 sounds like the latest of the NR [add-on](https://github.com/hassio-addons/addon-node-red).

**Comment by franco-101** [comment]
> The latest version of the [custom component](https://github.com/zachowj/hass-node-red) is version 1.0.9. Version 13 sounds like the latest of the NR [add-on](https://github.com/hassio-addons/addon-node-red).

Thanks a mate, updating the companion has resolved it!
