### ISSUE TITLE
HomeAssistant can't connect anymore

### ISSUE THREAD

**Issue by Shawn9347** [zachowj/node-red-contrib-home-assistant-websocket#652]
### Describe the bug

I am running homeassisant os along with the node-red addon. I have the home assistant connection configured like always. Suddenly, since yesterday, the connection is dropped and node-red says "[info] [server:Home Assistant] Connecting to http://supervisor/core" in the logs. 

### To Reproduce

In node-red, add home assistant with the "node-red-contrib-home-assistant-websocket" plugin and use "I use the home assistant addon" function. It won't connect. 

### Expected behavior

That the connection works. 

### Screenshots

![image](https://user-images.githubusercontent.com/48714886/180182769-e538dead-dd08-4c27-8bb2-05b6abd017f2.png)

![image](https://user-images.githubusercontent.com/48714886/180182906-d0330d35-e26e-4981-be09-3fee47c9e18a.png)

### This package's version (not the Home Assistant add-on version)

0.44

### Is Node-RED running in Docker?

Home Assistant add-on

### Node-RED version

3.0.0

### Node.js version

16.15.0

**Comment by zachowj** [comment]
Do the HA logs show it trying to connect?

**Comment by matteos1** [comment]
this error appear also to me
