### ISSUE TITLE
ha-api node returns empty payload

### ISSUE THREAD

**Issue by Merikei** [zachowj/node-red-contrib-home-assistant-websocket#653]
### Describe the bug

Thanks for the project! :smiley: I'm trying to try out more advanced use but the API node seems to be broken.

[The node documentation](https://zachowj.github.io/node-red-contrib-home-assistant-websocket/node/API.html#config) isn't clear, but based on ha-api WebSocket nodes I found in the cookbook, I have the format of the Data config correct.

According to the Home Assistant Websocket API docs, their API supports [pings](https://developers.home-assistant.io/docs/api/websocket#pings-and-pongs)

### To Reproduce

1. Create API node with Protocol: `WebSocket` and Data: `{"type": "ping"}`.
2. Trigger inject node.
3. The returned object only returns a _msgid, no payload.

### Expected behavior

A pong payload (example from linked HA API documentation)
``` json
{
    "id": 19,
    "type": "pong"
}
```

### Example Flow

```json
[{"id":"5693b223526d4acc","type":"inject","z":"5108744eeb563d3c","name":"Empty","props":[],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","x":730,"y":1520,"wires":[["f282a6a2b08f89ba"]]},{"id":"f282a6a2b08f89ba","type":"ha-api","z":"5108744eeb563d3c","name":"Ping","server":"","version":1,"debugenabled":false,"protocol":"websocket","method":"get","path":"","data":"{\"type\": \"ping\"}","dataType":"json","responseType":"json","outputProperties":[{"property":"payload","propertyType":"msg","value":"","valueType":"results"}],"x":870,"y":1520,"wires":[["20a8bed006e52c26"]]},{"id":"20a8bed006e52c26","type":"debug","z":"5108744eeb563d3c","name":"Pong","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":1010,"y":1520,"wires":[]}]
```

### This package's version (not the Home Assistant add-on version)

0.44.0

### Is Node-RED running in Docker?

Home Assistant add-on

### Node-RED version

3.0.0

### Node.js version

16.16.0-r0

### Additional context

Nothing in HA or NR logs

**Comment by zachowj** [comment]
The ping/pong would require the API node to listen for an incoming message with the same id. It currently does not support that. It only sends a command and outputs the response from the server.

Here's an example of it working in the heartbeat monitor built into the nodes. <https://github.com/zachowj/node-red-contrib-home-assistant-websocket/blob/main/src/homeAssistant/heartbeat.ts>

**Comment by zachowj** [comment]
I was mistaken, this is working as intended. The HA WebSocket lib handles the `pong` response. Which is just returning and empty response.

<https://github.com/home-assistant/home-assistant-js-websocket/blob/95f166b29a09fc1841bd0c1f312391ceb2812520/lib/connection.ts#L389-L396>

**Comment by Merikei** [comment]
Thanks for clearing that up!
I'll close this issue since it's working as intended.

---

I was actually trying to subscribe to calendar triggers initially, however that didn't work, so I went on to trying the more basic ping. So while mistaken, your initial comment sheds some light on me not getting the calendar triggers.

It would be nice to have a calendar-trigger node, especially since I now know it's not going to work on the API node.
For now I'll use a Home Assistant Automation, possibly to create an event that Node Red can see.
Not sure I'll have a chance to work on making the node, but if I ever do I'll comment below.
