### ISSUE TITLE
 Attention: This node requires Node-RED custom integration version 0.5.0+  to be installed in Home Assistant for it to function.

### ISSUE THREAD

**Issue by pilone2k6** [zachowj/node-red-contrib-home-assistant-websocket#656]
### Describe the bug

In node-red, device show the following message, but it is installed.

Attention: This node requires [Node-RED custom integration version 0.5.0+ ](https://github.com/zachowj/hass-node-red) to be installed in Home Assistant for it to function.

### To Reproduce

In Node-red, insert a new device node and the following message shows at the top

Attention: This node requires [Node-RED custom integration version 0.5.0+ ](https://github.com/zachowj/hass-node-red) to be installed in Home Assistant for it to function.

2208 of HA, HACS installed.

### Expected behavior

Not showing the message and working ;)

### Screenshots

![device](https://user-images.githubusercontent.com/77249052/182848573-9ad41588-263d-4a35-920c-4d6505aabb15.png)
)

### Example Flow

```json
Not even at that point
```

### This package's version (not the Home Assistant add-on version)

3.0.1

### Is Node-RED running in Docker?

Home Assistant add-on

### Node-RED version

3.0.1

### Node.js version

Unknown

### Additional context

Running on a pi 4

**Comment by dof250** [comment]
Did you install the Node-RED Companion from HACS? And did you add it as Integration in Home Assistant?

**Comment by pilone2k6** [comment]
Hi,

Was installed first as integration of home assistant then retried with
hacs. ;)

Still the same thing with version

Home Assistant 2022.8.3Supervisor 2022.08.3Operating System 8.4Interface
utilisateur : 20220802.0 - latest

Would you recommend some actions?

Thanks for your time!

Le ven. 5 août 2022, 9 h 11 a.m., dof250 ***@***.***> a
écrit :
