### ISSUE TITLE
wait-until times out if condition is met at the beginning

### ISSUE THREAD

**Issue by paranoidi** [zachowj/node-red-contrib-home-assistant-websocket#657]
### Describe the bug

I used wait-until to wait until list of light entities are off. Works well, except when all lights are already off then the node instead waits until timeout occurs. Another user reported same issue in discord chat.

With list of entities "check against current state" is not available.

### Expected behavior

Should pass immediately since the condition is already met.

### This package's version (not the Home Assistant add-on version)

?

### Is Node-RED running in Docker?

Home Assistant add-on

### Node-RED version

?

### Node.js version

?

**Comment by zachowj** [comment]
This is working as intended. If you're using a list of entities it doesn't check the current when the node receives input.
