### ISSUE TITLE
Cannot GET /homeassistant/36cb91e9.fdc0ce/entities

### ISSUE THREAD

**Issue by uuksu** [zachowj/node-red-contrib-home-assistant-websocket#66]
**Describe the bug**
Error is thrown after giving Home Assistant server information in state_changed node.

**To Reproduce**

1. Drop state_changed node to flow
2. Double click to open node editor
3. Add new server (mostly default values, I gave access token)
4. Click Add
5. Get error message "Cannot GET /homeassistant/36cb91e9.fdc0ce/entities". From browsers network log request shows as failed with status 404.

**Screenshot**

![screenshot](https://user-images.githubusercontent.com/8851723/50539527-63d7f300-0b8a-11e9-9377-798379c981b3.png)

**Expected behavior**
There should not be error popup and home assistant entities are browsable in node editor.

**Environment (please complete the following information):**

- Node Red Version: 0.19.5
- NR Home Assistant Plugin Version: 0.5.0
- Is Node Red running in Docker: no

**Other (please complete the following information):**

Might be related to these #2 #50

**Comment by zachowj** [comment]
After creating a new server you must deploy once for it to become active then you won't see this error.

**Comment by uuksu** [comment]
Workaround seems to work fine. After deploying I don't see the error anymore and entity id field is browsable.

Anyhow this still is bug or undocumented feature.
