### ISSUE TITLE
ha-entity , cannot pass sensor name or id as attribute

### ISSUE THREAD

**Issue by ouinouin** [zachowj/node-red-contrib-home-assistant-websocket#662]
### Describe the bug

Hi, 
first thanks for this great addon opening a lot of possibilities to home assistant.

i manage to pass the attributes from an incoming payload to  the  ha-entity node, and my goal was lazily to pass directly the unique id of the entity i refer to to this node , like this i would use only one node and would push the payload for many sensors in the same node (ala mqtt node)
unfortunately i guess that the node first registers to home assistant before receiving any payload so it sees having no name (i filled nothing on the "home assistant config" section.
its more a question than a bug report since i d just want to confirm what i m guessing, but this feature would be really nice : to "register entity" directly through payload. 
in the screenshot hereafter , i split a json and get the value in the payload and the "name" of the sensor in msg.parts.key so you can guess that it would save a lot of time while trying to gather some data from peripherals containing a lot of sensors (actually  a solar inverter.).
 

### Screenshots

![2022-08-28_16-15](https://user-images.githubusercontent.com/6713759/187078869-5fe3ef9b-d7bc-487b-9bf6-18a0503f0f37.png)

### This package's version (not the Home Assistant add-on version)

0.44.0

### Is Node-RED running in Docker?

Yes

### Node-RED version

3.0.1

### Node.js version

16 unsure

**Comment by Veejer** [comment]
I'd like to +1 on this request but modify it slightly.
I have a similar situation to ouinouin.  Instead of passing the unique Id via an attribute, I propose that the Name under Home Assistant Config group take input not only as a hardcoded string but also from a msg variable.

**Comment by zachowj** [comment]
7a70f4396e250c3688e323cbcd79a51fabb4f0bf
