### ISSUE TITLE
Validating "sensor" attributes broke previously working functionality.

### ISSUE THREAD

**Issue by okets** [zachowj/node-red-contrib-home-assistant-websocket#669]
### Describe the bug

Hello, This change broke setting attributes for a sensor through a config msg (not the UI).
https://github.com/zachowj/node-red-contrib-home-assistant-websocket/commit/b03f1b4649b26d9e3364dc1ef44672c0d28f87a5

I am getting `ValidationError: "attributes" must be an array`
However, `attributes `is defined as an `Object` in the documentation and is an object when asking for the object state.
Please revert or fix the validation.

### To Reproduce

1) create a sensor node (ha-sensor) with "update home assistant".
2) just give it a name and basic configuration.
3) try setting the state and a couple of attributes using a config message.
The validation error will pop up.

### Expected behavior

it used to work before this commit https://github.com/zachowj/node-red-contrib-home-assistant-websocket/commit/b03f1b4649b26d9e3364dc1ef44672c0d28f87a5.
I expect it to work as it used to. 

### Example Flow

```json
[{"id":"e18d8b3e42a6231a","type":"ha-sensor","z":"e54157451689ac7b","name":"Set Attributed Sensor","entityConfig":"dfc29ab9807c956e","version":0,"state":"true","stateType":"bool","attributes":[],"inputOverride":"allow","outputProperties":[],"x":1660,"y":2520,"wires":[[]]},{"id":"01aa096673848e13","type":"function","z":"e54157451689ac7b","name":"Update attributes","func":"const new_payload_attributes={\n    \"first\":1,\n    \"second\":2,\n    \"bar\": \"foo\"\n};\nmsg.payload = {'attributes':new_payload_attributes};\nreturn msg;","outputs":1,"noerr":0,"initialize":"","finalize":"","libs":[],"x":1450,"y":2520,"wires":[["e18d8b3e42a6231a"]]},{"id":"50ed0597da436989","type":"inject","z":"e54157451689ac7b","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":1280,"y":2520,"wires":[["01aa096673848e13"]]},{"id":"dfc29ab9807c956e","type":"ha-entity-config","server":"26a46cfcda59282c","deviceConfig":"","name":"Home Assistant Sensor With Attributes","version":"6","entityType":"sensor","haConfig":[{"property":"name","value":"Attributed Sensor"},{"property":"icon","value":""},{"property":"entity_category","value":""},{"property":"device_class","value":""},{"property":"unit_of_measurement","value":""},{"property":"state_class","value":""}],"resend":true}]
```

### This package's version (not the Home Assistant add-on version)

0.45.0

### Is Node-RED running in Docker?

Yes

### Node-RED version

3.0.2

### Node.js version

16.16.0

**Comment by jncanches** [comment]
Same here. I think the documentation must validated for this point

**Comment by okets** [comment]
Anyone has an idea how to revert to 0.44.0 (previous version)? (running NodeRed in Docker)
This broke some critical flows.

**Comment by jncanches** [comment]
I think you could use nom command in nodeRed folder as described here : https://discourse.nodered.org/t/node-red-admin-help-installing-a-particular-version-of-a-node/11673

**Comment by jncanches** [comment]
I was able to fix somes flows that was using this feature. Kind a bit tricky to find how but it works. That makes me think that it is not a bug but just a miss in documentation

**Comment by okets** [comment]
I dug deep into this. It's definitely a bug.
the only format it accepts is an array of objects that looks exactly like this:
` {property: "bar", valueType: "str", value: "foo"}`
You can change your code around this restriction, but you shouldn't be constrained to this format.
The documentation is correct, the validation has a bug.
