### ISSUE TITLE
Current state node State type boolean no longer working

### ISSUE THREAD

**Issue by DirkMu** [zachowj/node-red-contrib-home-assistant-websocket#671]
### Describe the bug

When checking the state of a entity (binary_sensor, switch, etc.) in the current state node it was possible to check against a boolean instead of 'on'. With 0.45.0 this broke and is no longer working. 

### To Reproduce

1. Use current state node and and inject node
2. Check if state is true/false
3. Set State type to boolean
4. Inject

### Expected behavior

Correct condition check. If entity is on and You check if state is true, the check is supposed to be true.  

### This package's version (not the Home Assistant add-on version)

0.45.0

### Is Node-RED running in Docker?

Yes

### Node-RED version

3.0.2

### Node.js version

16.13.1

**Comment by zachowj** [comment]
I was unable to reproduce this. Can you see if the latest release, v0.45.3, fixes this issue for you?

**Comment by DirkMu** [comment]
was it published to Node-RED palette already?

**Comment by zachowj** [comment]
yes, but I am not sure how often a local copy NR checks for updates.

https://flows.nodered.org/node/node-red-contrib-home-assistant-websocket

**Comment by DirkMu** [comment]
The module itself still shows 0.45.0
![image](https://user-images.githubusercontent.com/53949754/193330773-700048a0-fd69-4d0b-992b-1245ddf12f6d.png)

**Comment by DirkMu** [comment]
I just instellad 0.45.03

The issue persists. 
Please check if false. 

![image](https://user-images.githubusercontent.com/53949754/193340750-2dba77b9-3d29-4247-9cd8-fbac76ad5d30.png)

![image](https://user-images.githubusercontent.com/53949754/193340777-f3b9f0b8-5629-4686-a5d8-aa9dbfe49c41.png)

![image](https://user-images.githubusercontent.com/53949754/193340799-27daec26-222c-4b9b-8ddf-6d14498e5d3e.png)

It is supposed to be routed to output 2. Instead is is routed to 1.

**Comment by DirkMu** [comment]
I am not able to test 0.45.4 since it is not published. npm and palette manager still shows 0.45.3
![image](https://user-images.githubusercontent.com/53949754/193397903-48c01655-41be-4751-91a7-3c340d32ecc1.png)
