### ISSUE TITLE
wait until validation error with 0.45.4

### ISSUE THREAD

**Issue by tteck** [zachowj/node-red-contrib-home-assistant-websocket#677]
### Describe the bug

Upgraded to 0.45.4 validation error on all wait until nodes. Fall back to 0.45.0 all's good.

![Screenshot 2022-10-01 2 03 16 PM](https://user-images.githubusercontent.com/21342670/193422529-583f0f9c-a45e-4faf-b016-b8e5a29a5d26.png)

### This package's version (not the Home Assistant add-on version)

0.45.4

### Is Node-RED running in Docker?

No

### Node-RED version

3.0.1

### Node.js version

14.20.0

**Comment by zachowj** [comment]
What does input into the wait-until node look like? What does the error in the debug panel show?

**Comment by tteck** [comment]
![Screenshot 2022-10-01 2 38 46 PM](https://user-images.githubusercontent.com/21342670/193423621-d8971e13-c213-4795-b4dc-8325e331b925.png)

**Comment by zachowj** [comment]
Not sure at the moment as your setup works without issue for me.

**Comment by tteck** [comment]
Strange, 0.45.0 has no issue, but 0.45.4 does. 🤷🏻‍♂️ 
Thanks for looking into this.

**Comment by zachowj** [comment]
The wait-until node got refactored for 0.45.1. I'll try and broaden the validation and see if that helps.

**Comment by tteck** [comment]
0.45.5 fixed the issue!
Thank you
