### ISSUE TITLE
Status Messages are in UTC

### ISSUE THREAD

**Issue by Spartan-II-117** [zachowj/node-red-contrib-home-assistant-websocket#68]
Status messages should be presented in local time with 24 hour format to be cosistent with the rest of Node-Red

**Comment by zachowj** [comment]
They are formatted to local time in 24-hour format. Are you using Node-RED in docker and don't have the timezone set to your locale? If I recall correctly it defaults to UTC.

**Comment by Spartan-II-117** [comment]
I am, but didn't recall it being an issue in the past, also saw someone post about it on the HA subreddit, so i think node red must have changed something recently.
