### ISSUE TITLE
native_value property in sensor

### ISSUE THREAD

**Issue by malloc32** [zachowj/node-red-contrib-home-assistant-websocket#682]
### Describe the bug

In Home assistant Sensor Entity requied the property [native_value](https://developers.home-assistant.io/docs/core/entity/sensor/) but in node-red when I created a sensor this property doesn't exits, so when I'm trying to add the sensor in home assistant I have an error "Entity is non-numeric:"

### Screenshots

![image](https://user-images.githubusercontent.com/6923005/193432186-f2479cb7-5656-43ed-8a7a-1887761a365f.png)

![image](https://user-images.githubusercontent.com/6923005/193432177-1a2cb705-7707-45ef-a504-49361dce5c4c.png)

![image](https://user-images.githubusercontent.com/6923005/193432201-99f1e678-7fef-4558-ae08-84d633d5c856.png)

### This package's version (not the Home Assistant add-on version)

0.45.5

### Is Node-RED running in Docker?

Yes

### Node-RED version

2.2.2

### Node.js version

14.18.2

### Additional context

Node-RED Companion 1.1.2

**Comment by zachowj** [comment]
state is the native value

**Comment by malloc32** [comment]
O, no it is my fault, sorry.
