### ISSUE TITLE
Update nodes button doesn't work in 0.45.x

### ISSUE THREAD

**Issue by markxroberts** [zachowj/node-red-contrib-home-assistant-websocket#694]
### Describe the bug

Module upgraded to 0.45.9 and then 0.45.10
Upgrade node button in header opens dialog but then doesn't 'do' anything.
All entity nodes remain grey.
When 'grey' nodes selected individually, just get an advisory dialog which won't close.
Attempting to deploy new nodes just shows a red error message with no additional context.
I've been running node-red 2.1.4 docker for months without problem.   This issue only encountered in module 0.45.x

### To Reproduce

See above.

### Expected behavior

Expect upgrade dialog with warnings.

### This package's version (not the Home Assistant add-on version)

0.45.10

### Is Node-RED running in Docker?

Yes

### Node-RED version

2.1.4

### Node.js version

docker

### Additional context

.

**Comment by zachowj** [comment]
Are there any errors in the browser's console after using the button?

**Comment by markxroberts** [comment]
Ah, yes there is an error.  Screenshot:
<img width="1416" alt="Screenshot 2022-10-08 at 16 28 12" src="https://user-images.githubusercontent.com/24419927/194715202-0851eadf-486e-4c19-a01a-8fdabc584a77.png">

**Comment by zachowj** [comment]
Ok. getNodeLinks was added in 3.0.2 from the looks of it. I'll have to figure out a different way to do things.

**Comment by markxroberts** [comment]
Thanks for the hint.  Works with 3.0.2 docker.  I've upgraded to this and all OK.  If you have a lot of nodes (I have 300+) then it works better with Chrome than Safari.  Safari tells you that the webpage is using too much memory and reloads before you can deploy.  Chrome allows you to wait.
