### ISSUE TITLE
CPU% use increase an instability updating from 0.45.5 to 0.45.6 and newer

### ISSUE THREAD

**Issue by inorhan** [zachowj/node-red-contrib-home-assistant-websocket#696]
### Describe the bug

Since update 0.45.6 I noticed an approximate 30% CPU increase and instability in home assistant<->node red connection, to the point of flows not being able to read sensor's state from Home Assistant.

If I disable "Enable global context store not checked", everything works normally again, but I don´t want to lose global context. If I re-enable this option, the problem appears again.

I'm testing in a core I5: Home Assistant 2022.10.1, Supervisor 2022.09.1 Operating System 9.0
The server node informs of 1000 sensors/configs/connections between my HA and Nodered. 
I tested this problem with HA supervised and also with HA core in a container, with an without the option "Using the Home Assistant Add-on", with the same results in all cases.

### To Reproduce

With 0.45.5, "Enable global context store not checked"=checked   ->   Normal CPU use

With 0.45.6-10, "Enable global context store not checked"=checked   ->   + 30% CPU use, HA global contex doesn't update correctly 

With 0.45.6-10, "Enable global context store not checked"=not checked   ->   Normal CPU use

### Expected behavior

Normal CPU use. 
HA global context updates as usual.
No nodered disconnections.

### This package's version (not the Home Assistant add-on version)

0.45.6

### Is Node-RED running in Docker?

Home Assistant add-on

### Node-RED version

3.0.2

### Node.js version

HA Supervised

### Additional context

While testing with home assistant supervised: Node-RED App version used: 13.4.0. Node-RED version used: 3.0.2
While testing with home assistant core: Node-RED version used: 3.0.2

**Comment by zachowj** [comment]
0.45.6 fixed the global context so it actually updates when an entity state was changed. Prior it only updated once on load.

Do you have a CPU load if you don't have NR open in a browser?

**Comment by inorhan** [comment]
Hello zachowj 

The CPU load doesn't change significantly with NR open or close in the browser.
I can only see a big change down in CPU load, if I disable  "Enable global context store not checked".

I'm also checking without any flow in NR, only the config node for node-red-contrib-home-assistant-websocket. Same result: 0.45.5 works ok, newer versions don't.

Maybe I have too many sensors in HA for the global context variable in 0.45.6-10 ??

Thanks for the help.

**Comment by zachowj** [comment]
Right now it updates the global context for every entity change. Depending on your setup this could be 500 times a second. I can put a throttle on that and see if it helps.

**Comment by inorhan** [comment]
Thanks, that can help.
But the problem only shows with 0.45.6-10, not with older versiones (in all cases I have the same flows and configs).

**Comment by zachowj** [comment]
> But the problem only shows with 0.45.6-10, not with older versiones (in all cases I have the same flows and configs).

That is because it was broken from 0.45.0 to 0.45.5 and didn't update when an entity was changed.

**Comment by inorhan** [comment]
You are right, wasn't updating in 0.45.5.
I will have to go back to 0.44, and remove the new ha-sensors.
Will try the new versions you upload!
Thanks.

**Comment by inorhan** [comment]
Just to confirm. I went back to to 0.44, converted the flows using the old nodes, and the CPU load is normal again, and everything works. The HA global context update, and seems stable. 
I just have a lot of the new "ha-entity-config" nodes that I guess I have to manually delete, because they are not used in 0.44.
Regards

**Comment by zachowj** [comment]
You can try version 0.46.0+. In the end, I didn't throttle anything just tried to make it handle large entity sets efficiently. If this didn't fix it for you reopen this issue, please.
