### ISSUE TITLE
Error calling service, home assistant api error

### ISSUE THREAD

**Issue by JonLaliberte** [zachowj/node-red-contrib-home-assistant-websocket#70]
**Describe the bug**
Receiving this error in node-red: "Error calling service, home assistant api error"

**Environment (please complete the following information):**

- Node Red Version: 0.18.7
- NR Home Assistant Plugin Version: 0.5.1
- Is Node Red running in Docker: yes
- HA Version: 0.73.1 (too many breaking changes since to do a quick update to a more recent build)

- Have you searched previous issues for duplicates?: Yes

**Additional context**
I found issue #3, but it doesn't apply here.

I've had this installed and working for some time now. I updated the plugin from v0.2.1 to 0.5.1 the other day. After this I started getting the "Error calling service, home assistant api error" errors. 
The thing is, the calls seem to be working - but an error is logged each time.

For example I have a simple test flow with an inject node connected to a call service node to turn off a light. After injecting the light turns off, but I receive 2 errors in the debug log:

<img width="307" alt="screenshot 2019-01-02 14 42 01" src="https://user-images.githubusercontent.com/5403662/50609102-be2fc700-0e9c-11e9-8f8c-515a0e2ce550.png">

**Comment by zachowj** [comment]
Yes looks like something is going on. I haven't had a chance to fully look into why this is occurring but did test it on the latest build of node-red v0.19.5 and it seems to work. So if updating your Node-RED is a viable option I would recommend that until I can track this down.

**Comment by zachowj** [comment]
Looks like a breaking change was introduced into v0.5.0 without realizing it. Node-RED v0.19.+ is required now for version 0.5.0+
