### ISSUE TITLE
Issue with node-red-contrib-home-assistant-websocket “API-CALL-SERVICE”

### ISSUE THREAD

**Issue by andypnz** [zachowj/node-red-contrib-home-assistant-websocket#701]
### Describe the bug

Interesting issue!

Using Home Assistant on a RPi and running Node-red for my automations. Using a ESP8266 running ESPHome to send some serial data. I am using https://esphome.io/components/switch/uart.html so very easy to set up. 

```
uart:
  id: uart_bus
  tx_pin: GPIO1 #D3
  rx_pin: GPIO3 #D4
  baud_rate: 57600
  
switch:
  - platform: uart
    name: "Send_R"
    data: 'R'
  - platform: uart
    name: "Send_6"
    data: '6'
  - platform: uart
    name: "Send_4"
    data: '4' 
```
These switch entities are available in Home Assistant, and work exactly as expected. Turning the 'Send_4' switch on sends '4'. Great so far! So ESPHome is working as expected and Home Assistant is as expected.

The problem is in Node-red:
Within Node-red I am using the 'call service' node to activate the switch.... But when I set the entity in this node to say 'Send_4', the result is activates all three commands (Send_R, Send_6, Send_4).

```
[11:43:45][D][switch:013]: 'Send_R' Turning ON.
[11:43:45][D][switch:037]: 'Send_R': Sending state ON
[11:43:45][D][uart.switch:020]: 'Send_R': Sending data...
[11:43:45][D][switch:037]: 'Send_R': Sending state OFF
[11:43:45][D][switch:013]: 'Send_6' Turning ON.
[11:43:45][D][switch:037]: 'Send_6': Sending state ON
[11:43:45][D][uart.switch:020]: 'Send_6': Sending data...
[11:43:45][D][switch:037]: 'Send_6': Sending state OFF
[11:43:45][D][switch:013]: 'Send_4' Turning ON.
[11:43:45][D][switch:037]: 'Send_4': Sending state ON
[11:43:45][D][uart.switch:020]: 'Send_4': Sending data...
[11:43:45][D][switch:037]: 'Send_4': Sending state OFF
```

Using version 0.46.0 of the contrib-node. 

Is this a bug? Any solution?
Thank you!

### This package's version (not the Home Assistant add-on version)

0.46.0

### Is Node-RED running in Docker?

Home Assistant add-on

### Node-RED version

3.0.2

### Node.js version

?

**Comment by andypnz** [comment]
Seems everything under switch is sent if any individual task under switch is called using this api-service-call

For example, calling any one of these results in all three activating:
```
Switch:
  - platform: uart
    name: "Send_R"
    data: 'R'

  - platform: template
    name: "Switch_Send_6"
    id: switch_send_6
    turn_on_action:
      - uart.write: '6'

  - platform: template
    name: "Switch_Send_4"
    id: switch_send_4
    turn_on_action:
      - uart.write: '4'
```

**Comment by zachowj** [comment]
Do they show up in HA as individual switches? There should be no difference between using the call-service node in NR and clicking on the switch element in the HA UI.

What does your call service node look like? example?

**Comment by andypnz** [comment]
Yep, they are seen as individual switches in HA and work as expected.

This is one call service node in HA. Triggering this single node also triggers the other two switches,.....

`[
    {
        "id": "4d61197ec95d0e5e",
        "type": "api-call-service",
        "z": "813f50a4d073de20",
        "name": "",
        "server": "4b873e8b.9441d",
        "version": 5,
        "debugenabled": false,
        "domain": "switch",
        "service": "turn_on",
        "areaId": [
            "laundry"
        ],
        "deviceId": [
            "b0e4680f5d53e4451753c4272cde8e5f"
        ],
        "entityId": [
            "switch.send_r"
        ],
        "data": "",
        "dataType": "jsonata",
        "mergeContext": "",
        "mustacheAltTags": false,
        "outputProperties": [],
        "queue": "none",
        "x": 315,
        "y": 535,
        "wires": [
            [
                "abe63c7c687147e0",
                "b4a06e38ee683cd0"
            ]
        ]
    },
    {
        "id": "4b873e8b.9441d",
        "type": "server",
        "name": "Home Assistant",
        "version": 5,
        "addon": true,
        "rejectUnauthorizedCerts": true,
        "ha_boolean": "y|yes|true|on|home|open",
        "connectionDelay": true,
        "cacheJson": true,
        "heartbeat": false,
        "heartbeatInterval": 30,
        "areaSelector": "friendlyName",
        "deviceSelector": "friendlyName",
        "entitySelector": "friendlyName",
        "statusSeparator": "at: ",
        "statusYear": "hidden",
        "statusMonth": "short",
        "statusDay": "numeric",
        "statusHourCycle": "h23",
        "statusTimeFormat": "h:m",
        "enableGlobalContextStore": true
    }
]`

**Comment by andypnz** [comment]
I could show you the behaviour using screen sharing if that was of help? We could use the Discord Home Assistant 'hangout' lobby or similar?

**Comment by zachowj** [comment]
You have an area and device selected, so it's going to every switch in the area and on the device on. Remove the area and device and it will work as you expect.

**Comment by andypnz** [comment]
Awesome! I did not realise that :-) Thank you very much!!
