### ISSUE TITLE
Sensor object doesn't re-send its state

### ISSUE THREAD

**Issue by rgutialo** [zachowj/node-red-contrib-home-assistant-websocket#702]
### Describe the bug

I have a sensor that retrieves information from MQTT (a temperature sensor). I have a sensor object in node-red which updates the entity_id sensor value in Home Assistant. In previous versions, I used the output of this sensor to send the temperature to an influxdb database.

With the latest update, I cannot use this approach. Debugging the flow, it says:

`"TypeError: Cannot read properties of undefined (reading 'state')"`
This is the config for the sensor node:

![Captura de pantalla 2022-10-14 a las 14 24 27](https://user-images.githubusercontent.com/27749424/195846218-03d11c0f-6021-4c42-aeb2-945ba8f657db.png)

And this is the output message when debugging it:
`{"topic":"habitacion","qos":0,"retain":false,"_msgid":"6a9252ef6b8bbef4"}`

As you see, no payload is sent.

### To Reproduce

1. Create a sensor object in node red which state is updated through a` msg.payload.whatever` value
2. Config the sensor output as described before.
3. Put a debug object after the sensor one and check therer is no payload in the message.

### Expected behavior

In the output message sent by the sensor node, a payload object is filled with the information set up in the sensor node.

### This package's version (not the Home Assistant add-on version)

0.46.0

### Is Node-RED running in Docker?

Yes

### Node-RED version

3.0.2

### Node.js version

16.16.0

**Comment by zachowj** [comment]
Does it work without an error if you remove `msg.payload` from output properties?

**Comment by zachowj** [comment]
Also in the debug window does the error point to the sensor node or the entity config?

![image](https://user-images.githubusercontent.com/37859597/195925774-617936e2-6f5e-4122-97b8-fb71be11b629.png)
