### ISSUE TITLE
Value in "For" in a "Event: state" node prevents it from responding

### ISSUE THREAD

**Issue by WallyDW** [zachowj/node-red-contrib-home-assistant-websocket#703]
### Describe the bug

Event: state node stops reacting to changes if a value is set in the "For" field

### To Reproduce

Create an "Event: state" node and set the "For" value to something like 5 seconds.
Make it react to an entity in HA (I had it set to react to a climate entity in HA, where the state stayed the same, but the temperature attribute changed)
Make a change to the entity and see that no change occurred.
Change the "For" value to 0 and make a new change to see that it will now react to the change.

### Expected behavior

The node should react to the state change after the time in the "For" field have expired.

### This package's version (not the Home Assistant add-on version)

0.45.8 + 0.46.0

### Is Node-RED running in Docker?

Home Assistant add-on

### Node-RED version

3.0.2

### Node.js version

No idea

**Comment by zachowj** [comment]
and you have the if state empty?

**Comment by WallyDW** [comment]
I have tried with both the "if state" set to "is" and with a string set to empty and also with the "if state" set to "is not" and with a string set to test, which it will never be. Neither works with a value in the "for" field, but without a value it works.
"Current state equals previous state" can be checked and unchecked and the result without a value in the "for" field is again a no response, while without a value it behaves as expected.

**Comment by WallyDW** [comment]
I just made another flow and here I used a "Event: state" node too, but this one has "State type" set to Number and the state is the one changing here.
This one actually works with the "for" field set to a value.

The one that is bugged have "State type" set to string and only the attribute change, not the state.

**Comment by WallyDW** [comment]
Here are the two nodes:
`[{"id":"9a965190bc93f5a5","type":"server-state-changed","z":"be03f9025a1f137a","name":"Set thermometer by slider (work)","server":"541ade28.b4a62","version":4,"exposeToHomeAssistant":false,"haConfig":[{"property":"name","value":""},{"property":"icon","value":""}],"entityidfilter":"input_number.office_set_temperature","entityidfiltertype":"exact","outputinitially":false,"state_type":"num","haltifstate":"","halt_if_type":"str","halt_if_compare":"is","outputs":1,"output_only_on_state_change":true,"for":"3","forType":"num","forUnits":"seconds","ignorePrevStateNull":false,"ignorePrevStateUnknown":false,"ignorePrevStateUnavailable":false,"ignoreCurrentStateUnknown":false,"ignoreCurrentStateUnavailable":false,"outputProperties":[{"property":"payload","propertyType":"msg","value":"","valueType":"entityState"},{"property":"data","propertyType":"msg","value":"","valueType":"eventData"},{"property":"topic","propertyType":"msg","value":"","valueType":"triggerId"}],"x":150,"y":750,"wires":[[]]},{"id":"b82c71e33d84afbc","type":"server-state-changed","z":"be03f9025a1f137a","name":"React to thermometer changes (fails)","server":"541ade28.b4a62","version":4,"exposeToHomeAssistant":false,"haConfig":[{"property":"name","value":""},{"property":"icon","value":""}],"entityidfilter":"climate.officethermometer","entityidfiltertype":"exact","outputinitially":false,"state_type":"str","haltifstate":"","halt_if_type":"str","halt_if_compare":"is","outputs":1,"output_only_on_state_change":false,"for":"3","forType":"num","forUnits":"seconds","ignorePrevStateNull":false,"ignorePrevStateUnknown":false,"ignorePrevStateUnavailable":false,"ignoreCurrentStateUnknown":false,"ignoreCurrentStateUnavailable":false,"outputProperties":[{"property":"payload","propertyType":"msg","value":"","valueType":"triggerId"}],"x":160,"y":675,"wires":[[]]},{"id":"541ade28.b4a62","type":"server","name":"Home Assistant","version":5,"addon":true,"rejectUnauthorizedCerts":true,"ha_boolean":"","connectionDelay":false,"cacheJson":false,"heartbeat":false,"heartbeatInterval":"","areaSelector":"friendlyName","deviceSelector":"friendlyName","entitySelector":"friendlyName","statusSeparator":"at: ","statusYear":"hidden","statusMonth":"short","statusDay":"numeric","statusHourCycle":"h23","statusTimeFormat":"h:m","enableGlobalContextStore":true}]
`

**Comment by zachowj** [comment]
This is functioning as intended. The "For" check will only trigger once until the entity's state changes. It does not consider any changes to the attributes of the entity.

There is a bug here, when the state type is set to a number and the state of the entity can't be parsed into a valid number it returns `NaN` and in javascript `NaN` does not equal `NaN` when doing a comparison. That is why you see it start to wait for the "For" time in your example.

**Comment by WallyDW** [comment]
Well, I could not really accept the answer since it has worked before and since I wanted to redo the entire flow, then I deleted it and started over.
Now it works as before.
The "For" field works with the state field set to a string and an attribute change will trigger it.
There is no countdown though, but it is delayed and it is sending the message on.
