### ISSUE TITLE
Duplicate output after update

### ISSUE THREAD

**Issue by jeanniquini** [zachowj/node-red-contrib-home-assistant-websocket#71]
**Describe the bug**
Duplicate output after upgrading to v0.5.1. 
If I open any "current state" node the output is then duplicated.

**Screenshots**

![image](https://user-images.githubusercontent.com/43561057/50690406-4dabb600-1014-11e9-84b3-d1ab2bd791ed.png)

**Example Flow**
`[{"id":"2e6bb5d8.39a85a","type":"api-current-state","z":"30559228.a0d01e","name":"Note","server":"a1153b55.2eb9d8","halt_if":"off","halt_if_type":"","halt_if_compare":"is","override_topic":true,"override_payload":true,"override_data":true,"entity_id":"switch.note","state_type":"str","outputs":2,"x":330,"y":1560,"wires":[["ea54e7bf.87d148"],[]]},{"id":"a1153b55.2eb9d8","type":"server","z":"","name":"Home Assistant","legacy":false,"hassio":false,"rejectUnauthorizedCerts":true,"ha_boolean":"y|yes|true|on|home|open"}]`

**Environment**

- Node Red Version: 0.19.5
- NR Home Assistant Plugin Version: 0.5.1
- Is Node Red running in Docker: no

**Other:**

- Have you searched previous issues for duplicates?: yes

**Comment by zachowj** [comment]
It was a new feature added in v0.50.0. It's in the changelog, `Added secondary outputs for halt if logic for current-state, events-state, and poll-state nodes`.

When using the `halt if` logic for current-state, events-state, and poll-state nodes a second output will be available which will receive the `message` when the `halt if` is true. This new feature allows sometimes not having to use a switch statement directly after one of the above nodes and there's also other use cases for it.
