### ISSUE TITLE
Entity modules not loading integration

### ISSUE THREAD

**Issue by barefooter22** [zachowj/node-red-contrib-home-assistant-websocket#715]
### Describe the bug

When trying to use the Home Assistant entity modules, I get the following error:

Attention: This node requires [Node-RED custom integration version 1.1.0+ ](https://github.com/zachowj/hass-node-red) to be installed in Home Assistant for it to function.

It doesn't seem to be recognizing my HACS plugin.  This is not an issue with the other nodes such as the "Call Service" nodes.  Only the Home Assistant "entity" nodes such as binary sensor, button, sensor, switch, and update config.  All of these options fail while the other Home Assistant modules work fine.
![enity_module_fails_to_load](https://user-images.githubusercontent.com/12722473/196837532-280d9fdd-094a-42df-bf11-eaaafe088531.PNG)

### To Reproduce

1. Go to "home assistant entities" section and drag in one of the options
2. Go to Edit
3. Edit the entity config section
4. Click the pen
5. Fill in the Friendly Name and other sections
6. Click "Add"
7. Note error

### Expected behavior

This should connect to my HACs integration like the other modules such as the "Call Service" nodes.

### This package's version (not the Home Assistant add-on version)

0.46.0

### Is Node-RED running in Docker?

Yes

### Node-RED version

3.0.2

### Node.js version

v16.16.0

**Comment by zachowj** [comment]
Did you complete step 5? <https://github.com/zachowj/hass-node-red#hacs>

**Comment by barefooter22** [comment]
Hi @zachowj , You're talking about installing it via HACS right?  Yes I have it installed in HACS.

![image](https://user-images.githubusercontent.com/12722473/197306604-d58e926f-78e6-42f9-ba10-f5a526d59ed8.png)

**Comment by barefooter22** [comment]
What's interesting is that this issue only affects those 4 nodered modules.  My nodered has no issues with updating entities via "Call Service"

**Comment by zachowj** [comment]
> What's interesting is that this issue only affects those 4 nodered modules. My nodered has no issues with updating entities via "Call Service"

That's expected the integration is only required for some nodes to be fully functional.



> You're talking about installing it via HACS right?

No, after you have added the integration you have to enable it in Home Assistant. Follow the steps in step 5.

1. In the Home Assistant UI go to "Configuration"
2. "Integrations" click "+" 
3. search for "Node-RED"

**Comment by barefooter22** [comment]
Thanks @zachowj!  I enabled that and it looks like I don't get that particular error anymore.  Thanks for the help!
