### ISSUE TITLE
After updating node-red-contrib-home-assistant-websocket error

### ISSUE THREAD

**Issue by klio-klio** [zachowj/node-red-contrib-home-assistant-websocket#718]
### Describe the bug

After updating node-red-contrib-home-assistant-websocket my programming almost unusable. I would have to restore backup. What can I do?

### Screenshots

![image](https://user-images.githubusercontent.com/76972213/197039524-d085bdc3-6ea6-4d0f-9cfe-e73c358f7752.png)

### This package's version (not the Home Assistant add-on version)

0,46

### Is Node-RED running in Docker?

Yes

### Node-RED version

13,4

### Node.js version

14,7

**Comment by klio-klio** [comment]
![image](https://user-images.githubusercontent.com/76972213/197045225-1bf47197-3c27-4440-9bd6-59e890f17a20.png)

**Comment by zachowj** [comment]
What version of node-red are you running? The current version is 3.0.2 so not sure where you're getting 13.4.

**Comment by klio-klio** [comment]
where can i see it?

**Comment by zachowj** [comment]
![image](https://user-images.githubusercontent.com/37859597/197118960-0670a359-2ec1-46fc-bba7-5a226f39ce41.png)

**Comment by klio-klio** [comment]
V3. 0.2

**Comment by zachowj** [comment]
If you open a node with an error, is a server selected? After opening an error node and deploying does the error go away?

**Comment by klio-klio** [comment]
now I have seen this message. The server is actually selected... What do I have to do?
![error](https://user-images.githubusercontent.com/76972213/197460078-ef16e862-5d32-4ebe-bd0a-31d6c757ccac.jpg)

**Comment by klio-klio** [comment]
all found. Thanks for the support

**Comment by stcbus** [comment]
I am having this same error. @klio-klio  what did you end up doing to fix this? it's not great to close without commenting what fixed it.

**Comment by dangel666** [comment]
I am also having what is likely the same problem - I'm running HA with Node Red and some time ago I noticed that HA upgrades work fine but I'm unable to go beyond the NR addon release of 3.0.2 without the same thing happening to my HA nodes - deconz nodes carry on working.   Rolling back NR doesn't fix this - instead I have to restore a complete HA backup before things start working again. It's quite odd!

I've not had time to look at this till today so stuck with 3.0.2 till now.  I tried opening a broken node and checked the server selected - i have four "Home Assistant" servers(!).  The one selected didn't work so I'd tried the second one in the list.  Deploy.  Node appears to work...  In this case a fridge open/close sensor.   However, the next node in the same flow - a notify node which calls alexa_media didn't respond to me changing it the same way and still shows error..

If I look at my config on all flows I can see I indeed have four "Home Assistant" 'servers' - with 111 nodes using the first - which is solid boxed.  The following three have no nodes using them and are dashed.
![image](https://user-images.githubusercontent.com/44338896/210583405-21522166-f32a-4d54-ae30-c882f7412b2a.png)

As yet I don't quite know what to do other than keep hunting..

**Comment by dangel666** [comment]
So let's try disabling the 'wrong' servers:

4 Jan 15:05:07 - [info] Started flows
4 Jan 15:05:07 - [info] [deconz-server:Deconz Server] WebSocket opened
4 Jan 15:05:11 - [info] [server:fabd9cf1.19d2e] Connecting to http://supervisor/core
4 Jan 15:05:11 - [info] [server:fabd9cf1.19d2e] Connected to http://supervisor/core

Looks more straightforward.  And every still works with 3.0.2 at this point.

**Comment by klio-klio** [comment]
with me the server was not selected. After selecting once and deploy everything worked.
