### ISSUE TITLE
Make merging optional in Service Call node

### ISSUE THREAD

**Issue by chimpy** [zachowj/node-red-contrib-home-assistant-websocket#72]
Hello!

**Is your feature request related to a problem? Please describe.**
I feel frustrated when I want to chain Service Call nodes together and have to place a Change node (Delete: msg.payload) between them because what I assume is the merge resolution.

**Describe the solution you'd like**
This may be simply be because I rarely use merging in the Service Call node, but I'd love to have a tickbox where we could make this optional. It would save me copy/pasting a load of Change nodes!

**Describe alternatives you've considered**
Inserting a Change node to delete the msg.payload after each Service Call node.

**Additional context**
None.

Thanks, I love this project :)

**Comment by zachowj** [comment]
This is already available via the `Output Location` in the `call-service` node. Setting it to `None` still sends the message through but not the payload or you can set the location to something other than payload.

![chrome_2019-01-04_17-57-40](https://user-images.githubusercontent.com/37859597/50718971-6f279480-104a-11e9-822a-8d9c40c65d9b.png)

**Comment by chimpy** [comment]
Ah I wasn't aware there were so many updates. Thanks for being so active :)

**Comment by chimpy** [comment]
Hey @zachowj , sorry to bother you.
After upgrading to 0.5.0 I have "Error calling service, home assistant api error" on all of my service call nodes.
The service is called but I don't know why I have this error. The NR debug gives no more details, nor the log.
I have already refreshed my LLAT to no avail.

**Comment by zachowj** [comment]
I need to add it to the README but make sure you're using node v0.19+

**Comment by chimpy** [comment]
@zachowj @ehendrix23 Everything is working perfectly, thanks so much.
