### ISSUE TITLE
action not working

### ISSUE THREAD

**Issue by felixkang** [zachowj/node-red-contrib-home-assistant-websocket#724]
### Describe the bug

![image](https://user-images.githubusercontent.com/18622299/198677021-35a5d6cc-048e-4992-88d7-234ba46e7859.png)
Unable to control the device properly

### This package's version (not the Home Assistant add-on version)

13.5.0 

### Is Node-RED running in Docker?

Home Assistant add-on

### Node-RED version

unknown

### Node.js version

unknown

**Comment by zachowj** [comment]
You need to update the custom component.

**Comment by felixkang** [comment]
thanks
