### ISSUE TITLE
An attribute cannot be an array

### ISSUE THREAD

**Issue by hmorkemo** [zachowj/node-red-contrib-home-assistant-websocket#725]
### Describe the bug

After upgrading to NR 13.5, I get a lot of errors like this:
“ValidationError: “attributes.entities” must be one of [string, number, boolean, object]” when I try to update a ha node. 
The attributes.entitites is (in this case) an array of strings ([“A”, “B”]). This worked very well in 13.4. 
Entitites is defined as a J: expression. If I set entites = {a: 1, b: 2} it seems to work. If I set it to {a: ["A", "B"]}, it works too. This is a possible workaround for some cases, but not for all.
I have tried reloading the integration, restarting HA and NR. No change.

### Expected behavior

I expected it to work as it did before. Setting a J: expression to an array should work.

### This package's version (not the Home Assistant add-on version)

0.46.1

### Is Node-RED running in Docker?

Home Assistant add-on

### Node-RED version

3.0.2

### Node.js version

I don't know where to find it...

**Comment by zachowj** [comment]
Do you have an example flow you can post?

**Comment by hmorkemo** [comment]
[{"id":"27b881646e789477","type":"inject","z":"7ecbb3ca.5c3afc","name":"","props":[],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","x":910,"y":1110,"wires":[["8542ceb304e00dd3"]]},{"id":"8542ceb304e00dd3","type":"function","z":"7ecbb3ca.5c3afc","name":"","func":"// The first one is ok. The second one fails.\n// return { payload: { state: 42, attributes: { entities: { a: 1, b: 2 } } } };\nreturn { payload: {state: 42, attributes: {entities: [1,2]} }};","outputs":1,"noerr":0,"initialize":"","finalize":"","libs":[],"x":1070,"y":1110,"wires":[["2a8710c5c428ea98","b1dac07fc718ddc4"]]},{"id":"2a8710c5c428ea98","type":"ha-sensor","z":"7ecbb3ca.5c3afc","name":"sensor1","entityConfig":"983e68f1f2f62bb2","version":0,"state":"state","stateType":"msg","attributes":[{"property":"entities","value":"","valueType":"jsonata"}],"inputOverride":"allow","outputProperties":[],"x":1240,"y":1110,"wires":[[]]},{"id":"b1dac07fc718ddc4","type":"debug","z":"7ecbb3ca.5c3afc","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":1230,"y":1150,"wires":[]},{"id":"983e68f1f2f62bb2","type":"ha-entity-config","server":"114a65ff.5cd15a","deviceConfig":"","name":"sensor1","version":"6","entityType":"sensor","haConfig":[{"property":"name","value":"Sensor 1"},{"property":"icon","value":""},{"property":"entity_category","value":""},{"property":"device_class","value":""},{"property":"unit_of_measurement","value":""},{"property":"state_class","value":""}],"resend":false},{"id":"114a65ff.5cd15a","type":"server","name":"Home Assistant","version":5,"addon":true,"rejectUnauthorizedCerts":true,"ha_boolean":"y|yes|true|on|home|open","connectionDelay":true,"cacheJson":true,"heartbeat":false,"heartbeatInterval":"30","areaSelector":"friendlyName","deviceSelector":"friendlyName","entitySelector":"friendlyName","statusSeparator":"at: ","statusYear":"hidden","statusMonth":"short","statusDay":"numeric","statusHourCycle":"h23","statusTimeFormat":"h:m","enableGlobalContextStore":true}]

**Comment by hmorkemo** [comment]
Great!
