### ISSUE TITLE
events: state outputs even when state does not change

### ISSUE THREAD

**Issue by steve28** [zachowj/node-red-contrib-home-assistant-websocket#73]
**Describe the bug**
The "Events: state" node description says it outputs state-changed events from Home Assistant.  However, it outputs events even when the state did not change.  I have a z-wave power plug that when it's turned on or off, i get two events output from the node. The first appears to be when the state actually changes from "on" to "off" or vice versa.  The second, I believe, is a power report being sent from the plug.  This seems to trigger a state changed event, but the state does not, in fact, change.

For example, turning plug from off to on.  Two messages emerge from the node immediately:
 - the first message has state: "on",  old_state: "off" and new_state: "on" (expected)
 - the second message two has state: "on", old_state: "on" and new_state: "on" (not expected)

Message 1 (left) and Message 2 (right)
<img width="330" alt="screen shot 2019-01-04 at 11 39 09 am" src="https://user-images.githubusercontent.com/5874433/50707374-7f714c80-1015-11e9-88d4-a1ce480c6ad8.png"><img width="330" alt="screen shot 2019-01-04 at 11 39 18 am" src="https://user-images.githubusercontent.com/5874433/50707390-85672d80-1015-11e9-801f-cf7d36f018e1.png">

**To Reproduce**

1. Find a device that outputs messages that do not change the state - my use is a z-wave power plug that sends power reports.
2. Put a debug node the "events: state" node for the device in 1)
3. watch messages emerge from the node where the state does not change

**Expected behavior**
The node should not output the second message because the "state" did not change.  Perhaps the node needs to compare msg.data.old_state.state and msg.data.new_state.state to make sure there is actually a state change.

**Screenshots**

**Example Flow**
![image](https://user-images.githubusercontent.com/5874433/50707952-826d3c80-1017-11e9-8efd-341f7931ce6b.png)

**Environment (please complete the following information):**

- Node Red Version:0.19.5
- NR Home Assistant Plugin Version: 0.5.1
- Is Node Red running in Docker: yes

**Other (please complete the following information):**

- Have you searched previous issues for duplicates?: yes

**Comment by zachowj** [comment]
It triggers on what Home Assistant considers a `state_change` event which as you have seen means when anything within the entity changes. For your use case, a `trigger-state` with the state check or a Report by Exception node is what you'd want to use.

**Comment by chimpy** [comment]
Just to maybe clarify: the "state" is not just made up of the payload (on/off), but the entirety of the object's attributes. So if your lamp has an attribute "brightness", changing that will change the state, even though the lamp is on before and after this state change.

**Comment by steve28** [comment]
I understand, but it's confusing because the state object has an attribute called "state" and I would claim that _most_ people would expect a "state changed" node to (at least by default) only output events when the attribute "state" changes (i.e., on/off, home/not_home, open/closed).

For example, there could be a preference to have the node only output when `from_state.state` and `to_state.state` are different.  I know I can do this with additional nodes, but again, I would argue that _most times_ this node would be used for actual state attribute changes.

**Comment by zachowj** [comment]
> For example, there could be a preference to have the node only output when `from_state.state` and `to_state.state` are different. I know I can do this with additional nodes, but again, I would argue that _most times_ this node would be used for actual state attribute changes.

I would agree that this is a valid feature request.
