### ISSUE TITLE
Brightness is off by one

### ISSUE THREAD

**Issue by tamueller** [zachowj/node-red-contrib-home-assistant-websocket#732]
### Describe the bug

I'm using homeassistant, zigbee2MQTT and NodeRed and when using the node from this contrib, I get wrong brightness values.

When I use a node to set the Brightness to "200" for a lamp, the lamp goes to Brightness 199, also the zigbee2MQTT logs show me a payload of 199. 
When I use the z2m contrib in NodeRed directly, and set the Brightness to 200, it actually goes to 200, so it seems like it's not a NR, HA or Z2M issue, but related directly to this node. This happens all the time for me, and for most values around 200. When using Brightness 100 it works as expected.
I guess there might be some rounding issues involved.

### To Reproduce

Set the Brightness of a Lamp to 200 

### Expected behavior

Lamp goes to 200

### Example Flow

```json
[{"id":"a6e5972f14712daf","type":"api-call-service","z":"8a137cb3e70a8c7d","name":"Deckenlicht An","server":"","version":5,"debugenabled":false,"domain":"light","service":"turn_on","areaId":[],"deviceId":["c7224d281f38f738c4bb248956032d50"],"entityId":[],"data":"{\"brightness\":200}","dataType":"json","mergeContext":"","mustacheAltTags":false,"outputProperties":[],"queue":"none","x":1080,"y":500,"wires":[[]]},{"id":"f5134e731c295233","type":"inject","z":"8a137cb3e70a8c7d","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":920,"y":500,"wires":[["a6e5972f14712daf"]]}]
```

### This package's version (not the Home Assistant add-on version)

0.46.2

### Is Node-RED running in Docker?

Home Assistant add-on

### Node-RED version

13.5.1

### Node.js version

don't know

**Comment by zachowj** [comment]
This package doesn't modify any values passed to HA. Try the same call using the developer tools in HA and you should see the same results.

**Comment by tamueller** [comment]
No, when using the dev tools in HA the problem does not occour. It also does not occour if I use zigbee2Mqtt directly, or when I use the Z2M package in NodeRed - it only happens when using this package.
If you want, I can provide additional logs, screenshots or a video.

**Comment by S-E-B-123** [comment]
Can't confirm this. I used your code snipped and replaced only the device to one of my IKEA Zigbee's and the brightness was set to 200 as expected.
