### ISSUE TITLE
Water device class is missing when creating a sensor

### ISSUE THREAD

**Issue by gszigethy** [zachowj/node-red-contrib-home-assistant-websocket#733]
### Describe the bug

In HA release 2022.11 water usage has been introduced. When I create a sensor in node red, th device_class water is missing from the dropdown list.

### To Reproduce

1. Go to node red.
2. Create a new sensor.
3. In the Entity config create a new entity.
4. Pick type: sensor.
5. In device class dropdown water device class is missing.

### Expected behavior

1. Go to node red.
2. Create a new sensor.
3. In the Entity config create a new entity.
4. Pick type: sensor.
5. In device class dropdown water device class should be available. All device classes listed in the next link should be visible: https://www.home-assistant.io/integrations/sensor/

### Screenshots

![image](https://user-images.githubusercontent.com/46370269/199688920-2b08ec6f-7702-4a6c-8c07-2545e9ebaa30.png)

### This package's version (not the Home Assistant add-on version)

0.46.2

### Is Node-RED running in Docker?

Home Assistant add-on

### Node-RED version

Node red add-on v13.5.1

### Node.js version

Node red add-on v13.5.1

**Comment by schejbity** [comment]
Hi,
how do I force the Node-RED addon on HA to load this modification?

Thx.

**Comment by zachowj** [comment]
You would need to use [npm_packages](https://github.com/hassio-addons/addon-node-red/blob/main/node-red/DOCS.md#option-npm_packages) in the add-on config.

`node-red-contrib-home-assistant-weboscket@next`

or the exact tag

`node-red-contrib-home-assistant-weboscket@0.46.2-dev.4e8514c32`
