### ISSUE TITLE
Race condition on state_changed nodes and the global homeAssistant.states object

### ISSUE THREAD

**Issue by andreassolberg** [zachowj/node-red-contrib-home-assistant-websocket#74]
**Describe the bug**

When an `state_changed` node triggers a change for an `input_boolean`, there is a race condition with the `global.get('homeassistant').homeAssistant.states` object being updated.

When the state change is triggered, the payload is correct, but the states object is not updated.

I doubt this is specific for `input_booleans`, but that is the only one I've verified the problem.

**To Reproduce**

Here is a typical function node I am using:

```js
let ha = global.get('homeassistant').homeAssistant
let s = function(v) {
    return ha.states[v].state
}

if (s('input_select.mode') === 'Away') {

    msg.payload = 'scene.0etg_away'

} else if ( s('input_select.mode') === 'Night') {
    
    msg.payload = 'scene.0etg_off'

} else if ( s('input_boolean.floor0') === 'off') {
    
    msg.payload = 'scene.0etg_off'

} else if ( s('input_select.sceneoverride') === 'Flood') {
    
    msg.payload = 'scene.0etg_flood'

} else if ( s('input_boolean.active_kjellerstua') === 'on') {
    
    msg.payload = 'scene.0etg_dim'

} else if ( s('input_select.timeperiod') === 'earlyMorning') {
    
    msg.payload = 'scene.0etg_dim'

} else if ( s('input_select.timeperiod') === 'morning') {
    
    msg.payload = 'scene.0etg_normal'

} else if ( s('input_select.timeperiod') === 'day') {
    
    msg.payload = 'scene.0etg_normal'

} else if ( s('input_select.timeperiod') === 'leggeTid') {
    
    msg.payload = 'scene.0etg_soft'

} else if ( s('input_select.timeperiod') === 'evening') {
    
    msg.payload = 'scene.0etg_dim'

} else if ( s('input_select.timeperiod') === 'lateEvening') {
    
    msg.payload = 'scene.0etg_dim'

} else {
    
    msg.payload = 'scene.0etg_normal'
    
}

return msg
```

A changed `input_boolean.floor0` will cause the function node above to be executed, but it will be based upon the old value.

As a result, my outdoor lights turn off in the evening, and the lights in my bathroom turns off when I enter. The background music on the bathroom becomes louder when I open the door, and quiter when I close the door. The lights above the TV dims down when I pause a movie, and floods the room when I hit play.

**Environment (please complete the following information):**

I'm pretty sure the problem was introduced at the same time I updated to version `0.5.1`. The problem was not present in `0.5.0`.

- I've installed Node red using hass.io, the hass.io addon version `1.2.3`.
- Node Red Version: `0.19.5`

**Comment by zachowj** [comment]
Until I can get a fix pushed a quick fix might be to switch your state_change node from exact to substring. This is untested but I think it might work from my quick scan of the code

**Comment by andreassolberg** [comment]
I can confirm that with substring the bug does not occur!

**Comment by andreassolberg** [comment]
Thanks for accepting the bug! I really appreciate *node-red-contrib-home-assistant-websocket* btw.
