### ISSUE TITLE
Nod red crash 

### ISSUE THREAD

**Issue by kimstor1435** [zachowj/node-red-contrib-home-assistant-websocket#757]
### Describe the bug

My Node Red crash when it loose connection to HA, If I run a update on HA it will make NR crash due to lost connection.
Node Red running in Docker outside of HA.

### Screenshots

<img width="1196" alt="Skjermbilde 2022-11-17 kl  23 35 39" src="https://user-images.githubusercontent.com/61433087/202574750-d74d0a3a-c397-4b7c-9006-58f3497e8c57.png">

### This package's version (not the Home Assistant add-on version)

0.47.0

### Is Node-RED running in Docker?

Yes

### Node-RED version

3.0.2

### Node.js version

?

**Comment by GNewlon** [comment]
No fix for this, we are all getting node-red crashes. I set up a script to start node-red, cron: every minute. Good enough!

**Comment by marc-gist** [comment]
> No fix for this, we are all getting node-red crashes. I set up a script to start node-red, cron: every minute. Good enough!

If you have NodeRed in docker, just set restart-always.

The nodered companion integration can also cause the crash  of NodeRed :(

**Comment by nnkn** [comment]
![Snipaste_2023-01-23_11-01-19](https://user-images.githubusercontent.com/22342244/213959076-00bf4d47-8711-4f36-abe1-7921f0453a9b.png)
Exactly the same as you , ver 0.48.0
I run node red in docker and it will auto restart , but it affects the other flows, so I don't like  restart, anything I can do to avoid it ?
