### ISSUE TITLE
Missing domain "number" in call service

### ISSUE THREAD

**Issue by PetrS98** [zachowj/node-red-contrib-home-assistant-websocket#759]
### Describe the bug

Missing domain "number" in call service

### Screenshots

![image](https://user-images.githubusercontent.com/83243816/202876789-6eb79f00-b9b1-4ec9-9a52-0df829c264ef.png)

### This package's version (not the Home Assistant add-on version)

0.47.0

### Is Node-RED running in Docker?

No

### Node-RED version

13.5.3

### Node.js version

0.0.0

**Comment by zachowj** [comment]
if you restart NR without restart HA does it appear?

**Comment by PetrS98** [comment]
no, it won't appear

**Comment by zachowj** [comment]
Does it show in the HA developer tools > services?

Does this flow output a value?

```
[{"id":"e5abb36749461868","type":"ha-api","z":"d586b2ad49c330b9","name":"","server":"","version":1,"debugenabled":false,"protocol":"websocket","method":"get","path":"","data":"{\"type\": \"get_services\"}","dataType":"jsonata","responseType":"json","outputProperties":[{"property":"payload","propertyType":"msg","value":"","valueType":"results"}],"x":286,"y":784,"wires":[["1e69dbf1a7920f92"]]},{"id":"80fc606e8284248c","type":"inject","z":"d586b2ad49c330b9","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":132,"y":784,"wires":[["e5abb36749461868"]]},{"id":"86ce2c13a85a3ec3","type":"debug","z":"d586b2ad49c330b9","name":"exists?","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"payload","targetType":"msg","statusVal":"","statusType":"auto","x":596,"y":784,"wires":[]},{"id":"1e69dbf1a7920f92","type":"change","z":"d586b2ad49c330b9","name":"","rules":[{"t":"set","p":"payload","pt":"msg","to":"payload.number","tot":"msg"}],"action":"","property":"","from":"","to":"","reg":false,"x":432,"y":784,"wires":[["86ce2c13a85a3ec3"]]}]
```

**Comment by PetrS98** [comment]
_Does it show in the HA developer tools > services?_

no it is missing

_Does this flow output a value?_

![image](https://user-images.githubusercontent.com/83243816/202892953-baa99332-7fb3-4524-a891-96f9d73df90b.png)

**Comment by zachowj** [comment]
The number component isn't loaded on the HA side. NR only uses what's available in HA.

**Comment by PetrS98** [comment]
Ok, thank you for your help.
