### ISSUE TITLE
Change of behaviour of switch entity

### ISSUE THREAD

**Issue by dgthomson** [zachowj/node-red-contrib-home-assistant-websocket#769]
### Describe the bug

Sending

``
msg.enable = true
``

to a switch entity input previously changed the switch state without outputting any payload.

Newer versions will output a payload like:

``
{
_msgid: "5a8780608b0d28df",
enable: "false",
outputType: "input"
}
``

The documentation of the node still says

> msg.enable [boolean]
> Set to true to turn on the switch and false to turn it off. If the message has a property enable defined and set to a boolean the node will not have any output.

Which behaviour is correct?

### Expected behavior

Sending...

``
msg.enable = true
``

...does not give an output payload per the documentation.

### This package's version (not the Home Assistant add-on version)

0.47

### Is Node-RED running in Docker?

Yes

### Node-RED version

3.0.2

### Node.js version

0

**Comment by zachowj** [comment]
The documentation is correct behavior. What version of the custom component are you running? It works as documented for me on the latest version. 

> msg.enable = true

You show you're setting enable to `true` as a boolean and you get the output. I can reproduce this when I sent `enable` to `true` as a string not a boolean. Are you sure you're passing `enable` as a boolean?

**Comment by dgthomson** [comment]
<facepalm>

Really sorry for wasting your time, my bad.
