### ISSUE TITLE
Node Red flows stopped working after upgrade to HA 0.85.1

### ISSUE THREAD

**Issue by dkruyt** [zachowj/node-red-contrib-home-assistant-websocket#77]
**Describe the bug**

When upgrading to the latest HA version node-red HA flows stopped working. After downgrading again it is working again.

**To Reproduce**

Upgrade HA from 0.83.2 to 0.85.1

**Logs**

Some loggin errors I get with new HA.

Jan 13 19:56:53 node-red Node-RED[31874]: (node:31874) UnhandledPromiseRejectionWarning: #<Object>
Jan 13 19:56:53 node-red Node-RED[31874]: (node:31874) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 31)
Jan 13 19:56:53 node-red Node-RED[31874]: (node:31874) UnhandledPromiseRejectionWarning: #<Object>
Jan 13 19:56:53 node-red Node-RED[31874]: (node:31874) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 32)
Jan 13 19:56:53 node-red Node-RED[31874]: (node:31874) UnhandledPromiseRejectionWarning: #<Object>
Jan 13 19:56:53 node-red Node-RED[31874]: (node:31874) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 33)
Jan 13 19:56:58 node-red Node-RED[31874]: (node:31874) UnhandledPromiseRejectionWarning: #<Object>
Jan 13 19:56:58 node-red Node-RED[31874]: (node:31874) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 34)
Jan 13 19:56:58 node-red Node-RED[31874]: (node:31874) UnhandledPromiseRejectionWarning: #<Object>
Jan 13 19:56:58 node-red Node-RED[31874]: (node:31874) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 35)
Jan 13 19:56:58 node-red Node-RED[31874]: (node:31874) UnhandledPromiseRejectionWarning: #<Object>
Jan 13 19:56:58 node-red Node-RED[31874]: (node:31874) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 36)

**Environment**

- Node Red Version: 0.19.5
- NR Home Assistant Plugin Version: 0.5.1
- Is Node Red running in Docker: Sort of LXD Container

**Comment by zachowj** [comment]
What version of nodejs are you running?

**Comment by zachowj** [comment]
What is the state of the connection to HA when you see these errors? Are they only appearing when connecting to HA or are they always there?

**Comment by dkruyt** [comment]
Node.js  version: v8.10.0

It says it's connected to HA, but nothing is working after that. And I see those errors. They are not there in the older version of HA.

**Comment by dkruyt** [comment]
Jan 14 09:41:02 node-red Node-RED[34644]: 14 Jan 10:41:02 - [info] Node-RED version: v0.19.5
Jan 14 09:41:02 node-red Node-RED[34644]: 14 Jan 10:41:02 - [info] Node.js  version: v8.15.0

With the new node.js version still have the same issues. Downgrading HA resolves the issue.

an 14 09:44:26 node-red Node-RED[34644]: (node:34644) UnhandledPromiseRejectionWarning: #<Object>
Jan 14 09:44:26 node-red Node-RED[34644]: (node:34644) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
Jan 14 09:44:26 node-red Node-RED[34644]: (node:34644) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by zachowj** [comment]
are you using a legacy password and not long-lived access tokens?

**Comment by dkruyt** [comment]
Yes :( , changed it to tokens  Now it's working again. :)

Thanks 👍
