### ISSUE TITLE
Crash with invalid HA credentials

### ISSUE THREAD

**Issue by drencken** [zachowj/node-red-contrib-home-assistant-websocket#770]
### Describe the bug

When entering a token that is invalid for HA, node-red crashes and also can't be restarted.  This makes it basically impossible to fix the authentication issue in Node-red itself.

### To Reproduce

1. Enter a HA mode with an invalid token and deploy.
2. Observe that Node-Red disconnects from the browser because it crashes.
3. Attempt to restart Node-Red manually from the command line.
4. Observe that it crashes and won't start.

### Expected behavior

An error message in Node-Red itself with an option to change the token as needed.

### Screenshots

node-red output before the crash (IP address is redacted)

_22 Nov 20:50:05 - [info] Starting flows
22 Nov 20:50:05 - [error] [poll-state:ef818ac7e5350794] Error: Entity Id is required
22 Nov 20:50:05 - [info] Started flows
22 Nov 20:50:05 - [info] [server:Home Assistant] Connecting to http://192.168.x.x:8123
22 Nov 20:50:05 - [red] Uncaught Exception:
22 Nov 20:50:05 - [error] Error: Invalid access token for websocket
    at /root/.node-red/node_modules/node-red-contrib-home-assistant-websocket/dist/homeAssistant/Websocket.js:112:29
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Websocket.connect (/root/.node-red/node_modules/node-red-contrib-home-assistant-websocket/dist/homeAssistant/Websocket.js:82:23)_

### This package's version (not the Home Assistant add-on version)

0.47.0

### Is Node-RED running in Docker?

No

### Node-RED version

3.0.2

### Node.js version

18.12.1

**Comment by drencken** [comment]
I tried installing older version and it seems to work fine still in 0.44.0 but then exhibits this problem starting with 0.45.0

**Comment by ilium007** [comment]
I have hit this same issue, incorrect token pasted into homeassistant auth filed and nodered instantly crashed. I have spent hours trying to get it back up again to then enter the correct token string. How do I update a nodered instance (Docker container) to use 0.47.1?
