### ISSUE TITLE
Nodes not appearing in the palette after upgrade 

### ISSUE THREAD

**Issue by lbedogni** [zachowj/node-red-contrib-home-assistant-websocket#773]
### Describe the bug

The nodes provided by **node-red-contrib-home-assistant-websocket** do not appear anymore in the palette, and I receive the message in the screenshot every time I open node-red. I tried to uninstall, reinstall, nothing solves it. Any idea?

### To Reproduce

I simply start node-red.

### Screenshots

<img width="674" alt="Screenshot 2022-11-25 at 12 14 42" src="https://user-images.githubusercontent.com/417701/203973892-0554ace6-da13-4c04-b45e-3122f6279a97.png">

### This package's version (not the Home Assistant add-on version)

0.47.0

### Is Node-RED running in Docker?

Home Assistant add-on

### Node-RED version

3.0.2

### Node.js version

not sure

**Comment by zachowj** [comment]
Can you post your NR logs of NR loading up?

**Comment by lbedogni** [comment]
Sure, here it is:

`s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/00-banner.sh
-----------------------------------------------------------
 Add-on: Node-RED
 Flow-based programming for the Internet of Things
-----------------------------------------------------------
 Add-on version: 13.5.3
 You are running the latest version of this add-on.
 System: Home Assistant OS 9.3  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2022.11.4
 Home Assistant Supervisor: 2022.11.2
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
cont-init: info: /etc/cont-init.d/00-banner.sh exited 0
cont-init: info: running /etc/cont-init.d/01-log-level.sh
cont-init: info: /etc/cont-init.d/01-log-level.sh exited 0
cont-init: info: running /etc/cont-init.d/customizations.sh
cont-init: info: /etc/cont-init.d/customizations.sh exited 0
cont-init: info: running /etc/cont-init.d/nginx.sh
cont-init: info: /etc/cont-init.d/nginx.sh exited 0
cont-init: info: running /etc/cont-init.d/node-red.sh
patching file nodes/ui_base.html
Hunk #1 succeeded at 1164 (offset 633 lines).
up to date, audited 113 packages in 8s
28 packages are looking for funding
  run `npm fund` for details
2 critical severity vulnerabilities
To address all issues, run:
  npm audit fix
Run `npm audit` for details.
cont-init: info: /etc/cont-init.d/node-red.sh exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun nginx (no readiness notification)
services-up: info: copying legacy longrun nodered (no readiness notification)
s6-rc: info: service legacy-services successfully started
[15:03:32] INFO: Starting Node-RED...
> start
> node $NODE_OPTIONS node_modules/node-red/red.js "--settings" "/etc/node-red/config.js"
25 Nov 15:05:38 - [info] 
Welcome to Node-RED
===================
25 Nov 15:05:39 - [info] Node-RED version: v3.0.2
25 Nov 15:05:39 - [info] Node.js  version: v16.17.1
25 Nov 15:05:39 - [info] Linux 5.15.61-v8 arm64 LE
25 Nov 15:06:28 - [info] Loading palette nodes
25 Nov 15:06:44 - [info] Dashboard version 3.2.0 started at /endpoint/ui
25 Nov 15:06:46 - [warn] ------------------------------------------------------
25 Nov 15:06:46 - [warn] [node-red-contrib-home-assistant-websocket/all] SyntaxError: Malformed JSON in file: /config/node-red//node-red-contrib-home-assistant-websocket.json
Unexpected token  in JSON at position 0
25 Nov 15:06:46 - [warn] ------------------------------------------------------
25 Nov 15:06:46 - [info] Settings file  : /etc/node-red/config.js
25 Nov 15:06:46 - [info] Context store  : 'default' [module=memory]
25 Nov 15:06:46 - [info] User directory : /config/node-red/
25 Nov 15:06:46 - [warn] Projects disabled : editorTheme.projects.enabled=false
25 Nov 15:06:46 - [info] Flows file     : /config/node-red/flows.json
25 Nov 15:06:46 - [info] Server now running at http://127.0.0.1:46836/
25 Nov 15:06:46 - [warn] Error loading credentials: SyntaxError: Unexpected token � in JSON at position 0
25 Nov 15:06:46 - [warn] Error loading flows: Error: Failed to decrypt credentials
25 Nov 15:06:46 - [info] Waiting for missing types to be registered:
25 Nov 15:06:46 - [info]  - api-call-service
25 Nov 15:06:46 - [info]  - server-state-changed
25 Nov 15:06:46 - [info]  - ialarm status
25 Nov 15:06:46 - [info]  - ha-entity
25 Nov 15:06:46 - [info]  - ha-get-entities
25 Nov 15:06:46 - [info]  - api-current-state
[15:06:47] INFO: Starting NGinx...`

It seems the problem is a malformed JSON.

**Comment by zachowj** [comment]
You can delete the file and it will load correctly. Based on the position of the error I am guessing it's an empty file or if it's not empty posted it.

**Comment by lbedogni** [comment]
It was empty, deleted it, now everything works. Strange, probably the update messed it up.
