### ISSUE TITLE
UI / documentation on "Resend state and attributes" can be improved

### ISSUE THREAD

**Issue by Rudd-O** [zachowj/node-red-contrib-home-assistant-websocket#774]
### Describe the bug

When I create a regular sensor whose payload is text, it works absolutely perfectly... untily I restart HA.  When I do this, the sensor changes state in HA to `unknown`, instead of remembering the payload it had before.  EDIT: attributes disappear too.

This is unlike e.g. the switch type of entity created via NR, where its state is always what it was before restarting HA.

Now, it is normal that many sensors appears as `unknown` at the beginning of HA start, and most automations one writes must cope with that normally.  But it is *abnormal* that the sensor remains in that state until a new change in a NR flow pushes a new state to the sensor.

I believe this is an issue that needs to be corrected.

### This package's version (not the Home Assistant add-on version)

0.33.1

### Is Node-RED running in Docker?

No

### Node-RED version

1.3.3

### Node.js version

14.17.1

**Comment by zachowj** [comment]
In the latest releases, this is possible by selecting ["Resend state and attributes"](https://zachowj.github.io/node-red-contrib-home-assistant-websocket/node/entity-config.html#resend-state-and-attributes) in the entity config. Even on the older version you're running it should be in the entity node.

**Comment by Rudd-O** [comment]
OK.  That should be the default, and it should also be explained as "Resend state and attributes when reconnecting to Home Assistant (after a restart)" because it was absolutely not clear what that even did.  The documentation is also faulty, it says:

> When the entity in Home Assistant is created the state and attributes will also be set. This is only applicable with certain entities nodes.

According to what you just told me, that explanation is not correct.  The correct explanation ought to say "is created, or Home Assistant restarts".

**Comment by zachowj** [comment]
Pull requests for documentation improvements are always appreciated.
