### ISSUE TITLE
Persistent Notification not accepting "notification_id" when sending the message

### ISSUE THREAD

**Issue by jpoeppelman1** [zachowj/node-red-contrib-home-assistant-websocket#789]
### Describe the bug

Persistent Notification not accepting "notification_id" when sending the message

### To Reproduce

Domain: notify
Service: persistent_notification

Data:

{ "message":"The garage door has been open for 10 minutes.",
  "title":"Your Garage Door Friend",
  "notification_id":"test"
  }

RESULT:

"Call-service error. extra keys not allowed @ data['notification_id']"

### Expected behavior

The message should process with success so that it can be later dismissed using the notification_id.

### Screenshots

N/A

### Example Flow

```json
N/A
```

### This package's version (not the Home Assistant add-on version)

not sure

### Is Node-RED running in Docker?

Yes

### Node-RED version

3.0.2

### Node.js version

Not sure

### Additional context

NA

**Comment by zachowj** [comment]
https://www.home-assistant.io/integrations/persistent_notification/#service

`notification_id` is for the `persistent_notification.create` service.

**Comment by zachowj** [comment]
`persistent_notification` is the domain and `create` is the service.

**Comment by jpoeppelman1** [comment]
Wow, totally overlooked this.  Issue closed.  Thank you!

**Comment by jpoeppelman1** [comment]
Overlooked the documentation, closing the issue.
