### ISSUE TITLE
HTTP Supervisor API issues in HA 2022.11.X

### ISSUE THREAD

**Issue by illuzn** [zachowj/node-red-contrib-home-assistant-websocket#797]
### Describe the bug

I am using the API node to access information about whether an addon is running or not.

The API node throws this error: "Error Message: target must be an object"

### To Reproduce

1. Create API Node.
2. Configure as follows: HTTP, GET, http://supervisor/addons/a0d7b954_nodered/info
3. Set params to {}

### Expected behavior

A parsed JSON object with the results of that get request.

### This package's version (not the Home Assistant add-on version)

0.47.0

### Is Node-RED running in Docker?

Home Assistant add-on

### Node-RED version

13.5.3

### Node.js version

16.17.1

**Comment by S-E-B-123** [comment]
Hi, at least with HA 2022.12.0 the API-Node works without any problem.
Did you select `{} JSON` as params and leave the input field empty?
Here my test flow:
`[{"id":"98ac0dcd6e7fadf0","type":"inject","z":"38268b36a005e8a8","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":270,"y":1280,"wires":[["a7e7ec8a90eddd89"]]},{"id":"4eb8d666ab89181e","type":"debug","z":"38268b36a005e8a8","name":"debug 30","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","statusVal":"","statusType":"auto","x":580,"y":1280,"wires":[]},{"id":"a7e7ec8a90eddd89","type":"ha-api","z":"38268b36a005e8a8","name":"","server":"","version":1,"debugenabled":true,"protocol":"http","method":"get","path":"http://supervisor/addons/a0d7b954_nodered/info","data":"","dataType":"json","responseType":"json","outputProperties":[{"property":"payload","propertyType":"msg","value":"","valueType":"results"}],"x":430,"y":1280,"wires":[["4eb8d666ab89181e"]]}]`

**Comment by illuzn** [comment]
Thanks. I previously didn't leave the input field empty because it marked itself red when empty (hence filling it with {}).

Seems this should be marked as an optional field rather than a required field.

**Comment by enjibby** [comment]
I am also having this issue as part of implementing a node-red equivalent to the new local-calendar start and end events.

# To reproduce

1. Create a new API Node
2. Set the Protocol to 'HTTP', the Method to 'GET' and the Path to 'calendars/<calendar-entity-id>'.
3. Set the Params to '{ "start": "2023-01-01T00:00:00Z", "end": "2024-01-01T00:00:00Z" }'.

This also produces the error "Error Message: target must be an object".

Using a debug node, it appears that the Params property is stored as a string rather than as a JSON object.

**Comment by enjibby** [comment]
I believe I have found and fixed the issue in #828
