### ISSUE TITLE
Device types with Alexa

### ISSUE THREAD

**Issue by jer78** [zachowj/node-red-contrib-home-assistant-websocket#8]
I currently use one of the original Node Red plugins with Home Assistant and it seems it uses a Hue emulation to bring into Alexa? Will this be the same or can I have different types of devices?

**Comment by zachowj** [comment]
If you're referring to [node-red-contrib-home-assistant](https://github.com/AYapejian/node-red-contrib-home-assistant) as the original plugin. Switching to this fork should have no impact on Home Assistant using the emulated_hue component to communicate with Alexa if I am understanding your question correctly.

**Comment by jer78** [comment]
Thanks for the quick reply. Although I was wondering if I were to switch, would I get different functionality? As an example, I currently have a switch for my TV but can’t change the device from a light. So if I say turn off all lights it turns off the TV too. But if I could change the device type to a switch it could possibly avoid this. Or if I have one that is a speaker be able to control volume? Thanks.

**Comment by zachowj** [comment]
No, it won't change anything that you're referencing.
