### ISSUE TITLE
Output Initially / On Deploy

### ISSUE THREAD

**Issue by legomind** [zachowj/node-red-contrib-home-assistant-websocket#80]
**Is your feature request related to a problem? Please describe.**
Consider outputting state on the deployment of a node, not just the deployment of the configuration node

**Describe the solution you'd like**
An update to the existing option Output Initially / On Deploy for the trigger-state or state-changed nodes or an additional option.

**Describe alternatives you've considered**
A simple inject with current-state node does the trick, but it can be cumbersome

**Additional context**
This is only really a problem when the deployment mode is set to partially deploy a single flow or changed nodes only.

**Comment by zachowj** [comment]
What's your use case, just for testing?

**Comment by legomind** [comment]
In my case, I have a state-machine node that tracks events to securly unlock the front door when someone arrives home. It looks something like this:

WAITING -> [arrival event] -> PRIMED -> [motion or pressure_mat event] -> UNLOCKED -> [timeout event] -> WAITING
