### ISSUE TITLE
Mustache template in call service node is not able to render {{global.name}}

### ISSUE THREAD

**Issue by cannfoddr** [zachowj/node-red-contrib-home-assistant-websocket#81]
**Description**
I have an alarm flow that uses a global value {{global.alarm_trigger}} to hold the friendly name of the sensor that has triggered.   This is set based on an event change from a sensor and the flow stores the global value checks the alarm is armed and goes on to trigger the alarm.

The alarm triggered flow then sends a pushover message via a call service node to tell the user that the sensor that triggered the alarm using the global value.  If I use a template node to construct the message everything works.  If I embed the moustache template in the call service node with render templates enabled the {{global.alarm_trigger}} does not get rendered

**To Reproduce**

1. set global.alarm_trigger in flow to friendly name ie. "Garage Motion"
2. create call service node  for pushover with moustache template:
```
{
   "data":{
      "title": "HomeAssistant: Security",
      "message": "Alarm has been activated. Detected {{global.alarm_trigger}}."
    }
}
```
3. tick box for render templates
4. resulting message ends "Detected ."

**Expected behavior**
{{global.alarm_trigger}} should render to "Garage Motion" not null

**Screenshots**
![image](https://user-images.githubusercontent.com/1035066/51472572-caa79100-1d71-11e9-87f9-04bae454f588.png)

**Example Flow: working (move the template to call service to see issue)**
`[{"id":"bbf291c4.cd13d8","type":"server-state-changed","z":"1c78f795.492d28","name":"All PIRs","server":"c67e9b43.8d8f98","entityidfilter":"^binary_sensor\\.\\w+_[pir|door]_\\w+","entityidfiltertype":"regex","outputinitially":false,"state_type":"str","haltifstate":"off","halt_if_type":"","halt_if_compare":"is","outputs":2,"x":110,"y":640,"wires":[["3b9c2e2e.92b2a2","d041b019.b2e59"],[]]},{"id":"3b9c2e2e.92b2a2","type":"change","z":"1c78f795.492d28","name":"","rules":[{"t":"set","p":"alarm_trigger","pt":"global","to":"data.new_state.attributes.friendly_name","tot":"msg"}],"action":"","property":"","from":"","to":"","reg":false,"x":350,"y":640,"wires":[["d041b019.b2e59","ba5d235b.eca0f8"]]},{"id":"d041b019.b2e59","type":"debug","z":"1c78f795.492d28","name":"","active":true,"tosidebar":true,"console":false,"tostatus":true,"complete":"true","x":670,"y":460,"wires":[]},{"id":"ba5d235b.eca0f8","type":"switch","z":"1c78f795.492d28","name":"","property":"topic","propertyType":"msg","rules":[{"t":"else"},{"t":"cont","v":"garage_pir","vt":"str"}],"checkall":"true","repair":false,"outputs":2,"x":570,"y":640,"wires":[["f05ba280.90cc5"],["54e4f18a.a132a8"]]},{"id":"f05ba280.90cc5","type":"api-current-state","z":"1c78f795.492d28","name":"Get Alarm State","server":"c67e9b43.8d8f98","halt_if":"disarmed","override_topic":true,"override_payload":true,"entity_id":"alarm_control_panel.ha_alarm","outputs":1,"x":780,"y":620,"wires":[["5f6a0759.bdcff8"]]},{"id":"54e4f18a.a132a8","type":"template","z":"1c78f795.492d28","name":"","field":"payload","fieldType":"msg","format":"handlebars","syntax":"mustache","template":"{\n   \"data\":{\n      \"title\": \"HomeAssistant: Security\",\n      \"message\": \"Alarm has been activated. Detected {{global.alarm_trigger}}.\"\n    }\n}\n","output":"json","x":700,"y":720,"wires":[["971ec9ff.e69248","d041b019.b2e59"]]},{"id":"77b9628f.e82404","type":"inject","z":"1c78f795.492d28","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":480,"y":720,"wires":[["54e4f18a.a132a8"]]},{"id":"971ec9ff.e69248","type":"api-call-service","z":"1c78f795.492d28","name":"Pushover Adrian (Triggered)","server":"c67e9b43.8d8f98","service_domain":"notify","service":"po_adrian","data":"{}","render_data":false,"mergecontext":"","output_location":"payload","output_location_type":"msg","x":960,"y":720,"wires":[["d041b019.b2e59"]]},{"id":"5f6a0759.bdcff8","type":"switch","z":"1c78f795.492d28","name":"Armed ?","property":"payload","propertyType":"msg","rules":[{"t":"regex","v":"^armed_","vt":"str","case":true}],"checkall":"true","repair":false,"outputs":1,"x":1000,"y":620,"wires":[["e89d4a92.3945d8","d041b019.b2e59"]]},{"id":"e89d4a92.3945d8","type":"api-call-service","z":"1c78f795.492d28","name":"Trigger Alarm","server":"c67e9b43.8d8f98","service_domain":"alarm_control_panel","service":"alarm_trigger","data":"{\"entity_id\":\"alarm_control_panel.ha_alarm\"}","render_data":false,"mergecontext":"","output_location":"payload","output_location_type":"msg","x":1190,"y":620,"wires":[["d041b019.b2e59"]]},{"id":"c67e9b43.8d8f98","type":"server","z":"","name":"HomeAssistant","legacy":false,"hassio":false,"rejectUnauthorizedCerts":true}]
`
**Environment (please complete the following information):**

- Node Red Version: 0.19.5
- NR Home Assistant Plugin Version: 0.5.1
- Is Node Red running in Docker: yes

**Other (please complete the following information):**

- Have you searched previous issues for duplicates?: yes

**Additional context**
Think the original moustache template handling did not work with {{flow.name}} or {{global.name}} and had to be changed to add this support

**Comment by zachowj** [comment]
The templating system for the **call-service** and **fire-event** nodes currently can only render properties from the `msg` object.

I do have it on a list to add in the **flow**, **global**, and **states** context.
