### ISSUE TITLE
Wait Node (possible new node) looking for feedback

### ISSUE THREAD

**Issue by zachowj** [zachowj/node-red-contrib-home-assistant-websocket#82]
Have a new node sort of mocked up but not sure if it's worth implementing because its use can be duplicated with several other nodes. It's basically a copy of the **wait** condition in Home Assistant.

https://www.home-assistant.io/docs/scripts/#wait

> **WAIT**
>
>Wait until some things are complete. We support at the moment `wait_template` for waiting until a condition is `true`, see also on Template-Trigger. It is possible to set a timeout after which the script will continue its execution if the condition is not satisfied. Timeout has the same syntax as `delay`.

A possible use case could be:

You have a household member arriving home and you want to greet them by name when the front door is opened. First, have an **event-state** node trigger when a person's state goes from `not home` to `home` then a **wait** node that will trigger when the front door sensor changes which then fires the TTS to HA.

![chrome_2019-01-22_20-35-41](https://user-images.githubusercontent.com/37859597/51583424-59590280-1e85-11e9-8f83-86ec96487079.png)

Here's the editor window

![chrome_2019-01-22_20-32-14](https://user-images.githubusercontent.com/37859597/51583331-e485c880-1e84-11e9-9188-a641c9aa5516.png)

The output of the node right now has two outputs. One for if the condition becomes `true` and the second if the timeout occurs. Another option could be to only have one output that would add a property to the `msg` object, `msg.timedout = true` if the timeout occurred.

The node would also accept a `msg` object with the property of `msg.reset` to reset the node and cancel any current wait/timeouts in progress.

Questions?

1. Would this node be useful?
2. What format should the **Timeout** be in, seconds or in the same format as Home Assistant `00:00:01`? I am leaning towards seconds to keep it in-line with the **poll-state** node.
3. Which output option? Two outputs or one with an extra property on the `msg` object.
4. What should the default be for `Continue on Timeout`, checked or not checked?

Any other suggestions or improvements?

**Comment by goforthanddie** [comment]
I am just looking for something like that to, e.g., wait for a power socket to fall below a certain power consumption :). 

So:
1. Yes.
2. Maybe do it like it is done in the delay node? Field for integer + field for ms/s/m/h/d?
3. I think it makes sense to make it similar to the "current state" node which has an "halt if" function, meaning that the timeout just causes the node to halt. I think two outputs is nice to have but not necessary.
4. Unchecked

Thanks for your efforts.

**Comment by oakbrad** [comment]
1. Yes I think so!
2. I agree with above comment, can it be both?
3. I think two outputs is more useful and also easier to follow in flows. Many other nodes work exactly as you describe with 2 outputs (stoptimer, loop, etc.)
4. Unchecked

**Comment by eithe** [comment]
This would be great, will simplify my washing machine logic. I would like two outputs as well.

**Comment by carlos-sarmiento** [comment]
This would be super useful!

**Comment by chimpy** [comment]
Currently, I use a trigger node to do your example. When this entity (front door) opens, Person X must be "home".
However I think this is an interesting proposal: the timeout makes it cool.

This node could make flows using delay & traffic light nodes a lot simpler, for example:

![image](https://user-images.githubusercontent.com/380577/51904825-ea693580-23bf-11e9-9b3a-0e3e2e539a1e.png)

**Comment by legomind** [comment]
I personally thing this functionality belongs in a node unrelated to home assistant.
A wait until node could be configured to wait until a message on a given topic matches the provided conditions from any source, not just home assistant.

![image](https://user-images.githubusercontent.com/3710857/52123547-782d6680-25f4-11e9-9149-39261ee14d82.png)
