### ISSUE TITLE
Time displays in UTC

### ISSUE THREAD

**Issue by Hisma** [zachowj/node-red-contrib-home-assistant-websocket#83]
Saw someone closed this issue a few weeks ago, but it's happening to me and I can't explain why.
running node red docker container latest v8, node red version 19.5.
Home assistant is latest version, .86, also running in docker (not hass.io), and I am authenticating using long live token.

I generated the container using docker-compose, and I have the volumes "/etc/localtime:/etc/localtime:ro" and
"etc/timezone:/etc/timezone:ro" set. I am located in UTC -5 (EST), but my "call service" node shows a timestamp with standard UTC time, 5 hours later than my local time.
All other nodes in node red and debug messages show the correct local time, as well if I run the "date" command inside the docker container. This is definitely an issue specific to the service node I am using, not node red itself.  See image for proof - 
[Imgur](https://i.imgur.com/7O5THlc.png)

**Comment by zachowj** [comment]
Run this flow and what does it display in the debug tab?

```
[{"id":"8f353b43.9369c8","type":"inject","z":"5eb3594f.d294b8","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":92,"y":672,"wires":[["42e6362a.003848"]]},{"id":"d972a939.f4a9c8","type":"debug","z":"5eb3594f.d294b8","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"payload","x":386,"y":672,"wires":[]},{"id":"42e6362a.003848","type":"function","z":"5eb3594f.d294b8","name":"","func":"msg.payload = new Date();\n\nreturn msg;","outputs":1,"noerr":0,"x":238,"y":672,"wires":[["d972a939.f4a9c8"]]}]
```

**Comment by Hisma** [comment]
Mon Jan 28 2019 16:44:13 GMT-0500 (EST)
[Imgur](https://i.imgur.com/BJGFhAp.png)

That is the correct time by the way.

**Comment by zachowj** [comment]
If you just attach a inject node to a current state node does it give you the incorrect time below the node?

**Comment by Hisma** [comment]
same result, incorrect time below the node. 
[Imgur](https://i.imgur.com/EvBiLH5.png)
Time below the node SHOULD be 18:51, not 23:51.  It's displaying to UTC +0.  
Something else of note, even though the timestamp is wrong on the service node, other nodes display the correct time, and I have an automation that toggles lights depending on dawn/dusk, and it operated at the appropriate time.  But it still displayed the wrong timestamp underneath the service node.

**Comment by zachowj** [comment]
This is the exact code that displays the status date. Give it a try and see if it still displays the incorrect offset.

```
[{"id":"8f353b43.9369c8","type":"inject","z":"5eb3594f.d294b8","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":92,"y":672,"wires":[["42e6362a.003848"]]},{"id":"d972a939.f4a9c8","type":"debug","z":"5eb3594f.d294b8","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"payload","x":386,"y":672,"wires":[]},{"id":"42e6362a.003848","type":"function","z":"5eb3594f.d294b8","name":"","func":"msg.payload = new Date().toLocaleDateString('en-US', {\n            month: 'short',\n            day: 'numeric',\n            hour12: false,\n            hour: 'numeric',\n            minute: 'numeric'\n        });\n\nreturn msg;","outputs":1,"noerr":0,"x":238,"y":672,"wires":[["d972a939.f4a9c8"]]}]
```

**Comment by Hisma** [comment]
When I inject that node here is the debug output - 

```
1/29/2019, 6:12:28 PM node: 8b20087a.a07d48
msg.payload : string[13]
"Jan 29, 23:12"
```
The time is still incorrect.
Note that the debug message timestamp is 5 hours earlier, which again, is the correct time.

**Comment by zachowj** [comment]
Try adding the timezone via the environment variable in your docker-compose file.

```
  node-red:
    environment:
      - TZ=America/New_York
```

**Comment by Hisma** [comment]
Surprisingly, that fixed it.  Thank you! 
`1/29/2019, 8:12:04 PMnode: 8b20087a.a07d48
msg.payload : string[13]
"Jan 29, 20:12"`
I hope this is something that could be fixed though.   I could not find this information documented anywhere.  Defining the localtime file as a volume should be enough imo.
Appreciate you working with me to fix this

**Comment by zachowj** [comment]
Here's where I found it or could be something very similar to it.

https://github.com/docker-library/openjdk/issues/80
