### ISSUE TITLE
Zone node no debug or output

### ISSUE THREAD

**Issue by sw-will** [zachowj/node-red-contrib-home-assistant-websocket#840]
### Describe the bug

Trying to debug the the outputs from zone node and it is coming up empty.
I am expecting per documentation:
- topic
- payload
- data
- zones
I know the trigger is working because the downstream automations are activating but there's no outputs as per documentation.

### To Reproduce

I am testing using person entity, and modifying the latitude and longitude against a zone defined in home assistant.

### Expected behavior

Expecting outputs in the debug per the documentation.

### Screenshots

![image](https://user-images.githubusercontent.com/33868123/212522919-4b089009-65e0-4d0d-961b-640535e81e28.png)

### This package's version (not the Home Assistant add-on version)

0.48.0

### Is Node-RED running in Docker?

Home Assistant add-on

### Node-RED version

3.0.2

### Node.js version

18

**Comment by zachowj** [comment]
I am seeing the output of the zone node when the location is changed. Any errors in your logs when zone changes?

**Comment by carefulcomputer** [comment]
i see similar weird behavior. I get output rarely and most of the times I don't. 
Usecase : i setup an telegram alert if a person enters/leaves the zone, however i never got the alert. When I use event state node with zone defined as entity that works great for same use case.

**Comment by sw-will** [comment]
> I am seeing the output of the zone node when the location is changed. Any errors in your logs when zone changes?

The debug is completely blank but the trigger is working, there's no errors or anything. The zone does trigger when I modify the latitude and longitude I just can't make use of the output.

**Comment by carefulcomputer** [comment]
some more debugging. 'enter' works but 'leave' never works.

**Comment by carefulcomputer** [comment]
still an issue.

**Comment by carefulcomputer** [comment]
still an issue.

**Comment by zachowj** [comment]
There was a bug in the geolib library which may have caused issues. Give the latest release a try.

https://github.com/zachowj/node-red-contrib-home-assistant-websocket/pull/990

**Comment by carefulcomputer** [comment]
Thanks. Will do and confirm when I get a chance.

**Comment by carefulcomputer** [comment]
still an issue.

**Comment by LeopoldKing** [comment]
i can confirm that the same bug occurs for a button type entity. The logbook shows that it got triggered and even the "state changed" node will fire the change but the device node itself won't deliver a message

**Comment by carefulcomputer** [comment]
There must be a race condition somewhere. I see that the node triggers when someone leaves the zone, but rarely when someone comes back in the zone.

**Comment by carefulcomputer** [comment]
ping
