### ISSUE TITLE
Events-node receives only state_changed events

### ISSUE THREAD

**Issue by aalbul** [zachowj/node-red-contrib-home-assistant-websocket#85]
**Describe the bug**
I'm new to NodeRed so there is still a chance that i'm doing something wrong.
I'm currently have a huge Hass.io instance with around 150 Xiaomi devices.
NodeRed addon is installed and i can see state_changed events, but other events are not being sent to NodeRed.
On the screenshot you can see a list of events that i have in a system:
![screenshot 2019-02-03 at 22 11 30](https://user-images.githubusercontent.com/4253154/52182986-b6e53b80-2803-11e9-8b52-30fc02e33e8b.png)

But if i'm trying to listen for "xiaomi_aqara.click" in just doesn't work:
![screenshot 2019-02-03 at 22 13 12](https://user-images.githubusercontent.com/4253154/52182989-c4022a80-2803-11e9-9150-e851f1b1726f.png)

This is a screenshot of NodeRed after i tried to click my button multiple times:
![screenshot 2019-02-03 at 22 14 10](https://user-images.githubusercontent.com/4253154/52182994-ce242900-2803-11e9-9a65-3d6fa399d5e3.png)

From other side, if i will listen to all events (empty field), i will get state_changed events for my button:
![screenshot 2019-02-03 at 22 15 23](https://user-images.githubusercontent.com/4253154/52182998-d8462780-2803-11e9-918e-f6a536acec0b.png)

**To Reproduce**

Note sure if there are any pre-conditions related to configuration of HA or NodeRed. Just install NodeRed from the scratch on Hass.io via addon manager and try to create events node that is listening to some event that is not "state_changed"

**Expected behavior**
I expect "xiaomi_aqara.click" event to be propagated from HA to NodeRed

**Screenshots**
Added above

**Example Flow**
n/a

**Environment (please complete the following information):**

- Node Red Version: 0.19.5
- NR Home Assistant Plugin Version: 1.2.5
- Is Node Red running in Docker: hassio

**Other (please complete the following information):**

- Have you searched previous issues for duplicates?: yes

**Additional context**
I also opened the same issue on https://github.com/hassio-addons/addon-node-red here: https://github.com/hassio-addons/addon-node-red/issues/126 but their answer was logical (to me). That plugin just wraps node-red plugins so it could be on a protocol level.

**Comment by zachowj** [comment]
Try this sample flow to filter out all events except the `state_change` events and you should see your `xiaomi_aqara.click` events. I have a feeling that the event type will just be `xiaomi_aqara` and not `xiaomi_aqara.click` then you'll have to use a switch node or something to filter it down further. Also after adding the below flow just switch a light or something and you should see the `call_server` event just to confirm it's working for you.

```
[{"id":"21869758.1b9f18","type":"server-events","z":"ffbd7f06.4a014","name":"","server":"2dad33ee.42bf5c","event_type":"","x":160,"y":512,"wires":[["440cb092.2e253"]]},{"id":"4d0b267.56c24d8","type":"debug","z":"ffbd7f06.4a014","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":502,"y":512,"wires":[]},{"id":"440cb092.2e253","type":"switch","z":"ffbd7f06.4a014","name":"","property":"payload.event_type","propertyType":"msg","rules":[{"t":"neq","v":"state_changed","vt":"str"}],"checkall":"true","repair":false,"outputs":1,"x":354,"y":512,"wires":[["4d0b267.56c24d8"]]}]
```

**Comment by aalbul** [comment]
Oh my... I feel so stupid :)
In case if you use Xiaomi Wall Switch'es (with or without zero line), they are not triggering custom events. Just changing state.
I completely forgot about that. Anyway, thanks for your code snipped. That helped me a lot. I was actually able to catch custom events (but other ones like motion detected e.t.c.):
![screenshot 2019-02-04 at 08 57 29](https://user-images.githubusercontent.com/4253154/52196124-ec694380-285a-11e9-808d-2128eb632559.png)

Thank you for your help!
