### ISSUE TITLE
wait until doesnt work as described

### ISSUE THREAD

**Issue by Fruchuxs** [zachowj/node-red-contrib-home-assistant-websocket#873]
### Describe the bug

Hello, I played around with the "wait until" node, but I didn't get it to work.
First the "exact" filter is hard to handle, because if I type a mustache template into the entity_id, I can't clear it. But thats okay, I can workaround this. Then I get no error, if my mustache template is wrong.. But that is also okay, because I thought "hmm let us use a function node to put the values into that 'wait until' node, instead of this hard to debug mustache template". But this also didn't work.

I always get error messages: 
ValidationError: "entityId" is not allowed to be empty
ValidationError: "property" is not allowed to be empty

and so on.

I think I do something wrong.

### To Reproduce

Put the payload parameters in the node via a function node like described here:
https://zachowj.github.io/node-red-contrib-home-assistant-websocket/node/wait-until.html

### Example Flow

```json
[{"id":"a11345ab59d84d79","type":"function","z":"1e93935c.31da2d","name":"wait until format hack","func":"\nreturn {\n    payload: {\n        entity_id: msg.event.trigger.entity_id,\n        entityId: msg.event.trigger.entity_id,\n        property: \"state\",\n        comparator: \"off\"\n    }\n};","outputs":1,"noerr":0,"initialize":"","finalize":"","libs":[],"x":300,"y":520,"wires":[["54e2ab8a9a906b2c","e0210510bf22c7e8"]]},{"id":"54e2ab8a9a906b2c","type":"ha-wait-until","z":"1e93935c.31da2d","name":"","server":"66949006.ff21b","version":2,"outputs":2,"entityId":"","entityIdFilterType":"exact","property":"state","comparator":"is","value":"off","valueType":"str","timeout":"5","timeoutType":"num","timeoutUnits":"seconds","checkCurrentState":true,"blockInputOverrides":true,"outputProperties":[],"entityLocation":"data","entityLocationType":"none","x":460,"y":580,"wires":[["c1c94f70da62c60f"],["915e98cddf1b54fc"]]},{"id":"66949006.ff21b","type":"server","name":"hass_fruchuxs","version":5,"addon":false,"rejectUnauthorizedCerts":false,"ha_boolean":"y|yes|true|on|home|open","connectionDelay":true,"cacheJson":true,"heartbeat":false,"heartbeatInterval":"30","areaSelector":"friendlyName","deviceSelector":"friendlyName","entitySelector":"friendlyName","statusSeparator":"at: ","statusYear":"hidden","statusMonth":"short","statusDay":"numeric","statusHourCycle":"h23","statusTimeFormat":"h:m","enableGlobalContextStore":true}]
```

### This package's version (not the Home Assistant add-on version)

0.48.1

### Is Node-RED running in Docker?

Yes

### Node-RED version

3.0.2

### Node.js version

docker

**Comment by zachowj** [comment]
In the wait-until node uncheck "block input overrides"

**Comment by Fruchuxs** [comment]
Hey zachowj,

thank you! Such an obvious fail from me ..
