### ISSUE TITLE
halt if, state type boolean

### ISSUE THREAD

**Issue by AndreasRavn** [zachowj/node-red-contrib-home-assistant-websocket#88]
If I select the State Type to be boolean, I can't get the half if logic to work. I think it compares a string value with the typecasted boolean value and thereby always return the same result.

Suggestion would be to add "is true" and "is false" to halt if state select field. Like the switch node.

`[{"id":"7be3df3c.b09a08","type":"tab","label":"Flow 1","disabled":false,"info":""},{"id":"c8a604e5.e9b1b","type":"server-state-changed","z":"7be3df3c.b09a08","name":"","server":"b3647e80.a78bd","entityidfilter":"input_boolean.andreas","entityidfiltertype":"exact","outputinitially":true,"state_type":"habool","haltifstate":"true","halt_if_type":"","halt_if_compare":"is","outputs":2,"output_only_on_state_change":false,"x":329.14337158203125,"y":198.9227752685547,"wires":[["18dd1e56.dc1ca2"],["58e5b5e.8985ccc"]]},{"id":"18dd1e56.dc1ca2","type":"debug","z":"7be3df3c.b09a08","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"payload","x":704.1506652832031,"y":138.29779052734375,"wires":[]},{"id":"58e5b5e.8985ccc","type":"debug","z":"7be3df3c.b09a08","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":702.8345947265625,"y":231.8235321044922,"wires":[]},{"id":"e9d78177.105cf8","type":"server-state-changed","z":"7be3df3c.b09a08","name":"","server":"b3647e80.a78bd","entityidfilter":"input_boolean.andreas","entityidfiltertype":"exact","outputinitially":true,"state_type":"habool","haltifstate":"on","halt_if_type":"","halt_if_compare":"is","outputs":2,"output_only_on_state_change":false,"x":328.8345642089844,"y":378.82354736328125,"wires":[["bea7464a.45fdf8"],["7b2870b4.e73ab8"]]},{"id":"bea7464a.45fdf8","type":"debug","z":"7be3df3c.b09a08","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":703.8418579101562,"y":318.1985626220703,"wires":[]},{"id":"7b2870b4.e73ab8","type":"debug","z":"7be3df3c.b09a08","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":702.5257873535156,"y":411.72430419921875,"wires":[]},{"id":"6887f056.ec2228","type":"server-state-changed","z":"7be3df3c.b09a08","name":"","server":"b3647e80.a78bd","entityidfilter":"input_boolean.andreas","entityidfiltertype":"exact","outputinitially":true,"state_type":"habool","haltifstate":"false","halt_if_type":"","halt_if_compare":"is","outputs":2,"output_only_on_state_change":false,"x":334.8345642089844,"y":571.8235473632812,"wires":[["9c8d60cc.855708"],["812734ab.3aaeb"]]},{"id":"9c8d60cc.855708","type":"debug","z":"7be3df3c.b09a08","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":709.8418579101562,"y":511.1985626220703,"wires":[]},{"id":"812734ab.3aaeb","type":"debug","z":"7be3df3c.b09a08","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":708.5257873535156,"y":604.7243041992188,"wires":[]},{"id":"739b33b3.b506e4","type":"server-state-changed","z":"7be3df3c.b09a08","name":"","server":"b3647e80.a78bd","entityidfilter":"input_boolean.andreas","entityidfiltertype":"exact","outputinitially":true,"state_type":"habool","haltifstate":"off","halt_if_type":"","halt_if_compare":"is","outputs":2,"output_only_on_state_change":false,"x":334.5257568359375,"y":751.7243194580078,"wires":[["9e2edd95.103df8"],["3698a4e.3ce8adc"]]},{"id":"9e2edd95.103df8","type":"debug","z":"7be3df3c.b09a08","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":709.5330505371094,"y":691.0993347167969,"wires":[]},{"id":"3698a4e.3ce8adc","type":"debug","z":"7be3df3c.b09a08","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":708.2169799804688,"y":784.6250762939453,"wires":[]},{"id":"e9d8a6bb.da13","type":"api-current-state","z":"7be3df3c.b09a08","name":"","server":"b3647e80.a78bd","outputs":2,"halt_if":"true","halt_if_type":"str","halt_if_compare":"is","override_topic":false,"entity_id":"input_boolean.andreas","state_type":"habool","state_location":"payload","override_payload":"msg","entity_location":"","override_data":"none","x":1182.1544227600098,"y":192.63232421875,"wires":[["441cb96f.6d55d8"],["389c05bd.b09652"]]},{"id":"441cb96f.6d55d8","type":"debug","z":"7be3df3c.b09a08","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":1495.8345985412598,"y":140.8235321044922,"wires":[]},{"id":"389c05bd.b09652","type":"debug","z":"7be3df3c.b09a08","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":1494.5185279846191,"y":234.34927368164062,"wires":[]},{"id":"1450246c.cf8234","type":"inject","z":"7be3df3c.b09a08","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":929.1543922424316,"y":190.46322631835938,"wires":[["e9d8a6bb.da13"]]},{"id":"52192d69.b657f4","type":"inject","z":"7be3df3c.b09a08","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":933.8345336914062,"y":373.82354736328125,"wires":[["a6a1c2c6.0b8ac8"]]},{"id":"a6a1c2c6.0b8ac8","type":"api-current-state","z":"7be3df3c.b09a08","name":"","server":"b3647e80.a78bd","outputs":2,"halt_if":"on","halt_if_type":"str","halt_if_compare":"is","override_topic":false,"entity_id":"input_boolean.andreas","state_type":"habool","state_location":"payload","override_payload":"msg","entity_location":"","override_data":"none","x":1186.8345642089844,"y":375.9926452636719,"wires":[["a03a00e2.152a2"],["5dd54ad8.ec6024"]]},{"id":"a03a00e2.152a2","type":"debug","z":"7be3df3c.b09a08","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":1500.5147399902344,"y":324.18385314941406,"wires":[]},{"id":"5dd54ad8.ec6024","type":"debug","z":"7be3df3c.b09a08","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":1499.1986694335938,"y":417.7095947265625,"wires":[]},{"id":"b3647e80.a78bd","type":"server","z":"","name":"HASS","legacy":false,"hassio":false,"rejectUnauthorizedCerts":true,"ha_boolean":"y|yes|true|on|home|open"}]`

**Comment by zachowj** [comment]
I am surprised no one has reported this earlier it's been an issue for several releases. I'm guessing you're using authorization on node-red? I actually found this right after I released v0.7.0 and the fix, https://github.com/zachowj/node-red-contrib-home-assistant-websocket/commit/83018e944779208ce283361e4a7a58ea53953aca, is already on GitHub and just hasn't been pushed out to a release yet.

**Comment by AndreasRavn** [comment]
Yeah I do.

It's quite easy to work around with a switch node, so I've been postponing the bug filing for quite some time, sorry ☺️
