### ISSUE TITLE
This node requires Node-RED custom integration version 0.5.0+  to be installed in Home Assistant for it to function.

### ISSUE THREAD

**Issue by showa26** [zachowj/node-red-contrib-home-assistant-websocket#899]
### Describe the bug

Hello,

could someone help me how to solve the issue of not getting the version 0.5.0 installed. Dont get is fixed by yself ;-)
<img width="799" alt="Knipsel" src="https://user-images.githubusercontent.com/126822939/226999392-948c2fe8-5396-443b-b0f6-f5bec3fdcb49.PNG">

### This package's version (not the Home Assistant add-on version)

Current version: 14.1.0

### Is Node-RED running in Docker?

Yes

### Node-RED version

Current version: 14.1.0

### Node.js version

14.17.1

**Comment by zachowj** [comment]
If you've restarted NR and the alert is still there I would guess that you haven't completed the install of the custom component.
