### ISSUE TITLE
Call service target(s) not definable from editor with media_player domain

### ISSUE THREAD

**Issue by Eleengineer** [zachowj/node-red-contrib-home-assistant-websocket#920]
### Describe the bug

Call service node requires a target, but these fields disappear if domain is set to media_player and either reopening the editor or making a change to the service selection.

### To Reproduce

1. Open editor of fresh call service node
2. Set domain to media_player
3. _optional:_ Set one of the targets {area, device, entity} to a media player
4. Change service selection
5. Target fields disappear
6. Change domain to a selection that is not media_player
7. Target fields appear

### Expected behavior

Target fields should not disappear

### Screenshots

![image](https://user-images.githubusercontent.com/61326147/235312938-9272a807-5fdb-4888-9393-8a3c88b38163.png)
![image](https://user-images.githubusercontent.com/61326147/235313000-6f81c3bc-d8cb-4fcd-b830-f40510c8ca48.png)
![image](https://user-images.githubusercontent.com/61326147/235314696-9c5fad19-88a0-40ef-80bc-379ee72a6877.png)

### This package's version (not the Home Assistant add-on version)

0.49.1

### Is Node-RED running in Docker?

Home Assistant add-on

### Node-RED version

3.0.2

### Node.js version

unknown

**Comment by zachowj** [comment]
I'm not seeing this. The target fields didn't hide when I selected any of the services. Do you have any javascript errors in your browser console?

**Comment by Eleengineer** [comment]
hass might not be providing some data anyway as the target and mute/unmute could be altered in the visual editor previously. 
![image](https://user-images.githubusercontent.com/61326147/235351579-dbefd2c1-671d-4054-86e9-6026205f7b56.png)
![image](https://user-images.githubusercontent.com/61326147/235351729-43b7cdd3-2501-4b10-b96d-1d11a7b36c64.png)
