### ISSUE TITLE
Outdated "Tip" documentation

### ISSUE THREAD

**Issue by fredck** [zachowj/node-red-contrib-home-assistant-websocket#938]
### Documentation URL

https://zachowj.github.io/node-red-contrib-home-assistant-websocket/guide/custom_integration/

### The problem

Thanks for the nice, handy integrations ;)

The "Tip" entry has some wrong (and misleading) information:

* The field name is not anymore "Name" but "Friendly Name".
* There is no "HA config" nor "Home Assistant Config" in there... that configuration section has no title anymore so one understands that everything there is about HA.
   * Side note: I strongly believe that the "Name" field should be use to derive the entity_id though.
* There is a typo in "The entity ids **change** be changed in HA after creating them in NR."... it's a guess work here but I believe it should be "cannot".
  * HA and NR should be fully written, lazy boy :)
* The screenshot doesn't match what we have now:

<img width="511" alt="image" src="https://github.com/zachowj/node-red-contrib-home-assistant-websocket/assets/630060/89dcd111-2962-4d60-bc7d-e7ca84ec3e21">

**Comment by KNXBroker** [comment]
_The field name is not anymore "Name" but "Friendly Name"._ 

Identified the same today. The friendly name is used to create the entity id... Shouldn't the "name field" on the top be used for entity id generation?
