### ISSUE TITLE
Current State Node (Halt)

### ISSUE THREAD

**Issue by bonelessc** [zachowj/node-red-contrib-home-assistant-websocket#94]
Hi!

I am trying to halt a flow by using the current state node, but it is not working how I need it.

So, I am looking at a binary sensor. When this turns ON, I want to make sure a door is closed. If it is closed, I want to send the binary sensor state, not the door state.
Is this possible? If yes, want am I doing wrong?

Thank you so much for a great project!

`[{"id":"f9b7c846.68fcf","type":"tab","label":"Garage Example","disabled":true,"info":""},{"id":"4b06902.67c1f7","type":"server-state-changed","z":"f9b7c846.68fcf","name":"Garage Detection","server":"9e03419b.3df268","entityidfilter":"binary_sensor.motion_sensor_158d0001e574ae","entityidfiltertype":"substring","outputinitially":false,"state_type":"str","haltifstate":"error","halt_if_type":"str","halt_if_compare":"is","outputs":2,"output_only_on_state_change":true,"x":130,"y":100,"wires":[["ea672ac7.d28e48"],[]]},{"id":"ea672ac7.d28e48","type":"switch","z":"f9b7c846.68fcf","name":"On or Off","property":"payload","propertyType":"msg","rules":[{"t":"eq","v":"on","vt":"str"},{"t":"eq","v":"off","vt":"str"}],"checkall":"true","repair":false,"outputs":2,"x":320,"y":100,"wires":[["65c5679e.51744"],["661f1258.e73bb4"]]},{"id":"65c5679e.51744","type":"api-current-state","z":"f9b7c846.68fcf","name":"Main Garage Door","server":"9e03419b.3df268","outputs":2,"halt_if":"on  ","halt_if_type":"str","halt_if_compare":"is","override_topic":false,"entity_id":"binary_sensor.main_garage_door","state_type":"str","state_location":"payload","override_payload":"msg","entity_location":"data","override_data":"msg","x":530,"y":80,"wires":[["ddd3bcbc.d18bf","661f1258.e73bb4"],[]]},{"id":"ddd3bcbc.d18bf","type":"api-call-service","z":"f9b7c846.68fcf","name":"Garage Lights","server":"9e03419b.3df268","service_domain":"switch","service":"turn_on","data":"{\"entity_id\":\"switch.switch_10\"}","render_data":false,"mergecontext":"","output_location":"payload","output_location_type":"msg","x":980,"y":80,"wires":[[]]},{"id":"661f1258.e73bb4","type":"trigger","z":"f9b7c846.68fcf","op1":"","op2":"off","op1type":"nul","op2type":"str","duration":"1","extend":true,"units":"min","reset":"on","bytopic":"all","name":"Trigger 10min","x":760,"y":160,"wires":[["e8f70502.1852a"]]},{"id":"e8f70502.1852a","type":"api-call-service","z":"f9b7c846.68fcf","name":"Garage Lights","server":"9e03419b.3df268","service_domain":"switch","service":"turn_off","data":"{\"entity_id\":\"switch.switch_10\"}","render_data":false,"mergecontext":"","output_location":"payload","output_location_type":"msg","x":980,"y":160,"wires":[[]]},{"id":"9e03419b.3df268","type":"server","z":"","name":"HASS","legacy":true,"hassio":false,"rejectUnauthorizedCerts":true,"ha_boolean":"y|yes|true|on|home|open"}]`

**Comment by zachowj** [comment]
In the current-state node set the payload location to none. This will make it so the current-state node doesn't overwrite the previous message payload.

The Home Assistant Forums are a great place for general help.
https://community.home-assistant.io/c/third-party/node-red

**Comment by bonelessc** [comment]
Thank you so much!
