### ISSUE TITLE
Not connection to HA after Update

### ISSUE THREAD

**Issue by Wibias** [zachowj/node-red-contrib-home-assistant-websocket#96]
Hey!

After an update my Node-Red isnt connecting to my nginx homeassistant anymore?!

My  log is getting spammed with this message:

```
2 Mar 07:06:06 - [debug] [server:Home Assistant] config server event listener connecting

2 Mar 07:06:10 - [debug] [server:Home Assistant] config server event listener closed
```

Docker Image: node-red-docker:rpi-v8

Nodejs Version: v8.11.1

Can anyone help me with this?

**Comment by zachowj** [comment]
From the README

NOTE: This requires Node.js v8.12+ and Node-RED v0.19+. If you're running Node-Red in Docker you'll need to pull the -v8 image for this to work.

Try upgrading node.js to a version 8.12+

**Comment by Wibias** [comment]
Tried both 8.12.0 and 8.15.1 just now. Both also spam the same message in log.

**Comment by Wibias** [comment]
Its working now, after a restart.
