### ISSUE TITLE
Number doesn't work

### ISSUE THREAD

**Issue by tonychoux** [zachowj/node-red-contrib-home-assistant-websocket#969]
### Describe the bug

homeassistant verson：2023.6.3
Node-RED Companion Integration：v1.3.0
node-red-contrib-home-assistant-websocket: 0.50.0

Could not create Number entity in HA

```
Logger: homeassistant.components.number
Source: components/number/__init__.py:462
Integration: 数值输入器 (documentation, issues)
First occurred: 11:52:03 (3 occurrences)
Last logged: 11:52:03

Error adding entities for domain number with platform nodered
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 471, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 661, in _async_add_entity
    capabilities=entity.capability_attributes,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/number/__init__.py", line 255, in capability_attributes
    ATTR_MIN: self.min_value,
              ^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/number/__init__.py", line 295, in min_value
    return self._convert_to_state_value(self.native_min_value, floor_decimal)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/number/__init__.py", line 462, in _convert_to_state_value
    assert native_unit_of_measurement
AssertionError

``` 

```
Logger: homeassistant.components.number
Source: components/number/__init__.py:255
Integration: 数值输入器 (documentation, issues)
First occurred: 11:52:03 (3 occurrences)
Last logged: 11:52:03

Entity None (<class 'custom_components.nodered.number.NodeRedNumber'>) is using deprecated NumberEntity features which will be unsupported from Home Assistant Core 2022.10, please report it to the custom integration author.
``` 

### Screenshots

![QQ截图20230704121552](https://github.com/zachowj/node-red-contrib-home-assistant-websocket/assets/54809747/c323bfef-2df2-4bbb-b329-98ff8b277755)

### This package's version (not the Home Assistant add-on version)

0.50.0

### Is Node-RED running in Docker?

Yes

### Node-RED version

3.0.2

### Node.js version

-

**Comment by zachowj** [comment]
What is your config for the entity config?

**Comment by ShaneBridges1234** [comment]
mine randomly stops updating as well, the flow runs every hour but each day at some point stops updating the number.
![image](https://github.com/zachowj/node-red-contrib-home-assistant-websocket/assets/54516274/300be11c-ac6e-4533-874d-1d39ec3c5361)
![image](https://github.com/zachowj/node-red-contrib-home-assistant-websocket/assets/54516274/99e73373-66fc-4c70-8b49-78a5a9f95c04)

**Comment by zachowj** [comment]
@ShaneBridges1234 Unless you have the same error showing in your logs, please start a new issue. Do you have any errors showing in the NR logs? Could the function node "average solar camera temperatures" be stopping the flow?
