### ISSUE TITLE
"Please update your configuration..." message on using native unit of measurement 'None' 

### ISSUE THREAD

**Issue by vdiogo** [zachowj/node-red-contrib-home-assistant-websocket#978]
### Describe the bug

I get the following warning in my logs:
```
Logger: homeassistant.components.sensor
Source: components/sensor/__init__.py:650 
Integration: Sensor ([documentation](https://www.home-assistant.io/integrations/sensor), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22)) 
First occurred: 14:22:18 (6 occurrences) 
Last logged: 14:22:18

Entity sensor.temperatura_alvo_escritorio (<class 'custom_components.nodered.sensor.NodeRedSensor'>) is using native unit of measurement 'None' which is not a valid unit for the device class ('temperature') it is using; expected one of ['K', '°F', '°C']; Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.
Entity sensor.temperatura_alvo_sala (<class 'custom_components.nodered.sensor.NodeRedSensor'>) is using native unit of measurement 'None' which is not a valid unit for the device class ('temperature') it is using; expected one of ['K', '°F', '°C']; Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.
Entity sensor.temperatura_alvo_cozinha (<class 'custom_components.nodered.sensor.NodeRedSensor'>) is using native unit of measurement 'None' which is not a valid unit for the device class ('temperature') it is using; expected one of ['K', '°F', '°C']; Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.
Entity sensor.temperatura_alvo_quarto_meio (<class 'custom_components.nodered.sensor.NodeRedSensor'>) is using native unit of measurement 'None' which is not a valid unit for the device class ('temperature') it is using; expected one of ['K', '°F', '°C']; Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.
Entity sensor.temperatura_alvo_quarto_frente (<class 'custom_components.nodered.sensor.NodeRedSensor'>) is using native unit of measurement 'None' which is not a valid unit for the device class ('temperature') it is using; expected one of ['K', '°F', '°C']; Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.
```

When reviewing the node-red configuration I can see the unit of measurement set as expected, so unclear what could 
![image](https://github.com/zachowj/node-red-contrib-home-assistant-websocket/assets/24878195/43439ad7-222e-4d8d-82a8-87e56515ae52)

### To Reproduce

1. Go to logs

### Expected behavior

No warnings

### Screenshots

On the left are my logs and on the right the node-red configuration:
![image](https://github.com/zachowj/node-red-contrib-home-assistant-websocket/assets/24878195/6192a1aa-37ac-484b-8233-1a2150ff0ef9)

### Example Flow

```json
N/A
```

### This package's version (not the Home Assistant add-on version)

N/A

### Is Node-RED running in Docker?

Home Assistant add-on

### Node-RED version

14.3.0

### Node.js version

18.16.1-r0

### Additional context

N/A

**Comment by zachowj** [comment]
What version of the custom component are you using?

**Comment by vdiogo** [comment]
> 



> What version of the custom component are you using?

0.46.1
I see a more recent version to update: 0.55.0, should I?

**Comment by zachowj** [comment]
Not the version of the Home Assistant nodes inside Node-RED, but custom component that you installed via HACS or manually. https://github.com/zachowj/hass-node-red

**Comment by vdiogo** [comment]
> Not the version of the Home Assistant nodes inside Node-RED, but custom component that you installed via HACS or manually. https://github.com/zachowj/hass-node-red

That's in the header of this issue:
Node-RED version
14.3.0

**Comment by Hadatko** [comment]
Hello, i have same issue:
![image](https://github.com/zachowj/node-red-contrib-home-assistant-websocket/assets/13130700/740e7675-e087-4be0-9784-797f12b8f928)
