### ISSUE TITLE
No Node Status

### ISSUE THREAD

**Issue by goldbe4804** [zachowj/node-red-contrib-home-assistant-websocket#979]
### Describe the bug

haven't used node red in a bit- went to update something and saw that the nodes have nothing under them - i dont know how long its been like this- i did try to restore node red also reinstalled it with the same outcome -- the automations do seem to be working- dont know what to try next---- somtimes if i stop and restart NR it will be ok till i go to another page the come back & it also keep crashing
node red 3.0.2
ha 2003.7.1
thanks

![nr](https://github.com/zachowj/node-red-contrib-home-assistant-websocket/assets/56876314/3362f254-8a32-4765-b4bc-5d8b4868a2ee)

### This package's version (not the Home Assistant add-on version)

3.0.2

### Is Node-RED running in Docker?

Home Assistant add-on

### Node-RED version

3.0.2

### Node.js version

14.3.0

**Comment by zachowj** [comment]
Do you have browser any errors?
