### ISSUE TITLE
Update 'binary_sensor' via Fire Event node...

### ISSUE THREAD

**Issue by Swiftnesses** [zachowj/node-red-contrib-home-assistant-websocket#99]
Good day,

I'm trying to use the 'Fire Event' node to update a binary sensor (like I can from dev tools), I've tried every combination of 'event' and 'data' but nothing seems to work :(

Is this supported?

**Comment by Swiftnesses** [comment]
Upon investigation, I guess I need a node like this:

https://flows.nodered.org/node/node-red-contrib-hass

I also assume the new api node can be used for this...

**Comment by zachowj** [comment]
correct you need to use the api node
