### ISSUE TITLE
Entity field dissapears when using domain switch & Service

### ISSUE THREAD

**Issue by weha** [zachowj/node-red-contrib-home-assistant-websocket#998]
### Describe the bug

When I add a "call service", select domain switch & service turn_on for example then the entity field dissapears.
It works when entering the entity field first but it's a bit unhandy.

Before
![image](https://github.com/zachowj/node-red-contrib-home-assistant-websocket/assets/5836955/459d7fd0-a430-4649-9f90-e981c364ea2b)
After
![image](https://github.com/zachowj/node-red-contrib-home-assistant-websocket/assets/5836955/1e7049eb-a200-48f1-8101-17b92ea0bdfd)

### To Reproduce

Add as call service node
Select domain switch
Select a service (turn on) for example
The entity field dissapears

### Expected behavior

Access to the entity field

### This package's version (not the Home Assistant add-on version)

0.55

### Is Node-RED running in Docker?

Yes

### Node-RED version

3.0.2

### Node.js version

16.20

**Comment by zachowj** [comment]
Does it fix itself if you restart NR?

**Comment by weha** [comment]
@zachowj no, I've restarted numerous times since I noticed the issue and it's not even from the last update. I hoped it would have been fixed but it wasn't :)
It is from a certain update but I did not keep track of which version was installed but it was definitely a few versions back.
I did write it down once, and then the version was 0.42.8, it's possible it was still working then but I can't be sure.

**Comment by weha** [comment]
It does not seem to be limited to the switch domain, I have multiple other domains that have the same issue.
The strange thing is that in the last week things seemed to be working. 
So after a while it returns to normal? *shrug*
I did an update to 55.1 and now it's back :(

![image](https://github.com/zachowj/node-red-contrib-home-assistant-websocket/assets/5836955/454bc434-07cf-4a0d-88c1-67362f1bc5a2)

**Comment by koosc** [comment]
I am also seeing this, has anyone figured out the root cause?
